### ISSUE TITLE
Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by CSMarco** [tipsi/tipsi-stripe#102]
Hello,

I tried to integrate tipsi-stripe in my project and encountered the proplem, that I am always getting the error 'Cannot read property 'init' of undefined' when running the app.

I used this code in my App.js file: 

    import stripe from 'tipsi-stripe';

    stripe.init({
      publishableKey: 'pk_test_xxx',
    })

This code is exactly what is shown in the example project, except that I left out the merchantId field (Didn't work with that either)

I linked the library and added the Stripe pod to my Xcode project.

Did anyone experience similar errors or am I just missing out a mistake made by me?
Thank you in advance!

**Comment by isnifer** [comment]
Hi @CSMarco, of course, you're not the first man with this problem.
There are two related issues - https://github.com/tipsi/tipsi-stripe/issues/53 and https://github.com/tipsi/tipsi-stripe/issues/81.
I'm sure you didn't link `tipsi-stripe` correctly. Please, check these issues, and write here after that.

**Comment by CSMarco** [comment]
@isnifer Sadly this didn't help me with my problem. I've tried linking it manually aswell, but this didn't work either. Do you have any other ideas how to fix this problem?

**Comment by isnifer** [comment]
@CSMarco so, please show me how did you link `tipsi-stripe`. Show me `Link with binaries section` in your project, also please show me your HEADER_SEARCH_PATHS section in your project

**Comment by CSMarco** [comment]
@isnifer there you go
<img width="857" alt="1" src="https://user-images.githubusercontent.com/27492648/29269896-46cf478a-80f4-11e7-82a8-3bb1f6fc4cab.png">

<img width="508" alt="2" src="https://user-images.githubusercontent.com/27492648/29269900-4c194c54-80f4-11e7-8a58-504c48fc7a88.png">

**Comment by isnifer** [comment]
@CSMarco did you install `Pods`?

**Comment by CSMarco** [comment]
@isnifer Yes I did.

This is my Podfile:

    target 'appXXX' do
      pod 'Stripe', '~> 10.1.0'
    end

**Comment by isnifer** [comment]
@CSMarco so, one more thing in headers from our README:
Click on TPSStripe.xcodeproj in Libraries and go the Build Settings tab. Double click the text to the right of Header Search Paths and verify that it has **$(SRCROOT)/../../react-native/React** as well as **${SRCROOT}/../../../ios/Pods/Headers/Public** - if they aren't, then add them.

**Comment by CSMarco** [comment]
@isnifer They are already added there.

**Comment by isnifer** [comment]
@CSMarco I don't see them in your screenshot

**Comment by CSMarco** [comment]
@isnifer The screenshot is from my main project, but the other two are already added in the TPSStripe.xcodeproj as you can see in this screenshot:
<img width="552" alt="3" src="https://user-images.githubusercontent.com/27492648/29270281-54cae266-80f6-11e7-83c1-621998e7de93.png">

**Comment by isnifer** [comment]
@CSMarco I think it's not enough.
I see these HEADERS in our main project file:
![image](https://user-images.githubusercontent.com/1788245/29270347-08258e8a-80ff-11e7-98fd-6a1ef369e67b.png)

**Comment by CSMarco** [comment]
@isnifer Is Firebase or Google integration necessary? Because I have tried adding these other paths, but it still doesn't work:
    
    "$(PODS_ROOT)/Headers/Public"
    $(SRCROOT)/../node_modules/react-native/React

**Comment by isnifer** [comment]
No, we just use it in our app

**Comment by CSMarco** [comment]
@isnifer But do you have any other ideas for fixing this problem?

**Comment by isnifer** [comment]
@CSMarco can you show me screenshot oh the error. Is it like in mentioned issues?

**Comment by CSMarco** [comment]
@isnifer 
![simulator screen shot 14 08 2017 14 11 27](https://user-images.githubusercontent.com/27492648/29271165-7da6979e-80fa-11e7-9e89-7177bfd60c40.png)

**Comment by JonghunYu** [comment]
I have same error message for both example app in the package and my app
Below is screen capture from example app.
<img width="375" alt="2017-08-16 6 08 00" src="https://user-images.githubusercontent.com/7391181/29356051-f01fdd80-82ad-11e7-844b-c7244bfa1e10.png">

**Comment by JonghunYu** [comment]
My app works now after re-build in the .xcworkspace. Sorry for mistake

**Comment by isnifer** [comment]
Nice, @CSMarco how are you building your app? Via workspace?

**Comment by CSMarco** [comment]
@isnifer Yes, I am building the app via workspace, but rebuilding/completely regenerating the workspace with react-native doesn't work either

**Comment by CSMarco** [comment]
I fixed it: 
My project was initially using Expo and I ejected it. Now I created a new project with react-native init and compared the package.json of my project and the newly created project and edited it. Then I removed node_modules and ran npm install again. After that it ran perfectly fine.

**Comment by isnifer** [comment]
@CSMarco Nice. We need to update our README

**Comment by dpetkevich** [comment]
I'm experiencing the same issues and none of the above fixes are working.

**Comment by Luckygirlllll** [comment]
I'm getting this error in Android, so what is the solution?

**Comment by hopewise** [comment]
At last, I was able to compile, here is what I did:

sudo gem install stripe
sudo gem install -n /usr/local/bin cocoapods

`ios/Podfile`:
```
platform :ios, '9.0'
workspace 'MyApp'
 target 'MyApp' do
 pod 'Stripe', '~> 14.0.0'
 inherit! :search_paths
end
```
run `pod install` inside ios directory
run `react-native link tipsi-stripe` at project root

**Comment by alexpchin** [comment]
I am still getting this issue when running `yarn test` with a project that was originally expo and now bare.  @MarcoKCodes What was the offending package?

**Comment by MarcoKCodes** [comment]
@alexpchin as far as I can remember there wasn't a specific package causing this issue. As stated above all I did to resolve it in my specific case was ejecting from Expo, deleting the node_modules folder and running npm install again.

**Comment by alexpchin** [comment]
@MarcoKCodes Does this trigger any memories? I’ve ejected and removed node_modules but still finding this a problem? https://github.com/tipsi/tipsi-stripe/issues/551

**Comment by MarcoKCodes** [comment]
@alexpchin Sorry, but I can't really remember any details on this issue as I encountered that more than 2 years ago. Did you find a solution in the meantime?

**Comment by Sanglepp** [comment]
If anyone should have issues with this in 8.0.0-beta.9 then add the following to your podfile
` 
pod 'Stripe'
pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe' 
`

For some reason the RN autolinking doesn't work out of the box. At least for me. 
My projects RN version is 0.61.5
