### ISSUE TITLE
Is there a way to make the "Save for use in other apps" invisible?

### ISSUE THREAD

**Issue by cltsang** [tipsi/tipsi-stripe#106]
Greetings. I have a question as titled.
The choice itself is a bit unnecessarily alarming for my use. I can't seem to find a way to configure it to be hidden. Is it there because of stripe compliance?
Thank you.

**Comment by isnifer** [comment]
@cltsang Hi, what you mean `to be hidden`?

**Comment by cltsang** [comment]
Hi. Yes. I wonder if i can disable or hide that option in stripe.paymentRequestWithCardForm.

**Comment by cltsang** [comment]
as shown here ![this screen](https://cloud.githubusercontent.com/assets/1177226/20274560/1432abf2-aaa6-11e6-8505-0cdc3017fe22.gif)

**Comment by dmytrozavgorodniy** [comment]
Please check `smsAutofillDisabled` option for `paymentRequestWithCardForm` method

> smsAutofillDisabled Bool - When entering their payment information, users who have a saved card with Stripe will be prompted to autofill it by entering an SMS code. Set this property to true to disable this feature.

**Comment by cltsang** [comment]
I guess I'll have to build a custom form to have the email then.
Thanks.
