### ISSUE TITLE
Bitcoin and WePay support

### ISSUE THREAD

**Issue by mcousillas6** [tipsi/tipsi-stripe#107]
Hi,
I have a question for you guys, does the framework support bitcoin and WePay transactions? We need to support those features on a RN app an it would be awesome if we could use your framework.

**Comment by isnifer** [comment]
Hi, @mcousillas6! Currently, we do not support Bitcoin and WePay. We need a free time to investigate them.

**Comment by mcousillas6** [comment]
Okay, thanks for the quick answer!
