### ISSUE TITLE
Unable to resolve module `react`

### ISSUE THREAD

**Issue by MyTotoro** [tipsi/tipsi-stripe#111]
I'm trying to build and test out the tipsi-stripe example, tried resolving this error by following instructions but to no avail

```
error: bundling: UnableToResolveError: Unable to resolve module `react` from `/tipsi-stripe/src/components/PaymentCardTextField.android.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`
```

```
node -v: 8.4.0
npm -v: 5.4.0
"react": "^16.0.0-alpha.6",
"react-native": "0.44.0",
"tipsi-stripe": "../"
```

**Comment by isnifer** [comment]
So, @MyTotoro let me know what did you do, step-by-step?

**Comment by MyTotoro** [comment]
@isnifer 

Do you know if it works on your device? I'm trying to run the example on a physical Android device

```
git clone <>
npm install 
npm start (fills the current window with packager)
react-native run-android (in another terminal)
```

**Comment by isnifer** [comment]
@MyTotoro of course it works! This is a screenshot from my Galaxy S7
![image](https://user-images.githubusercontent.com/1788245/30029465-02bed4bc-9192-11e7-9a16-d560f9cd095f.png)

**Comment by MyTotoro** [comment]
Thanks, I pulled out the button and guts and implemented it into my app, I still can't run the example but this will do
