### ISSUE TITLE
Support for sources

### ISSUE THREAD

**Issue by flavordaaave** [tipsi/tipsi-stripe#112]
We'd like to use stripe for Alipay payments within our mobile app. Therefor we'd need to use [sources](https://stripe.com/docs/mobile/ios/sources)

Are there any plans for this plugin to support sources?

**Comment by isnifer** [comment]
@flavordaaave thank you for your issue, we need some time to discuss it.

**Comment by isnifer** [comment]
@flavordaaave Also we need to know test cases for this feature. If you ready to implement it with tests, of course, it will be merged faster. If not - we need to find a free time.
Because currently, I don't understand what this feature does :)

**Comment by flavordaaave** [comment]
@isnifer As mentioned we need this feature for Alipay, which is comparably to PayPal. So what the source feature actually does is to allow payments with [methods other than credit card](https://stripe.com/docs/sources).
For Alipay the user flow would be something like:
1. Create a source with the Stripe SDK of type `alipay` (specifying the currency & amount of the transaction)
2. The stripe SDK will then redirect the user to either the Alipay native app (if installed) or Alipay web app
3. The user completes the payment within the 3rd party app (e.g. Alipay)
4. The user get's redirect back to the app that initiated the payment
5. On the server-side we use [webhooks](https://stripe.com/docs/webhooks) to process the charge as soon as the payment is authorized by the user.

Unfortunately I'm not really experienced with native code (I could try to give it a shot on iOS but on Android, which we also need, I don't have any idea what to do). But I can definitely do some beta tests with our setup ;-)

**Comment by isnifer** [comment]
@flavordaaave ok, looks like a proxy between application and payment system. Thank you for you explanation

**Comment by Nepherhotep** [comment]
Hey @flavordaaave,

Thanks for explanation. Unfortunately we don't have this feature in our roadmap, but if you write the code for iOS part, we can implement remaining part for Android. However, we expect you to write production-ready code with tests, so we just make code review. If that works for you, let's handle this feature.

**Comment by flavordaaave** [comment]
@Nepherhotep sounds like a plan :+1::skin-tone-3:
I can not say anything about the timeline for now since we're currently aligning our internal roadmap but I'll keep you posted here as soon as I made some progress.

**Comment by flavordaaave** [comment]
@isnifer @Nepherhotep See ##113

**Comment by GulKhan** [comment]
Hi just wanted to chip in that the ability to create sources is also needed for the Stripe 3D secure process. see here https://stripe.com/docs/sources/three-d-secure#check-requirement
