### ISSUE TITLE
Any one Can you Explain Merchant IDs Process Explain Step by step

### ISSUE THREAD

**Issue by lavarajallu** [tipsi/tipsi-stripe#114]
Hello, Every One I want to   how to Create sample merchantID in react-native.
Can you Explain Step by step by Process

**Comment by isnifer** [comment]
@lavarajallu https://developer.apple.com/documentation/passkit/apple_pay/setting_up_apple_pay_requirements

**Comment by isnifer** [comment]
I hope you have done this.
