### ISSUE TITLE
fatal error: 'Stripe/Stripe.h' file not found for the example project on ios

### ISSUE THREAD

**Issue by lanzhzh** [tipsi/tipsi-stripe#116]
After clone the project, I ran the following command:
cd example & npm i 
cd ios & pod install 
open the example.xcworkspace with xcode and compile. 

Here is the screen shot

![image](https://user-images.githubusercontent.com/8751044/30302773-28f16362-9718-11e7-9f1b-827428e8ab6e.png)

**Comment by isnifer** [comment]
@lanzhzh Hi! First of all, did you read similar thread https://github.com/tipsi/tipsi-stripe/issues/11 ?

**Comment by lanzhzh** [comment]
@isnifer Yes, I read all the thread about this error and tried their methods, but none of them work for me. I just compiled and tried to run the example files, therefore, I don't think (and I have double checked ) I have any dependency issue. I also don't need to setup the podfile for the same reason. 

Please let me know if there is any info that I can provide. 

Thanks a lot!

**Comment by isnifer** [comment]
@lanzhzh try `pod repo update` and then `pod install` from `ios` folder

**Comment by lanzhzh** [comment]
@isnifer Thanks for the quick reply. Yes, I did that. It didn't solve the problem. My npm version is 5.4.1, pod version is 1.3.1, xcode version 8.3.3.

**Comment by isnifer** [comment]
@lanzhzh please, run android emulator and them run `npm run ci` from project root

**Comment by isnifer** [comment]
Closed due to inactivity
