### ISSUE TITLE
Authentication with Stripe-Account header

### ISSUE THREAD

**Issue by pxue** [tipsi/tipsi-stripe#118]
does this library support authenticating with the "stripe-account" header as specified in this [document](https://stripe.com/docs/connect/authentication)?

the use case is with shopify [sales channel](https://help.shopify.com/api/sdks/sales-channel-sdk/completing-a-payment#integrate-stripe-with-your-sales-channel-app) payment process.

**Comment by isnifer** [comment]
@pxue currently - no. You can try to create a PR.

**Comment by pxue** [comment]
is the current supported Stripe.framework version 10.1.0? Might be a bit more involved to update support to the latest version of the framework

**Comment by isnifer** [comment]
@pxue we have already PR for that

**Comment by pxue** [comment]
@isnifer are you talking about https://github.com/tipsi/tipsi-stripe/pull/44?

I'm talking about upgrading the underlying Stripe.Framework to v11.1.0 to support the stripeAccount header. Migrating isn't as straight forward since there're some backwards compat issues such as `paymentRequestWithMerchantIdentifier:` being deprecated in [v10.2.0](https://github.com/stripe/stripe-ios/blob/master/MIGRATING.md#migration-from-versions--1100)

**Comment by pxue** [comment]
either way I'll take a stab at it, thanks.

**Comment by isnifer** [comment]
@pxue no, we are planning to do it here - https://github.com/tipsi/tipsi-stripe/pull/113/files#diff-7344f2e44a3d1eee3019f6bcadc7c364

**Comment by pxue** [comment]
great thanks!

**Comment by isnifer** [comment]
@pxue we've updated Stripe Pod already in `master` branch and planning to publish it 4.2.0 when an Android part will be ready.

**Comment by isnifer** [comment]
@pxue so, you can start work on it, if you need it yet.

**Comment by pxue** [comment]
🙏 amazing. thank you.

**Comment by isnifer** [comment]
🤘

**Comment by kenmaca** [comment]
Hi guys. Firstly, thank you for the wonderful library.

I've put out a very simple PR to expose the `setStripeAccount` method from the Stripe library on both Android and iOS that should close this feature request. Can @isnifer or someone have a look and perhaps merge it in? Thanks!

**Comment by fbartho** [comment]
Fixed by #535 / will be released in tipsi-stripe@8.0

**Comment by bramski** [comment]
#535 did not work
Here is a new PR: https://github.com/tipsi/tipsi-stripe/pull/563
