### ISSUE TITLE
deviceSupportsAndroidPay?

### ISSUE THREAD

**Issue by sbycrosz** [tipsi/tipsi-stripe#12]
Awesome work on the library! 
I haven't really done much with Android, but Is there a way to have `deviceSupportsAndroidPay`?

-Sam

**Comment by itsmepetrov** [comment]
Hi, @sbycrosz, thank you so much!

Currently, Android Pay support is not ready for production since it under active development, but we can implement `deviceSupportsAndroidPay` similar to `deviceSupportsApplePay`.

@fAns1k please take a look.
