### ISSUE TITLE
Navigation Bar Tint Color on iOS

### ISSUE THREAD

**Issue by bikisDesign** [tipsi/tipsi-stripe#121]
I've found that the navigation Bar tint color is unable to be set in the `Theme` object while calling `paymentRequestWithCardForm`.  Is there a key that I'm unaware of or not in your documentation to set this value? 

![img_044ca2b8ea95-1](https://user-images.githubusercontent.com/11651975/30836215-87af1756-a211-11e7-9841-bc53c6d20615.jpeg)

**Comment by isnifer** [comment]
@bikisDesign As I can see in the Stripe documentation.
> The navigation bar style to use for any view controllers presented modally by the SDK. The default value will be determined based on the brightness of the theme’s `secondaryBackgroundColor`.

But, also, there is a `barStyle` property that we haven't implemented yet.

**Comment by isnifer** [comment]
@bikisDesign fixed in **3.7.4**
