### ISSUE TITLE
Is there a way to retrieve customer sources via customer id? 

### ISSUE THREAD

**Issue by timothykibler** [tipsi/tipsi-stripe#125]
For example, if I want to list the sources from a customer with their id cus_xxxxxxx.

I can just make the request separately but it'd be nice if there was a way to do it through the library.

**Comment by isnifer** [comment]
@timothykibler Hi, what sources do you mean?

**Comment by timothykibler** [comment]
Basically I want to get a list of available cards for a customer. I believe getting a customer by their customer id on the regular Stripe API returns all cards they’ve added as Sources?

**Comment by isnifer** [comment]
@timothykibler I'm sure you need to read Stripe docs first of all. We do not implement this feature. If it possible - PRs are welcome :)

**Comment by timothykibler** [comment]
It should be fairly trivial to do I feel, I’ll see what I can do for a PR :)

**Comment by isnifer** [comment]
Nice)
