### ISSUE TITLE
Saving cards for later - creating customer ID

### ISSUE THREAD

**Issue by jhendrick** [tipsi/tipsi-stripe#126]
With Stripe you can create a customerID instead of a token to save the card for later as described here: https://stripe.com/docs/charges.  Does tipsi-stripe have this capability, something like createCustomerIdWithForm?

**Comment by isnifer** [comment]
@jhendrick no, but you can help us improve `tipsi-stripe`

**Comment by cybergrind** [comment]
Hey @jhendrick 
Internally we're using this feature but it requires backend support:

* create token as usual
* send token to backend and instead of payment => create customer
* save customer on backend

So customer creation requires the secret key that shouldn't be used on frontend part.

**Comment by jhendrick** [comment]
Thanks @cybergrind that makes perfect sense.  I will plan to go with that approach.
