### ISSUE TITLE
Support New Google Payments API

### ISSUE THREAD

**Issue by agrosner** [tipsi/tipsi-stripe#128]
It appears that Android Pay APIs are getting deprecated and replaced by the Google Payments API: https://developers.google.com/payments/

It would be great if this lib was updated to support the new payments API. 
<img width="1282" alt="screen shot 2017-10-05 at 9 06 26 am" src="https://user-images.githubusercontent.com/2117859/31229161-cd4a7ef6-a9ad-11e7-8b54-4544d348bba4.png">

**Comment by isnifer** [comment]
@agrosner Hi! We will investigate this feature later. If Stripe supports it, we will too.

**Comment by agrosner** [comment]
https://stripe.com/docs/mobile/android/pay-with-google

**Comment by isnifer** [comment]
@agrosner ok, understand. We will update stripe-android sooner, after that we will be ready to implement new method for google payments :)

**Comment by paynd** [comment]
@agrosner take a look #184

**Comment by isnifer** [comment]
Landed in 5.0.0 https://github.com/tipsi/tipsi-stripe/releases/tag/5.0.0
