### ISSUE TITLE
payment method screen

### ISSUE THREAD

**Issue by gibo** [tipsi/tipsi-stripe#135]
Is the payment method screen, which allows users to select a (previously used) card part of this project. 

I'm aware api work would be needed to retrieve a list of users cards, but just wondered if the screen to display them is available?

It looks like this: 
https://stripe.com/img/blog/posts/ui-components-for-ios/wallet@2x.png

**Comment by isnifer** [comment]
@gibo in our app we have implemented this screen. This is not a part of the module. You should retrieve a list of user cards from the server. Your question little bit similar https://github.com/tipsi/tipsi-stripe/issues/126.

**Comment by gibo** [comment]
cool.

are there any plans to move the UI part of the code into this project?

**Comment by isnifer** [comment]
@gibo no, you can implement it like you want.
