### ISSUE TITLE
fatal error: 'Stripe/Stripe.h' file not found

### ISSUE THREAD

**Issue by balesz** [tipsi/tipsi-stripe#138]
Please put the `$(SRCROOT)/../../../ios/Pods/Headers/Public` directory to the HEADER_SEARCH_PATH build setting of the iOS project file. Very uncomfortable put it by hands all the time.

https://github.com/tipsi/tipsi-stripe/blob/7f364cbc1b9adcb1d13daf9b43f8ed969ada1780/ios/TPSStripe.xcodeproj/project.pbxproj#L195

https://github.com/tipsi/tipsi-stripe/blob/7f364cbc1b9adcb1d13daf9b43f8ed969ada1780/ios/TPSStripe.xcodeproj/project.pbxproj#L240

**Comment by isnifer** [comment]
@balesz please use 3.7.4 or `react-native link`. You don't need to do anything by hands. We will release a new version today.

**Comment by cybergrind** [comment]
@balesz 3.8.1 with fix was released

**Comment by balesz** [comment]
@cybergrind 
Please change the added `${SRCROOT}/../../../ios/Pods/Headers/Public` search path to "non recursive". The recursive setting broke the build.

**Comment by isnifer** [comment]
@balesz check 3.8.2
