### ISSUE TITLE
Coupon Support

### ISSUE THREAD

**Issue by jterps08** [tipsi/tipsi-stripe#153]
I did not see this in the documentation and I'm not an experienced developer. So, please forgive the question if the answer is obvious... Can Tipsi Stripe support coupons, subscriptions, or is that handled directly with the Stripe API using the token that Tipsi collects? Thanks!

**Comment by isnifer** [comment]
@jterps08 Hi! If Stripe doesn't support any feature `tipsi-stripe` too. Our module is just a wrapper

**Comment by isnifer** [comment]
So, I'm closing this issue, cause it does not relate `Stripe` or `tipsi-stripe`

**Comment by ElieMyIdea** [comment]
Hi, 

We would really like too implement Coupon on our app.
We saw that Stripe implemented this feature => https://stripe.com/docs/recipes/coupons-for-charges

Could it be possible for you to implement this feature too ?

Thanks for all !

**Comment by cybergrind** [comment]
@ElieMyIdea it won't be implemented in near term by our team. Maybe someone will send PR
