### ISSUE TITLE
No licence file found

### ISSUE THREAD

**Issue by henrikra** [tipsi/tipsi-stripe#154]
After running `pod install` I get following warning from this package:
`[!] Unable to read the license file /Users/henrik/projects/coolApp/ios/Pods/Stripe/LICENSE for the spec Stripe (10.1.0)`

So I guess you should add it? :)

**Comment by isnifer** [comment]
License for Pod. Not for this module. Try to remove pods, then `pod repo update` and `pod install` again

**Comment by henrikra** [comment]
Looks like when I just removed `Pods` folder and ran `pod install` again and after that the warning was gone :)
