### ISSUE TITLE
After token generate what to do for payment process in add card??

### ISSUE THREAD

**Issue by yogeshmoradiya121** [tipsi/tipsi-stripe#156]

**Comment by isnifer** [comment]
Perform Payment

**Comment by yogeshmoradiya121** [comment]
How??

**Comment by yogeshmoradiya121** [comment]
can you help with api request url or any code??

**Comment by isnifer** [comment]
@yogeshmoradiya121 start here, for example - https://stripe.com/docs/mobile/ios/standard. It's an official documentation.

**Comment by yogeshmoradiya121** [comment]
ok thnx.

**Comment by isnifer** [comment]
I'm closing this issue, cause it relates the official docs for Stripe.
