### ISSUE TITLE
Build Failed on Android

### ISSUE THREAD

**Issue by ikhsanalatsary** [tipsi/tipsi-stripe#158]
The Error Occurs:
```
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':tipsi-stripe'.
      > You have not accepted the license agreements of the following SDK components:
        [Android SDK Build-Tools 25].
        Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

My App dependencies:
1. react v16.0.0-alpha.12
2. react-native v0.48.4
3. tipsi-stripe v4.1.0

android build.gradle config:
```
android {
    compileSdkVersion 25
    buildToolsVersion "23.0.1"
    ....
    defaultConfig {
        .....
        minSdkVersion 16
        targetSdkVersion 25
        .....
    }
}
```

Device: 
* MBP OSX ElCapitan 10.11.6

How to resolve this?
Thanks

**Comment by isnifer** [comment]
@ikhsanalatsary Hi! You should accept licenses for build tools 25 on your own machine (in Android Studio for example)

**Comment by ikhsanalatsary** [comment]
@isnifer i tried `yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.0.2"` and `yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;26.0.2"` but still failed

**Comment by isnifer** [comment]
@ikhsanalatsary try just `25.0.0` too

**Comment by ikhsanalatsary** [comment]
Same. Still failed

**Comment by isnifer** [comment]
@ikhsanalatsary `complete the installation of the missing components`

**Comment by isnifer** [comment]
![image](https://user-images.githubusercontent.com/1788245/32495155-7ef28e14-c3d5-11e7-87c6-e3d18608e758.png)

**Comment by ikhsanalatsary** [comment]
Thanks, @isnifer for your help. so I need install android studio first. rebuild with it and it works.
