### ISSUE TITLE
Multiple xcode projects found

### ISSUE THREAD

**Issue by piubellofelipe** [tipsi/tipsi-stripe#160]
Hi everyone, I've been using tipsi-stripe in my project, and had problems when using with xcode.
my current versions are:
```
react-native: 0.44,
react: 16.0.0
```

my podfile looks like:
```
target 'xxxx' do
project './xxx.xcodeproj'
  pod 'Stripe', '~> 10.1.0'
  ...
end
```
I have been able to successfully run it, but when trying to, I encountered the following error every time I tried to link libraries:
```
"Multiple Xcode projects found"
```
which I discovered to be raised by line 14 on node_modules/tipsi-stripe/scripts/post-link-ios.rb
```
raise 'Multiple Xcode projects found' unless @project_paths.length == 1
```
It happens that my project does have multiple projects, and needs to have both.
I managed a workaround by commenting this line, but thought that maybe there's a way to make your lib available for people with multiple xcode projects, or at least note this on the docs?

**Comment by dmytrozavgorodniy** [comment]
Hi, @piubellofelipe! So you have a few .xcodeproj files in your ./ios directory? You are using a few project for a few apps?

**Comment by piubellofelipe** [comment]
Hi @dmytrozavgorodniy, thanks for the answer.
I am using an share extension (https://github.com/alinz/react-native-share-extension/), which creates one additional xcodeproj in my ./ios directory

**Comment by dmytrozavgorodniy** [comment]
@piubellofelipe yeah, in `post-link-ios` we trying create or modify your `Podfile` in order to install dependencies (Stripe). I think we should remove `post-link-ios` script, because users can have any project configuration.

In your case use can link tipsi-stripe using `react-native link command`, after that you should create or modify ourself.
