### ISSUE TITLE
Set the company name

### ISSUE THREAD

**Issue by stueynet** [tipsi/tipsi-stripe#166]
Is there a way to set the company name? Otherwise it defaults to just use the name of the app which is not what we are looking for. This shows up, for example, in the Text message that stripe sends you if you had saved the credit card info in the past. 

This would be something akin to the `name` prop in this component:

https://github.com/azmenak/react-stripe-checkout

Here it is in their code:
https://github.com/azmenak/react-stripe-checkout/blob/master/StripeCheckout.js#L88

**Comment by isnifer** [comment]
```js
import stripe from 'tipsi-stripe'
// ...

function pay(method) {
  if (method === APPLE_PAY) {
    const { items, options } = applePayOrderFormatter(order)
    return stripe.paymentRequestWithApplePay(items, options)
  }
}
```

```js
// applePayOrderFormatter.js

function applePayOrderFormatter(order) {
  // ...

  const items = [{
    label: 'SUBTOTAL',
    amount: subtotalPrice,
  }, {
    label: 'TAX',
    amount: totalTax,
  }, {
    label: 'SHIPPING',
    amount: deliveryPrice,
  }, {
    label: PAY_COMPANY_NAME, // Your company name, Apple, Microsoft, Tipsi, etc.
    amount: totalPrice,
  }]

  // ...

  const options = { ... }

  return { items, options }
}
```

**Comment by stueynet** [comment]
Thanks @isnifer. We aren't using Apple Pay. In our case, we are just using the package to add the user as a Stripe customer with their card and then our API makes charges where required. I am assuming maybe we can add a parameter to `stripe.paymentRequestWithCardForm()`?

So we are doing basically this:

```js
import stripe from 'tipsi-stripe';

stripe.init({
    publishableKey: env.stripeKey,
});

class ManageCards extends Component<*, Props, State> {
    props: Props;

    state = {
        loading: false,
    };

    render(): React.Element<*> {
            return (
                <TouchableOpacity onPress={this.handleCardPayPress}>
                    <Text style={{ color: colors.brandPeach1 }}>{label}</Text>
                </TouchableOpacity>
            );
        }
    
    handleCardPayPress = async () => {
        try {
            this.setState({
                loading: true,
            });
            const token = await stripe.paymentRequestWithCardForm({
                prefilledInformation: {
                    email: this.props.authUser.email,
                },
            });

            const newCard = ! this.props.authUser.stripe_active;
            this.props.updateCard(token.tokenId, newCard);

            this.setState({
                loading: false,
            });
        } catch (error) {
            this.setState({
                loading: false,
            });
        }
    };
```

**Comment by isnifer** [comment]
@stueynet actually, we didn't encounter this. I think it would be better if you read official docs and point me about the company name if it possible. We will do our best.

**Comment by isnifer** [comment]
@stueynet maybe your feature request similar https://github.com/tipsi/tipsi-stripe/issues/159? Look into docs, please, and tell me if not.

**Comment by stueynet** [comment]
@isnifer yeah I looked at the docs and the code and it wasn't immediately clear if this was possible or not. It seems to just automatically use `CFBundleName`
