### ISSUE TITLE
Failed to build gem native extension on react-native link tipsi-stripe

### ISSUE THREAD

**Issue by simistern** [tipsi/tipsi-stripe#167]
I am unable to get this project to compile and run. I have followed the instructions for installation on xcode but when I run `react-native link tipsi-stripe`, I get the following error: 

I am not sure how to proceed...

![screen shot 2017-11-15 at 1 11 39 pm](https://user-images.githubusercontent.com/3443214/32852687-c0110dc6-ca06-11e7-8a52-5cc429ce201c.png)

**Comment by isnifer** [comment]
@simistern let's try:

Ensure ruby is installed and up to date: `ruby -v`
Update gem's `sudo gem update --system`

**Comment by isnifer** [comment]
Closed due to inactivity
