### ISSUE TITLE
Samsung S7 Input Field is broken

### ISSUE THREAD

**Issue by agrosner** [tipsi/tipsi-stripe#168]
Hi, 
On the S7, the credit card entry does not operate properly. When typing the CC# then moving to the month/year + expiration, the UI appears to get stuck. If I try to use v1.4.8.8 of CreditCardEntry, the input field becomes blank.

![stripe](https://user-images.githubusercontent.com/2117859/32852820-262b86c2-ca07-11e7-98c5-755877ada85e.gif)

**Comment by paynd** [comment]
Hi @agrosner, will check it.

**Comment by paynd** [comment]
@agrosner 
What version of android do you use, android 8?

**Comment by agrosner** [comment]
7.0

**Comment by agrosner** [comment]
it also happens on the S8, because _samsung_

**Comment by agrosner** [comment]
It appears to be happening on other significant Android 7.0 devices..

**Comment by agrosner** [comment]
See https://github.com/tipsi/CreditCardEntry/pull/3. should fix the issue.

**Comment by paynd** [comment]
@agrosner https://github.com/tipsi/tipsi-stripe/pull/185

**Comment by agrosner** [comment]
cool. looks good.

**Comment by paynd** [comment]
#185 has been merged
