### ISSUE TITLE
provide email in options for paymentRequestWithCardForm()

### ISSUE THREAD

**Issue by shyaniv7** [tipsi/tipsi-stripe#17]
hello, i was wondering how difficult it would be to allow for an email to be added by the consumer of paymentRequestWithCardForm inside options so that options = { ..., email: test@test.com} and remove or auto populate the email field in the add card form for the costumer

Thanks in advance,
Yaniv

**Comment by cybergrind** [comment]
@shyaniv7 sorry for long response, @itsmepetrov please reply to this issue

**Comment by itsmepetrov** [comment]
Hi @shyaniv7 

Currently, we can only hide email field via `smsAutofillDisabled: false` option.

We use [STPAddCardViewController](https://stripe.github.io/stripe-ios/docs/Classes/STPAddCardViewController.html) from Stripe iOS API for drawing this view and we can change only those parameters which are provided by Stripe API.

As I can see, `STPAddCardViewController` has ability to specify `prefilledInformation` field, which can contain `email` and `phone`.

We can try to add this feature in next release.

PS: PRs are welcome 🙂
