### ISSUE TITLE
Android pay - how to retrieve shipping address?

### ISSUE THREAD

**Issue by shokimble** [tipsi/tipsi-stripe#173]
Hi,

I'm using Android pay and setting 

`
shipping_address_required = true
`
When I receive the token back unlike on Apple Pay there is no shipping information included even though it was entered.

Looking through the source (https://github.com/tipsi/tipsi-stripe/blob/master/android/src/main/java/com/gettipsi/stripe/StripeModule.java)  it looks like the token received back from stripe does not include this information as the source of com.stripe.android.model.Token doesn't refer to a shipping address.

If I'm missing something obvious please let me know. Otherwise I'd really like to be able to retrieve the information as Android Pay has a very nice address input mechanism. If you could give me pointers on how to implement, I'm happy to do so and submit a pull request. Looking through the stripe docs is not helping much.

**Comment by paynd** [comment]
Hi @shokimble!
Check #178

**Comment by shokimble** [comment]
Haha good timing. I was about to sit down and add it myself today as I just realised it comes from the Pay API not Stripe.

I will test it in a couple of hours but code review wise it looks good.

Now I can see what's available we should also have email address available for completeness (as in all the information available) and parity with the Apple Pay results. Heck some people might even need the billing address.

Are you happy to add that otherwise I can do it ?

Thanks a million!

**Comment by shokimble** [comment]
I can confirm it works perfectly - both when shipping address is enabled or disabled. It's just an empty object when it's disabled.

Let me know about the email and billing address support - I'm happy to do it just thought it would be neater all in the one go.

**Comment by shokimble** [comment]
I've found a separate but related issue with Android Pay. By default only the USA is allowed to be selected as a shipping country. I've logged an issue describing how to add more countries.

#180

**Comment by paynd** [comment]
@shokimble going to add email and billing address soon

**Comment by paynd** [comment]
@shokimble updated

**Comment by paynd** [comment]
#178 has been merged
