### ISSUE TITLE
Android prompt for address

### ISSUE THREAD

**Issue by tmaly1980** [tipsi/tipsi-stripe#174]
paymentRequestWithCardForm has the option 'requiredBillingAddressFields' . It seems to be iOS only. Are there any plans for adding that to the Android version? This is requiring me to rewrite my app to be cross platform with a custom form if I can't use your library to collect address info.

**Comment by paynd** [comment]
Hi @tmaly1980, I will add it asap.

**Comment by paynd** [comment]
@tmaly1980 
Sorry for late response.
Yes `requiredBillingAddressFields` are iOS-only for now. 
Unfortunately we have no ready-made UI to collect this information on Android, and it is not our primary goal for now. 
Any PR are welcome.

**Comment by paynd** [comment]
@tmaly1980 Can you check #197?

**Comment by isnifer** [comment]
@tmaly1980 did you check it?

**Comment by sunshineo** [comment]
@paynd or @isnifer , is it possible to move forward with the merge request #197 ?
