### ISSUE TITLE
Apple pay - After Payment processing a dialog is shown that the payment was not completed after which the app crashes with the below message

### ISSUE THREAD

**Issue by sujay-bidchat** [tipsi/tipsi-stripe#177]
# Illegal callback invocation from native module. This callback type only permits a single invocation from native code.

**Comment by isnifer** [comment]
@sujay-bidchat Hi! Please, provide full log, with screens may be

**Comment by isnifer** [comment]
Closed due to inactivity

**Comment by Charpell** [comment]
Use the `stripe.completeApplePayRequest()` method to complete your request if suucessfull and the `stripe.cancelApplePayRequest()` if there is a failure
