### ISSUE TITLE
Android Pay support specifying shipping countries

### ISSUE THREAD

**Issue by shokimble** [tipsi/tipsi-stripe#180]
This is related to #173.

By default Android Pay only allows the user to choose an address in the USA for shipping. You have to manually specify which countries you want to accept shipping addresses for.

See:

https://developers.google.com/android/reference/com/google/android/gms/wallet/MaskedWalletRequest.Builder#addAllowedCountrySpecificationForShipping(com.google.android.gms.identity.intents.model.CountrySpecification)

I suggest adding an additional field to the options for paymentRequestWithAndroidPay that supports an array of allowed ISO codes for the countries you wish to support.

**Comment by paynd** [comment]
I'll take a look asap.

**Comment by shokimble** [comment]
Did you manage to look at this one or should we looking at the new API implementation instead?

**Comment by paynd** [comment]
@shokimble I gonna add it to both API (Android Pay and Pay-With-Google).

**Comment by paynd** [comment]
@shokimble look at #187

**Comment by shokimble** [comment]
On Android Pay I feed in an array of countries where I know Android Pay is supported like AU/UK etc and in test mode only USA is shown still. This, I believe, based on searching around is expected in test mode.

When I switch to production and switch my stripe key also when Android Pay is instantiated I get a message with request failed - An unexpected error has occurred please try again later.

adb logcat for  ReactNative only shows the following when I click ok on the dialog.

ReactNativeJS: 'Error:', { [Error: Purchase was cancelled] framesToPop: 1, code: 'PURCHASE_CANCELLED' }

I don't think this is caused by your addition. I'll roll back and check, I suspect the app needs to be authorised by Google first to go to production. I'm trying to find the docs on that.

Did you manage to get country options in the test wallet environment? Do you concur on the need to go to prod and the errors I'm getting when going?

**Comment by shokimble** [comment]
Ah yep found the info from Google. The README.md for the project links to a 404.

https://developers.google.com/payments/test-and-deploy

There are more steps involved. I'm blocked on testing until they get back to me.

**Comment by shokimble** [comment]
Google Pay Team got back to me pretty quickly. They want a production ready build which I'm nowhere near yet so I can't help test this any further at this point.

**Comment by paynd** [comment]
Hmm. Pretty strange.
For example I've used:
```
{
  total_price: '100.00',
  currency_code: 'USD',
  shipping_address_required: true,
  shipping_countries: ["US", "CA"],
  line_items: [...],
}
```
And I got 2 available countries to ship: USA, Canada.
Can you post your code somewhere?

**Comment by paynd** [comment]
When I tried:
```shipping_countries: ["AU", "UK"],```
I see only Australia available to ship.
But AFAIK there is no such ISO 3166-2 code as "UK", If you mean United Kingdom, you should use "GB" code.

**Comment by paynd** [comment]
Its obvious, but have you set stripe `publishableKey`?  :)

**Comment by paynd** [comment]
Also, take a look at #184 
I've added shipping countries option too.

**Comment by shokimble** [comment]
Argh I thought I had a clean build but it seems not. It's working now. 

I'll try with paymentRequestWithPayWithGoogle() shortly.

**Comment by paynd** [comment]
#187 has been merged
