### ISSUE TITLE
Amex CVV not handled correctly

### ISSUE THREAD

**Issue by hannta** [tipsi/tipsi-stripe#181]
Im unable to add Amex card with 4 digit CVV, using `paymentRequestWithCardForm`.

- Enter Stripe Amex test card number.
- Enter valid expiration month & year.
- Enter 4 digit CVV
- Press DONE
Nothing happens, no error message etc.

If I change CVV to 3 digit number, im able to add card.

**Comment by paynd** [comment]
@hannta It's reprodusing on android OS, isnt it?

**Comment by hannta** [comment]
@paynd yes.

**Comment by paynd** [comment]
@hannta please check code from #189 
Is it fix your problem?

**Comment by hannta** [comment]
Thanks @paynd, quickly tried this and it looks like if fixes the issue.

**Comment by cybergrind** [comment]
@hannta fix was released in 4.5.2
