### ISSUE TITLE
How do I populate Customer for credit card payments?

### ISSUE THREAD

**Issue by grahamyesfit** [tipsi/tipsi-stripe#182]
I'm calling paymentRequestWithCardForm with an options object. How do I populate the Customer? When I look at the posted payment on Stripe, the Customer column is blank (but the payment amount and credit card information is populated, and I have a chargeId).

**Comment by cybergrind** [comment]
Hey @grahamyesfit 
You should create credit card on your backend side using token from tipsi-stripe and store result in a database to reuse it. So, creating customer is basically the alias to save credit card and you should think if you really want to do it.

https://stripe.com/docs/sources/customers

**Comment by grahamyesfit** [comment]
Hey @cybergrind 
Thanks for the reply. I really don't want to create credit cards and customers in that way - I really like the way the Stripe checkout on the web works. It remembers your cards and when you call the API to make a payment, it sets the Customer column to the email address you send it - no need to create and store anything on my back end. It seems like if I want to provide the same kind of functionality for the user as web Stripe component, I'm going to have to start storing tokens and such in my back end. Is that correct?

**Comment by cybergrind** [comment]
Maybe I wasn't clear - creating the client is analog to save card information for further payments without having in your database sensitive information (like card no or cvv code).
If you want to create client with email - add email when you create customer. You don't need to store tokens - they are just one-time thing, you need to store customers tokens, they look like `cus_AFGbOSiITuJVDs`. Customer token + your secret key = ability to charge user at any moment, without having user approve and card details.
Regarding Stripe checkout on the web - I'm not sure that it doesn't store information on the backend, somewhere you need to store information. Also, you can retrieve user information from Stripe when you have customer token.
