### ISSUE TITLE
Postal code should allow alphanumeric inputs

### ISSUE THREAD

**Issue by xiamx** [tipsi/tipsi-stripe#183]
When using `paymentRequestWithCardForm` with `requiredBillingAddressFields: 'zip'`, the zip/postal code input field only allows numeric inputs. In Canada, postal code are alphanumeric.

**Comment by isnifer** [comment]
@xiamx wow, thank you.

**Comment by sunshineo** [comment]
This seems fixed to me. After switch country to Canada then zip can enter alphanumeric

**Comment by rezasazesh** [comment]
Also in Australia the Zip codes are 4 digits but the form input won't allow me to click done if the number of digits in Zip are less than 5!

**Comment by sregg** [comment]
@sunshineo how did you change the country?

**Comment by sunshineo** [comment]
@sregg I meant after user switch country on the UI the zip code input allows enter letters
