### ISSUE TITLE
Warning React Native peer dependency

### ISSUE THREAD

**Issue by henrikra** [tipsi/tipsi-stripe#190]
I get this warning when installing this module
`warning "tipsi-stripe@3.9.0" has incorrect peer dependency "react-native@^0.40".`

I am running React Native 0.50.3

**Comment by isnifer** [comment]
@henrikra yes, we know. Low priority issue

**Comment by isnifer** [comment]
@henrikra I will fix it in 4.5.1.

**Comment by henrikra** [comment]
Great!

**Comment by isnifer** [comment]
Fixed in 4.5.1
