### ISSUE TITLE
Apple Mach -o Linker error after running react-native link tipsi-stripe

### ISSUE THREAD

**Issue by SambhavAnand** [tipsi/tipsi-stripe#195]
I need to incorporate stripe payments into my react native app, and chose tipsi-stripe to do the same.
I correctly installed the tipsi-stripe module, as well as successfully linked the file, however when I try to run it through Xcode, I get an error saying Apple mach -o linker error

**Comment by isnifer** [comment]
@SambhavAnand Looks like there is no problem? Did you run `.xcodeproj` instead of `.xcworkspace`?

**Comment by SambhavAnand** [comment]
@isnifer I did run xcodeproj and got the error

**Comment by isnifer** [comment]
@SambhavAnand you should run `.xcworkspace`

**Comment by omorhefere** [comment]
hi @isnifer i ran `.xcworkspace` and still got this error
