### ISSUE TITLE
Warning: Overriding previous layout animation with new one before the first began:

### ISSUE THREAD

**Issue by SambhavAnand** [tipsi/tipsi-stripe#196]
When I render the stripe.payWithCardRequest form and submit the form, I am able to correctly long the reponse, but the following warning - 

Warning: Overriding previous layout animation with new one before the first began:
<RCTLayoutAnimationGroup: 0x608000852750; creatingLayoutAnimation: (null); updatingLayoutAnimation: <RCTLayoutAnimation: 0x608001a74740; duration: 0.250000; delay: 0.000000; property: (null); springDamping: 0.000000; initialVelocity: 0.000000; animationType: 5;>; deletingLayoutAnimation: (null)> -> <RCTLayoutAnimationGroup: 0x600000c4e5e0; creatingLayoutAnimation: (null); updatingLayoutAnimation: <RCTLayoutAnimation: 0x600001274840; duration: 0.400000; delay: 0.000000; property: (null); springDamping: 0.000000; initialVelocity: 0.000000; animationType: 5;>; deletingLayoutAnimation: (null)>.

How do I Solve this?

**Comment by isnifer** [comment]
@SambhavAnand Hi! There is no method called `payWithCardRequest`

**Comment by SambhavAnand** [comment]
@isnifer thanks for the quick response.

I meant the paymentRequestWithCardForm method. Sorry for the confusion

**Comment by isnifer** [comment]
@SambhavAnand show me how do you call this method

**Comment by SambhavAnand** [comment]
@isnifer 
<img width="841" alt="screen shot 2017-12-10 at 4 00 57 pm" src="https://user-images.githubusercontent.com/12015103/33809348-647a81c4-ddc3-11e7-85c9-4a0acae92c67.png">

**Comment by isnifer** [comment]
@SambhavAnand Looks like in this moment multiple components do animations, yes?

**Comment by SambhavAnand** [comment]
@isnifer That's the error that I'm getting, but I don't see what the other animation is. Any ideas?

**Comment by SambhavAnand** [comment]
Great. Will do. Thank you so much!

**Comment by isnifer** [comment]
@SambhavAnand write me if it will not helpful

**Comment by SambhavAnand** [comment]
Thank you. I'm trying to figure it out with the help of the example.
-Sambhav

**Comment by SambhavAnand** [comment]
@isnifer I'm still getting the same issue

**Comment by isnifer** [comment]
@SambhavAnand what's happened on click? Code from Example doesn't produce this error, I'm sure

**Comment by SambhavAnand** [comment]
So I changed the basic structure to make it like in the example ->
there's basically a button that when I click, it renders the page. When I enter the data, I get the same warning

**Comment by isnifer** [comment]
@SambhavAnand try do not render anything - just get a response. Looks like your renders produce an error

**Comment by SambhavAnand** [comment]
This is what I did


import React, {PureComponent} from 'react';
import { View, Text, StyleSheet } from 'react-native';
import stripe from 'tipsi-stripe';
import {Button} from 'native-base';

stripe.init({
  publishableKey: ''
});

export default class Payments extends PureComponent {
  state ={
    loading: false,
    token: null
  }
  handleCardPayPress = async () => {
    try {
      this.setState({
        loading: true,
        token: null,
      })
      const token = await stripe.paymentRequestWithCardForm({
        // Only iOS support this options
        smsAutofillDisabled: true,
        requiredBillingAddressFields: 'zip',
      })

      console.log('Result:', token) // eslint-disable-line no-console
      this.setState({
        loading: false,
        token,
      })
    } catch (error) {
      console.log('Error:', error) // eslint-disable-line no-console
      this.setState({
        loading: false,
      })
    }
  }

  render() {
    const { loading, token } = this.state

    return (

      <Button onPress={this.handleCardPayPress}>
      <Text>Click me</Text>
      </Button>




    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instruction: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  token: {
    height: 20,
  },
})

**Comment by SambhavAnand** [comment]
@isnifer any thoughts?

**Comment by isnifer** [comment]
@SambhavAnand I don't see any issues
![paymentrequestwithcardform](https://user-images.githubusercontent.com/1788245/33820864-7b659262-de62-11e7-8258-b1ceafb9bb92.gif)
