### ISSUE TITLE
Build failed after upgrading to React Native v0.51.0

### ISSUE THREAD

**Issue by ikhsanalatsary** [tipsi/tipsi-stripe#198]
This problem after upgrading my project dependencies to react-native v0.51.0, react v16.0.0, tipsi-stripe v4.5.1 & try building iOS in Xcode v8.2.1. Screenshots:
1. 
![screen shot 2017-12-12 at 8 21 01 pm](https://user-images.githubusercontent.com/5897415/33887029-ff57f0e2-df7a-11e7-8dfc-fb00f1e1c7b9.png)
2.
![screen shot 2017-12-12 at 8 21 37 pm](https://user-images.githubusercontent.com/5897415/33887052-0c647c9c-df7b-11e7-9e6c-f23b53705c7e.png)
3.
![screen shot 2017-12-12 at 8 21 56 pm](https://user-images.githubusercontent.com/5897415/33887060-10f65230-df7b-11e7-94ff-20312c6d4d93.png)
4.
![screen shot 2017-12-12 at 8 22 36 pm](https://user-images.githubusercontent.com/5897415/33887067-165a0302-df7b-11e7-933d-c8e4a696a105.png)
5.
![screen shot 2017-12-12 at 8 22 48 pm](https://user-images.githubusercontent.com/5897415/33887073-1aa7e730-df7b-11e7-8e45-bb4b296b9170.png)

how to resolve this problem?

Thank you

**Comment by isnifer** [comment]
@ikhsanalatsary update Stripe pod:
```
pod 'Stripe', '~> 11.2.0'
```

**Comment by ikhsanalatsary** [comment]
Thank you @isnifer the problem solved but still no luck with other dependencies :confused:

**Comment by isnifer** [comment]
@ikhsanalatsary don't forget `pod install`. Search issues for other deps on the github

**Comment by xuanheScript** [comment]
@ikhsanalatsary I also encountered this problem, can tell is how to solve it?

**Comment by isnifer** [comment]
@xuanheScript open your Podfile and update Stripe pod:
```
pod 'Stripe', '~> 11.2.0'
```

**Comment by xuanheScript** [comment]
@isnifer I write in the Podfile will be wrong, if you do not add the version number there is no problem
![image](https://user-images.githubusercontent.com/19216775/34260866-373e564e-e6a2-11e7-9d05-56b0b335458c.png)
![image](https://user-images.githubusercontent.com/19216775/34260882-4677bdee-e6a2-11e7-8af0-a205c5713bbe.png)

**Comment by isnifer** [comment]
@xuanheScript so next thing like your terminal said just do:
```
pod repo update
```

**Comment by xuanheScript** [comment]
@isnifer Thank you, I try, this may be a long time, because the Chinese firewall, you know, if you still have problems, I will contact you, thank you very much for your guidance 😄

**Comment by isnifer** [comment]
@xuanheScript yes, sure.
