### ISSUE TITLE
Native module AccessibilityInfoModule tried to override AccessibilityInfoModule for module name AccessibilityInfo

### ISSUE THREAD

**Issue by trustfall** [tipsi/tipsi-stripe#199]
I'm working with an ExpoKit build, and have a working build with iOS, and I think I just about have it working with Android, I'm trying to find out where I could possibly remove this instance, or where it might be coming from? I see a lot of issues where people are calling two instances of a package in `MainApplication.java`, but I am just calling one. Any idea where this issue may be happening?

**Comment by isnifer** [comment]
@trustfall If you're using Expo, use their own copy of `tipsi-stripe` https://github.com/expo/expo/commit/af4336849902454dc1c8df6f4702d156761e977f

**Comment by trustfall** [comment]
We were just a bit concerned as it looks as though it hasn't been updated in 3 months, that's why we chose to just use tipsi instead 😃

**Comment by isnifer** [comment]
@trustfall Hi, did you solve your issue?

**Comment by trinadhkoya9** [comment]
@isnifer how can you close this. We are experiencing the same issue
