### ISSUE TITLE
unable to load script from assets 'index.android.bundle'

### ISSUE THREAD

**Issue by llvc** [tipsi/tipsi-stripe#203]
I cloned the 'tipsi-stripe' and run the react-native project in example folder.
Nothing is changed in package.json. I just run it.
Build succeeded.
But I got an error **'unable to lead script from assets 'index.android.bundle''** on android phone after launch.
Let me know what's wrong.
Thanks.

**Comment by llvc** [comment]
I could resolve this by https://stackoverflow.com/questions/44446523/unable-to-load-script-from-assets-index-android-bundle-on-windows

**Comment by digvijayMobantica** [comment]
This issue helped me resolve the problem in following steps.

(in project directory) mkdir android/app/src/main/assets

react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

react-native run-android

**Comment by VKGraphics** [comment]
same error give me solution ?

**Comment by digvijayMobantica** [comment]
Above code work for your issue.

I have same error but it solved my problem
