### ISSUE TITLE
cardId of stripe response is null in android

### ISSUE THREAD

**Issue by llvc** [tipsi/tipsi-stripe#206]
I am showing a snippet.
```
const options = {
            smsAutofillDisabled: true
}

stripe.paymentRequestWithCardForm( options )
        .then( function( res ) {
            console.log(res)
            console.log('token=:', res.tokenId)
            console.log('card id=:', res.card.cardId)
        } )
```
I can get tokenId and cardId in ios version.
But I can also get a tokenId in android but cardId is null in android.
Let me know what's wrong.
Thanks

**Comment by paynd** [comment]
@llvc Thank you for issue. Will fix it asap.

**Comment by paynd** [comment]
@llvc check #207

**Comment by llvc** [comment]
I removed tipsi-stripe by command and installed again.
but I cannot still get a cardId in android.
I am attaching a response from stripe

```
card:
	addressCity: null
	addressCountry: null
	addressLine1: null
	addressLine2: null
	addressState: null
	addressZip: null
	brand: "Visa"
	cardId: null
	country: "US"
	currency: null
	expMonth: 4
	expYear: 2024
	last4: "4242"
	name: null
__proto__: Object
created: 1513687765000
livemode: false
tokenId: "tok_1BakXXXXXXXXXX"
user: false
```
Thanks

**Comment by kingarawana** [comment]
Any updates on when this fix will be merged? I'm running into the same bug. Is there anything I can do to get it working locally until this gets merged to master?

**Comment by isnifer** [comment]
@kingarawana I hope, today. Just wait for tests

**Comment by isnifer** [comment]
@llvc @kingarawana fixed in 4.5.2

**Comment by llvc** [comment]
Very thanks. It's fixed

**Comment by isnifer** [comment]
@llvc awesome, thank you for your feedback
