### ISSUE TITLE
Genetare token of Bank account using createTokenWithBankAccount method without routingnumber parameter

### ISSUE THREAD

**Issue by wmt-iOS-Harpal** [tipsi/tipsi-stripe#208]
To create a token with Bank account we have **createTokenWithBankAccount** method. It has **routingNumber** as an optional parameter as describe in a document and I use that library to use in Singapore. How to create token without giving routing number ??
```js
let params = {
                // mandatory
                accountNumber: '000123456',
                countryCode: 'sg',
                currency: 'sgd',
                accountHolderName: 'Test user'
            };
await stripe.createTokenWithBankAccount(params)
                .then((data) => {
                    this.addToken(data.tokenId, data.bankAccount.last4);
                }).catch((error) => {
                    this.setState({
                        isLoaderVisible: false
                    });
                    showSnackBar(error.message);
                });
});
```

**Comment by paynd** [comment]
Hi @wmt-iOS-Harpal [Here](https://stripe.com/docs/api#customer_create_bank_account)  `routing_number` marked as optional parameter. Looks like it is depends on country. 

> The routing number, sort code, or other country-appropriate institution number for the bank account. For US bank accounts, this is required and should be the ACH routing number, not the wire routing number. If you are providing an IBAN for account_number, this field is not required. 

May be it's required for Singapore?

**Comment by wmt-iOS-Harpal** [comment]
In Singapore there is not such a thing. I don't have routing number. Document describes that is optional but I can't proceed without routing number

**Comment by paynd** [comment]
Looks like you are right. But it would be better to ask this question to stripe team. 
https://github.com/stripe/stripe-android/issues/495

**Comment by paynd** [comment]
Also created issue in [stripe-ios](https://github.com/stripe/stripe-ios/issues/874) too.

**Comment by Happudada** [comment]
In **stripe/stripe**'s document to create bank account token routing number is given as an optional, but we can't leave it as optional.

To solve that issue I research some bank related sites and find one solution.
The Routing number is a 7 digit number which is a combination of **Bank code** and **Branch code**.

**Bank code is 4 digit number** and **Branch code is 3 digit** number. By combine that two respected number we can make routing number.

Parameter to pass in **createTokenWithBankAccount** method
```js
let params = {
                accountNumber: this.state.accountNo,
                countryCode: 'sg',
                currency: 'sgd',
                routingNumber: `${this.state.bankCode}${this.state.branchCode}`
            };
```

I design Payment screen as under

![simulator screen shot 20-dec-2017 2 59 56 pm](https://user-images.githubusercontent.com/31007929/34200456-25a4c424-e597-11e7-95da-5d29ae920405.png)

**Comment by paynd** [comment]
Thank you @Happudada!
@wmt-iOS-Harpal Does it helps?

**Comment by wmt-iOS-Harpal** [comment]
Yes it is work for me now.!!
txxx @Happudada

**Comment by isnifer** [comment]
Awesome!
