### ISSUE TITLE
This library allows subscription?

### ISSUE THREAD

**Issue by developersoul** [tipsi/tipsi-stripe#209]
I wanna create a subscription, instead of one payment, is possible?

**Comment by isnifer** [comment]
@developersoul no

**Comment by Dallas62** [comment]
@isnifer @developersoul 
Actually you can use the token or create a source and after that, create a subscription in your backend.
For now, it's work with cards (auto-renew) and I will try soon with ApplePay/GooglePay.

**Comment by JanErikFoss** [comment]
@Dallas62 What's the status on this now?

**Comment by cybergrind** [comment]
@JanErikFoss it should work if you create source from token. At least you can find some other question where I've answered to the similar question
