### ISSUE TITLE
Changelogs

### ISSUE THREAD

**Issue by hannta** [tipsi/tipsi-stripe#210]
It would be nice to have some kind of changelog at least on breaking changes.

There is recent major release 4.0.0 but no words what has changed? And in 4.1.2 there is breaking change, you need to add `tipsiStripeRedirectScheme` to your `build.gradle`?

**Comment by isnifer** [comment]
@hannta https://github.com/tipsi/tipsi-stripe/pull/133
We have already a PR to make `tipsiStripeRedirectScheme` not required

**Comment by hannta** [comment]
Ok thanks @isnifer  This issue was more about changelogs overall, `tipsiStripeRedirectScheme` was just good example why changelogs are important 🙂

**Comment by apolishch** [comment]
I would LOVE this product to adopt changelogs...

**Comment by isnifer** [comment]
https://tipsi.github.io/tipsi-stripe/docs/changelog.html
