### ISSUE TITLE
Add a `keyboardAppearance` prop to <PaymentCardTextField .../> to set the Keyboard in 'light' or 'dark'

### ISSUE THREAD

**Issue by BricePissard** [tipsi/tipsi-stripe#212]
Would be nice to be able, as it is available for ```<TextInput />```, to set the `keyboardAppearance` as:
```javascript
<PaymentCardTextField
  ...
  keyboardAppearance = {"dark"}
/>
```
Otherwise if the theme of the app is in `dark` it's a bit ugly to have the `light` keyboard appearing.

Is it complicated to implements?

**Comment by isnifer** [comment]
Hi, @BricePissard, we will take a look!

**Comment by densa** [comment]
#249
