### ISSUE TITLE
cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by kingtross88** [tipsi/tipsi-stripe#213]
getting error while initializing stripe. Does anyone know how to properly set this up?

**Comment by isnifer** [comment]
@kingtross88 did you read [any related](https://github.com/tipsi/tipsi-stripe/search?q=init&type=Issues&utf8=%E2%9C%93) issues about that?

**Comment by wmonecke** [comment]
@kingtross88  Had the same issue. Just close your simulator and your packager, then re-run `react-native run-ios` or  `react-native run-android`.

**Comment by isnifer** [comment]
I'm closing this issue cause it's inactive
