### ISSUE TITLE
I get a linker error when building my project

### ISSUE THREAD

**Issue by omorhefere** [tipsi/tipsi-stripe#215]
After following the tutorial here: https://github.com/tipsi/tipsi-stripe

I get this error: 
"Apple Mach-O Linker (ld) Error Group" 
":Linker command failed with exit code 1 (use -v to see invocation)"

I opened my project using`.xcworkspace`

For the last part of the tutorial where it says: 
"Drag the following folder into your project:
node_modules/tipsi-stripe/ios/TPSStripe/
"

I dragged that file into the folder that held the folders called "pods", "products", "frameworks"

Was that the correct thing to do?

Also when I link "tipsi-stripe" I get an error because I don't have an android folder. I only have ios, do i need to have an android folder?

**Comment by isnifer** [comment]
@omorhefere did you install pods?

**Comment by omorhefere** [comment]
@isnifer hi, yes i did. I updated my post.

**Comment by isnifer** [comment]
@omorhefere so, If you did manual linking - did you do steps 3 and 4? https://github.com/tipsi/tipsi-stripe#manual

**Comment by omorhefere** [comment]
@isnifer ohh, i wasn't aware that I also had to do the steps under manual. I'll do that now. btw, where do i fin `libTPSStripe.a`?

**Comment by isnifer** [comment]
@omorhefere you should use `react-native link tipsi-stripe` or manual linking.
If you drag TPSStripe manually into your project that means you did manual linking.
Or you did it after `react-native link tipsi-stripe`?

**Comment by omorhefere** [comment]
i did it after ` react-native link tipsi-stripe`

**Comment by isnifer** [comment]
@omorhefere so, you shouldn't do it. `react-native link tipsi-stripe` already done it. https://github.com/tipsi/tipsi-stripe/blob/master/scripts/post-link-ios.rb

I would like to recommend you remove folder that you drag manually from workspace and try to rebuild

**Comment by omorhefere** [comment]
Thank you, i did this but still got the same error. I even deleted node modules and reinstalled everything.

when i run `react-native link` i get this error 'Error: ENOENT: no such file or directory, open '/Users/omorhefere/VA/code/vBus/android/build.gradle' because i don't have an android folder just IOS. I'm detaching from expokit. 

Could that be causing a problem

**Comment by isnifer** [comment]
@omorhefere wow. Expo has their own copy of `tipsi-stripe`. I recommend you use it

**Comment by omorhefere** [comment]
Thank you, it builds when I use that.
