### ISSUE TITLE
Issue while creating token with bank account with IBAN.

### ISSUE THREAD

**Issue by wmonecke** [tipsi/tipsi-stripe#216]
When creating a token with a bank account like so:
```
const tokenParams = {
   accountNumber: this.state.ibanInput,
   countryCode: 'es',
   currency: 'eur',
   accountHolderName: this.state.bankOwnerName,
   accountHolderType: this.state.type
};

stripe.createTokenWithBankAccount(tokenParams)
.then(token => console.log(token))
.catch(err => console.log('error while creating token from bank account:', err));
```
 I see the following error:

`Error: You cannot use a live bank account number when making transfers or debits in test mode`

The app is for Spain so for `accountNumber` I am providing an IBAN (maybe this is the issue?).
But the Stripe docs do say that you can do this in Spain. I was looking into [#208](https://github.com/tipsi/tipsi-stripe/issues/208).

I am not doing transfers or debits, just creating a token to connect the bank account to a stripe account (using Stripe-Connect here). Where can I find a "test" bank account or where can I enable creating tokens with real bank accounts?

**Comment by paynd** [comment]
Can you try one of [this test numbers](https://stripe.com/docs/connect/testing#account-numbers) (choose IBAN options from dropdown)? Looks like in test mode Stripe assumes that any number that isn't explicitly one of their test numbers is a potentially real account.

**Comment by wmonecke** [comment]
@paynd Oh wow I am sorry I missed that in the docs. Thank you so much for pointing it out!

**Comment by wmonecke** [comment]
@paynd I tried using the provided accounts like this one: 
```
DE89370400440532013000 | Payout succeeds.
```

yet I still see the same error. Any clue on how to approach this?

**Comment by paynd** [comment]
@wmonecke hmm.
```
params: {
      accountNumber: 'DE89370400440532013000', // required field
      countryCode: 'de', // required field
      currency: 'eur', // required field
      accountHolderName: 'Test holder name',
      accountHolderType: 'company',
    }
const token = await stripe.createTokenWithBankAccount(this.state.params)
console.log('Result:', token) // eslint-disable-line no-console
```
That works for me:
<img width="469" alt="default" src="https://user-images.githubusercontent.com/1286226/34342786-1d9a9d7e-e9cc-11e7-8139-6b0fac1b7922.png">

**Comment by isnifer** [comment]
@wmonecke Hi, did you solve your issue?

**Comment by wmonecke** [comment]
Yes I did, I was missing out on the `countryCode:` 'de', // required field`.

Thanks!!
