### ISSUE TITLE
allow to add optional fields to a card

### ISSUE THREAD

**Issue by fabriziomoscon** [tipsi/tipsi-stripe#22]
Would it be possible to change the method `createTokenWithCard` https://github.com/tipsi/tipsi-stripe/blob/issue_18/android/src/main/java/com/gettipsi/stripe/StripeModule.java#L179-L202
to allow the card object to have `Name` and `AddressZip`? I believe those fields are very important to enhance antifraud tools.

```
card.setName();
card.setAddressZip();
```

**Comment by itsmepetrov** [comment]
Fixed in #24
