### ISSUE TITLE
Cannot read property 'init' of undefined for stripe.init()

### ISSUE THREAD

**Issue by GenericJam** [tipsi/tipsi-stripe#223]
I am successfully using this library on Android with no problems. On iOS, I cannot get past this error. I have tried to follow all of the other fixes in the other bug report threads with similar issues to no avail. ([#102](https://github.com/tipsi/tipsi-stripe/issues/102), [#53](https://github.com/tipsi/tipsi-stripe/issues/53), [#81](https://github.com/tipsi/tipsi-stripe/issues/81)) This includes reinstalling the project and starting from scratch several times. Using the instructions with Pods and manually. I have installed the example project and got it working.
This has never been an Expo project.
The library links and appears to be working until I try to initialize it with stripe.init().

`import stripe from 'tipsi-stripe';
console.log('STRIPE', stripe);

stripe.init({
  publishableKey: 'pk_test_xxxx'
});`

This console log shows that it is there but when I actually try to use it, it says it is undefined.
`STRIPE Stripe {stripeInitialized: false, init: function, deviceSupportsApplePay: function, canMakeApplePayPayments: function, paymentRequestWithApplePay: function…}canMakeApplePayPayments: function ()cancelApplePayRequest: function ()completeApplePayRequest: function ()createSourceWithParams: function ()createTokenWithBankAccount: function ()createTokenWithCard: function ()deviceSupportsApplePay: function ()init: function ()openApplePaySetup: function ()paymentRequestWithApplePay: function ()paymentRequestWithCardForm: function ()stripeInitialized: true__proto__: Object
ExceptionsManager.js:65 Cannot read property 'init' of undefined`
  
  
![image](https://user-images.githubusercontent.com/5807145/34740746-bacd7f90-f53d-11e7-8d25-f420fdddf81b.png)
![image](https://user-images.githubusercontent.com/5807145/34741127-e45500f8-f53e-11e7-80e6-520fcf86a9ea.png)

If I run stripe.init() without any arguments which makes it fail as it should, I get this error:
ExceptionsManager.js:65 Failed options type: The options `publishableKey` is marked as required in `Stripe.init`, but its value is `undefined`.
What is going on?

**Comment by GenericJam** [comment]
Working now. It was a linking error. Make sure the Header Search Paths at the PROJECT level are linking to the Stripe ones in node_modules>tipsi-stripe>ios>TPSStripe.

Thanks for this library. Very helpful!

**Comment by wmonecke** [comment]
Hi @GenericJam!

I just installed the library and came to this exacts same issue. I can also log stripe and I can see the `.init` function available although it fails when I use it.

I have no clue what the Header Search Paths are or how to set them properly (I come from web development). Could you be more specific on how to set this correctly (through xCode or where)?

Thank you!

**Comment by isnifer** [comment]
@wmonecke just start reading [Installation guide](https://github.com/tipsi/tipsi-stripe#installation)

**Comment by GenericJam** [comment]
I agree you should follow the installation guide as that seems to work for most people but I tried both methods (pod and manual) and it didn't copy over the header search paths it needed to build properly. It will build but it doesn't get put into 'NativeModules' so it isn't there when tipsi-stripe tries to pull it out and you get the undefined or null type error when you try to use it.

[Using this screen as a guide](https://github.com/tipsi/tipsi-stripe/issues/102#issuecomment-322169160), you need to make sure the bottom one is one your list in the Header Search Paths. If you are new to Xcode, click on the folder at the top left of the left pane. This will bring you back to your project folder. Click on the folder at the top that has your project name, go to Build Settings in the center panel. [Look here](http://docs.bluedotinnovation.com/display/DEVDOC10/iOS+-+Setting+the+Header+Search+Path) for reference of what it should look like. There will probably be lots of things in this so just do a search in the top right corner of the center panel for 'header search paths' or something similar and go to the results. Click on the paths section and it will pop up this little dialog to allow you to edit them. You can either type it in manually or with Finder open you can drag the node_modules>tipsi-stripe>ios>TPSStripe folder into this dialog and it will link them itself.

That was what solved it for me. Apologies if any of these instructions are inaccurate as I'm doing it from memory as I'm not at work. Hopefully this fixes it for you.

Also, when in doubt clean your build and or build folders.

**Comment by hopewise** [comment]
@GenericJam  broken link http://docs.bluedotinnovation.com/display/DEVDOC10/iOS+-+Setting+the+Header+Search+Path

**Comment by GenericJam** [comment]
@hopewise 
Try this:
https://docs.bluedot.io/ios-sdk/ios-faq-troubleshooting/
![image](https://user-images.githubusercontent.com/5807145/56219800-a2c18400-6067-11e9-9477-5b0f63e580f7.png)

The screen looks like this:
https://i.stack.imgur.com/PDEAj.png

**Comment by hopewise** [comment]
Thanks @GenericJam

**Comment by spyshower** [comment]
$Genericjam Can you give me some help here please? It's been so many hours working on this and I still can't get it working...

<img width="1260" alt="Screenshot 2019-04-24 at 23 11 58" src="https://user-images.githubusercontent.com/7046283/56690574-73092080-66e6-11e9-9ec4-39f61db56b31.png">

**Comment by spyshower** [comment]
@GenericJam
