### ISSUE TITLE
No entitlement for merchant identifier

### ISSUE THREAD

**Issue by sbkl** [tipsi/tipsi-stripe#224]
Hi,

I don't think this issue is related to the tipsi-stripe library but I post it here in case someone encountered this issue.

I'm stuck with this issue when trying to make the test on an actual device (payment interface opens properly on simulator):

=> Failed to present in-app payment interface: Error Domain=PKPassKitErrorDomain Code=4 "No entitlement for merchant identifier: myMerchantId" UserInfo={NSLocalizedDescription=No entitlement for merchant identifier: myMerchantId}.

Steps I have followed:

from the Stripe website, I have downloaded the stripe.certSigningRequest

In my apple developer account, App id (I'm using push notifications successfully) and merchant id are created and I created the Payment Processing Certificate linked to that merchant id with the stripe.certSigningRequest from the above step.

I doubled clicked this file to put it in my Keychain access (certificate status showing 'This certificate is valid').

Then I uploaded this certificate to the stripe website in my account.

Apple pay is activated in xcode with the relevant merchant id checked in.

I tried to clear the provisioning profile created automatically by xcode and downloaded them manually as I thought it was an issue with cache not being reset properly.

Any idea what I am missing?

**Comment by sbkl** [comment]
Actually forgot to add merchant. in front the merchant id when declaring with tipsi-stripe. My bad.

**Comment by anatoliykant** [comment]
> Actually forgot to add merchant. in front the merchant id when declaring with tipsi-stripe. My bad.

Hey, @sbkl 
And where do you need to add merchant in the code of a mobile iOS application or in the tipsi-stripe admin area?

**Comment by sbkl** [comment]
In the code. Add it to a .env file with  [react native dotenv](https://www.npmjs.com/package/react-native-dotenv) and reference its variable into the code.

**Comment by Assass1n1191** [comment]
I had exactly same issue and the problem was that I had a typo in code, in merchantIdentifier in PKPaymentRequest object
