### ISSUE TITLE
paymentRequestWithCardForm crashes system.

### ISSUE THREAD

**Issue by hegemon33** [tipsi/tipsi-stripe#229]
Hello,
I'm trying to use paymentRequestWithCardForm to get client's credit card number and do the payment but find out I can't just prefill country code 'HK'  (Hong Kong) as below...

```
const options = {
        requiredBillingAddressFields: 'full',
        managedAccountCurrency: 'HKD',
        prefilledInformation: {
          billingAddress: {
            country: 'HK',
          },
        },
      };
const token = await stripe.paymentRequestWithCardForm(options);
```

The above code will crash Xcode simulator.
If I change the country to 'US'  or 'TW' everything was fine.

Can anyone help check this? Thanks a lot.

Note:
I'm using the packages below:
"react": "^16.2.0",
"react-native": "^0.52.0",
"tipsi-stripe": "^4.6.1",

**Comment by isnifer** [comment]
@hegemon33 first of all - what OS?

**Comment by hegemon33** [comment]
I'm using the latest xcode, so it should be ios 11.

**Comment by isnifer** [comment]
@hegemon33 Hi, did you solve your issue?

**Comment by joshuadiezmo** [comment]
Same Error. but for me, its  fine if I use HK.

**Comment by mitul-alliancetek** [comment]
I have same issue app crashed once i fill the information 

```
const options = {
      requiredBillingAddressFields: 'full',
      prefilledInformation: {
        billingAddress: {
          name: 'Gunilla Haugeh',
          line1: 'Canary Place',
          line2: '3',
          city: 'Macon',
          state: 'Georgia',
          country: 'US',
          postalCode: '31217',
        },
      },
    }
```

This is what i have used
