### ISSUE TITLE
Stripe/Stripe.h' file not found

### ISSUE THREAD

**Issue by BlackStef** [tipsi/tipsi-stripe#230]
Hi, I've got a problem with this stripe API (only on IOS). 
I know they are a lot of topic about this error, but I didn't found anything working... 

I can't make the troubleshooting section of this tuto cause I don't have the "build phase" tab in TPStripe.xcodeproj. Only "infos" and "build settings". 

![image](https://user-images.githubusercontent.com/12743769/35488111-ad4f977c-0483-11e8-988a-1cc06b6bc279.png)

I've trying this : 
https://github.com/tipsi/tipsi-stripe/issues/29

But I don't have Framework search path in my build settings of stripe project. 
I don't use Cocoapods, I link all my libraries manually. 

Thank you in advance :)

**Comment by isnifer** [comment]
@BlackStef you should use Pods. If you didn't install pods you've got this error.

**Comment by isnifer** [comment]
It's pretty simple – xcode can't find something if you didn't install it

**Comment by BlackStef** [comment]
And it's pods ? 
Strange, in the tuto they are few way, with pods, with react-native link, and manually. 

Since I develop on react-native I've never had to install pods. I have a lot of different library ^^ 
xCode is looking for Stripe.h, not pods ?

**Comment by isnifer** [comment]
@BlackStef and it means nothing, lol. `tipsi-stripe` is a wrapper around iOS and Android bindings for Stripe. Stripe delivers their library as Pod. We just use it and wrap for you.

**Comment by BlackStef** [comment]
So I just installed pods and configure the podsfile as on the example. I don't have my error anymore, he pass this step when compiling. 

But in the final phase (after "linking" on xCode) I have these errors : 
![image](https://user-images.githubusercontent.com/12743769/35693077-5f4b6cf2-077d-11e8-8be2-d00bb4b4f255.png)

I have lunch my react-native link after that to try but every is already linked : 
![image](https://user-images.githubusercontent.com/12743769/35693132-84cbd3d6-077d-11e8-9163-1edb951692c2.png)

Do you have an idea ?

**Comment by densa** [comment]
@BlackStef you install pods for testing target
Try move lines from **#Stripe** to **#Pods for testing** under **#Pods for cookin** line

**Comment by BlackStef** [comment]
Ok it work now :) 
Sorry I don't know cocoapods.. Seems complicated. 

Thank you !

**Comment by leoskyrocker** [comment]
Ran into the same problem and suspected that `pod install` was needed. It wasn't from the documentation though as the manual ios steps didn't really say anything about having to do `pod install`. To me it reads like:
Option A) run react-native link
Option B) use cocoapods
Option C) do it manually

I chose option A, but ended up realizing that you need both Option A + Option B for it to work.

**Comment by isnifer** [comment]
@leoskyrocker `react-native link` includes a step with cocoapods https://github.com/tipsi/tipsi-stripe/blob/master/scripts/post-link-ios.rb

**Comment by leoskyrocker** [comment]
Thanks @isnifer, it was definitely failing silently then because cocoapods is not installed in my machine as of running `react-native link`.
Glad to know it has the lines though. For me since I don't have cocoapods I had to do `sudo gem install -n /usr/local/bin cocoapods`, remove the pod line for Stripe from ios/Podfile and rerun the link script (or manually run pod install).

**Comment by guidolodetti** [comment]
Same problem for me. Tried multiple times, always following the documentation instructions and even trying installing Stripe manually, but there is no way for me to compile the example! What can I do?

**Comment by isnifer** [comment]
@guidolodetti `'Stripe/Stripe.h' file not found` means — you didn't install Stripe pod correctly.

**Comment by guidolodetti** [comment]
@isnifer what's the correct way to install the framework? `git clone`d the project and followed the instruction; feels a bit strange I have to install it manually

**Comment by isnifer** [comment]
@guidolodetti, first of all, you should check that you have `pod` command. Show me result of:
```sh
which pod
```

**Comment by celwell** [comment]
> Thanks @isnifer, it was definitely failing silently then because cocoapods is not installed in my machine as of running `react-native link`.
> Glad to know it has the lines though. For me since I don't have cocoapods I had to do `sudo gem install -n /usr/local/bin cocoapods`, remove the pod line for Stripe from ios/Podfile and rerun the link script (or manually run pod install).

was failing silently for me too; once I installed the cocoapods gem it worked!

**Comment by seamive** [comment]
Hello,
We ran the following
```
yarn add tipsi-stripe
cd ios && pod install

```


### POD FILE
```

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'mySuperApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Pods for mySuperApp

  #OpenSSL
  pod 'OpenSSL-Universal', '~>1.0.2.20'
  #Stripe
  pod 'Stripe'#, '~> 19.4.0'
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Firebase/AppDistribution'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'

  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'
  target 'mySuperAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```

Then after this

We did `'npx react-native link tipsi-stripe'` and it linked

But we still get the error, we are not sure about 1 thing and that is where to copy the folder of i.e node_modules/tipsi-stripe/ios/TPSStripe/


We're getting build failed for the same reason Stripe/Stripe.h not found however when we check the Pod folder, the Stripe folder is there and pod installed it!
