### ISSUE TITLE
createSourceWithParams fails type validation

### ISSUE THREAD

**Issue by corysimmons** [tipsi/tipsi-stripe#232]
https://github.com/tipsi/tipsi-stripe/blob/master/src/utils/types.js#L104 should include `card` or https://github.com/tipsi/tipsi-stripe#params-2 should be updated to remove `card` from `type`.

**Comment by prayasht** [comment]
Running into the same problem with using `createSourceWithParams` with a card.

**Comment by khatri** [comment]
Hi Guys,
Any update on this issue ?

**Comment by iagorm** [comment]
I'm using expo wrapper of this lib and this error still exists, anything we can do to create a source with a card, I really need this feature because of 3D cards existence.

**Comment by cybergrind** [comment]
@iagorm I don't see any tests in this PR. So it can be merged only with tests

**Comment by iagorm** [comment]
This night I can fork the project and make a PR of this problem.

**Comment by Slexom** [comment]
I've the same issue.
 `"dependencies": {
    "react": "16.6.1",
    "react-native": "0.57.5",
    "tipsi-stripe": "^6.1.2"
  },`
`Error: Failed params type: Invalid params `type` of value `card` supplied to `Stripe.createSourceWithParams`, expected one of ["bancontact","giropay","ideal","sepaDebit","sofort","threeDSecure","alipay"].`
