### ISSUE TITLE
StripeModule, CreditCardFormOnChangeEvent is not working with com.facebook.react

### ISSUE THREAD

**Issue by lin-zy1229** [tipsi/tipsi-stripe#236]
Errors in `com.gettipsi.stripe.StripeModule`, and `com.gettipsi.stripe.CreditCardFormOnChangeEvent` class.

In build.gradle, I used this.
`implementation "com.facebook.react:react-native:+" `

Well, there is not `com.facebook.react.bridge.BaseActivityEventListener` class, and `StripeModule` can't be compiled.
And `com.facebook.react.uimanager.events.Event` class doesn't have suitable constructor, and `CreditCardFormOnChangeEvent` class can't be complied also.

react-native: 0.52

Build failed in Android Studio:
<img src='https://image.prntscr.com/image/ttDvKFbtRDmJrhVe0YKJ1w.png'></img>

- `com.gettipsi.stripe.StripeModule`
<img src='https://image.prntscr.com/image/Rh3a_idWQO2RmqU182FDtg.png'></img>
<img src='https://image.prntscr.com/image/HMb5QRriT4G095ckgX3W7A.png'></img>

- `com.gettipsi.stripe.CreditCardFormOnChangeEvent`
<img src='https://image.prntscr.com/image/XiE1CmyQTwybxO2BTZCmrw.png'></img>

**What is the solution to make this work?**

**Comment by isnifer** [comment]
@lin-zy1229 did you solve your issue?
How did you install `tipsi-stripe` to your application? Did you follow all guides?

**Comment by lin-zy1229** [comment]
@isnifer I resolved it by using lower version of react.
    "react": "16.0.0",
    "react-native": "0.51.0",
it works for theses.
