### ISSUE TITLE
manual install - cannot find libTPSStripe.a 

### ISSUE THREAD

**Issue by ionatower** [tipsi/tipsi-stripe#237]
Hi, we do not use cocoapods in our projects and would like to use the manual option but couldn't find this file: libTPSStripe.a

**Comment by isnifer** [comment]
`tipsi-stripe` is a wrapper around native modules for both platforms

**Comment by ionatower** [comment]
I searched the directory and I cant find it.

**Comment by isnifer** [comment]
@ionatower yes, sure! If you didn't install Stripe Pod you will not find it

**Comment by ionatower** [comment]
Is there no way of doing this without cocoapods? it is a real issue for us.

**Comment by isnifer** [comment]
@ionatower currently — no. What's wrong with Pods? You're not the first with this problem, but all of people just install Stripe Pod

**Comment by ionatower** [comment]
We avoid pods where possible, we have experienced a lot of problems with them. Also it is a complex setup with our CI environment which does our build and tests. If there is a better way without pods, that would be preferable.

**Comment by nzrsrk** [comment]
what you mean by stripe pod??? no information about that in official tipsi stripe site.. how will use the codpod?? please help 
Manual step 3:
Add libTPSStripe.a to Build Phases → Link Binary With Libraries. i cant find libTPSStripe.a on bulid phase

**Comment by isnifer** [comment]
@nzrsrk you're wrong. First of all, it has been written in Docs main page — [Requirements](https://tipsi.github.io/tipsi-stripe/docs/index.html).
The next one — [Installation page](https://tipsi.github.io/tipsi-stripe/docs/installation.html)

**Comment by nzrsrk** [comment]
@isnifer got it thank you for the replay

**Comment by spyshower** [comment]
It's inside Libraries --> Products in Xcode. Some people wanna see how nervous you can get instead of actually writing a guide.
