### ISSUE TITLE
Get selected shipping method & update total before payment processed?

### ISSUE THREAD

**Issue by christaggart** [tipsi/tipsi-stripe#238]
I wasn't able to find a way to handle this in the docs, but is there an event that can be handled if let's say there are two shipping methods, and one is $10 and the other is $20 and the user changes their selection.

How are folks updating the final total amount or the tax amount (based on shipping address or selected shipping method) with the selected shipping value? 

TPSStripeManager does not seem to implement any of the event listeners like ```didSelectShippingMethod``` and ```didSelectShippingContact```.

**Comment by isnifer** [comment]
Hi, @christaggart, Apple Pay it handles itself as I understand
