### ISSUE TITLE
uninstalling tipsi-stripe

### ISSUE THREAD

**Issue by aysfzaicmu** [tipsi/tipsi-stripe#239]
I tried to uninstall tipsi-stripe by uninstalling from npm and then unlinking. I removed the link from 'Link Binary with Library' and uncommented my code that uses tipsi-stripe, but unfortunately I get cannot read property of init of undefined(even though the code is commented out). I had cleared out my node_modules and reset packager cache.

**Comment by isnifer** [comment]
@aysfzaicmu Hi, show me a screenshot of an error, please
