### ISSUE TITLE
Android Pay Shipping address not working

### ISSUE THREAD

**Issue by shokimble** [tipsi/tipsi-stripe#240]
I opened an issue https://github.com/tipsi/tipsi-stripe/issues/173 back in December about adding shipping address support for Android Pay and at the time it was implemented and I tested it and it was working fine.

I since have upgraded to the latest tipsi-stripe and it's no longer working for me. I am trying to  downgrade to the 0.44 release which included the feature initially but having some sdk version issues.

I was running off a git branch and I'm not sure which since I nuked it before upgrading (doh). 

I thought initially I was going crazy so I created a basic app on the latest version which doesn't appear to have any breaking changes since the shipping address was featured.

Basic app:

https://gist.github.com/shokimble/b96c7da3bbe0d92694a18c909551e130

I get the following output:

![image](https://user-images.githubusercontent.com/2515338/36085065-11aac31a-1017-11e8-8ff6-6463f4243c17.png)

I was expecting a field called extra with the shipping address similar to iOS.

Can anyone reproduce this problem? What ended up getting merged into tipsi-stripe if it wasn't the code from @paynd I originally tested.

Here's the original PR https://github.com/tipsi/tipsi-stripe/pull/178

**Comment by shokimble** [comment]
BTW I am not somehow using an old version as the shipping_countries enforcement is working as expected.

**Comment by shokimble** [comment]
Any ideas @paynd ? I'm at a loss the code looks correct. I have the correct version installed of tipsi-stripe . I'm totally  stumped.

**Comment by paynd** [comment]
Hi @shokimble !
I will check it today evening or tomorrow morning. Sorry for delay.

**Comment by shokimble** [comment]
Google pay is looking good but it's now lost the email address field which for me at least makes it useless as I need it.

I'm checking out the source now and I'll add it and submit a PR. I'm not going to add it as a configurable option because I believe it should be compulsory. Along with the card it's something that everyone has to supply when signing up for Google Pay so there's no friction in adding it.

**Comment by shokimble** [comment]
I'm self closing. This issue is obsolete now.

Check out issue #278 for the link to the PR fixing the email address issue.
