### ISSUE TITLE
Can't install examples

### ISSUE THREAD

**Issue by LukasNavickas** [tipsi/tipsi-stripe#245]
After executing "npm install" on examples folder and opening the project in Android Studio, I get the following error:

```
"Error:(1, 0) Plugin with id 'com.android.library' not found.
<a href="openFile:C:\User\tipsi-stripe-master\android\build.gradle">Open File</a>"
```

How can I launch this project?

**Comment by isnifer** [comment]
@LukasNavickas not sure if someone checked this on windows, but just run `npm run ci` from the root, as described here https://github.com/tipsi/tipsi-stripe/blob/master/package.json#L7

**Comment by LukasNavickas** [comment]
I get 'scripts' is not recognized as an internal or external command.
I will try to include the package in my current project and will let you know how it went.

**Comment by paynd** [comment]
Hey @LukasNavickas !
Unfortunately you can't open RN project in AndroidStudio correctly.

**Comment by isnifer** [comment]
@LukasNavickas did you solve your issue?

**Comment by flora8984461** [comment]
The same issue for me, getting `'scripts' is not recognized as an internal or external command,` on win 10. 

Any updates on the issue? 

Thanks!
