### ISSUE TITLE
RNPushNotification conflict

### ISSUE THREAD

**Issue by wmonecke** [tipsi/tipsi-stripe#246]
When using Push Notifications with tipsi-stripe I get conflict errors because tipsi-stripe uses push notifications already (?) I managed to resolve on the iOS side by not linking the push notification library with binaries but I am stuck with android and have no idea on how to continue.

The app crashes on start and I only have this error message:

```
FATAL EXCEPTION: Thread-3
02-14 12:36:36.183  6303  6346 E AndroidRuntime: Process: com.lisdo, PID: 6303
02-14 12:36:36.183  6303  6346 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzr, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
```

I am pretty sure that I have to exclude something in the dependencies in `android/app/build.gradle` like in [this](https://github.com/react-community/react-native-maps/issues/1408) issue but I have no clue how to compare libraries for conflicts like in iOS.

Any help or clue is welcome!!

**Comment by isnifer** [comment]
@wmonecke we do not use any push services. Sure, your bug is not related `tipsi-stripe`

**Comment by wmonecke** [comment]
@isnifer Oh okok! Thank you :)
