### ISSUE TITLE
Improperly called by android.widget.textview

### ISSUE THREAD

**Issue by prjmax** [tipsi/tipsi-stripe#248]
I can't make it to work on Android, in my logs I have this: 

W/View: requestLayout() improperly called by android.widget.TextView{2d8b29c VFED..C.. ......ID 1080,0-1200,73 #7f10000a app:id/cc_four_digits} during layout: running second layout pass

When I try to enter the CC number I get the text in red after the 4th digit and it is just not working, any clue what am I doing wrong?

**Comment by isnifer** [comment]
@prjmax Hi, sorry for the delay. Did you solve your issue?
If not — show me full error log, an example of code and do a screenshot

**Comment by prjmax** [comment]
Hi @isnifer, I manage to solve it, I reckon it was a misconfiguration in the android project. Thank you though
