### ISSUE TITLE
iOS TPSCardField build error.

### ISSUE THREAD

**Issue by lin-zy1229** [tipsi/tipsi-stripe#252]
<img src="https://i.imgur.com/9Bn0ppw.png" />

Error: `Unexpected '@' in program`
What is the solution of this error?

**Comment by isnifer** [comment]
@lin-zy1229 not sure. What are you doing at all?

**Comment by lin-zy1229** [comment]
This is resolved, I am not sure how they disappeared. I did nothing for them.
