### ISSUE TITLE
Google Pay and Apple Pay does not supported 

### ISSUE THREAD

**Issue by sunil-patel** [tipsi/tipsi-stripe#257]
I am from india, I know android and apple pay is not supported in india but for testing i have to do, so I've installed tipsi-stripe to my app and set up every thing as per the guide but still it shows me Android and Apple pay is not supported. even though i have changed the region from phone and used VPN. 

Can you please guide me how to enable android and apple pay?

Thanks

**Comment by Mactub07** [comment]
instruction for ApplePay 
https://developer.apple.com/library/content/ApplePay_Guide/
https://developer.apple.com/support/apple-pay-sandbox/

you should:

- create completelly clean apple account (USA region important);
- register card (see apple instruction) in apple pay;
- add to your merchant.id in your apple developer account;
- after that you can use Apple pay

**Comment by isnifer** [comment]
@sunil-patel

**Comment by sunil-patel** [comment]
Thanks @Mactub07  let me try out for apple pay. but what about the Android Pay?

**Comment by isnifer** [comment]
@sunil-patel Android/Google Pay is only available on devices. And if it is not available in India — you can't play with it.

**Comment by isnifer** [comment]
So, I'm closing this issue, cause it's not related `tipsi-stripe` itself
