### ISSUE TITLE
Android Pay is deprecated

### ISSUE THREAD

**Issue by henrikra** [tipsi/tipsi-stripe#259]
Android Pay is nowadays Google Play https://pay.google.com/about/

At least README should be updated. I don't know if code changes are required 🤔

**Comment by isnifer** [comment]
@henrikra yes, we know. You might see we have already a PR for that https://github.com/tipsi/tipsi-stripe/pull/184, but there is a new 5 version will be released today with a Google Pay support.

**Comment by henrikra** [comment]
Oh nice!
