### ISSUE TITLE
StripeModule.paymentRequestWithCardForm expects 3 arguments

### ISSUE THREAD

**Issue by igemnace** [tipsi/tipsi-stripe#26]
When I call `stripe.paymentRequestWithCardForm()`, it errors out, saying `StripeModule.paymentRequestWithCardForm got 2 arguments, expected 3`.

This comes from `invoke` in `BaseJavaModule.java:291` (top-most entry in the stack trace). I checked `StripeModule.java` in my `node_modules` folder, but the `paymentRequestWithCardForm` method seems to rightfully take in 2 arguments.

I'm testing on a physical device running Android 4.4.4. My dev environment is running React Native 0.39, with `tipsi-stripe@1.4.0`.

I'm at a loss. Where could this be coming from?

**Comment by cybergrind** [comment]
@itsmepetrov @fAns1k please look into this

**Comment by itsmepetrov** [comment]
Hi, @igemnace, thank you for your feedback. I will try to reproduce this bug on Android 4.4.4 today.

**Comment by igemnace** [comment]
Thanks @itsmepetrov. If you need any more info, I'll try to reproduce on my end as well. I was on a physical device so I couldn't take screenshots.

**Comment by fAns1k** [comment]
Hi  @igemnace!
I have tried to run the example on Android 4.3 physical device, but can't reproduce this error. I need more information. Could you share the code where you get this error?

**Comment by fAns1k** [comment]
We managed to reproduce the bug and already working to fix it.
Meanwhile, you can call the method with an empty object (like `stripe.paymentRequestWithCardForm({})`) to avoid facing the issue until the fix.

**Comment by igemnace** [comment]
Thanks, @fAns1k!
