### ISSUE TITLE
types error on rn@0.47.2

### ISSUE THREAD

**Issue by nomoreboredom** [tipsi/tipsi-stripe#262]
Hello All, 

Thanks for the great component!!
Currently I am trying to run it, but when I import:

```import stripe from 'tipsi-stripe'```

I receive:  'Invalid argument supplied to oneOf, expected an instance of array.' 
Also, I do get 'tipsi_stripe_1.default.init is not a function', however I think I linked the library correctly.

Any idea what may be causing this? The error points to @ | types.js:20

Cheers

**Comment by isnifer** [comment]
@nomoreboredom Yeah, I see. I will create a patch
