### ISSUE TITLE
IOS build issue

### ISSUE THREAD

**Issue by sydridgmLee** [tipsi/tipsi-stripe#269]
when I test with following commands as in instructions:

1. Go to example folder cd example
2. Install CocoaPods dependencies (iOS only) **pod install --project-directory=ios**
3. Install npm dependencies **npm install**
Configure project before build **PUBLISHABLE_KEY=<...> MERCHANT_ID=<...> npm run configure**
5. Build project:
**npm run build:ios** - for iOS

I got this error:

CompileC /Users/sydridgm/Desktop/tipsi-stripe-master/example/ios/build/Build/Intermediates.noindex/RCTImage.build/Release-iphonesimulator/RCTImage.build/Objects-normal/i386/RCTImageCache.o RCTImageCache.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by isnifer** [comment]
Hi, @sydridgmLee! Try `PUBLISHABLE_KEY=<...> MERCHANT_ID=<...> npm run ci` from root

**Comment by sydridgmLee** [comment]
I've try it. 

But got another error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

And I have install Android studio V3.1 on my mac. And following [this](https://stackoverflow.com/questions/32634352/react-native-android-build-failed-sdk-location-not-found?answertab=active#tab-top) solution. But it does not work.

**Comment by isnifer** [comment]
@sydridgmLee Do you have windows?

**Comment by sydridgmLee** [comment]
NO....

**Comment by isnifer** [comment]
@sydridgmLee so, try for mac https://stackoverflow.com/questions/19986214/setting-android-home-enviromental-variable-on-mac-os-x, not for windows :)

**Comment by sydridgmLee** [comment]
In the .bash_profile, I already add the Android sdk path to $PATH

export ANDROID_HOME=/Users/sydridgm/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools

but it still cannot work...

**Comment by wkwyatt** [comment]
@sydridgmLee I sometimes have to declare the variable locally to the the terminal environment I'm on before I run the command try doing that

**Comment by isnifer** [comment]
@sydridgmLee did you solve your issue?

**Comment by sydridgmLee** [comment]
@wkwyatt @isnifer I just create a new project and use part of isnifer's code. It works
