### ISSUE TITLE
Recurring / Subscription Payments

### ISSUE THREAD

**Issue by Mubashirkhan** [tipsi/tipsi-stripe#272]
Can we make recurring / subscription payments with this module ???

**Comment by isnifer** [comment]
@Mubashirkhan No

**Comment by ComethTheNerd** [comment]
Might want to update the copy on the website...

![image](https://user-images.githubusercontent.com/7267037/39094313-7a08c8f0-4625-11e8-858e-8c3692d7f035.png)

**Comment by isnifer** [comment]
Or just create a PR to add new feature :)

**Comment by AdamZaczek** [comment]
Ok, this is just a straight up scam guys. We took 2 days to deal with connecting this lib, integrating it, making payments etc. All that was left was making subscription call. Now I'm reading it's impossible. Not a comlete solution huh?

**Comment by cybergrind** [comment]
@AdamZaczek this library is just wrapper around Stripe SDK for IOS and Android. Obviously, it cannot support things that aren't currently provided by these SDK's.

Probably you can ask why it isn't here in devs repos: https://github.com/stripe/stripe-android and https://github.com/stripe/stripe-ios

1. You still can do it, but it will require work on the backend side if you want to go with Stripe: 
just save card by using the token you can get from tipsi-stripe and using this API https://stripe.com/docs/api/cards/create and then charge this card every month or other desired period of time.
Or you can use https://stripe.com/docs/billing/subscriptions/creating api with a saved card. But all these things are beyond a client side library and must be done on the backend side.

2. In case you suggest some edits to documentation feel free to submit PR this will help other people to avoid your path.

P.S. Adam, please note that this is an open source project and we only spend our time and money supporting it. So if you really want to help you're free to improve things. But accusations and blaming aren't going to help us get anywhere. I'm truly sorry that you've wasted your time doing unnecessary things but you would get the same result with any other client-side library

**Comment by AdamZaczek** [comment]
Ok, if this works in a way you're describing I will be happy to help to update the docs!

So, if I use .paymentRequestWithNativePay can I just forward received token to my api?
I mean, Apple clearly displays the payment as a one-time thing, not a subscription based deal so can I even do it?
I know how to handle payment on backend side in such case!

**Comment by cybergrind** [comment]
You will need this API to create token: https://tipsi.github.io/tipsi-stripe/docs/createtokenwithcard.html

And we don't show payment dialogue in that case but show it as 'add card screen':
![image](https://user-images.githubusercontent.com/192182/57712004-8457a400-7678-11e9-8a29-765715f9cf3d.png)

If you want to do this with apple pay - I'm not sure how to customize dialogue, but it should be possible.
And it should be working in the end: https://support.stripe.com/questions/use-apple-pay-for-recurring-payments

**Comment by AdamZaczek** [comment]
It looks like using token works! You can even do it with native pay. I'll try to send in the PR once I have a bit more time, thanks and sorry for initial harsh words!

**Comment by cybergrind** [comment]
Hey, @AdamZaczek hope you're well! 

Do you think you will have time to make this documentation section in the near future? Or I shouldn't bother you with it?

**Comment by AdamZaczek** [comment]
@cybergrind
Hi! I made subscriptions work on iOS but couldn't on android.
I do not remember what was wrong at this point because we had to unlink tipsi-stripe to build the app in the first place.

**Comment by javi10823** [comment]
Any update about this? I need to implement recurring payments with Tipsi Stripe

**Comment by DavidKHahn** [comment]
@AdamZaczek Hello Adam, can you share your code snippet regarding the iOS? I'm also trying to connect using tipsi Stripe.

**Comment by john-harding** [comment]
Below is how I wrote the code for iOS (including a free trial), and an explanation below:
```
const items = [
    {
        label: `Monthly subscription`,
        amount: String(monthlyPrice),
        type: "final",
    },
    {
        label: `First payment on ${firstPayDate}`,
        amount: String(-monthlyPrice),
        type: "final",
    },
    {
        label: `My Company ($${amountToday} today)`,
        amount: String(monthlyPrice),
        type: "pending",
    },
];

const options = {};

stripe
    .paymentRequestWithNativePay(options, items)
    .then((result) => {
        this.props.createCard(result).finally(() => {
            stripe.completeApplePayRequest();
        });
        return;
    })
    .catch((err) => {
        console.log("pay request err");
        console.log(err);
    });
```

I'm following guidelines from Apple here:
https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/payment-types/

Essentially all of the `items` are just to inform the user what you are charging them.  Unfortunately you cannot set the last item to `0` (for displaying a free trial) with `tipsi-stripe` yet.  It is supported on iOS 12+, but even version `8.0.0-beta.10` of `tipsi-stripe` does not support it yet.  

You can follow along with the issue I created here:
https://github.com/tipsi/tipsi-stripe/issues/645

Once it is supported, I'll use the below:
```
let items;
const majorVersionIOS = parseInt(Platform.Version, 10);

if (majorVersionIOS >= 12) {
    items = [
        {
            label: `Monthly subscription`,
            amount: String(monthlyPrice),
            type: "final",
        },
        {
            label: `First payment on ${firstPayDate}`,
            amount: String(-monthlyPrice),
            type: "final",
        },
        {
            label: "My company",
            amount: String(amountToday),
            type: "final",
        },
    ];
} else {
    items = [
        {
            label: `Monthly subscription`,
            amount: String(monthlyPrice),
            type: "final",
        },
        {
            label: `First payment on ${firstPayDate}`,
            amount: String(-monthlyPrice),
            type: "final",
        },
        {
            label: `My Company ($${amountToday} today)`,
            amount: String(monthlyPrice),
            type: "pending",
        },
    ];
}
```
