### ISSUE TITLE
Stripe init is not a function

### ISSUE THREAD

**Issue by pohara9720** [tipsi/tipsi-stripe#274]
I have linked the library and have installed with cocoapods. I can see it linked in Xcode however when i do 
import stripe from 'tipsi-stripe'

and run 
componentDidMount(){
stripe.init({
          publishableKey: 'MYKEY',
        })
}

i get an error saying that _tipsiStripe2.default.init is not a function

**Comment by pohara9720** [comment]
I have also rebundled my app as well

**Comment by pohara9720** [comment]
ahhh its stripe.setOptions({})

Nevermind thank you this issue is closed

**Comment by Koshukey** [comment]
same here

**Comment by EugenePizzerbert** [comment]
same here
