### ISSUE TITLE
PaymentCardTextField style props doesn't support `overflow: 'hidden'`

### ISSUE THREAD

**Issue by TheDutchCoder** [tipsi/tipsi-stripe#276]
The docs say it supports all view styles, but it doesn't.

If you add a border radius, bg-color and overflow hidden, you can see the background overflows the borders.

Example:
```js
<View style={styles.field}>
  <Text>Test</Text>
</View>

<PaymentCardTextField
  style={styles.field}
  onParamsChange={this.handleFieldParamsChange}
/>

const styles = StyleSheet.create({
  field: {
    borderRadius: 20,
    padding: 10,
    backgroundColor: '#fff',
    borderWidth: 1,
    overflow: 'hidden'
  }
})
```

**Comment by isnifer** [comment]
I have added support for iOS:
![image](https://user-images.githubusercontent.com/1788245/42037060-04d5adf0-7af0-11e8-81fe-b8cbccfaba72.png)
