### ISSUE TITLE
External (Bank) Account Support

### ISSUE THREAD

**Issue by masiamj** [tipsi/tipsi-stripe#28]
Fantastic library!

Have you thought of including support for tokenizing external accounts like bank accounts or debit cards?

Thanks!

**Comment by itsmepetrov** [comment]
Hi @masiamj, thank you for your feedback.

As I understand from the [documentation](https://stripe.github.io/stripe-ios/docs/Classes/STPAPIClient.html#/c:objc(cs)STPAPIClient(im)createTokenWithBankAccount:completion:), we can add `createTokenWithBankAccount` method similar to `createTokenWithCard`.

Or is there some other methods that should we provide to support tokenizing bank accounts or debit cards?

**Comment by masiamj** [comment]
That's correct as I understand it.

This would be an excellent addition, especially for those looking to build marketplace-type apps that require both payment and payout methods.

**Comment by masiamj** [comment]
I saw the commits by @dmytrozavgorodniy about this issue. Has the feature been merged from issue_28 to master? Thanks for your work.

**Comment by masiamj** [comment]
Hey there!

Still just curious if the commits by Dmytro to fix this issue has been merged in?

Thanks

**Comment by itsmepetrov** [comment]
Hi @masiamj, currently it is not merged, @dmytrozavgorodniy is still working on it

**Comment by dmytrozavgorodniy** [comment]
Hey, @masiamj, I think we'll be done soon, we will let you know. Thanks for your attention.

**Comment by masiamj** [comment]
Excellent, thanks for you diligent work @dmytrozavgorodniy.

**Comment by cybergrind** [comment]
@masiamj android realization is here. ios is going to be next

**Comment by itsmepetrov** [comment]
Added in `3.1.0`

**Comment by jterps08** [comment]
Hi @cybergrind @itsmepetrov can you confirm that iOS support exists for CreateTokenWithBankAccount please? If so, the docs should be updated for https://github.com/tipsi/tipsi-stripe#request-with-external-bank-account-params-object-android-only-at-the-moment

**Comment by cybergrind** [comment]
hey @jterps08, yeah it was added in https://github.com/tipsi/tipsi-stripe/pull/71
we're going to fix doc
