### ISSUE TITLE
Delivery option Apple Pay

### ISSUE THREAD

**Issue by Amurmurmur** [tipsi/tipsi-stripe#281]
I was wondering if I can use Delivery option in when using ApplePay with stripe.
In the docs it says I can use Shipment  object, however it is not exactly what I need.
```
const token = await stripe.paymentRequestWithApplePay([{
        label: 'Whisky',
        amount: '50.00',
      }, {
        label: 'Vine',
        amount: '60.00',
      }, {
        label: 'Tipsi',
        amount: '110.00',
      }], {
        // requiredBillingAddressFields: ['all'],
        // requiredShippingAddressFields: ['all'],
        shippingMethods: [{
          id: 'fedex',
          label: 'FedEX',
          detail: 'Test @ 10',
          amount: '10.00',
        }],
      })

```

Is there a deliverMethods parameter or somethng and/or a delivery address option

**Comment by isnifer** [comment]
@Amurmurmur I'm sorry, but what's the difference between shipping and delivery?

**Comment by isnifer** [comment]
```js
// ...
shippingMethods: [{
  id: 'DELIVERY',
  label: 'DELIVERY',
  detail: 'Delivery details',
  amount: '0.00',
}],
requiredShippingAddressFields: ['phone', 'postal_address']
```
For example

**Comment by Amurmurmur** [comment]
@isnifer There is an undocumented option in the options objects ( I had to dig into the ios source code to find it out )

{
        currencyCode: 'USD',
        countryCode: 'US',
        requiredBillingAddressFields: ['all'],
        requiredShippingAddressFields: ['all'],
        shippingType: 'delivery', // <-- This is not documented, available options are: delivery | store_pickup | service_pickup
      }

Thanks a lot again for the help @isnifer  👍  And thank you so much for such a nice component!!!

**Comment by isnifer** [comment]
@Amurmurmur wow, looks like need to document this, thank you :)
