### ISSUE TITLE
<PaymentCardTextField> , numberPlaceholder attribute support only for android , not supported for IOS

### ISSUE THREAD

**Issue by Buwaneka1993** [tipsi/tipsi-stripe#284]
I have checked this component in both android and IOS devices. Then I found '**numberPlaceholder**' attribute not support for IOS devices.
<PaymentCardTextField
                 style={styles.field}
                 disabled={false}
                 onParamsChange={this.handleFieldParamsChange}
                 numberPlaceholder={'0000 0000 0000 0000'}
               />

**Comment by isnifer** [comment]
@Buwaneka1993 you can help us with it :)

**Comment by isnifer** [comment]
@Buwaneka1993 fixed in 5.2.4
