### ISSUE TITLE
error index.js tries to require 'react-native', but there are several files providing this module. 

### ISSUE THREAD

**Issue by yernandus** [tipsi/tipsi-stripe#285]
![screen shot 2018-05-10 at 13 02 53](https://user-images.githubusercontent.com/4067414/39856643-836955dc-5452-11e8-9bd9-978033ba677a.png)
![screen shot 2018-05-10 at 13 03 34](https://user-images.githubusercontent.com/4067414/39856666-91a77052-5452-11e8-9b10-02d3569c417b.png)
![screen shot 2018-05-10 at 13 03 54](https://user-images.githubusercontent.com/4067414/39856680-9d73c2d2-5452-11e8-9a7d-81ef5942fdb5.png)

**Comment by isnifer** [comment]
@yernandus Please provide normal error log and screenshots for this error. What are you did before — step by step

**Comment by yernandus** [comment]
steps: 
1. yarn add tipsi-stripe
2. react-native link tipsi-stripe
3. npm run ios

**Comment by isnifer** [comment]
@yernandus you don't need to add tipsi-stripe as Pod

**Comment by yernandus** [comment]
@isnifer, that was added after linking. trying without it

**Comment by yernandus** [comment]
now I am getting this 
![screen shot 2018-05-10 at 13 10 48](https://user-images.githubusercontent.com/4067414/39856960-97f20034-5453-11e8-9ea2-3794b464a7cb.png)

**Comment by isnifer** [comment]
@yernandus nope. `tipsi-stripe` never adding itself to Pods. Only Stripe.

**Comment by isnifer** [comment]
@yernandus restart packager with `--reset-cache`

**Comment by yernandus** [comment]
@isnifer , I did not add tipsi-stripe to PodFile manually. that happened after react-native link tipsi-stripe. resting cache

**Comment by isnifer** [comment]
@yernandus looks like a link was not successful absolutely. You need to check this doc https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual
Steps 1-4

**Comment by yernandus** [comment]
manual linking helped. thank you @isnifer for the quick help.

**Comment by isnifer** [comment]
@yernandus enjoy!
