### ISSUE TITLE
workaround for using 'use_frameworks!'

### ISSUE THREAD

**Issue by KazuyaHara** [tipsi/tipsi-stripe#29]
I met same error with #11 and found how to workaround this issue. So please let me share that on here.

**Issue:**
- when uncomment `use_frameworks!` in Podfile, build fails with message below. (even it worked without `use_frameworks!` before) 
```
fatal error: 'Stripe/Stripe.h' file not found`
#import <Stripe/Stripe.h>
        ^
1 error generated.
```

**Solution:**
1. Click TPSStripe.xcodeproj in the project navigator and go the Build Settings tab.
2. Look for Framework Search Paths and make sure it contains `$BUILD_DIR/$CONFIGURATION$EFFECTIVE_PLATFORM_NAME/Stripe`
3. Change to the Build Phases, and in the section Link Binary with Libraries click the + and add Stripe.framework.

**Comment by itsmepetrov** [comment]
@sergeyzhukov please take a look

**Comment by magneticz** [comment]
Thanks a lot @KazuyaHara, this worked for me!

**Comment by sergeyzhukov** [comment]
https://github.com/tipsi/tipsi-stripe/pull/38

**Comment by sergeyzhukov** [comment]
[https://github.com/tipsi/tipsi-stripe/pull/38](url)

**Comment by KazuyaHara** [comment]
@itsmepetrov @itsmepetrov @cybergrind 
Thank you, guys! Please also publish to npm. When I ran `npm install` older version was installed.

**Comment by cybergrind** [comment]
@KazuyaHara published version 2.1.0

**Comment by buhe** [comment]
'Stripe/Stripe.h' is not found when archive my app.
just update framework header search to ${BUILD_DIR/$CONFIGURATION$EFFECTIVE_PLATFORM_NAME/Stripe}
everything is okey...

**Comment by alexanderlamb** [comment]
@buhe I'm having a similar problem.

'Stripe/Stripe.h' is not found when archiving my app. Building and running in simulator or device is totally fine..  Both release and debug work.  Just fails when using Archive in xcode.

Did you add ```${BUILD_DIR/$CONFIGURATION$EFFECTIVE_PLATFORM_NAME/Stripe}``` to TPSStripe.xcodeproj Header Search Paths or your main projects Header Search Paths?

**Comment by itsmepetrov** [comment]
@sergeyzhukov please take a look

**Comment by wangdaliu** [comment]
I also have this problem, only use archive

**Comment by isnifer** [comment]
@wangdaliu @alexanderlamb @buhe @KazuyaHara 3.2.0 released with fix for this error, thank you!

**Comment by grahamyesfit** [comment]
Can this be reopened? I'm getting the same error with `use_frameworks!` as reported above. Adding a Framework Search Path to TPSStripe.xcodeproj is not an option for me, as we use a build server that gets the latest from NPM every build. I'm using `tipsi-stripe 5.2.1` and `Stripe 11.2.0`.

**Comment by isnifer** [comment]
Hi, @grahamyesfit. I'm sure, you just didn't linked module correctly. Check if you installed Pods correctly. Check header search paths in your own project. Also build your app via xcworkspace, not a xcodeproj file

**Comment by grahamyesfit** [comment]
Thanks @isnifer. To be clear, my project builds and runs correctly if I remove `use_frameworks!` from my pod file, which suggests that the pod is correctly installed and that my search paths are correct. Here are my Framework Search Paths:

```
$(inherited)
$(PROJECT_DIR)/Frameworks 
```

Are you suggesting that when I use `use_frameworks!` I need additional header and framework search paths?

I have been building my app via xcworkspace since I started using pods several months ago.

**Comment by grahamyesfit** [comment]
@isnifer, never mind. When I added `use_frameworks!`, I didn't notice an error when I ran `pod update`. I've fixed the error and now the build gets beyond the Stripe error I was previously receiving. Thanks anyway.

**Comment by Michaelvilleneuve** [comment]
Hi,
How is this a solution ? Editing node_modules directly should never be a solution.
No one commits their node_modules, and any reasonable company is building with a CI process, meaning any edition of node_modules are removed at build time.

Is there any way to fix this without doing something hacky ?
