### ISSUE TITLE
Alipay is always showing "There was an unexpected error -- try again in a few seconds"

### ISSUE THREAD

**Issue by verna1228** [tipsi/tipsi-stripe#290]
As title, same issue happened when using the example project.  the error is show after redirection to app.  Any help is appreciated.  Thanks.

**Comment by brilliantjc** [comment]
how to set up Alipay? the example file provides a SourceScreen talk about Alipay, but nothing related to the real payment process. Thank you so much!

**Comment by verna1228** [comment]
updated the stripe sdk. the error dismissed, but another issue happened.  follow up in https://github.com/tipsi/tipsi-stripe/issues/299

**Comment by Freddy03h** [comment]
@verna1228 you upgraded to which version number ?

**Comment by verna1228** [comment]
i upgraded to 13.0.1.  many thanks.

**Comment by macmatrix** [comment]
How did you resolve? I have the same issue
