### ISSUE TITLE
createSourceWithParams promise is never resolved

### ISSUE THREAD

**Issue by Weakky** [tipsi/tipsi-stripe#291]
Hey there,

After the payment is authorized and the redirection towards the app is done, it looks like the view is loosing its state, and therefore never resolves the `createSourceWithParams` promise.

It may be due to a completely different problem, but still, this can be reproduced on the example.

Just press the `Create source for ali payment` button, authorize the payment, and watch the `source` state never get set.

Cheers !

**Comment by brilliantjc** [comment]
how to redirect towards the app? Thank you thank you so much!!

**Comment by brilliantjc** [comment]
got the same issue, the stripe online system got the source, but the app source state is still undefined. 
<img width="491" alt="screen shot 2018-05-27 at 4 43 24 pm" src="https://user-images.githubusercontent.com/25623417/40592269-0703e218-61d2-11e8-8d69-ced36b335d09.png">
<img width="556" alt="screen shot 2018-05-27 at 4 43 02 pm" src="https://user-images.githubusercontent.com/25623417/40592270-07f8c04e-61d2-11e8-8a2e-1b0bb263cece.png">
<img width="537" alt="screen shot 2018-05-27 at 4 18 11 pm" src="https://user-images.githubusercontent.com/25623417/40592271-091fdb60-61d2-11e8-889b-3c69ff520a39.png">

**Comment by isnifer** [comment]
@brilliantjc first of all:
At 0 `source` is really `undefined`
At 1 there is no log, but `source` should be defined if createSourceWithParams will return a result
At 2 `source` is available too
At 3 `source` is `undefined` because every `const` is visible only in it's lexical scope

**Comment by isnifer** [comment]
@Weakky you tried it on your own app, or tried to build our example locally?

**Comment by Weakky** [comment]
@isnifer I used your example. As a workaround, I ended-up creating the source server-side.

**Comment by isnifer** [comment]
@Weakky thank you for your response, I will try to reproduce an error on my device
