### ISSUE TITLE
Does the <PaymentCardTextField> utilize the Stripe Mobile SDK?

### ISSUE THREAD

**Issue by duro** [tipsi/tipsi-stripe#292]
I ask simply to ensure that use of it allows me to continue to comply with the guidelines in this document:

https://stripe.com/docs/security#pci-dss-guidelines

According to that document, as long as I am using the Mobile SDK, I qualify for the lowest PCI scope, `Pre-filled SAQ A`

**Comment by cybergrind** [comment]
@duro yep. tipsi-stripe just wrapper above mobile stripe SDK and doesn't do extra queries or logs for private information. So it is PCI compliant that way.

**Comment by duro** [comment]
@cybergrind The only thing I noticed is that the <PaymentCardTextField> omits the full card number on field change. I think this is a no-no for lowest PCI scope. In order to qualify for lowest PCI scope the developer has to have no access to full card number. Hence why Stripe React Elements for web uses iFrames for each field.

Thoughts?

**Comment by cybergrind** [comment]
@duro If you haven't added it yourself there is no way to developer or any third-party to access any payment data under default circumstances

**Comment by SudoPlz** [comment]
Hey @cybergrind , @fred-stripe mentioned that tipsi stripe

> provides their own version of the Stripe components copied from an older version of the SDKs instead of bridging the SDKs directly:

Found [here](https://github.com/stripe/react-stripe-elements/issues/21#issuecomment-307163466).

That comment was posted on  8 Jun 2017, does tipsi-stripe wrap the official SDK's directly now?
Thanks

**Comment by cybergrind** [comment]
hey @SudoPlz. We're wrapping Stripe SDK but we have our custom CC input widget because of our design requirements. However, this doesn't mean that tipsi-stripe isn't PCI DSS compliant. It means that you're not eligible for SAQ A.
If you really want to provide wrappers to native SDK provided fields - feel free to submit PR. In that case you will be eligible for SAQ A

**Comment by SudoPlz** [comment]
Hi @cybergrind  and thanks for your response.
Why do you think it makes sense to create that PR as part of tipsi instead of making it a separate module?
Will there be any code re-use if we open a PR in tipsi? It sounds like totally separate logic (implementing own UI a.k.a the tipsi way VS using stripes UI a.k.a the stripe sdk way)

**Comment by cybergrind** [comment]
@SudoPlz I believe that we can put it as a module in `tipsi-stripe` if it requires no additional dependencies. And it will provide a single package that is eligible for SAQ A. 
And it makes more sense in terms of usability and convenience (single tested package vs two packages and possibly non-compatible versions)

But if you want to contribute it to `tipsi-stripe` you will need to write appropriate e2e tests for it.

**Comment by SudoPlz** [comment]
@cybergrind Taking a look at tipsi [code](https://github.com/tipsi/tipsi-stripe/blob/master/ios/TPSStripe/TPSStripeManager.m#L372), it looks like tipsi uses [STPAddCardViewController](https://stripe.github.io/stripe-ios/docs/Classes/STPAddCardViewController.html) for receiving credit card data when using `paymentRequestWithCardForm`.

I'm now confused, **why does that not guarantee SAQ A eligibility**?
When using that tipsi (and the app using it) only receives a token and no credit card info is stored or transmitted from our code.

Is what we're discussing above already implemented?

**Comment by cybergrind** [comment]
@SudoPlz for android we're using custom input library https://github.com/tipsi/CreditCardEntry

**Comment by mjurincic** [comment]
> Sounds like the only thing that needs to be done is add code that uses the [Android sdk for stripe](https://github.com/stripe/stripe-android)

Is this correct we are looking in integrating tipsi-stripe instead our own solution so we are Evaluating options.

**Comment by juddey** [comment]
Hey @SudoPlz :wave: 

Are you still interested in this lib or did you go with something else?

**Comment by SudoPlz** [comment]
@juddey still interested, we just postponed implementing that feature. What's up?

**Comment by juddey** [comment]
@SudoPlz I was thinking of maybe wrapping stripes android sdk as an option for this lib for SAQ A compliance and thought you might have got down the road somewhat

But then I found: https://github.com/stripe/react-stripe-js/issues/48....

**Comment by SudoPlz** [comment]
yeah I don't think anything has changed since then, SAQ A is still not a possibility for react-native projects (on both iOS and Android) with a ready to use library.

**Comment by juddey** [comment]
Yeah this lib is about the closest if you don't want to go a webview solution
and even then its not really "endorsed" by stripe either

**Comment by juddey** [comment]
Yeah you're right and the effort to make this compliant is not a couple of lines of code
so even if the android sdk was added it wouldn't have been done by stripe  
and stripe are looking at RN support so they might not even use the work even if you were to do it
