### ISSUE TITLE
How to change the credit card number placeholder with paymentRequestWithCardForm()

### ISSUE THREAD

**Issue by arnaud-git** [tipsi/tipsi-stripe#293]
Hello,

Is it possible to modify the credit card number placeholder in the form displayed when using paymentRequestWithCardForm ? I did not find anything related to this in the documentation.

Thank you for your time!

**Comment by isnifer** [comment]
Hi, @arnaud-git, there is a PR about that — https://github.com/tipsi/tipsi-stripe/pull/86. But not finished yet

**Comment by erikdstock** [comment]
@isnifer This PR looks like it hasn't been touched since January. I could PR a change to just add the getters + setters for the iOS component as this has become an issue for us as well.

**Comment by isnifer** [comment]
@arnaud-git use <PaymentCardTextField /> component — https://tipsi.github.io/tipsi-stripe/docs/paymentcardtextfield.html
