### ISSUE TITLE
Name not showing up in token for Apple Pay

### ISSUE THREAD

**Issue by EdmundMai** [tipsi/tipsi-stripe#30]
I'm trying to use tipsi-stripe with apple pay. I'm not seeing the name:
```

      stripe.paymentRequestWithApplePay(
        helpers.applePayFormat(cartItems),
        {},
      )
      .then(token => {
        console.log("tokennnnnnnnnnnnnnnnnnnnnnnnn: ", token);
        ...
        stripe.completeApplePayRequest();
      })
      .catch(error => {
        console.log(error);
      });

```

this prints out:

```

'tokennnnnnnnnnnnnnnnnnnnnnnnn: ', { livemode: false,
  created: 1487648584,
  card: 
   { cardId: 'card_19pUYNCV51Zcg8T4miMFvgFn',
     funding: 'credit',
     country: 'US',
     expMonth: 12,
     brand: 'Visa',
     last4: '0000',
     expYear: 2020,
     dynamicLast4: '4242' },
  tokenId: 'tok_19pUYOCV51Zcg8T4fxBLN15G',
  extra: 
   { shippingContact: null,
     shippingMethod: null,
     billingContact: null } }

```

Is this because I'm not in livemode?

**Comment by cybergrind** [comment]
@EdmundMai could you please pass option from this section https://github.com/tipsi/tipsi-stripe#options to ensure that you've requested name? 
As I understand you haven't requested any user information in your request.

**Comment by itsmepetrov** [comment]
I think @EdmundMai meant [`name` from card params](https://stripe.github.io/stripe-ios/docs/Classes/STPCardParams.html#/c:objc(cs)STPCardParams(py)name).

 As I can see, we provide full info from card params:
- https://github.com/tipsi/tipsi-stripe/blob/master/ios/TPSStripe/TPSStripeManager.m#L258
- https://github.com/tipsi/tipsi-stripe/blob/master/ios/TPSStripe/TPSStripeManager.m#L300-L317

This means that there are several variants:
- You uses test credit cards (4242 4242 4242 4242) that does not contain cardholder's name;
- You not in `livemode` (dev) and Apple Pay does not provide cardholder's info in this mode;
- Some issue in [Stripe iOS](https://github.com/stripe/stripe-ios) library.

Unfortunately, at the moment, I do not have access to production application and account to check these variants.

But I found some interesting info:
- [Does the Apple Pay token contain cardholder data? More details about tokenization implementation.](https://www.linkedin.com/pulse/20141003182832-55352834-does-the-apple-pay-token-contain-cardholder-data-more-details-about-tokenization-implementation)
- [What's the bare minimum information that Stripe requires to charge a credit card?](https://www.quora.com/Whats-the-bare-minimum-information-that-Stripe-requires-to-charge-a-credit-card)

**Comment by isnifer** [comment]
@EdmundMai did you solve this issue?

**Comment by EdmundMai** [comment]
@isnifer I managed to get the shipping contact name, couldn't get it for billing though:

```
const options = {
  requiredShippingAddressFields: "name" // works, but not for billing
};
stripe
  .paymentRequestWithApplePay(
    helpers.applePayFormat([selectedItem]),
    options
  )
  .then(token => {
    // token.extra.shippingContact.name
    ...
    stripe.completeApplePayRequest();
  })
  .catch(error => {
    console.log(error);
  });
```

**Comment by isnifer** [comment]
@EdmundMai did you try it on the device? Did you add 
```js
requiredShippingAddressFields: "name"
```
into `options`

**Comment by cybergrind** [comment]
out of date
