### ISSUE TITLE
apple pay is not configured

### ISSUE THREAD

**Issue by israelidanny** [tipsi/tipsi-stripe#309]
Everything seems to work in the simulator, but when attempting to pay from device it throws an error that says `apple pay is not configured`.

The merchant id is set in `setOptions` and apple pay is enabled in capabilities.

**Comment by jacobsilverman** [comment]
Same issue on device only. Works fine in simulator.

<img width="547" alt="applepaynotconfigured" src="https://user-images.githubusercontent.com/4277705/41429371-4f1a060e-7050-11e8-97e9-85e7370ed05f.png">

**Comment by israelidanny** [comment]
Upon further investigation I found out that this error gets triggered when the user doesn't have any cards set up. This doesn't seem very friendly UX-wise. Is there any way to programatically bring the user to the screen where he's supposed to add Apple Pay cards. This seems like a major risk of losing potential customers.

**Comment by israelidanny** [comment]
Oops.. I didn't RTFM
https://tipsi.github.io/tipsi-stripe/docs/openapplepaysetup.html
