### ISSUE TITLE
Setup Apple Pay requirement

### ISSUE THREAD

**Issue by benjaminreid** [tipsi/tipsi-stripe#31]
Hello 👋 ,

Currently, Apple deem it necessary if a device that supports Apple Pay and the user hasn't setup a payment card to show a "Setup Apple Pay" button. I can't see that this library offers the facility to check if a user has setup a card or not.

It'd be brilliant if it could, because as a whole `tipsi-stripe` is amazing but is missing this one little thing that could stop a lot of people from using it.

If you look at [react-native-stripe‘s example](https://github.com/lrettig/react-native-stripe#example) they are able to check the whether the user has a card or not and provide the facility to open the native view to setup a card on iOS. I believe [this](https://github.com/lrettig/react-native-stripe/blob/b7480ce77262cb8731b9fc229c755c54cb1b18da/StripeNative/StripeNativeManager.m#L70-L73) is the native code used to "link" users offer to payment setup screen.

Would this be something you'd look to implement?

**Comment by cybergrind** [comment]
Hey @nouveller , definitely we are going to add this feature.

**Comment by nouveller** [comment]
@cybergrind That's really good to here. I'll keep an eye out for the pull request and see if I can help when it's being worked on.

**Comment by SuhairZain** [comment]
Hi @itsmepetrov, any updates on this?

**Comment by cybergrind** [comment]
@benjaminreid @SuhairZain this was a quite long task but we've merged it

**Comment by SuhairZain** [comment]
@cybergrind Thanks a ton for this. I'll check it out and let you know. 👍
