### ISSUE TITLE
sending 'sortCode' for GB users when using 'createTokenWithBankAccount' 

### ISSUE THREAD

**Issue by ppatel890** [tipsi/tipsi-stripe#313]
We are generating bank tokens for users in Great Britain, and sending `accountNumber` and `sortCode` to generate the token. Based on the logs on the Stripe dashboard, the `sortCode` is not in the `POST` request. The users gets an error saying 'Please enter a bank sort code that supports transfers to and from your account'. Should this param be passed to the underlying Stripe-ios library? Or should we be sending the `sortCode` as a `routingNumber`?

Any help is appreciated! Thank you. Library version below.

` "tipsi-stripe": "^4.6.4",`

**Comment by isnifer** [comment]
Hi, @ppatel890, I don't know different between `sortCode` and `routingNumber`. But, did you try your solution?

**Comment by ppatel890** [comment]
`sortCode` is used for bank accounts in Great Britain. Sending the `sortCode` as `routingNumber` did work properly, and generate the bank token. It is unfortunate that stripe did not throw an error in test mode though, and we only found out after pushing to prod.

**Comment by saimAbdullah** [comment]
> `sortCode` is used for bank accounts in Great Britain. Sending the `sortCode` as `routingNumber` did work properly, and generate the bank token. It is unfortunate that stripe did not throw an error in test mode though, and we only found out after pushing to prod.

Thanks it worked.
