### ISSUE TITLE
paymentRequestWithAndroidPay does nothing - the promise does not resolve (on detached Expo Android app)

### ISSUE THREAD

**Issue by miraan** [tipsi/tipsi-stripe#318]
Same issue as https://github.com/tipsi/tipsi-stripe/issues/98.

I've installed tipsi-stripe. Setting up Apple Pay was easy - it works great. Unfortunately I can't get `paymentRequestWithAndroidPay` to work. When I call it, it opens up the Payment Details Google Pay screen. I tap Continue with a card selected. Then the screen slides away, but nothing happens. The promise doesn't resolve with token details.

This is with my stripe test token and with `androidPayMode` set to `test`. If I use my production stripe token and `androidPayMode` set to `production` I get an error dialog 'Request Failed - The merchant is not enabled for Google Pay`, which is understandable.

However, in order to get production access to Google Pay, I need to send over an APK to them with the test environment payment flow working, which I cannot do currently due to this.

**Comment by miraan** [comment]
Looks related to https://github.com/expo/expo/issues/651. The solution there seems promising - will try and report back here.

**Comment by miraan** [comment]
Can confirm that the solution mentioned in https://github.com/expo/expo/issues/651 works.

In tipsi-stripe's build.gradle, add to `dependencies` the exponent module. For me on expo v28 currently, that's:

```
implementation('host.exp.exponent:expoview:28.0.0@aar') {
  exclude module: 'CreditCardEntry'
}
```

Then in `StripeModule.java`, replace

```
private final ActivityEventListener mActivityEventListener = new BaseActivityEventListener() {
	@Override
	public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
		boolean handled = getPayFlow().onActivityResult(activity, requestCode, resultCode, data);
		if (!handled) {
			super.onActivityResult(activity, requestCode, resultCode, data);
		}
	}
};
```

with

```
private final host.exp.exponent.ActivityResultListener mActivityEventListener = new host.exp.exponent.ActivityResultListener() {
	@Override
	public void onActivityResult(int requestCode, int resultCode, Intent data) {
		boolean handled = getPayFlow().onActivityResult(requestCode, resultCode, data);
		if (!handled) {
			Log.e("StripeModule", "onActivityResult not handled");
		}
	}
};
```

And replace `reactContext.addActivityEventListener(mActivityEventListener);` with `Exponent.getInstance().addActivityResultListener(mActivityEventListener);`.

You'll also need to change the `PayFlow` interface abstract `onActivityResult` method to `abstract boolean onActivityResult(int requestCode, int resultCode, Intent data);` (i.e. remove the first `Activity activity` parameter. And update the PayFlow implementations `GoogleApiPayFlowImpl` and `ObsoleterApiPayFlowImpl`. They don't use this parameter anyway.

Bit of a hack, but works. Hope someone finds useful.

**Comment by shopped** [comment]
Encountered the same issue for my ExpoKit app. I also had to take some additional steps in the tipsi-stripe package...

In build.gradle I had to include transitive
```
compile ('host.exp.exponent:expoview:28.0.0@aar') {
    transitive = true
    exclude module: 'CreditCardEntry'
  }
```

In StripeModule.java I had to add imports for new code
```
import host.exp.expoview.Exponent;
import android.util.Log;
```
