### ISSUE TITLE
Example Build Error

### ISSUE THREAD

**Issue by danielmhanover** [tipsi/tipsi-stripe#320]
Hey!

The example doesn't build unless you add "use_frameworks!" to its Podfile. Can someone make this change and PR?

**Comment by isnifer** [comment]
@danielmhanover Hey! The example works perfectly. Just build locally for testing

**Comment by isnifer** [comment]
@danielmhanover show me your error log. Also, are you building it?

**Comment by danielmhanover** [comment]
react-native run-ios

In file included from /Users/danielhanover/Documents/GitHub/tipsi-stripe/ios/TPSStripe/TPSCardField.m:9:
/Users/danielhanover/Documents/GitHub/tipsi-stripe/ios/TPSStripe/TPSCardField.h:10:9: fatal error: 'Stripe/Stripe.h' file not found
#import <Stripe/Stripe.h>

**Comment by danielmhanover** [comment]
I'm running react-native run-ios from within the example directory

**Comment by danielmhanover** [comment]
Any ideas?

By the way, for context, I am trying to add a feature to the library to allow implementation of the EphemeralKeyProvider, so I can have the user identity and sources persist across app launches.

**Comment by danielmhanover** [comment]
Alright, I understand why you haven't done this already :(

Working on a workaround that might also achieve the same effect without interacting at all with native code more than tipsi is already.

**Comment by isnifer** [comment]
@danielmhanover there is a fix for you — https://github.com/tipsi/tipsi-stripe/pull/322

**Comment by danielmhanover** [comment]
Thanks! What was the problem?

**Comment by isnifer** [comment]
@danielmhanover `tipsi-stripe` is using Stripe Pod. When the module is installing from `file:../` npm itself just create a symlink to this folder, but Xcode and react-native packager do not follow symlinks — both of them need real files on their places in node_modules.
I've created a PR to fix that like we did it in our CI script:
1. Pack module via `npm pack`
2. Rename packed module from `${MODULE_NAME}-${MODULE_VERSION}.tgz` to `${MODULE_NAME}-latest.tgz`
3. Changed dependency for an example project from `file:../` to `file:../tipsi-stripe-latest.tgz` which will unpack and install `tipsi-stripe` to `node_modules` of an example and does not produce errors

**Comment by danielmhanover** [comment]
Ah, ok thanks. I'm going to work on integrating something like this - https://github.com/hammadj/react-native-stripe-checkout - with this library, as tipsi-stripe provides no UI to present a list of payment options. Is this something you'd be interested in PR'ing?

**Comment by isnifer** [comment]
@danielmhanover Yes, it would be nice. You can fork a project and create a new component inside `src/components`

**Comment by danielmhanover** [comment]
I'm going to create a new component and provide a way to send tipsi an STPCustomer object with a list of sources

**Comment by isnifer** [comment]
@danielmhanover looks like it should be an array :)

**Comment by danielmhanover** [comment]
of course

**Comment by isnifer** [comment]
@danielmhanover we have merged this PR. So, you can grab and try it out.
