### ISSUE TITLE
iOS Build Failed: fatal error: 'Stripe/Stripe.h' file not found

### ISSUE THREAD

**Issue by Base29** [tipsi/tipsi-stripe#327]
Hello Guys ... When I try to build my app through I get this error ... 

> In file included from /Users/FaisalHussain/ReactNativeApps/FlokiApp/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.m:9:
> /Users/FaisalHussain/ReactNativeApps/FlokiApp/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:10:9: fatal error: 'Stripe/Stripe.h' file not found
> #import <Stripe/Stripe.h>
>         ^~~~~~~~~~~~~~~~~
> 1 error generated.

I reinstalled the tipsi-stripe module but still no success ... What could be the issue ?

**Comment by isnifer** [comment]
@Base29 Hey! You need to install pods — https://tipsi.github.io/tipsi-stripe/docs/installation.html

**Comment by Base29** [comment]
Yeah i know and I have already installed pods ... but the error was due to a faulty installation of the module ... I had to reinstall it and it worked ... Thanks
