### ISSUE TITLE
PaymentCardTextField Android color not changing

### ISSUE THREAD

**Issue by Marcdup1** [tipsi/tipsi-stripe#329]
Setting the style color on the field doesn't change the input text color on android. It works on ios
```
<PaymentCardTextField
    style={{ color: 'red' }}
   ...
/>
```

**Comment by isnifer** [comment]
@Marcdup1 try `#FF0000`

**Comment by Marcdup1** [comment]
@isnifer It still has black text for android

**Comment by reinhardholl** [comment]
Any other ideas @isnifer ?

**Comment by isnifer** [comment]
@reinhardholl yes, looks like need to fix https://github.com/tipsi/CreditCardEntry

**Comment by lucasroca** [comment]
Any progress or workaround on this?

**Comment by lalmachado** [comment]
I'm having the same problem
