### ISSUE TITLE
ios build issue

### ISSUE THREAD

**Issue by rheilgm** [tipsi/tipsi-stripe#33]
btw, im running on react-native v0.38

all i get when running `react-native run-ios`
is this error 

> CompileC /Users/user/repos/sample-mobile/ios/build/Build/Intermediates/TPSStripe.build/Debug-iphonesimulator/TPSStripe.build/Objects-normal/x86_64/TPSCardFieldManager.o TPSStripe/TPSCardFieldManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by itsmepetrov** [comment]
Hi, @rheilgm, which version of `tipsi-stripe` are you using? If you need to support React Native < 0.40, you should install @1.4.0 version.

**Comment by rheilgm** [comment]
hi I already solved the issue just now, had to modify the PodFile to proper format
and yep i already installed 1.4.0.

Thanks anyways, really great plugin :)
