### ISSUE TITLE
Shipping address with .paymentRequestWithCardForm()

### ISSUE THREAD

**Issue by evelynccordner** [tipsi/tipsi-stripe#332]
I noticed there is an optional field: `shipping_address_required` for `.paymentRequestWithApplePay()` and `.paymentRequestWithAndroidPay()`.

Is it possible to also have a shipping address with `.paymentRequestWithCardForm()`

**Comment by evelynccordner** [comment]
Or access to this view controller would also work: https://stripe.com/docs/mobile/ios/custom#stpshippingaddressviewcontroller

**Comment by isnifer** [comment]
@evelynccordner Hi! What you mean when say "possible to have"? You mean you want a standard UI for setting shipping address?

**Comment by SamMatthewsIsACommonName** [comment]
I'm also encountering a similar issue. The card form is a nice easy UI out of the box but we're getting a lot of payment declined on valid cards, apparently because not capturing address info.
Any ideas what we should do? I think the address view controller would be amazing... however understand this is an open source library!! Thanks

**Comment by SamMatthewsIsACommonName** [comment]
@evelynccordner can I ask what did you end up doing as a solution for this?

**Comment by evelynccordner** [comment]
@isnifer correct, something like this https://stripe.com/docs/mobile/ios/custom#stpshippingaddressviewcontroller wrapped for React Native.

**Comment by evelynccordner** [comment]
@SamMatthewsIsACommonName we were toying with the idea of using apple pay to collect the shipping address, but as it turns out we need the shipping address to calculate shipping costs, so that method doesn't quite work for us.

**Comment by SamMatthewsIsACommonName** [comment]
@evelynccordner thanks for the heads up and idea, we may end up doing the same with the stripe address.

**Comment by evelynccordner** [comment]
@isnifer just following up here. Would love to see Tipsi-Stripe support a wrapper for:

```
- (void)paymentAuthorizationViewController:(PKPaymentAuthorizationViewController *)controller
                  didSelectShippingContact:(PKContact *)contact
                                completion:(void (^)(PKPaymentAuthorizationStatus status, NSArray<PKShippingMethod *> *shippingMethods,
                                                     NSArray<PKPaymentSummaryItem *> *summaryItems))completion.
```

**Comment by eliasturbay** [comment]
Hey @isnifer @yassinecc, any news on this? Thanks in advance!

**Comment by yassinecc** [comment]
Hi @eliasturbay , I have started working on this and have a WIP version on iOS that exposes STPShippingAddressViewController. There is however [an issue](https://github.com/appium/appium/issues/12094) with the E2E tests on CI, if you have experience with Appium/Webdriveragent we can have a look at it cc @cybergrind
