### ISSUE TITLE
Apple Pay token is actually raw credit card info

### ISSUE THREAD

**Issue by jrdzha** [tipsi/tipsi-stripe#334]
Currently, I am generating a Stripe token using Apple Pay and sending it to my Firebase Cloud Function backend where I am using it to create a charge like so:

```
stripe.charges.create({
    amount: amount,
    currency: 'usd',
    source: token,
});
```

However, I am getting the following error:

**Error: Sending credit card numbers directly to the Stripe API is generally unsafe. We suggest you use test tokens that map to the test card you are using, see https://stripe.com/docs/testing.**

Does this mean that the token generated by Tipsi-Stripe is not actually a Stripe token, but just what Apple Pay generates?

Thanks!

**Comment by isnifer** [comment]
@jrdzha Hi! Could you please provide your code for token creation.

**Comment by jrdzha** [comment]
My fault. I was sending the entire token generated by tipsi in, where instead you are only supposed to use the tokenId.
