### ISSUE TITLE
Android crashing on .createSourceWithParams() redirect

### ISSUE THREAD

**Issue by NikoMontana** [tipsi/tipsi-stripe#335]
I took me some time, but hopefully I can help somebody with this solution, to avoid that waste of time in future.

```
<activity android:name=".RedirectUriReceiver">
  <intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="${tipsiStripeRedirectScheme}" tools:replace="android:scheme" />
  </intent-filter>
</activity>
```

the documentation of this may be outdated. My app crashed without leaving an error. I opened Android Studio to see the logcat for the messages. It told me "ClassNotFound" for "RedirectUriReceiver". 

I solved it by adding the full namespace to the manifest at the activity declaration:

`<activity android:name="com.gettipsi.stripe.RedirectUriReceiver">`

**Comment by nenti** [comment]
Thx for fix @NikoMontana, you saved my day.

The ticket should be reopened until this is corrected in the docs. Android crashes on return when you follow the documentation.

**Comment by cinnabarcaracal** [comment]
Thanks @NikoMontana, I was getting the same crash (using tipsi-stripe 6.1.2).

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.******.******, PID: 8349
                  java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.******.******/
                  com.******.******.RedirectUriReceiver}: java.lang.ClassNotFoundException: Didn't find class
                  "com.******.******.RedirectUriReceiver" on path: DexPathList[[zip file "/data/app/
                  com.******.******-3gaJhAlKn3pS0zuFuhYnIw==/base.apk"],nativeLibraryDirectories=[/data/app/
                  com.******.******-3gaJhAlKn3pS0zuFuhYnIw==/lib/x86,
                  /data/app/com.******.******-3gaJhAlKn3pS0zuFuhYnIw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
```

**Comment by lukebrandonfarrell** [comment]
@NikoMontana You are awesome!
