### ISSUE TITLE
Cancelling paymentRequestWithCardForm screen Programatically

### ISSUE THREAD

**Issue by Sharev** [tipsi/tipsi-stripe#338]
Is there a way to cancel the 'Add a Card' screen programatically

**Comment by Sharev** [comment]
The 'Add a card' screen doesn't go away even on reloading the app unless user presses Cancel or Done. 
Added a picture of what screen I am talking about -
![snip20180724_4](https://user-images.githubusercontent.com/8383154/43117119-8beb8ce8-8f4e-11e8-8f95-99aabad18a33.png)

**Comment by Sharev** [comment]
@isnifer Does my above comment make it a bug?

**Comment by isnifer** [comment]
@Sharev this view is a Native view. Not sure it can just hide if you will reload an app
