### ISSUE TITLE
Getting Unhandled Promise Rejection when using stripe.deviceSupportsAndroidPay()

### ISSUE THREAD

**Issue by JesseTheDev** [tipsi/tipsi-stripe#339]
So i'm attempting to use the package, but I'm getting no value returned from the promise. From the code below "here" is shown, but "allowed" is never shown. 

`async componentWillMount() {`
        `console.warn('here');`
       ` const allowed = await stripe.deviceSupportsAndroidPay();`
       ` console.warn('allowed', allowed);`
        `this.setState({ allowed });`
` }`

I'm attempting to see the value of this.state.allowed in the render() function, but it remains the default false value. This has all been tested on my phone and on an emulator.

Here's a screen shot of the warning in an emulator:

<img width="267" alt="screen shot 2018-07-23 at 2 43 38 pm" src="https://user-images.githubusercontent.com/6569225/43096391-efdf603a-8e86-11e8-9e7e-f2828ded45cb.png">

**Comment by isnifer** [comment]
@JesseTheDev, Hi! You need an emulator with Google Play Services.
![image](https://user-images.githubusercontent.com/1788245/43106560-d1df4b80-8ee1-11e8-9345-4ed73c96ae54.png)

Also, I would like to recommend you wrap most of all your `tipsi-stripe` calls with try\catch. A response of most of them depends on phone/emulator settings.

Good luck!
