### ISSUE TITLE
Do not deprecate GooglePay and ApplePay methods

### ISSUE THREAD

**Issue by squirly** [tipsi/tipsi-stripe#347]
Due to branding guidelines, having these methods separate allows for conditionally setting up UI, to meet branding compliance with Apple Pay and Google Pay.

Additionally the Google Pay and Apple Pay follow different flows. Apple Pay works as the final checkout step, before showing a success screen; while Google Pay is used instead of a regular credit card collection form, before showing a confirmations screen. When creating a compliant workflow, it is necessary to differentiate between the two flows. One, for managing the confirmation screen when using Android Pay; and two, for showing the correct buttons and payment method logos.

Alternatively, a new method could be created that returns the native method. Eg:
```ts
function getNativePaymentMethod(): 'applePay' | 'googlePay';
```

**Comment by bramski** [comment]
This looks like a breaking change in the 5.x.x versions?

**Comment by squirly** [comment]
It is slated to be a breaking change in `6`, as the change happened in `5.4.0`. See [CHANGELOG.md: 5.4.0](https://github.com/tipsi/tipsi-stripe/blob/master/CHANGELOG.md#540---2018-07-27).

> Breaking changes will be introduced in version 6

I think the usability of the API changes should be further evaluated, for the above reasons, before version 6 is released.

**Comment by isnifer** [comment]
@squirly Hi! Actually, I don't see any problem you described above. Why did you setup a UI depends on 3rd-party module? 
You have a `Platform.select` in `react-native` package to do it.
I really don't understand how this change can break something on your side, on someone's side.

**Comment by isnifer** [comment]
@bramski nope, we've just introduced new methods and deprecated existed.
