### ISSUE TITLE
at example app, cannot npm install done

### ISSUE THREAD

**Issue by Koshukey** [tipsi/tipsi-stripe#348]
I tried to run example app. 
When I do npm install, it stopped here in the picture and does not continue installing.
What is going on ???
<img width="1435" alt="2018-07-31 15 20 32" src="https://user-images.githubusercontent.com/31874274/43441383-999f9212-94d5-11e8-93ee-e7ae26eda5c5.png">

**Comment by spencewine** [comment]
@Koshukey how did you fix? I'm having a similar issue
