### ISSUE TITLE
Undeclared 'STPSourceTypeBitcoin:' 

### ISSUE THREAD

**Issue by jzhw0130** [tipsi/tipsi-stripe#354]
tipsi-stripe: 5.2.4

The Native Library(stripe/stripe-ios) has removed bitcoin support, but the RN library has not removed the usage, so the error happens now. 

https://github.com/stripe/stripe-ios/issues/1006#issue-348136192

**Comment by isnifer** [comment]
@jzhw0130 Hi! Just downgrade version of Stripe Pod. We have plans to update Stripe dependency in near future. See example dir in root of repo

**Comment by jzhw0130** [comment]
ok thx
