### ISSUE TITLE
Google Pay in Emulator

### ISSUE THREAD

**Issue by paintedbicycle** [tipsi/tipsi-stripe#356]
Hi all,

The docs are very light on how to get Google Pay running. In fact the links to the Google documentation from your documentation are all broken, leading to further difficulty.

I'm having trouble getting Google Pay to show up in my app (I've only tried in Emulator). Apple Pay works fine, credit card works fine and I'm using the newest "NativePay" functions from your library. Basically the Android pay button just doesn't show, leading me to assume my device is not ready to support it.

I have:

- installed the wallet enabled manifest code
- installed the latest tipsi stripe
- updated the google play services dependencies
- I'm running API 27+

But Android Pay doesn't show up, only the credit card form. I'm assuming it's something to do with the Emulator and some basic setup that needs to be done in order to get it working. If so, it's likely good information to put in the documentation. 

Some things I'm wondering:

1. Do I need to use a VPN to point my device to specific countries?
2. Do I need to set up the wallet on my Emulator before hand?
3. Do I need to create a Google account or other configuration in the Emulator?

Any other reasons you can think of why it's not showing up in the Android emulator?

Paul

**Comment by paintedbicycle** [comment]
It is not possible.

https://stackoverflow.com/questions/26100032/how-to-test-in-app-billing-on-an-emulator

https://developer.android.com/google/play/billing/billing_testing

> You cannot use the emulator to test Google Play Billing; you must install your application on a device to test Google Play Billing.

**Comment by densa** [comment]
@paintedbicycle it possible if use genymotion

**Comment by paintedbicycle** [comment]
@densa Have you done that successfully? I downloaded Genymotion, but when I create a Google Pixel 2 using Android 8.0 and go to the Google Play Store, the Google Pay app says it's not compatible with my device.
