### ISSUE TITLE
build successfully on android but the app unable to open

### ISSUE THREAD

**Issue by chanthea** [tipsi/tipsi-stripe#357]
## The problem

build successfully on android but the app unable to open. No errors are shown. It just keep closing when trying to open it without any errors. It's working fine when i remove unlink tipsi-stripe lib. Tested on Genymotion and real devices

## Environment
* "tipsi-stripe": "^5.5.1"
*  Android: 
* OS version: Window 10
*"react-native": "^0.55.4",

```
 compileSdkVersion 27
    buildToolsVersion '27.0.3'

    defaultConfig {
        applicationId "com.fitwoohoo"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }
```
![screenshot 759](https://user-images.githubusercontent.com/13411778/44055984-1a350b46-9f71-11e8-9807-7cd303beb338.png)

Updated : I check the logcat and here what it make the app crashed. 
![capture](https://user-images.githubusercontent.com/13411778/44059442-9b51c656-9f7b-11e8-9f53-a548d752c9e6.PNG)

**Comment by isnifer** [comment]
Hi! @chanthea, please, do not skip sections in issue template

**Comment by thomashagstrom** [comment]
We also have this issue

- React-Native 0.57.1
- tipsi-stripe ^5.6.0
- Android Studio 3.2
-     buildToolsVersion = "27.0.3"
-     minSdkVersion = 21
-     compileSdkVersion = 27
-     targetSdkVersion = 27
-     supportLibVersion = "27.1.1"
-     googlePlayServicesVersion = "15.0.0"
-     androidMapsUtilsVersion = "0.5+"
