### ISSUE TITLE
Redirect without user interaction

### ISSUE THREAD

**Issue by NikoMontana** [tipsi/tipsi-stripe#359]
I am using the createSourceWithParams function and after a successful payment the user gets redirected to the given returnURL. I wanted to ask if it is possible to skip this extra screen in the webview and directly call the return url so the user returns to the app without interaction "return to APPNAME"

**Comment by isnifer** [comment]
@NikoMontana no. We do not control this step. Stripe only.

**Comment by NikoMontana** [comment]
@isnifer I have talked now to Stripe about this. They said I should call the payment processor, in my case sofort. Now after talking to sofort, they told me I can configure this by loging in into the sofort dashboard. But this is not possible since stripe registers you at sofort. 

Ok, close to get fed up with this, I talked once again to stripe. And they told me that the normal behaviour is that the returnURL will get triggered after a successfull / failed charge. 

Now concluding - we are controling this step.
