### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by xenobarbital** [tipsi/tipsi-stripe#361]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I'm tinkering with tipsi-stripe's paymentRequestWithCardForm() method to make it support UI localization (project app is supposed to support EN, IT and DE). I'm browsing tipsi-stripe's documentation and can't find anything localization-related. Also changing language settings of the Android device changes UI only partly (see screenshots). On iOS it disregards device language settings and shows only English UI.

## Environment
* `tipsi-stripe` version: 5.2.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: both
* OS version: iOS 11.4.1, Android 7.0
* React-Native version: 0.55.4
* (Android only) `com.google.firebase:firebase-core` version: 11.8.0
* (Android only) `com.google.android.gms:play-services-base` version: 11.8.0

## Screenshots
![stripe_en](https://user-images.githubusercontent.com/15430055/44344421-bbaa7300-a4a1-11e8-8c95-4dfe4b2152aa.png)
![stripe_it](https://user-images.githubusercontent.com/15430055/44344473-d41a8d80-a4a1-11e8-9454-6a3be2f8aa00.png)
![stripe_de](https://user-images.githubusercontent.com/15430055/44344483-da106e80-a4a1-11e8-9351-2d631758776f.png)

**Comment by isnifer** [comment]
Hi @xenobarbital! Your issue duplicates #288 and fixed in 5.3.0 — #325. So, just upgrade to the latest version of tipsi-stripe :)
