### ISSUE TITLE
React/UIView+React.h file not found on #import <React/UIView+React.h> in TPSCardField.h

### ISSUE THREAD

**Issue by asifalikhokhar** [tipsi/tipsi-stripe#363]
I've been running into this issue for almost whole day
It says React/UIView+React.h file not found on 
#import <React/UIView+React.h> 
in TPSCardField.h file

Any help please ?
I have already followed complete installation and linking guide

**Comment by isnifer** [comment]
@asifalikhokhar Hi! Please, follow issue template. It helps us get more information to help you.

**Comment by Bamorem** [comment]
Hi any solution since August of 2018 ?
I have the same issue using : 
"tipsi-stripe": "^8.0.0-beta.10"
"react-native": "^0.61.5"
