### ISSUE TITLE
Cocoa and requirements question

### ISSUE THREAD

**Issue by EstebanBP** [tipsi/tipsi-stripe#364]
Hi, I have two questions and I couldn't find answer to them.

- I've seen this issue #62 but I do not know if it is possible to install this library without using cocoa. I have never used it yet.
- Does this library work on iPhones/iPads with iOS 9? I've seen +10 iOS is required but I'm not sure (https://tipsi.github.io/tipsi-stripe/docs/index.html)

Edit: I managed to setup cocoa on my project and everything seems to be working nice, but I couldn't find in documentation how to localize texts. It is not using device settings language (at least while using iOS)

**Comment by isnifer** [comment]
@EstebanBP We do not manage localization strings on `tipsi-stripe` side. See https://github.com/stripe/stripe-ios for iOS.

**Comment by akepecs** [comment]
Is it possible to install this library without Cocoapods?

**Comment by EstebanBP** [comment]
@isnifer I did not find a way so I had to use Cocoapods
