### ISSUE TITLE
Android build failing (cannot find symbol)

### ISSUE THREAD

**Issue by danwoodbury** [tipsi/tipsi-stripe#365]
## The problem
I am getting a huge amount of errors while trying to build my android project after installing this library. on iOS it works seemlessly but for some reason android is having none of it. Ive looked through the other issues and cannot see anything of the same ilk.

i linked via `react-native link tipsi-stripe` and got the errors so I went through the manual setup and everything is setup correctly. I have also tried cleaning the project using `./gradlew clean` but with no luck.

## Environment
* `tipsi-stripe` version: 5.6.0
* iOS or Android: Android
* React-Native version: 0.56.0
* (Android only) `com.google.firebase:firebase-core` version: 15.0.2
* (Android only) `com.google.android.gms:play-services-base` version: 15.0.0

## Links to logs and sources
[build-logs](https://gist.github.com/danwoodbury/69f75393e747f3781b2c5338c9c59c1b#file-stripe-errors)
[android/app/build.gradle](https://gist.github.com/danwoodbury/69f75393e747f3781b2c5338c9c59c1b#file-build-gradle)

## Screenshots, GIFs (Must to have)
Build dosnt get this far

Thanks in advance

**Comment by isnifer** [comment]
@danwoodbury Please, do not ignore any section of the issue template — it's not difficult. 
Look into **YOUR** `android/app/build.gradle` and compare with https://github.com/tipsi/tipsi-stripe/blob/master/example/android/app/build.gradle

**Comment by danwoodbury** [comment]
thanks for the pointer @isnifer. I had already done what you suggested and just did it again for safe measure but to no avail. The main difference i see is that I am using grade 4.4 due to it being a requirement for firebase, but im not sure that would make much difference?

Here is my `build.gradle` file incase I have missed something. I have obviously sanitized it and stripped keys etc...

```
apply plugin: "com.android.application"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js",
    bundleInFeature: true,
    devDisabledInFeature: true,
    bundleInStaging: true,
    devDisabledInStaging: true
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
apply from: "../../node_modules/react-native-sentry/sentry.gradle"


def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

// Automate build number
def rawBuildNumber = System.getenv("BITRISE_BUILD_NUMBER") ?: "999"
def buildNumber = Integer.parseInt(rawBuildNumber)

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"

    dexOptions {
        jumboMode true
    }

    defaultConfig {
        applicationId "com.example.app"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode buildNumber
        versionName "0.11.2"
        resValue "string", "build_config_package", "com.example.app"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        renderscriptTargetApi 26
        renderscriptSupportModeEnabled true
        multiDexEnabled true
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            buildConfigField "String", "CODEPUSH_KEY", '""'
        }
        feature {
            applicationIdSuffix ".feature"
            buildConfigField "String", "CODEPUSH_KEY", '""'
        }
        staging {
            applicationIdSuffix ".staging"
            buildConfigField "String", "CODEPUSH_KEY", '""'
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            buildConfigField "String", "CODEPUSH_KEY", '""'
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride = versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation project(':rn-fetch-blob')
    implementation project(':react-native-branch')
    implementation(project(':react-native-firebase')) {
        transitive = false
    }
    implementation project(':react-native-blur')
    implementation project(':react-native-svg')
    implementation project(':react-native-splash-screen')
    implementation project(':@example/react-native-mixpanel')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-code-push')
    implementation project(':react-native-sentry')
    implementation project(':react-native-config')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-camera')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:support-v4:26.1.0"
    implementation "com.android.support:design:26.1.0"
    implementation "com.android.support:appcompat-v7:26.1.0"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-camera')
    implementation project(':tipsi-stripe')

    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-core:15.0.2"
    implementation "com.google.firebase:firebase-messaging:15.0.2"
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'
    implementation 'com.android.support:multidex:1.0.3'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

repositories {
    maven {
        url 'https://maven.google.com/'
        name 'Google'
    }
}

apply plugin: 'com.google.gms.google-services'

```

**Comment by isnifer** [comment]
@danwoodbury try to add these deps to your `android/app/build.gradle`. Hope it helps!
```gradle
// Where to find the latest version for Google Modules
// https://developers.google.com/android/guides/setup
implementation 'com.google.android.gms:play-services-base:15.0.1'
implementation 'com.google.android.gms:play-services-wallet:16.0.0'
```

**Comment by FakeBounce** [comment]
> Could not find play-services-base.jar (com.google.android.gms:play-services-base:15.0.1).
>   Searched in the following locations:
>       https://jcenter.bintray.com/com/google/android/gms/play-services-base/15.0.1/play-services-base-15.0.1.jar

Can't update play-services-base to 15.0.1

**Comment by danwoodbury** [comment]
@isnifer unfortunately not. I am getting the same errors still after adding `play-services-wallet` and upgrading `play-services-base`, even after a clean

**Comment by TarasDumych** [comment]
@danwoodbury try change `com.stripe:stripe-android:6.0.0` to `com.stripe:stripe-android:6.1.2` in `node_modules/tipsi-stripe/android/build.gradle`

**Comment by danwoodbury** [comment]
@TarasDumych you are a trooper. That works. Not working completely in app but i will figure that out. Only thing is how would I make this change permanent?

**Comment by TarasDumych** [comment]
@danwoodbury  Noway. Only make a PR and update the library. I just left a note in Readme.md in my project(temporary solution).

**Comment by danwoodbury** [comment]
@TarasDumych i have just added `implementation 'com.stripe:stripe-android:6.1.2'` to my own dependencies and it works fine, obviously still temporary-ish until i can run this package without it, but it enables our project to run through a ci

**Comment by ajaykumar97** [comment]
adding
`implementation 'com.google.android.gms:play-services-base:15.0.1'`
`implementation 'com.google.android.gms:play-services-wallet:16.0.0'`

solved the problem
