### ISSUE TITLE
Tipsi_react-Native App is crashing

### ISSUE THREAD

**Issue by Manojmadhav** [tipsi/tipsi-stripe#366]
## The problem
We have incorporated the tipsi-stripe with react-native, the solution is built without any issues but app is crashing while loading 

## Environment
* `tipsi-stripe` version:  ^5.6.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: Windows 10 and 7
* React-Native version: 0.55.4
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version: 

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion  26
* android.buildToolsVersion "26.0.2"
* android.defaultConfig.minSdkVersion 16
* android.defaultConfig.targetSdkVersion 22
* android.defaultConfig.multiDexEnabled (if exists)

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

![img-20180824-wa0111](https://user-images.githubusercontent.com/40380817/44643183-3c5ef700-a9ed-11e8-84fb-a62a3386467f.jpg)
![img-20180824-wa0102](https://user-images.githubusercontent.com/40380817/44643188-3ff27e00-a9ed-11e8-8411-092630dc63e4.jpg)

## Code To Reproduce Issue (Good To Have)
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by isnifer** [comment]
@Manojmadhav Hi! As I correct understand you. 
You need to go to `example/src/Root.js`
And replace lines 17-18 with correct values.
```js
stripe.setOptions({
  publishableKey: '<PUBLISHABLE_KEY>', // <= HERE PASS REAL PUBLISHABLE KEY AT LEAST
  merchantId: '<MERCHANT_ID>', // <= PASS REAL MERCHANT ID FOR iOS
  androidPayMode: 'test',
})
```

**Comment by isnifer** [comment]
@Manojmadhav If you haven't skipped this section:
![image](https://user-images.githubusercontent.com/1788245/44655579-5fde6d80-a9fe-11e8-98d6-0bd06f7a2efa.png)
You did find yourself answer to your question

**Comment by Manojmadhav** [comment]
@isnifer Thank you for the update, We do not use applepay since we do not have  merchantId: hence we commented the code as mentioned shown below

import MenuItem from '../../components/MenuItem'
//import ApplePayScreen from '../Stripe/ApplePayScreen'
import AndroidPayScreen from '../Stripe/AndroidPayScreen'
import CardFormScreen from '../Stripe/CardFormScreen'
import CustomCardScreen from '../Stripe/CustomCardScreen'
import CustomBankScreen from '../Stripe/CustomBankScreen'
import CardTextFieldScreen from '../Stripe/CardTextFieldScreen'
import SourceScreen from '../Stripe/SourceScreen'
import testID from '../../utils/testID'

stripe.setOptions({
  publishableKey: 'pk_test_n70bkOns9PqUMG4go5E77356',
  merchantId: '1234',
  androidPayMode: 'test',
})

export default class Root extends PureComponent {
  state = {
    index: 0,
    isDrawerOpen: false,
    routes: [
      Platform.select({
        //ios: ApplePayScreen,
        android: AndroidPayScreen,


Also for a testing purpose  how we can get a test merchantId?
NB: We have gone through the site many times https://tipsi.github.io/tipsi-stripe/docs/ :-)

**Comment by Manojmadhav** [comment]
![image](https://user-images.githubusercontent.com/40380817/44669971-0ea29e00-aa3f-11e8-8beb-df47c7b26290.png)
Also we have tried to test the sample which is provided but it is not installing NPM, with various errors, we have done all possible ways from ourside. CAn you please help us on this?
