### ISSUE TITLE
Build Error for iOs

### ISSUE THREAD

**Issue by ruler47** [tipsi/tipsi-stripe#367]
## The problem
I cant build iOs app. 
`ld: 39 duplicate symbols for architecture x86_64`

## Environment
* `tipsi-stripe` version:  5.6.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable):  5.6.0
* iOS or Android:  iOs
* OS version: MacOs X 10.13.4
* React-Native version:  0.56.0

## Links to logs and sources
Error log from Xcode:
https://gist.github.com/ruler47/ad99552af5630e6ccc8374f011844d2b
Podfile (was updated, because default react version was 0.11):
https://gist.github.com/ruler47/133bdb7072e7a8b097d720152c45796d

## Screenshots, GIFs (Must to have)
![image](https://user-images.githubusercontent.com/7658092/44841432-fc497f80-ac4b-11e8-82e7-b94148e1c778.png)

**Comment by densa** [comment]
It looks like you add library twice
Can you show xcode file structure?

**Comment by ruler47** [comment]
I just deleted `libTPSStripe.a` from `Link Binary With Libraries` and build was successful.
I think that diplicate was into libPods-AppName.a
![image](https://user-images.githubusercontent.com/7658092/44842391-5c412580-ac4e-11e8-95ff-24a13297bc0b.png)

**Comment by MobileDevStar** [comment]
> I just deleted libTPSStripe.a from Link Binary With Libraries and build now successful.
I think that duplicate was into libPods-AppName.a
YOU SAVED ME!!!

**Comment by heiheiLqq** [comment]
what is libPods-AppName.a
