### ISSUE TITLE
AndroidPay test environment 

### ISSUE THREAD

**Issue by perfectdim** [tipsi/tipsi-stripe#368]
Trying to work with NativePay using tipsi-stripe.
ApplePay works perfectly, both dev and prod mode.
AndriodPay didn't work in test mode, in prod and TEST mode it said that we need to be accepted by google (its ok), but to be accepted we need to provide APK with working test mode.
On Android even deviceSupportsNativePay and canMakeNativePayPayments method crush application with critical error.

## Environment
* `tipsi-stripe` version: "5.6.0"
* iOS or Android: Android issue
* OS version: sdk 25,26,27 tried on MI, Redmi5, Samsung, Note, Pixel
* React-Native version: "0.56.0"
* (Android only) `com.google.firebase:firebase-core` version: 16.0.1
* (Android only) `com.google.android.gms:play-services-base` version: 15.0.1

* android.compileSdkVersion 26
* android.buildToolsVersion 26.0.3
* android.defaultConfig.minSdkVersion 23
* android.defaultConfig.targetSdkVersion 26
* android.defaultConfig.multiDexEnabled (if exists) 

![2018-08-31 16 58 07](https://user-images.githubusercontent.com/21329734/44911794-858eae00-ad41-11e8-849f-ed30433d92c4.png)
![2018-08-31 16 58 18](https://user-images.githubusercontent.com/21329734/44911800-8d4e5280-ad41-11e8-9d95-ba3973740cde.png)
![img_0974](https://user-images.githubusercontent.com/21329734/44911868-d9999280-ad41-11e8-9c87-4d13042b51f9.JPG)
![android](https://user-images.githubusercontent.com/21329734/44912622-431aa080-ad44-11e8-9f7f-336161456581.gif)

**Comment by perfectdim** [comment]
Additional information:
paymentRequestWithCardForm method works great for IOS and Android.
If I do not use deviceSupportsNativePay and canMakeNativePayPayments methods, but run paymentRequestWithNativePay in TEST mode with TEST token, then I get message that I need to be accepted by google.

![android2 2](https://user-images.githubusercontent.com/21329734/44913475-ebc9ff80-ad46-11e8-8987-0f428c369edc.gif)

**Comment by isnifer** [comment]
@perfectdim Hi! Try to run `deviceSupportsNativePay` or `canMakeNativePayPayments` before try to pay. These methods exists not just for fun.
Wrap all these requests with `try-catch` call and see an error.

```js
async function pay() {
  try {
    // Indicates about google pay availability
    const isDeviceSupportsNativePay = await stripe.deviceSupportsNativePay()
    const isUserHasAtLeastOneCardInGooglePay = await stripe.canMakeNativePayPayments()

    if (isDeviceSupportsNativePay && isUserHasAtLeastOneCardInGooglePay) {
      await stripe. paymentRequestWithNativePay(options)
    }
  } catch (error) {
    console.log(error) // In debug mode see the error
    showUserAMessageAboutHisDeviceOrAboutHisCardsOrSomethingElse()
  }
}
```

**Comment by perfectdim** [comment]
solved. 
This should be in application tag =)
```
<meta-data
android:name="com.google.android.gms.wallet.api.enabled"
android:value="true" />
```
my fault ))

**Comment by CelsiusWilliams** [comment]
I am having the same problem. But I have this meta-data tag in my manifest already

**Comment by cjvilla2012** [comment]
@CelsiusWilliams You need to call setOptions before using any other methods. The Android code has a default value for the Environment that is invalid and throws an Exception not handled by the library. The setOptions method sets the Environment.

E.g.:

    ```
stripe.setOptions({
        publishableKey: 'pk_test_fromstripe',
        merchantId: 'applemerchantid', // Optional
        androidPayMode: 'test', // Android only
    })
    const paymentSupported = await stripe.deviceSupportsNativePay();
```

**Comment by CelsiusWilliams** [comment]
@cjvilla2012 
Thanks, I already got it working.

**Comment by cjvilla2012** [comment]
@prameetc Yes
