### ISSUE TITLE
[Question] Gift card support?

### ISSUE THREAD

**Issue by shokimble** [tipsi/tipsi-stripe#369]
Does anyone know if gift cards work in any shape or form with tipsi stripe? Short of actually signing up with one of stripes partners I see no way of verifying whether it works. So sorry if the question did sound stupid, hopefully it's not so much.

Here are the partners stripe lists:

https://stripe.com/works-with/category/gift-certificates

I know Google pay lets you store gift cards but I get the feeling only prepaid credit cards are going to work. This is not what I want as I want them to be only able to buy within my app.

**Comment by isnifer** [comment]
Hi @shokimble! If it requires any code updates to `tipsi-stripe` — PRs are welcome!
