### ISSUE TITLE
App gets stuck at .createTokenWithBankAccount()

### ISSUE THREAD

**Issue by briancajulis** [tipsi/tipsi-stripe#372]
## The problem
My app gets stuck at .createTokenWithBankAccount() when I try to give it random parameters to test for a case when the user enters in the wrong account information.  When given the test params given by the Stripe docs, it will succeed, but when given random test params, it get stuck at creating a stripe token for bank accounts.

Stripe Test Params: Success
```
bankParams = {
     countryCode: 'AT',
     currency: 'EUR',
     accountNumber: 'AT89370400440532013000',
     accountHolderName: 'Test',
     accountHolderType: 'individual'
};
```

Stripe Test Params: Stuck at creating token
```
bankParams = {
     countryCode: 'AT',
     currency: 'EUR',
     accountNumber: 'AT611904300235473201',
     accountHolderName: 'Test',
     accountHolderType: 'individual'
};
```

My Code
```
const createStripeTokenWithBank = async () => {
     try {
          const bankParams = {
               countryCode: 'AT',
               currency: 'EUR',
               accountNumber: 'AT611904300235473201',
               accountHolderName: 'Test',
               accountHolderType: 'individual'
          };
          
          console.log('awaiting stripe token');
          const token = await stripe.createTokenWithBankAccount(bankParams);

          console.log('received token response');  // Never reaches here
          return token;
     } catch (err) {
          console.log(err);
          return err;
     }
};
```

## Environment
* `tipsi-stripe` version: ^5.6.0
* iOS 
* React-Native version: 0.56.0

**Comment by andyboythekid** [comment]
I too ran into this problem -- the catch blocks aren't assigned in these methods. I've added a PR but you can update the changes yourself: https://github.com/tipsi/tipsi-stripe/pull/392
