### ISSUE TITLE
Re-open Error Code on Android with Stripe.createTokenWithCard() on 5.6.0

### ISSUE THREAD

**Issue by LcsLpr** [tipsi/tipsi-stripe#373]
Same issue who was closed however it is not fixed ...
Ref here : #287

**Comment by LucasLpr** [comment]
> ```
> const card = await Stripe.createTokenWithCard({
>         number: newCard.number,
>         expMonth: parseInt(newCard.expiration),
>         expYear: parseInt(newCard.expiration.substring(4)),
>         cvc: newCard.cvc,
>         name: this.state.user.name
>       })
>       .catch(error => {
>         console.log(error);
>       })
> ```
> The error print :
> 
> > 
> > Error: Your card's expiration month is invalid.
> > at createErrorFromErrorData (NativeModules.js:121)
> > at NativeModules.js:78
> > at MessageQueue.__invokeCallback (MessageQueue.js:398)
> > at MessageQueue.js:137
> > at MessageQueue.__guardSafe (MessageQueue.js:314)
> > at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
> > at debuggerWorker.js:70
> 
> My question is : How do I get the object ? I want to get the error code and not the error message ...
> 
> (Ps : error.message give me this : "Error: Your card's expiration month is invalid.")

**Comment by LucasLpr** [comment]
Still here
