### ISSUE TITLE
Google pay production mode?

### ISSUE THREAD

**Issue by Meadows-VisionSharp** [tipsi/tipsi-stripe#376]
## Before I have submitted the issue 
[X] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[X] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[X] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[X] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Tried to enable production mode using live stripe key only to get a blank error on app load. The config/setup has worked just great up to now with androidpaytest mode set accordingly:
`androidPayMode: 'test'`
But setting the above to 'production' and changing the publishable key to a live alternative immediately causes an error page on the app loading with no message at all.

As there are no guides on using tipsi-stripe in production mode, i was wondering if you could provide some guidance and also update the docs with the same information as its a little misleading to say the androidPayMode just needs to be changed from test to production which in my case doesn't seem to be true. I can only assume theres android xml changes that also need to be put it place?

## Environment
* `tipsi-stripe` version: 5.2.1
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): N/A
* iOS or Android: Android
* OS version: MacOS
* React-Native version: 0.50.4
* (Android only) `com.google.firebase:firebase-core` version: N/A
* (Android only) `com.google.android.gms:play-services-base` version: N/A

For `Android`, please provide the following sections from `android/app/build.gradle`:
* compileSdkVersion: 26
* android.buildToolsVersion 28.0.1
* android.defaultConfig.minSdkVersion 16
* android.defaultConfig.targetSdkVersion 26
* android.defaultConfig.multiDexEnabled (if exists) N/A

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

## Code To Reproduce Issue (Good To Have)
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by cybergrind** [comment]
@Meadows-VisionSharp just go here https://developers.google.com/pay/api/android/guides/test-and-deploy/integration-checklist on the end of the page you will have a link to form, add your app, select tokenization method = stripe
