### ISSUE TITLE
glog/logging.h file not found

### ISSUE THREAD

**Issue by sanealytics** [tipsi/tipsi-stripe#378]
Sorry, I'm new to react-native and Xcode (I'm a backend developer).
I'm trying to get this to work and think I followed instructions. Here is what I did.

## Before I have submitted the issue 
[x ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Briefly describe the issue you are experiencing (or the feature you want to see added to `tipsi-stripe`). 
Tell us what you were trying to do and what happened instead. 

1. npm install --save tipsi-stripe
2. npm run eject
3. react-native link tipsi-stripe (already have pod)
4. Update Podfile as per example/ios/Podfile
5. pod install from iOS directory
6. MainApp -> Libraries already has TPSStripe.xcodeproj
7. Updated license in Xcode (as this is a new project now)
8. Build Phases → Link Binary With Libraries for main app profile already shows library, added to test profile too.
9. In MainApp -> Libraries -> TPSStripe.xcodeproj -> Build Settings tab, I already see the right paths under Header Search Paths
10. Build gets errors:

'glog/logging.h' file not found (from third-party -> folly package) 
'config.h' file not found (from third-party -> glog package)

## Environment
* `tipsi-stripe` version: 5.6.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: iOS, xCode 10.0
* OS version: Mac OS High Sierra 10.13.6
* React-Native version: 0.55.4
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version: 

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!

https://gist.github.com/sanealytics/c26ae7732c861c27b7fb7aa0a1568ec6

* [ios/Podfile](https://gist.github.com/link_to_podfile) 
https://gist.github.com/sanealytics/cadefdc44cffcd1f5bcf3916c8a8e311

## Screenshots, GIFs (Must to have)
![screen shot 2018-09-28 at 4 58 53 pm](https://user-images.githubusercontent.com/1840180/46233207-d3e29d00-c33f-11e8-9986-deafd6d708c4.png)

I'd love to get this to work so I can accept payments and this solution looks pretty elegant. I'd really appreciate some help in figuring this out.

**Comment by sanealytics** [comment]
Turns out this is an Xcode 10.0 issue. Use legacy build for now.

**Comment by zry754331875** [comment]
it doesn`t work for me
