### ISSUE TITLE
Unable to build with firebase-core-16.0.3

### ISSUE THREAD

**Issue by rahsheen** [tipsi/tipsi-stripe#379]
## Before I have submitted the issue 
[x ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I am unable to build my app after upgrading firebase-core dependency to 16.0.3. If I supply the global firebaseVersion as 16.0.3, I get the error:

> * What went wrong:
> Failed to capture snapshot of input files for task ':tipsi-stripe:compileDebugAidl' property 'importDirs' during up-to-date check.
> > The library com.google.firebase:firebase-iid is being requested by various other libraries at [[17.0.2,17.0.2]], but resolves to 16.0.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

If I do _not_ include `firebaseVersion` I get:

> Failed to capture snapshot of input files for task ':tipsi-stripe:compileReleaseAidl' property 'importDirs' during up-to-date check.
> > The library com.google.firebase:firebase-analytics is being requested by various other libraries at [[16.0.3,16.0.3]], but resolves to 11.8.0. Disable the plugin and check your depen

## Environment
* `tipsi-stripe` version: 5.6.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): n/a (also had issue with 5.2.1)
* iOS or Android: Android
* OS version: 
* React-Native version: 0.57
* (Android only) `com.google.firebase:firebase-core` version: 16.0.3
* (Android only) `com.google.android.gms:play-services-base` version: 15.0.1

## Links to logs and sources
[build.gradle and app/build.gradle](https://gist.github.com/rahsheen/cf6f2b1d92f322feeaeed4268c64d007)

For `Android`, please provide the following sections from `android/app/build.gradle`:
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
        firebaseVersion = "16.0.3"
        googlePlayServicesVersion = "15.0.1"
    }
multiDexEnabled true

**Comment by beausmith** [comment]
@rahsheen - I'm having a similar issue. Any luck with a fix/workaround?

**Comment by evaleirasclapps** [comment]
Same here!

**Comment by EugeValeiras** [comment]
@rahsheen  @beausmith Did you fixed it?

**Comment by beausmith** [comment]
@EugeValeiras Not fixed… still trying… 😐 Please post any successes here.

Perhaps useful are things you can find in the [Network Graph](https://github.com/tipsi/tipsi-stripe/network)… this one was interesting:
- https://github.com/joeyvadala/tipsi-stripe/commit/858b01ef129954f5936efed1340defb4b2e3450b

There are many more commits ahead of the official master branch in the Network Graph view which may contain a fix for this.

**Comment by NikoMontana** [comment]
Your not alone 💯

**Comment by cybergrind** [comment]
> The library com.google.firebase:firebase-iid is being requested by various other libraries at [[17.0.2,17.0.2]], but resolves to 16.0.0.
What if you set firebase to the 17.0.2 version?

**Comment by NikoMontana** [comment]
@cybergrind It is requesting then the 17.0.2. I am on react native firebase v5 and they install instructions point to 16.0.3. I will give it a try but I am not sure if this will work.

**Comment by beausmith** [comment]
An update… so I originally got this error in the following scenario:

1. Computer auto updated to Xcode 10.
2. React Native 55.4 project would no longer build.
3. Upgraded to RN 57.1.
4. Fixed a couple things that Xcode complained about: 
    - conflicting Info.plist files.
    - "Use legacy build system" in iOS.
5. Tried to build and got this error related to `tipsi-stripe` requiring older versions of `firebase-core`
6. Stuck.

Then decided to try alternate route…

1. Computer auto updated to Xcode 10.
2. Fixed a couple things that Xcode complained about: 
    - conflicting Info.plist files.
    - "Use legacy build system" in iOS.
3. No longer stuck. 

Now I know that I probably won't be able to upgrade to React Native until `tipsi-stripe` is updated to work with latest versions of react-native. 🎉

**Comment by NikoMontana** [comment]
Then I think we should update this lib to react-native 0.57.1 or change to adyen, anyway cheaper :D

**Comment by rahsheen** [comment]
You can't just downgrade google-services if you have other dependencies that rely on an up-to-date version.

**Comment by NikoMontana** [comment]
@rahsheen for me it is working with 10+ third party libs. This is a temp. solution, but if you have a better one, let me know.

**Comment by emlynmac** [comment]
@NikoMontana I can confirm this worked for me too. Thanks!

**Comment by Bill-Niz** [comment]
Any fix yet?

**Comment by nikodunk** [comment]
@NikoMontana this fix now breaks Firebase Messaging.

**Comment by ronilitman** [comment]
Any fix yet?

**Comment by rahsheen** [comment]
Is that with latest tipsi-stripe and react-native? @ronilitman

**Comment by ronilitman** [comment]
@rahsheen Yes, RN 0.59.8 and tipsi-stripe 7.5.0. My error message is a little bit diffrent:
`The library com.google.firebase:firebase-iid is being requested by various other libraries at [[18.0.0,18.0.0]], but resolves to 17.1.2.`

I tried to use various of versions, now my versions are:
` implementation 'com.google.firebase:firebase-core:16.0.9'`
` implementation 'com.google.firebase:firebase-messaging:18.0.0'`

Any suggestions? Thank you!

**Comment by rahsheen** [comment]
> @rahsheen Yes, RN 0.59.8 and tipsi-stripe 7.5.0. My error message is a little bit diffrent:
> `The library com.google.firebase:firebase-iid is being requested by various other libraries at [[18.0.0,18.0.0]], but resolves to 17.1.2.`
> 
> I tried to use various of versions, now my versions are:
> ` implementation 'com.google.firebase:firebase-core:16.0.9'`
> ` implementation 'com.google.firebase:firebase-messaging:18.0.0'`
> 
> Any suggestions? Thank you!

Does specifying a specific firebaseVersion as in #375 help at all? I haven't had a chance to try that yet.

**Comment by jbernhardt23** [comment]
I'm actually using other firebase dependencies myself and was getting this issue. I updated my google services to 4.2.0 instead of downgrading it. 

`classpath 'com.google.gms:google-services:4.2.0'`

**Comment by ranggabadrus** [comment]
Any fix yet?
