### ISSUE TITLE
Linking Tipsi with "react-native link tipsi-stripe" adds deprecated "React" to project

### ISSUE THREAD

**Issue by dmkaner** [tipsi/tipsi-stripe#381]
## Before I have submitted the issue 
[✓] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[✓] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[✓] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[✓] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Currently, linking tipsi-stripe with the command "react-native link tipsi-stripe" does link tipsi, but it also adds "react" to the podfile. When it is installs "react" through the podfile, a status update in terminal mentions that it is deprecated, but now when you try to run your project there will be a lot of conflicting files and just really makes a mess. I've tried removing react manually at this point but something else down the line always breaks. I then attempted to start over and link it manually to evade this, but when linking manually I am stopped at the part where you must add "libTPSStripe.a" to your iOS build phases. There is an issue related to this but it came about for them because they were not using pods, I on the other hand am using pods and have Stripe in my podfile. It's weird that this is all happening because the project was actually working great with tipsi without even having linked it, but then all of a sudden an error: "undefined is not an object (evalutating 'StripeModule.init'). 

The Tipsi library is great aside from this, happy to describe this in more detail if needed, thanks!

## Environment
* `tipsi-stripe` version: 5.6.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): NA
* iOS or Android: iOS (haven't tested Android yet but I'm sure the same issue would persist)
* OS version: 9.0
* React-Native version: 0.55.3

## Links to logs and sources
https://github.com/dmkaner/tipsiProjectBug

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

<img width="334" alt="screen shot 2018-10-02 at 3 12 09 pm" src="https://user-images.githubusercontent.com/12825396/46371147-92126900-c655-11e8-9709-1a6dc81323ca.png">

<img width="568" alt="screen shot 2018-10-02 at 3 14 55 pm" src="https://user-images.githubusercontent.com/12825396/46371292-f6cdc380-c655-11e8-9a79-b9c10e31077d.png">

**Comment by NikoMontana** [comment]
Please Post your podfile

**Comment by swingywc** [comment]
Hi @cybergrind @isnifer , sorry to disturb you but I think it an fatal issue. On my side, I ran perfectly with `react-native` `v0.57.1` before installing `tipsi-stripe`. However once I follow the installation guide and install `tipsi-stripe`, it cannot build my app (I use `react-native run-ios`). Some of my error log will be attached below:

![image](https://user-images.githubusercontent.com/9659080/46568975-863de400-c980-11e8-8705-94abd1d81c95.png)
![image](https://user-images.githubusercontent.com/9659080/46568987-ca30e900-c980-11e8-9734-cb3427d89f20.png)
![image](https://user-images.githubusercontent.com/9659080/46568989-d9179b80-c980-11e8-8882-52ed5f135dc9.png)
![image](https://user-images.githubusercontent.com/9659080/46569002-02d0c280-c981-11e8-8e76-2e5e40d2a5cf.png)

Seem likes `tipsi-stripe` or `Stripe` install `React (0.11.0)` in Cocoapods which leads to duplicate React package.

**Comment by cybergrind** [comment]
@swingywc right now we don't have time to fix this issue. There are a couple possible ways:
* Downgrade RN to working (check RN 0.45 https://github.com/tipsi/tipsi-stripe/tree/master/example)
* Fix it by someone else and send PR (note that we need RN 0.45 working and all TravisCI tests working too)

**Comment by cybergrind** [comment]
Or you can wait until we bump RN version on our side and fix issues

**Comment by ideerge** [comment]
Any news on this? Tipsi-stripe has never run correctly yet so far on my computer.

**Comment by cybergrind** [comment]
@ideerge no news on this.

Personally, I can suggest starting with example app in this repo and steps in `.travis/ci.sh`. This works on Travis and should work in your case. Maybe you will figure out what is wrong in your case

**Comment by andidev** [comment]
This may solve the issue
https://github.com/react-native-community/react-native-svg/issues/621#issuecomment-424989842

**Comment by christopheragnus** [comment]
Hi there, is there a fix for this? I have run `pod install` but I don't get the React deprecated error. Its says the link is successful but I get the same error as above:

`undefined is not an object (evaluating 'StripeModule.init')`

According to the call stack, it seems to be caused when I attempt to call any `stripe` functions.

**Comment by ndrisso** [comment]
Thanks @andidev! This is an extended explanation on how to hack/fix the issue https://sandstorm.de/de/blog/post/react-native-managing-native-dependencies-using-xcode-and-cocoapods.html

**Comment by bnol** [comment]
@swingywc I'm running into the same issue. Have you found any solution so far? My project is an ejected Expo project which I cannot downgrade the react-native version :(
`"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",` (RN 0.57.1)

**Comment by fbartho** [comment]
We solved this issue by using the npm package `Xcode` in order to rewrite the header imports so that they resolve correctly. -- We do not support Cocoapods in our project.
