### ISSUE TITLE
IOS BUILD FAILED

### ISSUE THREAD

**Issue by imadarif** [tipsi/tipsi-stripe#387]
ld: warning: directory not found for option '-F/Users/vservicesltd/Desktop/appygo_mobileApp/ios/../node_modules/react-native-payments-addon-stripe/Carthage/Build/iOS/'
ld: library not found for -lReactNativePayments
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sfyfe31** [comment]
Are you sure you've used `tipsi-stripe`? It's [react-native-payments](https://github.com/naoufal/react-native-payments) which uses `react-native-payments-addon-stripe`.

**Comment by TsarlinDomingo** [comment]
Hello @sfyfe31 

Right after npm install, I tried to run react-native run-ios and the build fails for the example project with the following result:

`
Installing build/Build/Products/Debug-iphonesimulator/example.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
`

Could you help what is missing/wrong to be fixed here?

**Comment by sfyfe31** [comment]
You haven't entered your `Bundle Identifier` in Xcode. You have to do this first before you can run in simulator.

**Comment by imadarif** [comment]
this issue is resolved by removing ios folder and eject ios again. then reconfigure this plugin. it works perfectly

**Comment by TsarlinDomingo** [comment]
Got it working now, thanks!
