### ISSUE TITLE
'React/UIView+React.h' file not found

### ISSUE THREAD

**Issue by emurigar** [tipsi/tipsi-stripe#390]
Hi,
I'm trying to install the module in IOS in android the instalation go well.
My Pod file is the following:
`# Use iOS 8 and above
platform :ios, '8.0'

# Specify Workspace
workspace 'example'

target 'example' do
  # Stripe
  pod 'Stripe', '~> 11.2.0'

  # Install additional dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

end`

But when I compile the error is the following: ''React/UIView+React.h' file not found'

I'm using:
"react": "16.3.1",
"react-native": "0.55.4",
"tipsi-stripe": "5.6.0"

Thanks

**Comment by lautapercuspain** [comment]
Any update on this ??

**Comment by cybergrind** [comment]
@lautapercuspain this doesn't look like tipsi-stripe's error. There are quite a lot of similar issues in search, so I believe it is some general react-native problem
