### ISSUE TITLE
Update brand logos due to approve failure with finance provider services

### ISSUE THREAD

**Issue by iagorm** [tipsi/tipsi-stripe#402]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
The project are using brand logo outdated, this is causing reproved checks with financial services, the project must update the card brands. 

## Environment
* `tipsi-stripe` version: ^6.1.2
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): ^5.6.0
* iOS or Android: Both
* OS version: MacOS 10.13.5
* React-Native version: 0.55
* (Android only) `com.google.firebase:firebase-core` version: 16.0.1
* (Android only) `com.google.android.gms:play-services-base` version: none

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion 27
* android.buildToolsVersion 27.0.3
* android.defaultConfig.minSdkVersion 19
* android.defaultConfig.targetSdkVersion 26
* android.defaultConfig.multiDexEnabled true

## Screenshots, GIFs (Must to have)
![48125488-f7193a00-e265-11e8-9821-8ee1417f9ef5](https://user-images.githubusercontent.com/13892132/48130113-b116a300-e272-11e8-9f6e-6b9081aada0c.png)

**Comment by fbartho** [comment]
@iagorm -- are you sure the images are included in this library? -- I think the images come from the native Stripe SDK? -- I couldn't find them when casually searching.

If the images aren't in this library, then this ticket should be filed against Stripe's SDKs for iOS & Android!
