### ISSUE TITLE
createSourceWithParams for card type

### ISSUE THREAD

**Issue by mdeket** [tipsi/tipsi-stripe#406]
I keep getting Promise rejection when set type to be 'card'. 
Your documentation says that you support 'card' as type when creating a Source, however then I started looking into your source code and found out that actually 'card' is not supported.
I attached screenshots to see what I mean.

## Environment
* `tipsi-stripe` version: ^6.1.2

## Screenshots
Found in utils/types.js: 
![screen shot 2018-11-13 at 11 12 40 am](https://user-images.githubusercontent.com/9460508/48406537-10722880-e735-11e8-9cab-9e4c8584e7e9.png)
However documentation says this:
![screen shot 2018-11-13 at 11 14 04 am](https://user-images.githubusercontent.com/9460508/48406649-4adbc580-e735-11e8-9bea-ae57618e20cd.png)

**Comment by tendolukwago** [comment]
Any follow up on this?

**Comment by cybergrind** [comment]
@tendolukwago not yet

**Comment by Slexom** [comment]
I've the same issue.
 `"dependencies": {
    "react": "16.6.1",
    "react-native": "0.57.5",
    "tipsi-stripe": "^6.1.2"
  },`
`Error: Failed params type: Invalid params `type` of value `card` supplied to `Stripe.createSourceWithParams`, expected one of ["bancontact","giropay","ideal","sepaDebit","sofort","threeDSecure","alipay"].`

**Comment by LRNZ09** [comment]
This issue is related https://github.com/tipsi/tipsi-stripe/issues/232
