### ISSUE TITLE
apple pay working on emulator not on real device

### ISSUE THREAD

**Issue by imadarif** [tipsi/tipsi-stripe#407]
shows this device is not supported

I implemented apple pay with stripe in ios using react native. So when the time of testing a program it is runs fine with simulators but not in real device. To test the apple pay with real device it doesn't show the payment sheet to process the transaction. My doubt is to test with apple pay with real device can we add test cards to wallet or have the sandbox account ? is required adding test cards to wallet when using stripe gate way? Could you please give me a clarity?

**Comment by cybergrind** [comment]
hi @imadarif 
it should work on real device with sandbox account, but apple pay isn't supported on all devices (eg. ipad mini 3 isn't supported)

https://support.apple.com/en-us/HT208531

if it isn't the case you can test either with test card + sandbox account, or you can take your real account + real card - stripe won't charge it for test payments and you can refund payments any time from dashboard
