### ISSUE TITLE
 the certificate used to sign your request is invalid. 

### ISSUE THREAD

**Issue by sudobrackets** [tipsi/tipsi-stripe#409]
## Before I have submitted the issue 
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Briefly describe the issue you are experiencing (or the feature you want to see added to `tipsi-stripe`). 
Tell us what you were trying to do and what happened instead. 

## Environment
* `tipsi-stripe` version: 
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: 
* OS version: 
* React-Native version: 
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version: 

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion
* android.buildToolsVersion
* android.defaultConfig.minSdkVersion
* android.defaultConfig.targetSdkVersion
* android.defaultConfig.multiDexEnabled (if exists)

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

## Code To Reproduce Issue (Good To Have)
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by cybergrind** [comment]
Looks like Apple Pay certificate error. Please check your certificate in both apple and stripe admins
