### ISSUE TITLE
Old expirty date

### ISSUE THREAD

**Issue by rakeshbijoriyagate6** [tipsi/tipsi-stripe#410]
When I tried to enter old expiry date for the card stripe API not returning any error or response.

It is only happening in iOS code. Android code is working file

Both console in following code not executing.

stripe.createTokenWithCard(params).then(val => {
                console.log(val);

            }).catch((error) => {
                console.log(error)
            })

**Comment by navneetgarggate6** [comment]
This issue is fixed in new version If your are using old version below 7 then 
You need to add following 2 lines for method createTokenWithCard in ios/TPSStripe/TPSStripeManager.m

promiseResolver = resolve;
promiseRejector = reject;
