### ISSUE TITLE
PaymentCardTextField returning valid when invalid CVC for american express.

### ISSUE THREAD

**Issue by VicFrolov** [tipsi/tipsi-stripe#411]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
When users add a credit card via `PaymentCardTextField`, I check if it is valid, if it is, I automatically run `createTokenWithCard`. The definition of "valid" is `Whether or not the form currently contains a valid card number, expiration date, and CVC` from the tipsi-stripe docs.

When doing this with an AMEX however, if the user gets to 3 digits in CVC, it claims it to be valid, and runs createTokenWithCard.

I can fix this on my side by checking if the card is an AMEX, if so, wait for the CVC to be 4, but I think this is something that should be accounted for.

## Environment
* `tipsi-stripe` version: "^6.1.2"
* iOS or Android: iOS
* OS version: 12
* React-Native version: ^0.57.7

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

## Code To Reproduce Issue (Good To Have)
Have some function triggered onTextChange

```
async handleFieldParamsChange(valid, params) {
    if (valid) {
        console.log("is valid with 3 CVC for AMEX card");
    }
}
```

and in render:
```
<PaymentCardTextField
  disabled={false}
  onParamsChange={this.handleFieldParamsChange}
/>
```

**Comment by nchase** [comment]
@cybergrind this is an old issue, but FYI it still happens on iOS

**Comment by cybergrind** [comment]
@nchase hey! ATM there is no active dev team behind this library so all fixes rely solely on community efforts.
Right now we don't publish any new stable releases, only merges to the `experimental` branch and release only beta releases.

If it happens on current `8.0.0-beta.11` it is probably a subject to fix, but don't expect it fixed by someone else. Because it is in this state for 2 years already
