### ISSUE TITLE
How to prevent `focusCreditCard` from being called on Android?

### ISSUE THREAD

**Issue by staydecent** [tipsi/tipsi-stripe#412]
## The problem

When the `PaymentCardTextField` component renders on Android, it takes focus and opens the keyboard right away, without the user tapping on the field.

I've tried looking through the code to find a prop/option to prevent this, but have failed. From what I can tell this is the android code that focuses the input when it renders: https://github.com/tipsi/tipsi-stripe/blob/339cea10bc7c45b341154c37d3ef4d96db6cc906/android/src/main/java/com/gettipsi/stripe/CustomCardInputReactManager.java#L66

Is there a prop/option that I have missed that would prevent this from happening? If not, I suppose I could hide the `PaymentCardTextField` component until the user taps a button or something.

## Environment
* `tipsi-stripe` version: 6.1.2
* iOS or Android: Android
* OS version: Many, is not OS version dependant
* React-Native version: 0.57.7

Thanks!

**Comment by cybergrind** [comment]
I believe there is no such option yet. So, maybe for now the best way is to show form only when you want to focus input

**Comment by dancherb** [comment]
I'm also unsatisfied with this behaviour - I originally worked around by hiding the component until the user taps an "Add payment method" button, but a client has specifically requested for the component to start off rendered (but without any weird keyboard focus) and digging around in the source code hasn't yielded any results. Please re-open. @staydecent @cybergrind

**Comment by cybergrind** [comment]
@dancherb hey. I don't think that re-opening will change anything.
We don't have any workforce to implement it right now. So, you have two options:
1) implement and use your own form and pass everything to internal stripe api

**Comment by quachsimon** [comment]
@cybergrind  is this something that is being looked into anymore?

This seems to break my UI everytime the keyboard input auto focuses the moment it is rendered on Android.

It is fine on iOS.

Have there been any discussion on this topic and how we can prevent it from auto focusing?

I am not a native Android dev by any means.

![Screenshot_1562611020](https://user-images.githubusercontent.com/20729321/60835056-3babfb00-a190-11e9-9eae-4b3561d3e7a1.png)

**Comment by cybergrind** [comment]
Hi @quachsimon , I wish I could help you with that. It seems that we need an option to disable this behavior but I cannot give any ETA for this right now

**Comment by quachsimon** [comment]
Thanks for the prompt response @cybergrind ! Will try to find a workaround for Android in the mean time...

**Comment by cybergrind** [comment]
@quachsimon workaround for that is to create your own form and use just https://tipsi.github.io/tipsi-stripe/docs/createtokenwithcard.html api instead of `paymentRequestWithCardForm`

**Comment by yurilawnguru** [comment]
Hi @cybergrind , I still having this issue. I've been trying to force dismissing the  keyboard but with not changing anything.  Do you have some tips to cheater this behavior?

**Comment by cybergrind** [comment]
Hi @yurilawnguru , probably until option added only use custom fork without this behavior
