### ISSUE TITLE
Stripe ios full management form?

### ISSUE THREAD

**Issue by nevodavid** [tipsi/tipsi-stripe#414]
Can we get to do this thing? like in stripe ios picture?
![image](https://user-images.githubusercontent.com/6898878/49649809-d9a1e080-fa5c-11e8-96b9-de5da34cc7ec.png)

**Comment by cybergrind** [comment]
@nevodavid right now you can do it only on your side. We don't provide such screen out-of-box

**Comment by nevodavid** [comment]
I have a question, you might now,
if I do the select payment method at my side, will it mess with the PCI Compliance ?
I need a special certification for that?
order as long as it only to fetch card last numbers and type it's good enough?

**Comment by cybergrind** [comment]
@nevodavid to add the card you need only token from `createTokenWithCard` and that will be enough.
So there is no fuss with PCI if you don't try to store some private info (like CC number)

**Comment by nevodavid** [comment]
I mean,
let's say the customer come back to make another purcahse, I want to show him available cards he used and can use, so I need to use the customer.cardList from the server,
will it still be ok?

**Comment by cybergrind** [comment]
Yep, there are no personal data in that case. You will have some `cus_XXXXXX` token that cannot be used without your private key.

**Comment by nevodavid** [comment]
Ok, thank you very much! :)

**Comment by cybergrind** [comment]
@nevodavid no problem :+1:
