### ISSUE TITLE
Build for Android: Execution failed for task ':app:transformClassesWithDesugarForDebug'

### ISSUE THREAD

**Issue by viper4595** [tipsi/tipsi-stripe#419]
## The problem
This error shows up every time I build for Android. Everything works fine if I don't link tipsi-stripe

## Environment
* `tipsi-stripe` version: 6.1.2
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: 
* React-Native version: 0.56.1
* (Android only) `com.google.firebase:firebase-core` version: none
* (Android only) `com.google.android.gms:play-services-base` version: 16.0.0

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion 26
* android.buildToolsVersion 27.0.3
* android.defaultConfig.minSdkVersion 19
* android.defaultConfig.targetSdkVersion 26
* android.defaultConfig.multiDexEnabled (if exists) true/false has no effect

**Comment by jessk77** [comment]
same problem :(
