### ISSUE TITLE
Google Pay: Unexpected Developer Error, please try again later

### ISSUE THREAD

**Issue by prameetc** [tipsi/tipsi-stripe#420]
## The problem
When Android Pay is used with live stripe key, I get the error `Unexpected Developer Error, please try again later`. Can someone guide me here? My `androidPayMode` is `test`.

## Environment
* `tipsi-stripe` version: 6.1.0
* Android
* OS version: Mac OS High Sierra 10.13.6
* React-Native version: 0.53.3

* (Android only) `com.google.android.gms:play-services-base` version: 11.4.2

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion 26
* android.buildToolsVersion: 26.0.2
* android.defaultConfig.minSdkVersion 19
* android.defaultConfig.targetSdkVersion: 26
* android.defaultConfig.multiDexEnabled true

**Comment by ideerge** [comment]
news?

**Comment by iyashamihsan** [comment]
check your code where you build your client and change Environment_test to Environment_Production
mPaymentsClient =
                Wallet.getPaymentsClient(this,
                        new Wallet.WalletOptions.Builder()
                                .setEnvironment(WalletConstants.ENVIRONMENT_TEST)
                                .build());

change WalletConstants.ENVIRONMENT_TEST to WalletConstants.ENVIRONMENT_PRODUCTION

**Comment by angularprojects4all** [comment]
Still getting issue?
I am using cordova, ionic, google pay together.

please post about this.

**Comment by Prakashharsa** [comment]
I am also facing the same issue, please guide me if you any  solution for this.

**Comment by simeyla** [comment]
I've seen this several times while testing on Safari - web based app. 
(so not same environment but same error)

Force quitting the tab tends to fix it. Since it's on my phone I can't easily debug it further than this.

**Comment by SarjuHansaliya** [comment]
Try this command `adb -d logcat -s WalletMerchantError` in your terminal after connecting your device. May be you will get some clue from there.

**Comment by santhanamanimaran** [comment]
> Try this command `adb -d logcat -s WalletMerchantError` in your terminal after connecting your device. May be you will get some clue from there.

You saved my day. Thanks.

**Comment by NinpoU-u** [comment]
@SarjuHansaliya please say how can I use this command. I've got just -Waiting for the device - in the terminal. And in logcat nothing appear.
Debugging with WIFI, Android 12.
