### ISSUE TITLE
Integrate with react-native-firebase-starter for Android

### ISSUE THREAD

**Issue by TheGreatAndrew** [tipsi/tipsi-stripe#421]
## Before I have submitted the issue 
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem: 
I use react-native-firebase-starter, linking -> everything work
But when I link tipsi-stripe -> error below
Failed to capture snapshot of input files for task ':tipsi-stripe:compileDebugRenderscript' property 'importDirs' during up-to-date check.
> The library com.google.firebase:firebase-iid is being requested by various other libraries at [[17.0.4,17.0.4]], but resolves to 11.8.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

## Environment
* `tipsi-stripe` version: 6.1.2
* IOS or Android
* OS version: 10.13.6
* React-Native version: 5.1.0
* (Android only) `com.google.firebase:firebase-core` version: 16.0.4
* (Android only) `com.google.android.gms:play-services-base` version: 16.0.1

## Links to logs and sources
https://gist.github.com/TheGreatAndrew/4772f7a8f8df1738d269ee33c3b3f779

For `Android`, please provide the following sections from `android/app/build.gradle`:

* compileSdkVersion = 27
* buildToolsVersion = "28.0.2"
* minSdkVersion = 18
* targetSdkVersion = 26

## Code To Reproduce Issue (Good To Have)
simply follow instruction on (for Android only):
1) https://github.com/invertase/react-native-firebase-starter
2) careful not to duplicate code on settings.gradle and MainApplication getPackages()
3) https://tipsi.github.io/tipsi-stripe/docs/linking.html manual linking

**Comment by jchirik** [comment]
Were you able to fix this?

**Comment by TheGreatAndrew** [comment]
@jchirik no, i am a novice but I try a lot of methods.
Did you have the same situation with me, where you only do the most BASIC install of these 2 libraries and you output errors?

**Comment by heyaj19** [comment]
@jchirik  and @TheGreatAndrew  I have been getting the same error only on Android. 

I was able to get it by setting fixed versions for firebaseVersion 

I started getting tipse failed at zzmbf library. Have you guys had any luck?
