### ISSUE TITLE
wechat pay support

### ISSUE THREAD

**Issue by jimmyshen007** [tipsi/tipsi-stripe#427]
Hi experts, this is just a enquiry about wechat pay support? Any plan on that? Thank you!

**Comment by cybergrind** [comment]
@jimmyshen007 we aren't using wechat pay. But the integration of new source should be quite easy so feel free to submit PR with tests =)

**Comment by lightninglu10** [comment]
Any updates on this?

**Comment by jimmyshen007** [comment]
@cybergrind I didn't see stripe IOS api has support for creating wechat pay source. Not sure if that is possible or not.

**Comment by cybergrind** [comment]
AFAIK sources don't require any specific API's, it is just source type + some additional params passed.
Anyway if you don't feel that you can do that just wait, someone will implement it eventually

**Comment by khoand0407** [comment]
any update

**Comment by scaralfred** [comment]
Hello guys. Any update on this?
