### ISSUE TITLE
input file must be a fat file when the -extract option is specified

### ISSUE THREAD

**Issue by RyushiShiohama** [tipsi/tipsi-stripe#43]
Hi,

Thank you for providing such a great library.

I've tried to setup this lib with my react-native app and I've got 'input file must be a fat file when the -extract option is specified' error. 

Initially, while setting up, I faced the error mentioned in the issue below (Stripe/Stripe.h file not found).

https://github.com/tipsi/tipsi-stripe/issues/29

Since our app still has some dependency on libraries, which doesn't support RN v0.40.0 breaking changes, our app uses RN v0.39.2. Hence, I use tipsi-strip v1.4.0 and apply the fix suggested in the issue. (add Library Search Path and Add Stripe.framework at Link Binary With Libraries)

Then, the error above stopped showing up, instead I got the error below.

fatal error: lipo: input file (xxxxxxxxxxxxxxxxxxxxxx/Build/Products/Debug-iphonesimulator/app_name.app/Frameworks/Stripe.framework/Stripe) must be a fat file when the -extract option is specified

Do you have any idea why this happens and how I can solve this?

My environments are as below:

RN v0.39.2
tipsi-strip v1.4.0
Xcode 8.2.1

My Podfile looks like this:
```
platform :ios, '8.1'
use_frameworks!

target 'app_name' do
  pod 'Crashlytics'
  pod 'Fabric'
  pod 'Stripe', '~> 9.2.0'

  inherit! :search_paths
end
```

**Comment by sergeyzhukov** [comment]
@RyushiShiohama 

There shouldn't be any problems with old versions of lib and use_frameworks, I tried to create new project, used your Podfile, added Stripe.framework and framework search paths and everything compiled without this error.

Please be sure that you cleaned up you build dir

**Comment by RyushiShiohama** [comment]
@sergeyzhukov 

Thank you for the reply. We finally found the script we use to discard unnecessary binary for WebRTC.framework somehow picked up Stripe.framework too and the error was caused. So, that was our problem... Sorry for the trouble and again thank you for your support!

Please disregard and close this issue.

**Comment by cybergrind** [comment]
@RyushiShiohama great, thank you for your time

**Comment by bartutiryakioglu** [comment]
Hey, I was trying your solution but getting this error. input file (libgrpc.a) must be a fat file when the -remove option is specified. Do you have any idea why?
