### ISSUE TITLE
Android IllegalStateException: Attempted to get instance of CustomerSession without initialization

### ISSUE THREAD

**Issue by projectpublius** [tipsi/tipsi-stripe#432]
## Before I have submitted the issue 
[X] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[X] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[X] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[X] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
App crashes on a client device running Android 7.1.1 due to "java.lang.IllegalStateException: Attempted to get instance of CustomerSession without initialization" (see screenshot).  Potentially OS related as the same issue was reported in the stripe-android repository (https://github.com/stripe/stripe-android/issues/564) for a different device running Android 7.1.1.

## Environment
* `tipsi-stripe` version: 7.2.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: 7.1.1
* React-Native version: 0.58.3
* (Android only) `com.google.firebase:firebase-core` version: 16.0.6
* (Android only) `com.google.android.gms:play-services-base` version: 16.0.1

## Screenshots, GIFs (Must to have)
![image](https://user-images.githubusercontent.com/20936762/52179049-705ff480-27a3-11e9-847d-b8cd7cd28ca1.png)

**Comment by normdoow** [comment]
I am getting this issue as well. It seems to only happen on Android 7.1.1 for me.
