### ISSUE TITLE
Expose credit card details validation

### ISSUE THREAD

**Issue by iadcg** [tipsi/tipsi-stripe#435]
Hi great stuff here. Saves us a lot of time. 
I have this situation, need some clues on how to do this.

I wish to work with createTokenWithCard only since I will be creating my own credit card entry form in RN.
What I understand is the the credit card info validation will only be done when u try to add the card in Stripe to get the token.
Then from what your library does, it has its own validation in the form by calling Utils.validateCard(Card).

I want to this kind of validation in my form too and wish to use Stripe's validation.
Wouldnt it be cool to expose this validation in Stripe.js??

**Comment by cybergrind** [comment]
Hey @iadcg!

Thought about it for a while. Got a conclusion that there are not so many gains over pure js validation libraries.
And way more difficulties in providing the same API for both platforms and complicated testing (because you have to write e2e tests to verify that everything works between JS-Native part).

**Comment by xeb10154** [comment]
Hi @iadcg, 

Apologies for reviving this old post, but what did you do for your form entry validation in the end?

Also, @cybergrind, is creating my own entry form component with <TextInput> fields for inserting card details considered PCI compliant??

Thanks in advance.

**Comment by cybergrind** [comment]
Hi @xeb10154!
PCI compliance is mostly about good practices. So if you've done everything correctly in your own form you will be PCI compliant.
Major gain when you're using Stripe SDK form - you're eligible for SAQ-A PCI compliance (= you're not having any CC data on your side and everything is handled by PCI-compliant Stripe SDK).
