### ISSUE TITLE
'compile' is obsolete for Android at the end of 2018

### ISSUE THREAD

**Issue by jpolo** [tipsi/tipsi-stripe#437]
## Before I have submitted the issue 
[X ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ X] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[X ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ X] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem

This happens when compiling android project :
```bash
> Configure project :tipsi-stripe
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
```

We are in the beginning of 2019, so this removal is imminent...

## Environment
* `tipsi-stripe` version: 7.2.0

## Links to logs and sources

* android.compileSdkVersion 28
* android.buildToolsVersion 28.0.3
* android.defaultConfig.minSdkVersion 21
* android.defaultConfig.targetSdkVersion 28
* android.defaultConfig.multiDexEnabled (if exists) --

## Code To Reproduce Issue (Good To Have)

Just launch `react-native run-android` with the provided compiler config

**Comment by sirajahmad1** [comment]
I am having same issue
