### ISSUE TITLE
Vertically stack TextField's

### ISSUE THREAD

**Issue by vTrip** [tipsi/tipsi-stripe#439]
## Before I have submitted the issue 
[x ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Are there any possibilities to style the layout on the PaymentCardTextField. Currently is displays on one line and handles overflow which is super nice.

However it would be great for the "form" to have its text fields vertically stacked. Is this a limitation of the library or can this be done?

Cheers.

## Environment
* `tipsi-stripe` version: ^7.3.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: iOS
* OS version: 12
* React-Native version: 0.57.7 
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version: 

## Links to logs and sources
n/a

## Screenshots, GIFs (Must to have)

![simulator screen shot - iphone x - 2019-02-20 at 19 09 49](https://user-images.githubusercontent.com/15204972/53076152-1a30d680-3543-11e9-98e7-b62a0f01ce99.png)

## Code To Reproduce Issue (Good To Have)
n/a

**Comment by Mavenic** [comment]
How do you manage to remove ZipCode from PaymentCardTextField ?
