### ISSUE TITLE
NoClassDefFoundError Android app not starting

### ISSUE THREAD

**Issue by andriko007** [tipsi/tipsi-stripe#442]
## The problem
Installation was done using `react-native link tipsi-stripe` and after building app didn't run

## Environment
* `tipsi-stripe` version: 7.4.0
* iOS or Android: Android
* OS version: 9

## Links to logs and sources
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.blendid, PID: 20759
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6627)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6174)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6089)
        at android.app.ActivityThread.access$1200(ActivityThread.java:212)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1806)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6912)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.blendid-Rq3OGPANW7-68fycwqu37A==/base.apk"],nativeLibraryDirectories=[/data/app/com.blendid-Rq3OGPANW7-68fycwqu37A==/lib/arm, /data/app/com.blendid-Rq3OGPANW7-68fycwqu37A==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
       
```

**Comment by cybergrind** [comment]
@andriko007 hi. could you please find what is a maximal working version of tipsi-stripe for you?

**Comment by andriko007** [comment]
@cybergrind Hi. I just need applePay, googlePay and credit cards adding

**Comment by cybergrind** [comment]
Could you please try other versions from https://github.com/tipsi/tipsi-stripe/blob/master/CHANGELOG.md and find which version is working for you?

**Comment by andriko007** [comment]
@cybergrind Ok, I'll try

**Comment by ajaykumar97** [comment]
App is crashing as soon as open in android. 
My
tipsi-stripe version: ^7.4.0
React-Native version: ^0.57.3

**Comment by andriko007** [comment]
@cybergrind I tried to run from version 6.0.0 to last version, nothing helped

**Comment by cybergrind** [comment]
@andriko007 so it doesn't look like anything that is caused by tipsi-stripe. Try to find a solution somewhere else.

**Comment by reidkersey** [comment]
I am getting the same issue. tipsi-stripe uninstalled, and everything works fine. Tried backing down to 7.2.0 and I get the following error messages:
`> Configure project :tipsi-stripe
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (28.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:checkDebugClasspath
WARNING: Conflict with dependency 'com.google.android.gms:play-services-maps' in project ':app'. Resolved versions for runtime classpath (16.0.0) and compile classpath (11.8.0) differ. This can lead to runtime crashes. To resolve this issue follow advice at https://developer.android.com/studio/build/gradle-tips#configure-project-wide-properties. Alternatively, you can try to fix the problem by adding this snippet to C:\Users\reidk\Documents\Git\AwesomeProject\android\app\build.gradle:
dependencies {
    implementation("com.google.android.gms:play-services-maps:16.0.0")
}

WARNING: Conflict with dependency 'com.google.android.gms:play-services-base' in project ':app'. Resolved versions for runtime classpath (16.0.1) and compile classpath (11.8.0) differ. This can lead to runtime crashes. To resolve this issue follow advice at https://developer.android.com/studio/build/gradle-tips#configure-project-wide-properties. Alternatively, you can try to fix the problem by adding this snippet to C:\Users\reidk\Documents\Git\AwesomeProject\android\app\build.gradle:
dependencies {
    implementation("com.google.android.gms:play-services-base:16.0.1")
}

WARNING: Conflict with dependency 'com.google.android.gms:play-services-tasks' in project ':app'. Resolved versions for runtime classpath (16.0.1) and compile classpath (11.8.0) differ. This can lead to runtime crashes. To resolve this issue follow advice at https://developer.android.com/studio/build/gradle-tips#configure-project-wide-properties. Alternatively, you can try to fix the problem by adding this snippet to C:\Users\reidk\Documents\Git\AwesomeProject\android\app\build.gradle:
dependencies {
    implementation("com.google.android.gms:play-services-tasks:16.0.1")
}

WARNING: Conflict with dependency 'com.google.android.gms:play-services-basement' in project ':app'. Resolved versions for runtime classpath (16.0.1) and compile classpath (11.8.0) differ. This can lead to runtime crashes. To resolve this issue follow advice at https://developer.android.com/studio/build/gradle-tips#configure-project-wide-properties. Alternatively, you can try to fix the problem by adding this snippet to C:\Users\reidk\Documents\Git\AwesomeProject\android\app\build.gradle:
dependencies {
    implementation("com.google.android.gms:play-services-basement:16.0.1")
}

WARNING: Conflict with dependency 'com.android.support:support-v4' in project ':app'. Resolved versions for runtime classpath (28.0.0) and compile classpath (27.1.0) differ. This can lead to runtime crashes. To resolve this issue follow advice at https://developer.android.com/studio/build/gradle-tips#configure-project-wide-properties. Alternatively, you can try to fix the problem by adding this snippet to C:\Users\reidk\Documents\Git\AwesomeProject\android\app\build.gradle:
dependencies {
    implementation("com.android.support:support-v4:28.0.0")
}

WARNING: Conflict with dependency 'com.android.support:support-media-compat' in project ':app'. Resolved versions for runtime classpath (28.0.0) and compile classpath (27.1.0) differ. This can lead to runtime crashes. To resolve this issue follow advice at https://developer.android.com/studio/build/gradle-tips#configure-project-wide-properties. Alternatively, you can try to fix the problem by adding this snippet to C:\Users\reidk\Documents\Git\AwesomeProject\android\app\build.gradle:
dependencies {
    implementation("com.android.support:support-media-compat:28.0.0")
}


> Task :app:preDebugBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-v4' has different version for the compile (27.1.0) and runtime (28.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 22s
23 actionable tasks: 4 executed, 19 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: gradlew.bat installDebug

Error: Command failed: gradlew.bat installDebug
    at checkExecSyncError (child_process.js:637:11)
    at Object.execFileSync (child_process.js:655:13)
    at runOnAllDevices (C:\Users\reidk\Documents\Git\AwesomeProject\node_modules\react-native\local-cli\runAndroid\runAndroid.js:299:19)
    at buildAndRun (C:\Users\reidk\Documents\Git\AwesomeProject\node_modules\react-native\local-cli\runAndroid\runAndroid.js:135:12)
    at isPackagerRunning.then.result (C:\Users\reidk\Documents\Git\AwesomeProject\node_modules\react-native\local-cli\runAndroid\runAndroid.js:65:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)`

Also of note, the linker doesn't seem to be working using windows, so I had to manually link.

When linking I get the error: 
`rnpm-install ERR! Something went wrong while linking. Error: spawn UNKNOWN 
Please file an issue here: https://github.com/facebook/react-native/issues

spawn UNKNOWN

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:372:11)
    at spawn (child_process.js:559:9)
    at cb (C:\Users\reidk\Documents\Git\AwesomeProject\node_modules\react-native\local-cli\core\makeCommand.js:25:28)
    at Promise (C:\Users\reidk\Documents\Git\AwesomeProject\node_modules\react-native\local-cli\link\promisify.js:12:1)
    at new Promise (<anonymous>)
    at module.exports (C:\Users\reidk\Documents\Git\AwesomeProject\node_modules\react-native\local-cli\link\promisify.js:11:1)
    at C:\Users\reidk\Documents\Git\AwesomeProject\node_modules\react-native\local-cli\link\link.js:165:9`

One more thing that *may* have something to do with it, is that I had to enable multidex when I added this package. I have `multiDexEnabled true` in my build.gradle

**Comment by reidkersey** [comment]
No luck with 6.1. Same errors as my above comment.

**Comment by mrmello** [comment]
Hi, any updates on this? I've got the same issue

**Comment by ajaykumar97** [comment]
I didn't remember how I resolved the issue but the following config is working fine for me:
```
"tipsi-stripe": "7.5.0",
"react": "16.8.3",
"react-native": "0.59.8"
```
In ``android/build.gradle``:

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
}
```
In ``android/app/build.gradle``:
```
dependencies {
  implementation project(':tipsi-stripe')
}
```
And install ``tipsi-stripe`` using ``react-native install tipsi-stripe``

**Comment by mrmello** [comment]
> I didn't remember how I resolved the issue but the following config is working fine for me:
> 
> ```
> "tipsi-stripe": "7.5.0",
> "react": "16.8.3",
> "react-native": "0.59.8"
> ```
> 
> In `android/build.gradle`:
> 
> ```
> buildscript {
>     ext {
>         buildToolsVersion = "28.0.3"
>         minSdkVersion = 16
>         compileSdkVersion = 28
>         targetSdkVersion = 28
>         supportLibVersion = "28.0.0"
>     }
> }
> ```
> 
> In `android/app/build.gradle`:
> 
> ```
> dependencies {
>   implementation project(':tipsi-stripe')
> }
> ```
> 
> And install `tipsi-stripe` using `react-native install tipsi-stripe`

Thanks!

**Comment by ajaykumar97** [comment]
@mrmello Welcome.

**Comment by ninetofour** [comment]
https://github.com/wix/react-native-navigation/issues/3950

**Comment by littletower** [comment]
This comment https://github.com/evollu/react-native-fcm/issues/998#issuecomment-404736950 fixed it for me. (used 17.0.0 instead of 12.0.1)
