### ISSUE TITLE
Tipsi-Stripe fails gradle lintRelease

### ISSUE THREAD

**Issue by jakebloom** [tipsi/tipsi-stripe#445]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Our CI environment is failing because this package fails gradle's lintRelease step.

## Environment
* `tipsi-stripe` version: 7.4.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: Pie
* React-Native version: 0.57.7
* (Android only) `com.google.firebase:firebase-core` version: 16.0.6
* (Android only) `com.google.android.gms:play-services-base` version: none

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!
https://gist.github.com/jakebloom/bec4c5de87780a71ca4f82e6980c7b86

* [android/build.gradle](https://gist.github.com/jakebloom/56a916a7ee488f00aa2c6b621ee51cc5)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion: 27
* android.buildToolsVersion: 27.1.1
* android.defaultConfig.minSdkVersion: 21
* android.defaultConfig.targetSdkVersion: 26
* android.defaultConfig.multiDexEnabled: true

## Screenshots, GIFs (Must to have)
![screen shot 2019-03-04 at 5 27 19 pm](https://user-images.githubusercontent.com/5188779/53774306-c9a26d00-3ea2-11e9-80d2-c5c7c0912a0c.png)

## Code To Reproduce Issue (Good To Have)
Link the package as instructed

**Comment by cybergrind** [comment]
Hi @jakebloom!  Probably you need to include noted libraries into your build.gradle file and set the same version for both

**Comment by jakebloom** [comment]
@cybergrind I've done a bit more digging here - the issue isn't in my build.gradle, it is a mismatch between stripe and react native:

- Tipsi-Stripe requires The stripe android SDK version 8.1.0
- The stripe android SDK 8.1.0 requires com.android.support version 27.1.0 (https://github.com/stripe/stripe-android/blob/v8.1.0/build.gradle#L44)
- React Native v0.57.7 requires com.android.support:appcompat 27.1.1 (https://github.com/facebook/react-native/blob/v0.57.7/ReactAndroid/build.gradle#L299)

Which is causing the lint here to fail

**Comment by cybergrind** [comment]
@jakebloom we don't target any particular RN (we're using 0.54 for example), so you have to choose which version are you going to use and fix it on your application. You can do this with force flag: https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:enforcing_dependency_version
