### ISSUE TITLE
ioexception during API request to stripe (https://api.stripe.com/v1/tokens) unable to resolve host no address associated with hostname

### ISSUE THREAD

**Issue by sflowerlisa22** [tipsi/tipsi-stripe#450]
## Before I have submitted the issue 
[x ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Suddenly getting error: ioexception during API request to stripe (https://api.stripe.com/v1/tokens) unable to resolve host no address associated with hostname

## Environment
* `tipsi-stripe` version: 
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: 
* OS version: 
* React-Native version: 
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version: 

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion
* android.buildToolsVersion
* android.defaultConfig.minSdkVersion
* android.defaultConfig.targetSdkVersion
* android.defaultConfig.multiDexEnabled (if exists)

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

## Code To Reproduce Issue (Good To Have)
Try to recieve token from .paymentRequestWithCardForm()

**Comment by meliodev** [comment]
I just had the same issue without changing any line of code. Does anybody have a solution for this issue ?

**Comment by JiboStore** [comment]
I encountered the same only when I am making the request through my dockerized app running in digital-ocean droplets. I have no problem if it is running via digital-ocean app platform, localhost, nor my local machine running the same docker containers.. I'm lost as what is going on, retrieving the customer data is fine
