### ISSUE TITLE
Bitmoji keyboard

### ISSUE THREAD

**Issue by guyguy333** [tipsi/tipsi-stripe#454]
## The problem
If you have Bitmoji keyboard installed on your iOS system, the keyboard generates weird issues when you type Card numbers. The keyboard switch to Bitmoji and I'm unable to type numbers. I attached a GIF. The issue happens with an iPhone X but I'm not able to reproduce it on an iPhone 7.

## Environment
* `tipsi-stripe` version: 7.4.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: iOS
* OS version: 12
* React-Native version: 0.58.4

## Links to logs and sources
PodFile:
```
  pod 'Stripe', '~> 14.0.0'
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'
```

## GIF 
![ezgif-2-623efaa1b544](https://user-images.githubusercontent.com/4040959/54598623-312af180-4a39-11e9-922e-d6ad6093e16c.gif)

## Code To Reproduce Issue

```javascript
onAddPaymentCardPress = async () => {
    try {
      const token = await stripe.paymentRequestWithCardForm({
        prefilledInformation: {
          billingAddress: {
            name: "Test",
            country: "FR",
            postalCode: "12345",
            email: "email",
          },
        },
      })
      // Things with token.tokenId
      }).catch((error) => {
        // Error catch
      })
    } catch (error) {
      // Error catch
    }
  }
```

Edit:

- Tested on an iPhone Xr, reproduced
- Native Stripe iOS example test -> no issue with the Bitmoji keyboard

**Comment by pkostrzewski** [comment]
There is still not fixed issue.... If you have installed custom keyboard on your device the options numeric, number-pad, and decimal-pad on keyboardType in TextInput is triggering this custom keyboard.

Only one solutian that i find is to use on TextInput
keyboardType="phone-pad"
