### ISSUE TITLE
Unrecognized app. Please make sure you trust this app before proceeding

### ISSUE THREAD

**Issue by thodwris** [tipsi/tipsi-stripe#455]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I'm developing an application with react native and I am using this library in order to use Google Pay with stripe integration. I already linked the test key from stripe and the merchant Id from play store. I have a serious issue though. After running the app, when the Google Pay popup form opens, i get the Google Pay dialog but with a message "Unrecognized app. Please make sure you trust this app before proceeding". However when I enter a test card and press continue I get an additional error that says Transaction declined: invalid payment method. [OR-CCSEH-05] I would appreciate any help.

## Environment
* `tipsi-stripe` version: 7.4.0
* iOS or Android: Android
* React-Native version: 0.57.8

## Screenshots, GIFs (Must to have)
<img width="399" alt="Screenshot 2019-03-22 at 11 32 42" src="https://user-images.githubusercontent.com/297024/55173145-765acc00-517b-11e9-8cb2-bff9954a3e26.png">
<img width="445" alt="Screenshot 2019-03-18 at 17 35 04" src="https://user-images.githubusercontent.com/297024/55173531-2597a300-517c-11e9-9cda-c78fb1e14432.png">

**Comment by ClovisLeb** [comment]
@thodwris 
Hi, I have a similar problem. Did you resolve it? For me, the same "unrecognized app"  message is displayed and my message error is "Request Failed, Unexpected developer error, please try again". 

Note: I didn't have this error a couple days ago. I installed react-native-firebase, react-native-maps and react-native-onesignal native packages since. Could those packages interfere with tipsi-stripe in the build tools?

-React-native 0.58.6
-Tipsi-stripe 7.4.0

Thank you.

**Comment by thodwris** [comment]
Hi @ClovisLeb 

I just contacted google and they resolved the error you see on the popup meaning now that I don't get in on google pay.

Thank you

**Comment by ClovisLeb** [comment]
Hi,

Thank you for your reply.

If anyone encounter this kind of developer error, make sure you instantiate stripe with the test key and not the production one while making sure "androidPayMode" property is set to "test".

**Comment by cybergrind** [comment]
@ClovisLeb we would really appreciate if you can put a section into documentation about it and send a PR
https://github.com/tipsi/tipsi-stripe/blob/master/website/docs-md/google-pay.md
