### ISSUE TITLE
Apple Pay - paymentRequestWithNativePay final items label character limit?

### ISSUE THREAD

**Issue by quachdev** [tipsi/tipsi-stripe#457]
When setting up the last item of the items options found here: https://tipsi.github.io/tipsi-stripe/docs/paymentrequestwithapplepayitemsoptions.html my company name is cut off for Apple Pay. 

Is this limitation due to Apple Pay or is this something set in the lib (and if so, can it be changed?)

eg. `MyService Company Technologies Inc.` gets reduced to `MyService Company`.

Edit: Could this be why? From Apple [Docs](https://developer.apple.com/documentation/apple_pay_on_the_web/apple_pay_js_api/requesting_an_apple_pay_payment_session):

`displayName: A string of 64 or fewer UTF-8 characters containing the canonical name for your store, suitable for display.  Do not localize the name.`

It doesn't explain why my eg. above gets cut off though because it is way below 64 characters. This is assuming that the displayName is the same as that final item option.

Edit 2: I think this is more relevant to what I'm asking which is the [ApplePayLineItem](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaylineitem).

And the one I'm referring to is the [total](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypaymentrequest/1916119-total).

From here I don't see any mention of any limits to the label string. What could be cutting off the text?

**Comment by cybergrind** [comment]
hi @quachdev 
We don't use any custom forms for Apple so it all comes from sdk/system level.

**Comment by quachdev** [comment]
@cybergrind , thanks for the reply.

Is it safe to assume that the `displayName` mentioned in the docs is the same as the last item in the items options array from the docs or is it completely different?

**Comment by quachdev** [comment]
@cybergrind , thanks. I went through the docs and the PKPaymentSummaryItem is just a class that takes in a String as the label and there does not seem to be any mentions of limiting the label.

Is there anyway to test why the company name may be cutting off? I've been stumped on this problem for a while 😅
