### ISSUE TITLE
Possible to custom paymentRequestWithCardForm() ?

### ISSUE THREAD

**Issue by askemeline** [tipsi/tipsi-stripe#463]
Hello, firstable I would say thank you for this project it's very cool!
I need to custom more the form and I would like to know if it's possible to custom it ?
Thanks and have a good day

**Comment by cybergrind** [comment]
Hi @askemeline! This library is mostly a wrapper around stripe ios and android SDKs. So it is possible to write your own forms and just create a payment with https://tipsi.github.io/tipsi-stripe/docs/createtokenwithcard.html or https://tipsi.github.io/tipsi-stripe/docs/createsourcewithparamsparams.html

**Comment by askemeline** [comment]
Hi @cybergrind  ok, thanks so much for your answer :)
