### ISSUE TITLE
Featuring tipsi-stripe in Docusaurus

### ISSUE THREAD

**Issue by Hongarc** [tipsi/tipsi-stripe#475]
Hello, we would like to feature your project to the Docusaurus users page.

Are you with me on this?

More info about this [here](https://github.com/facebook/Docusaurus/issues/1080)

**Comment by Hongarc** [comment]
Can you reply me?

**Comment by cybergrind** [comment]
Hi, @Hongarc I'm not sure what I have to do there.

**Comment by Hongarc** [comment]
I created facebook/Docusaurus#1423.
I need you accept featuring your project on Docusaurus

**Comment by 488taimoor** [comment]
Is there some one solved this issue in windows for android?

**Comment by cybergrind** [comment]
@Hongarc done, feel free to reopen it

**Comment by cybergrind** [comment]
@Hongarc thank you for your efforts!
