### ISSUE TITLE
noAmount error - does not support Apple Pay developer guidelines

### ISSUE THREAD

**Issue by ptrang** [tipsi/tipsi-stripe#479]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
If the last item in 'items' array has amount '0' then I receive noAmount error.
https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/payment-types/
**Apple's guidelines says it should be allowed to have a payment total of '0.00' for recurring billing.**

## Environment
* `tipsi-stripe` version: 7.5.0
* iOS or Android: iOS
* OS version: 12.2
* React-Native version: 0.57.8

## Links to logs and sources
do not need logs.  easily reproducible.  code below to mimic developer guidelines.

## Screenshots, GIFs (Must to have)
cannot reproduce below picture from apple developer guidelines.
![](https://developer.apple.com/design/human-interface-guidelines/apple-pay/images/ApplePaySheet_ZeroPayment.png)

## Code To Reproduce Issue (Good To Have)
```
let monthly_price = '9.99'
let items = [
                      {
                        label: 'Monthly Service',
                        amount: '9.99'
                      },
                      {
                        label:
                          'First Month Free',
                        amount: '-9.99'
                      },
                      {
                        label: 'Company Name, Inc.',
                        amount: '0.00'
                      }
                    ];
let options = {};
stripe.paymentRequestWithNativePay(options, items)
```

**Comment by fbartho** [comment]
![image](https://user-images.githubusercontent.com/209712/61756387-858c0800-ad70-11e9-83ac-f0153a052a3b.png)
The documentation seems ambiguous -- I'm not sure it supports zero values. Screenshot Source: https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypaymentrequest/1916119-total

Looking at the source code, the error is thrown here: https://github.com/tipsi/tipsi-stripe/blob/7ae12e4f8ef86e65bde032c5ffd32f5ee80c7e86/ios/TPSStripe/TPSStripeManager.m#L533-L537

So if you want to implement this, you should start there, and then add screenshots proving a zero-value is safe!
