### ISSUE TITLE
Library issue after upgrading to 0.59.2: Error: Unable to resolve module `react-native/Libraries/StyleSheet/StyleSheetPropType

### ISSUE THREAD

**Issue by jojonarte** [tipsi/tipsi-stripe#480]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
After upgrading react-native from 0.55.4 to 0.59.2 I could no longer be able to run the app.

## Environment
* `tipsi-stripe` version: ^5.5.0
* iOS or Android: iOS
* OS version: 
* React-Native version: 0.59.2

## Links to logs and sources
https://gist.github.com/jojonarte/40c0d959812630372c2d88565a65f802

*https://gist.github.com/jojonarte/39b761c6857c6df35c4b5231b48e1124

## Screenshots, GIFs (Must to have)
![Simulator Screen Shot - iPhone 6 - 2019-05-31 at 12 12 17](https://user-images.githubusercontent.com/11880365/58681075-60e16880-839d-11e9-9a01-cf81185ec048.png)

**Comment by alexander126** [comment]
You are probably using older version of the lib. This problem is caused by the exclusion of StyleSheetPropType after react-native 0.58. Update tipsi-stripe to a version 7.2.0 (or higher) in order to fix it. 
Ref: https://github.com/tipsi/tipsi-stripe/issues/430

**Comment by jojonarte** [comment]
Yes, I upgraded and it's working now, sorry I didn't feedback quick.

**Comment by NarendraSingh88** [comment]
> .2.0

After doing that, I got a new error - 

**TypeError: null is not an object (evaluating 'StripeModule.init')**

![Screenshot_20190731-163532](https://user-images.githubusercontent.com/39184801/62207334-80067180-b3b1-11e9-88bb-cdbc1ddbf28d.png)

**Comment by kaloncheung124** [comment]
Did you resolve this?
