### ISSUE TITLE
3D Secure 2 Declined

### ISSUE THREAD

**Issue by lukebrandonfarrell** [tipsi/tipsi-stripe#481]
## The problem

This library supports 3D secure.

![Simulator Screen Shot - iPhone 8 - 2019-06-07 at 15 11 26](https://user-images.githubusercontent.com/18139277/59107419-e4b8c900-8938-11e9-9ec3-24014dda688a.png)

What about 3D Secure 2? When using a 3D secure SCA test card `4000 0000 0000 3220` in our app with tipsi-stripe we get this error:

![Simulator Screen Shot - iPhone 8 - 2019-06-07 at 15 21 04](https://user-images.githubusercontent.com/18139277/59107748-9526cd00-8939-11e9-8df0-bfa838f7162f.png)

## Environment
* `tipsi-stripe` version: 7.4.0
* iOS or Android: Both
* React-Native version: 0.57.4

**Comment by cybergrind** [comment]
hi @lukebrandonfarrell It will work only after #448

**Comment by lukebrandonfarrell** [comment]
@cybergrind Thanks for the response, I'm going to try and integrate natively, and will pull request if no one else does closer to the time... just got to get my head around how they work.

**Comment by cloudy-ninja** [comment]
Hi,

**Comment by cloudy-ninja** [comment]
I am trying to integrate tipsi-stripe and 3D secure.
I am going to use stripe.confirmCardPayment in tipsi- stripe.
but got error.

**Comment by devadi1996** [comment]
@lukebrandonfarrell did you find any solution for that?

**Comment by lukebrandonfarrell** [comment]
@devadi1996 Nope, we are building our own in-house version of Stripe 3D secure, it will be used alongside react-native-navigation and the external component API. Keep an eye on: https://github.com/aspect-apps/react-native-navigation-stripe-3d-secure. We will probs open-source in next 2 - 3 months.

**Comment by akhilsanker** [comment]
Hi @lukebrandonfarrell 
Have you solved the problem?

Thanks

**Comment by lukebrandonfarrell** [comment]
@akhilsanker we wrote our own library https://github.com/aspect-apps/react-native-stripe-payments
