### ISSUE TITLE
this device does not support apple pay?

### ISSUE THREAD

**Issue by caoyang819** [tipsi/tipsi-stripe#483]
I have successfully installed the simulator and it can run, but the real machine tells me that the current device does not support it. I'm in China. I need help.

**Comment by caoyang819** [comment]
It can be displayed if apple has viva

**Comment by LaVielle** [comment]
What real machine are you trying to use Apple Pay with? Some iPhones don't support it (iPhone 5S and under). See https://support.apple.com/en-us/HT208531

**Comment by Haseeb005** [comment]
I am also having the same issue in my real device,, i have iPhone 6, and it's compatible also. Can any body help me??

**Comment by RWOverdijk** [comment]
Same. And my device definitely supports apple pay as I use it often. I'm on 8.0.0-beta.10

**Comment by vinpro24** [comment]
Same. Any idea? Can help me

**Comment by hcw12889** [comment]
Check if you forgot to add "Apple Pay" capability to the app in Xcode ("Signing and Capabilities" section).
