### ISSUE TITLE
build fails with an exception for task ':app:transformClassesWithDexBuilderForDebug' after installing tipsi-stripe

### ISSUE THREAD

**Issue by Ania-chan** [tipsi/tipsi-stripe#485]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I'm building an Android app in react-native and I need to add a payment page with Stripe. After I run `yarn add tipsi-stripe` and `react-native link tipsi-stripe` builds are failing with an exception for task ':app:transformClassesWithDexBuilderForDebug'.

## Environment
* `tipsi-stripe` version: 7.5.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: Android 9.0
* React-Native version: 0.59.9
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version: 

## Links to logs and sources
* [android/build.gradle](https://gist.github.com/Ania-chan/5523c8bd901428f634d257abe25f1d24)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion = 28
* android.buildToolsVersion = 28.0.3
* android.defaultConfig.minSdkVersion = 16
* android.defaultConfig.targetSdkVersion = 28
* android.defaultConfig.multiDexEnabled (if exists)

## Code To Reproduce Issue (Good To Have)
https://github.com/proud-stories/proud-stories

**Comment by Ania-chan** [comment]
Sorry for creating this issue. I could fix this problem by adding these lines to android/app/build.gradle:
```
    implementation 'com.android.support:design:27.1.0'
    compile 'com.android.support:multidex:1.0.3'
    compile (project(':tipsi-stripe')) {
        exclude group: 'com.google.android.gms'
        exclude group: 'com.google.firebase'
        }
}
``` 
and also adding `multiDexEnabled true` to defaultConfig

**Comment by benevbright** [comment]
God, you saved me. thanks very much.
Out of curiosity,
How could you come up with this solution?

**Comment by Ania-chan** [comment]
I'm glad to hear it :) It cost me whole day of frustration.
I found the solution in one of the past GitHub issues but right now I can't remember exactly where.
