### ISSUE TITLE
npm i in the example folder fails with an integrity check violation

### ISSUE THREAD

**Issue by mindlapse** [tipsi/tipsi-stripe#486]
## Before I have submitted the issue 
[ x ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ x ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ x ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ x ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Attempted to `npm i` in the `examples` folder.  It failed with an integrity check issue (see below) on the local `../tipsi-stripe-latest.tgz` file.

## Environment
* `tipsi-stripe` version: 7.5.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: n/a
* OS version: n/a
* React-Native version: n/a
* (Android only) `com.google.firebase:firebase-core` version: n/a
* (Android only) `com.google.android.gms:play-services-base` version: n/a

## Links to logs and sources
```
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting tipsi-stripe@file:../tipsi-stripe-latest.tgz:
npm ERR! Verification failed while extracting tipsi-stripe@file:../tipsi-stripe-latest.tgz:
npm ERR! Integrity check failed:
npm ERR!   Wanted: sha512-PiLootnsX5GXayRTRq+S2T4vYqr0xuF/Rc5jtX/6Bg7j8P0bkwD9jereTUbQwY5MNDUdZyz4oR7845RBVG/KjA==
npm ERR!    Found: sha512-fbSDKHv5TPzuZIODsqP6XF/oIvSqWQNtBkEPOIxlmEfUda401hJXsx+JGb1apTvbm0LKKshEaN1otwR0JX3fgw==
```

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion n/a
* android.buildToolsVersion n/a
* android.defaultConfig.minSdkVersion n/a
* android.defaultConfig.targetSdkVersion n/a
* android.defaultConfig.multiDexEnabled (if exists) n/a

## Screenshots, GIFs (Must to have)
![image](https://user-images.githubusercontent.com/405560/59632597-92399280-9118-11e9-960c-a92a39249648.png)

## Code To Reproduce Issue (Good To Have)
 n/a

**Comment by jSkrills** [comment]
@mindlapse I just experienced this issue and I just attempted a clone for the first time.

**Comment by ryanvanderpol** [comment]
@jSkrills same, can't get the example project to run. did you ever figure this out?

**Comment by verakutsenko** [comment]
@ryanvanderpol - re-clone and remove package-lock.json from example directory and then you can npm install

**Comment by zhangciwu** [comment]
Maybe to remove `example/package-lock.json` and add it to gitignore

**Comment by jSkrills** [comment]
@ryanvanderpol, I did not, I just had to move on
