### ISSUE TITLE
ios build Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by heiheiLqq** [tipsi/tipsi-stripe#494]
react-native  0.51
tipsi-stripe:7.4.0
Prodflie:14.0.0

Undefined symbols for architecture x86_64:
  "_kFIRLoggerSwizzler", referenced from:
      ___63+[FIRSwizzler swizzleClass:selector:isClassSelector:withBlock:]_block_invoke in FirebaseMethodSwizzler(FIRSwizzler_ab9d688a1f3f1b9f621e5ddefa409049.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by fbartho** [comment]
That bug looks like a problem with Firebase, and not with this library. I don't have this issue at this time!
