### ISSUE TITLE
react-native 0.60 Remove "rnpm" config

### ISSUE THREAD

**Issue by bramski** [tipsi/tipsi-stripe#495]
## Before I have submitted the issue 
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Upgraded our app to react-native 0.60
Run `npm start`

## Environment
* `tipsi-stripe` version: 0.7.5
* iOS or Android: All
* OS version: All
* React-Native version: 0.60

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

![Screen Shot 2019-07-04 at 8 51 10 AM](https://user-images.githubusercontent.com/421781/60678312-f5296a00-9e38-11e9-83c3-121f8f920171.png)

**Comment by funnyjerry** [comment]
![image](https://user-images.githubusercontent.com/40970351/61508387-2cdd0800-aa1c-11e9-9fe6-54546a4e841a.png)

**Comment by ThomasGHenry** [comment]
Same. Any news?

**Comment by JB-CHAUVIN** [comment]
Anything new ?

**Comment by jdavidteki** [comment]
same, any update?

**Comment by joaopaulorefatti** [comment]
same problem.

**Comment by mgarabedian** [comment]
Any update on this?

**Comment by umarali** [comment]
Hello? Any update on this?

**Comment by Yhnlvy** [comment]
Same. Any news?

**Comment by Dhanraj-bidchat** [comment]
any update on this?

**Comment by jan-happy** [comment]
+1

**Comment by Gustash** [comment]
+1

**Comment by dcx86** [comment]
any update on this?
