### ISSUE TITLE
Working with ejected Expo Web app?

### ISSUE THREAD

**Issue by JeanHules** [tipsi/tipsi-stripe#498]
Have you worked with the new Expo Web? I am trying to make this work on an ejected ios/android/web app and keep running into the following error:

![Screen Shot 2019-07-08 at 11 30 53 AM](https://user-images.githubusercontent.com/1322530/60832434-7d817500-a181-11e9-8a23-dacbbacce48e.png)

**Comment by haveamission** [comment]
@JeanHules Did you ever figure this out? Still not working apparently.

**Comment by JeanHules** [comment]
@haveamission I don't recall the work around (I think I tried every possible one), but looking at the project code, I believe I utilized the *.ios.js and *.android.js extensions to bypass the device specific errors, but the bigger issue you need to consider is Apple approving an app that uses Stripe. Be sure to read the rules of submitting an app before you go through with any iOS payment stuff. Apple obviously wants in app purchases which take like 15%, but there are some exceptions. Good luck.

**Comment by haveamission** [comment]
@JeanHules Yeah, I think I am going to go with another library I found that abstracts everything, and uses native in app purchasing on both Google and Apple, as well as Stripe for web.

**Comment by kopax** [comment]
Hi @haveamission , I want to integrate stripe for web, ios and native all at once.

I rather not want to eject, I believe I just need an http client and I have fetch, what are my best options to succeed not in too long according to your experience?

**Comment by thieu75** [comment]
@haveamission @kopax 
I'm stuck with the same problem with an ejected Expo project and web.
Did you resolve this?
Thanks

**Comment by kopax** [comment]
I solved it without ejecting. For iOS and Native, I used a webview, reusing the same UI for react, and passing url params. That was by far the easiest way and I didn't need tipsi-stripe.

**Comment by kopax** [comment]
@cybergrind may I know why this was tagged as [`wont-fix`](https://github.com/tipsi/tipsi-stripe/labels/wont-fix)?

Was this implemented yet properly for expo application already?
