### ISSUE TITLE
android build FAILURE:

### ISSUE THREAD

**Issue by Infokora** [tipsi/tipsi-stripe#506]
## Before I have submitted the issue 
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
> Task :tipsi-stripe:compileDebugJavaWithJavac FAILED
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/RedirectUriReceiver.java:5: error: packa
ge android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:3: error: package a
ndroid.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:5: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/Errors.java:3: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/PayFlow.java:5: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/StripeModule.java:7: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/StripeModule.java:8: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/dialog/AddCardDialogFragment.java:8: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/OpenBrowserActivity.java:7: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/RedirectUriReceiver.java:14: error: cannot find symbol
  protected void onCreate(@Nullable Bundle savedInstanceState) {
                           ^
  symbol:   class Nullable
  location: class RedirectUriReceiver
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:209: error: cannot find symbol
  public static WritableMap convertSourceToWritableMap(@Nullable Source source) {
                                                        ^
  symbol:   class Nullable
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:208: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:237: error: cannot find symbol
  public static WritableMap stringMapToWritableMap(@Nullable Map<String, String> map) {
                                                    ^
  symbol:   class Nullable
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:236: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:252: error: cannot find symbol
  public static WritableMap convertOwnerToWritableMap(@Nullable final SourceOwner owner) {
                                                       ^
  symbol:   class Nullable
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:251: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:272: error: cannot find symbol
  public static WritableMap convertAddressToWritableMap(@Nullable final Address address) {
                                                         ^
  symbol:   class Nullable
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:271: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:290: error: cannot find symbol
  public static WritableMap convertReceiverToWritableMap(@Nullable final SourceReceiver receiver) {
                                                          ^
  symbol:   class Nullable
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:289: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:306: error: cannot find symbol
  public static WritableMap convertRedirectToWritableMap(@Nullable SourceRedirect redirect) {
                                                          ^
  symbol:   class Nullable
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:305: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:321: error: cannot find symbol
  public static WritableMap convertCodeVerificationToWritableMap(@Nullable SourceCodeVerification codeVerification) {
                                                                  ^
  symbol:   class Nullable
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:320: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:335: error: cannot find symbol
  public static WritableMap mapToWritableMap(@Nullable Map<String, Object> map){
                                              ^
  symbol:   class Nullable
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:334: error: cannot find symbol
  @NonNull
   ^
  symbol:   class NonNull
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:349: error: cannot find symbol
  public static void pushRightTypeToMap(@NonNull WritableMap map, @NonNull String key, @NonNull Object object) {
                                         ^
  symbol:   class NonNull
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:349: error: cannot find symbol
  public static void pushRightTypeToMap(@NonNull WritableMap map, @NonNull String key, @NonNull Object object) {
                                                                   ^
  symbol:   class NonNull
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:349: error: cannot find symbol
  public static void pushRightTypeToMap(@NonNull WritableMap map, @NonNull String key, @NonNull Object object) {
                                                                                        ^
  symbol:   class NonNull
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:406: error: cannot find symbol
  public static String getStringOrNull(@NonNull ReadableMap map, @NonNull String key) {
                                        ^
  symbol:   class NonNull
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:406: error: cannot find symbol
  public static String getStringOrNull(@NonNull ReadableMap map, @NonNull String key) {
                                                                  ^
  symbol:   class NonNull
  location: class Converters
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:57: error: cannot find symbol
  public GoogleApiPayFlowImpl(@NonNull Fun0<Activity> activityProvider) {
                               ^
  symbol:   class NonNull
  location: class GoogleApiPayFlowImpl
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:61: error: cannot find symbol
  private PaymentsClient createPaymentsClient(@NonNull Activity activity) {
                                               ^
  symbol:   class NonNull
  location: class GoogleApiPayFlowImpl
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:67: error: cannot find symbol
  private void isReadyToPay(@NonNull Activity activity, boolean isExistingPaymentMethodRequired, @NonNull final Promise promise) {
                             ^
  symbol:   class NonNull
  location: class GoogleApiPayFlowImpl
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:67: error: cannot find symbol
  private void isReadyToPay(@NonNull Activity activity, boolean isExistingPaymentMethodRequired, @NonNull final Promise promise) {
                                                                                                  ^
  symbol:   class NonNull
  location: class GoogleApiPayFlowImpl
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:121: error: cannot find symbol
  private PaymentDataRequest createPaymentDataRequest(@NonNull final String totalPrice,
                                                       ^
  symbol:   class NonNull
  location: class GoogleApiPayFlowImpl
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:122: error: cannot find symbol
                                                      @NonNull final String currencyCode,
                                                       ^
  symbol:   class NonNull
  location: class GoogleApiPayFlowImpl
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:127: error: cannot find symbol
                                                      @NonNull final Collection<String> countryCodes
                                                       ^
  symbol:   class NonNull
  location: class GoogleApiPayFlowImpl
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:169: error: cannot find symbol
  private void startPaymentRequest(@NonNull Activity activity, @NonNull PaymentDataRequest request) {
                                    ^
  symbol:   class NonNull
  location: class GoogleApiPayFlowImpl
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:169: error: cannot find symbol
  private void startPaymentRequest(@NonNull Activity activity, @NonNull PaymentDataRequest request) {
                                                                ^
  symbol:   class NonNull
  location: class GoogleApiPayFlowImpl
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:182: error: cannot find symbol
  public void paymentRequestWithAndroidPay(@NonNull ReadableMap payParams, @NonNull Promise promise) {
                                            ^
  symbol:   class NonNull
  location: class GoogleApiPayFlowImpl
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:182: error: cannot find symbol
  public void paymentRequestWithAndroidPay(@NonNull ReadableMap payParams, @NonNull Promise promise) {
                                                                            ^
  symbol:   class NonNull
  location: class GoogleApiPayFlowImpl
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:200: error: cannot find symbol
  public void deviceSupportsAndroidPay(boolean isExistingPaymentMethodRequired, @NonNull Promise promise) {
                                                                                 ^
  symbol:   class NonNull
  location: class GoogleApiPayFlowImpl
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/Errors.java:30: error: cannot find symbol
  static String toErrorCode(@NonNull Exception exception) {
                             ^
  symbol:   class NonNull
  location: class Errors
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/Errors.java:39: error: cannot find symbol
  static String getErrorCode(@NonNull ReadableMap errorCodes, @NonNull String errorKey) {
                              ^
  symbol:   class NonNull
  location: class Errors
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/Errors.java:39: error: cannot find symbol
  static String getErrorCode(@NonNull ReadableMap errorCodes, @NonNull String errorKey) {
                                                               ^
  symbol:   class NonNull
  location: class Errors
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/Errors.java:43: error: cannot find symbol
  static String getDescription(@NonNull ReadableMap errorCodes, @NonNull String errorKey) {
                                ^
  symbol:   class NonNull
  location: class Errors
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/Errors.java:43: error: cannot find symbol
  static String getDescription(@NonNull ReadableMap errorCodes, @NonNull String errorKey) {
                                                                 ^
  symbol:   class NonNull
  location: class Errors
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/PayFlow.java:18: error: cannot find symbol
  protected final @NonNull Fun0<Activity> activityProvider;
                   ^
  symbol:   class NonNull
  location: class PayFlow
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/PayFlow.java:23: error: cannot find symbol
  public PayFlow(@NonNull Fun0<Activity> activityProvider) {
                  ^
  symbol:   class NonNull
  location: class PayFlow
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/PayFlow.java:59: error: cannot find symbol
  public void setPublishableKey(@NonNull String publishableKey) {
                                 ^
  symbol:   class NonNull
  location: class PayFlow
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/PayFlow.java:87: error: cannot find symbol
  public static boolean isPlayServicesAvailable(@NonNull Activity activity) {
                                                 ^
  symbol:   class NonNull
  location: class PayFlow
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/StripeModule.java:55: error: cannot find symbol
  @Nullable
   ^
  symbol:   class Nullable
  location: class StripeModule
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/StripeModule.java:58: error: cannot find symbol
  @Nullable
   ^
  symbol:   class Nullable
  location: class StripeModule
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/StripeModule.java:93: error: cannot find symbol
  public void init(@NonNull ReadableMap options, @NonNull ReadableMap errorCodes) {
                    ^
  symbol:   class NonNull
  location: class StripeModule
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/StripeModule.java:93: error: cannot find symbol
  public void init(@NonNull ReadableMap options, @NonNull ReadableMap errorCodes) {
                                                  ^
  symbol:   class NonNull
  location: class StripeModule
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/StripeModule.java:131: error: cannot find symbol
  private static int androidPayModeToEnvironment(@NonNull String androidPayMode) {
                                                  ^
  symbol:   class NonNull
  location: class StripeModule
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/StripeModule.java:315: error: cannot find symbol
  void processRedirect(@Nullable Uri redirectData) {
                        ^
  symbol:   class Nullable
  location: class StripeModule
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/OpenBrowserActivity.java:19: error: cannot find symbol
  protected void onCreate(@Nullable Bundle savedInstanceState) {
                           ^
  symbol:   class Nullable
  location: class OpenBrowserActivity
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/dialog/AddCardDialogFragment.java:123: error: cannot find symbol
    doneButton.setTextColor(ContextCompat.getColor(getActivity(), R.color.colorAccent));
                            ^
  symbol:   variable ContextCompat
  location: class AddCardDialogFragment
/Users/user/Projekts/dryft/mobile/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/dialog/AddCardDialogFragment.java:124: error: cannot find symbol
    dialog.getButton(AlertDialog.BUTTON_NEGATIVE).setTextColor(ContextCompat.getColor(getActivity(), R.color.colorAccent));
                                                               ^
  symbol:   variable ContextCompat
  location: class AddCardDialogFragment
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
62 errors

## Environment
* `tipsi-stripe` version: 
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: 
* OS version: 
* React-Native version: 
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version: 

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion
* android.buildToolsVersion
* android.defaultConfig.minSdkVersion
* android.defaultConfig.targetSdkVersion
* android.defaultConfig.multiDexEnabled (if exists)

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

## Code To Reproduce Issue (Good To Have)
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by steubs** [comment]
Might be an issue related to AndroidX, I've had very similar looking errors with other packages. I'd look into that if you haven't yet. 

Has Tipsi released anything about androidx support yet?

**Comment by cybergrind** [comment]
hey @steubs . No, we haven't. Probably we will after we get working CI solution

**Comment by aGORyan** [comment]
With the 8/1/2019 Google Play Store requirement to support x64, requiring RN 0.59.1+, right around RN 0.6 which includes Androidx support, releasing a tipsi-stripe update with Androidx support is pretty important.

**Comment by mikeKane** [comment]
Agreed. Is there any workaround at the moment to get tipsi stripe building with android x?

I thought jetifier would fix these issue but it does not.

Should we just fork the repo and run the migration tool? 

Right now it’s a blocker on my project and I would love to get this fixed up. 

If there’s anything I can do please let me know. Also why is this a closed issue?

**Comment by mleung** [comment]
Any movement on this? I'm still unable to build for RN 0.6 with package android.support.annotation does not exist

Thanks.

**Comment by tmaly1980** [comment]
This is a pretty serious issue! I've had to upgrade to RN 0.60 due to Apple deprecating UIWebView and warning messages about older implementations, and tipsi-stripe not supporting AndroidX (which has been out a while) is a problem. Why wait for some CI implementation, @cybergrind ?

**Comment by tmaly1980** [comment]
https://github.com/tmaly1980/tipsi-stripe

Migrating it to AndroidX isn't that hard, mostly search-replace. But I'm not 100% sure how to submit a pull request for this.

**Comment by cybergrind** [comment]
@tmaly1980 will be done only after SCA merge which was intended to be released 1st Sept but still isn't fully finished.

**Comment by zeallat** [comment]
@Infokora Why this issue was closed?

**Comment by YJoris** [comment]
Same issue, @Infokora why is it closed ?

**Comment by Sehur** [comment]
I just had the same issue

**Comment by SCasarotto** [comment]
I am also having this issue. Any update?

**Comment by osikes** [comment]
This is issue for me too. Is forking only option to support modern react native on android?

**Comment by hadare1** [comment]
any updates on this?

**Comment by danlupascu** [comment]
Hey, I'm having the same issue ... why is this closed?

**Comment by osikes** [comment]
So @danlupascu I think what's confusing is the master branch does not have support for android x... but the latest release in npm of tipsi-stripe 7.5.1, does have support. I was ultimately able to get tipis-stripe 7.5.1 to work on android x with Hermes enabled, on react native 0.61.

**Comment by janoist1** [comment]
+1

**Comment by janoist1** [comment]
> https://github.com/tmaly1980/tipsi-stripe
> 
> Migrating it to AndroidX isn't that hard, mostly search-replace. But I'm not 100% sure how to submit a pull request for this.

Does not work for me.

**Comment by Baskerville42** [comment]
For me works running `jetify`
```
"jetifier": "^1.6.5",
"react-native": "0.60.6",
"tipsi-stripe": "^7.5.1"
```

**Comment by janoist1** [comment]
I gave up, got rid of this unreliable library.

**Comment by yemi** [comment]
@janoist1 Did you try the beta version? I recently just found out about it, and since its not visible on github I might not have been the only one missing it:  https://www.npmjs.com/package/tipsi-stripe/v/8.0.0-beta.9

**Comment by ElliDy** [comment]
You can simply use `npx jetify` after npm install. It will replace all imports, which now uses androidx.

**Comment by axelinternet** [comment]
@janoist1 Found any suitable alternative?

**Comment by surhidamatya** [comment]
Facing the same issue whhile trying to build apk via circleci

 `Task :tipsi-stripe:compileDebugJavaWithJavac FAILED`
this line
`npx jetify`
just fixes the issue while running in local machine but does not fix the issue in circleci

**Comment by siddiqaQ** [comment]
Same Issue .

**Comment by ravi-poonia** [comment]
Just run npx jetify in circleci as well
