### ISSUE TITLE
Docs for paymentRequestWithNativePay incomplete/inconsistent

### ISSUE THREAD

**Issue by multiplegeorges** [tipsi/tipsi-stripe#507]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem

The methods signatures for `paymentRequestWithApplePay(items, options)` and `paymentRequestWithNativePay(options, items)` are inconsistent.

https://github.com/tipsi/tipsi-stripe/blob/master/src/Stripe.js#L74

vs.

https://github.com/tipsi/tipsi-stripe/blob/master/src/Stripe.js#L87

Also, the documentation mentions that `paymentRequestWithNativePay` is preferred, but doesn't indicate the new parameter order.

## The Solution

Update docs or change method signatures to always go in `(items, options)` order.

## Environment
* `tipsi-stripe` version: Latest

**Comment by baugarten** [comment]
Yeah, this is confusing for a few reasons. One, `paymentRequestWithNativePay` is undocumented. Two, `paymentRequestWithNativePay` accepts totally different parameters based on the platform and the paramters have totally different formats. It seems to me that two different methods makes more sense, unless of course tipsi-stripe wants to defined a platform-agnostic argument list and then munge the arguments into the correct formats depending on the platform

**Comment by fbartho** [comment]
We want to have a platform-agnostic argument list, and we totally control the arguments that we should send.

I've slated looking into this as a candidate for 8.1 which will be started after we finally ship 8.0 (in beta now).

I think it'll have to be a breaking change, but hopefully it'll make sense. /cc @baugarten

**Comment by baugarten** [comment]
@fbartho that sounds good to me, I think a platform-agnostic argument list is a great end-state.

It's definitely a little funny doing something like... because of the order of arguments and such. Looking forward to 8.0!

```js
if (Platform.OS === 'android') {
   argumentList = makeAndroid();
} else {
  argumentList = makeIOS();
}
stripe.paymentRequestWithNativePay.apply(stripe, argumentList);
```

**Comment by Adokiye** [comment]
Can't find the documentation for paymentRequestWithNativePay anywhere, please can someone post a link or something, I don't even know the parameters to pass to the endpoint

**Comment by baugarten** [comment]
@Adokiye I found the source code to be the most useful documentation for this project.

You can see the interfaces here https://github.com/tipsi/tipsi-stripe/blob/d9c8be08b7ce3757f6bc5ee5198f46c63a38e2c1/src/Stripe.js#L64 which is helpful for knowing which interface methods expect which types.

And https://github.com/tipsi/tipsi-stripe/blob/d9c8be08b7ce3757f6bc5ee5198f46c63a38e2c1/src/utils/types.js#L132 for seeing the type definitions
