### ISSUE TITLE
react-native link tipsi-stripe is not working RN60.0.4

### ISSUE THREAD

**Issue by cobra0901** [tipsi/tipsi-stripe#511]
![image](https://user-images.githubusercontent.com/40814780/61868211-7ee5c800-af0b-11e9-8c1e-054f8b5ec776.png)

Auto-link failed.

**Comment by LeandroGartner** [comment]
Maybe this will help you https://github.com/tipsi/tipsi-stripe/issues/504#issuecomment-518992108
