### ISSUE TITLE
Build Fail in iOS

### ISSUE THREAD

**Issue by yudzuru** [tipsi/tipsi-stripe#512]
## The problem
Build Fail in iOS experiencing the below warnings:
Illegal type 'NSNumber * _Nullable' used in a boxed expression

## Environment
* `tipsi-stripe` version: 7.5.1
* iOS or Android: iOS
* React-Native version: 0.59.5

## Screenshots, GIFs (Must to have)
<img width="1185" alt="螢幕截圖 2019-07-28 下午1 08 42" src="https://user-images.githubusercontent.com/27944028/62002118-d917a080-b138-11e9-98b1-60eb5d0630f5.png">

**Comment by yudzuru** [comment]
Fixed by Reinstall pods and use new build system.

**Comment by ElieMyIdea** [comment]
> Fixed by Reinstall pods and use new build system.

Which Stripe IOS SDK version are you using in your pods ? I'm facing this issue with Stripe v16 but not with stripe v15

Using tipsi-stripe version: 7.5.1 and react-native 0.59.10

**Comment by yudzuru** [comment]
> > Fixed by Reinstall pods and use new build system.
> 
> Which Stripe IOS SDK version are you using in your pods ? I'm facing this issue with Stripe v16 but not with stripe v15
> 
> Using tipsi-stripe version: 7.5.1 and react-native 0.59.10

I am using v14 as stated in the example package of tipsi-stripe.
(Stripe ~>14.0.0, tipsi-stripe: 7.5.1, react-native 0.59.5)

I've changed the build system with File > Workspace setting between legacy & new system before I reinstall my Pods.
Then the warning is changed to library missing (cause by firebase not installed correctly). 

Therefore I think this error may due to the Build System or the dependencies are changed when upgrading from v15 to v16.

**Comment by rdewolff** [comment]
Facing same error with Stripe 19.0.1
