### ISSUE TITLE
createSourceWithParams() not working in android the promise not get resolved

### ISSUE THREAD

**Issue by rajaramanZencode** [tipsi/tipsi-stripe#513]
## Before I have submitted the issue 
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I am trying to create sourceId of type card with the help of createSourceWithParams() and its working fine in ios but android not working the promise never got resolved.

## Environment
* "tipsi-stripe": "^7.5.0"
*  Android only
*  "react-native": "0.59.8",

Code To Reproduce:

 const params = {
            type: 'card',
            number: this.cardDetails.number,
            expMonth: this.cardDetails.expMonth,
            expYear: this.cardDetails.expYear,
            cvc: this.cardDetails.cvc
        }
        this.cardDetails = null
        const sourceToken = await stripe.createSourceWithParams(params);
        

        let addNewCard = new APIRequest()
        addNewCard.method = 'POST'
        addNewCard.isCustomerToken = true
        addNewCard.path = APIPaths.addNewCard
        addNewCard.params = {
            sourceToken:sourceToken.sourceId,
            setAsPrimary: this.state.isPrimaryCard
        }
        this.setState({ isLoading: true })
        apiCall(addNewCard).then(response => {
            this.setState({ isRefreshing: false, isLoading: false,isPrimary:false})
            if (response.success) {
                this.getCardsList();
                showToaster(response.message);
            } else {
                showAlert(response.error.errorMessage.message)
            }
        })

**Comment by omarinho** [comment]
This works sometimes. Sometimes is not working. Any help?

**Comment by RiusmaX** [comment]
Same problem here.

My code : 

JS :
`const params = {
      type: 'alipay',
      amount: price,
      currency: subscription.currency.code,
      returnURL: 'example://stripe-redirect'
    }

    try {
      const source = await stripe.createSourceWithParams(params)
      console.log(source)
    } catch (e) {
      console.log(e)
    }
`

build.gradle : 
`
android {
   //...
    defaultConfig {
        //...
        manifestPlaceholders = [onesignal_app_id: "17faf0a5-7500-4aeb-820c-955e6036a97c",
                                onesignal_google_project_number: "REMOTE",
                                tipsiStripeRedirectScheme: "example"]
   //...
  }
`

androidManifest.xml : 
`
 <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="@string/fb_login_protocol_scheme" />
            <data android:scheme="${tipsiStripeRedirectScheme}" tools:replace="android:scheme" />
        </intent-filter>
`

After the source authorization, I'm redirected to my app but nothing happen.

Did I miss something ?
