### ISSUE TITLE
Can I please get quick advice on the status of android pay support

### ISSUE THREAD

**Issue by greg-dove** [tipsi/tipsi-stripe#52]
I see that android pay is described as 'under active development' and that in an issue from December it was described as 'Currently, Android Pay support is not ready for production since it under active development'

I am just curious as to the likely timeframce (any general guide would be helpful) for when it 'might' be production-ready. Thanks for you work on this lib, it seems great so far!

**Comment by cybergrind** [comment]
@greg-dove the main reason for that is the `preview` status of android pay support in stripe: https://stripe.com/docs/mobile/android#android-pay
So after it will be ready, we will do our tests and change it. 
We just don't want to mark something as production ready that isn't in our production application.

**Comment by greg-dove** [comment]
Thanks for clarifying, I had not seen that yet on the stripe side - much appreciated.  :)
