### ISSUE TITLE
ERROR: Failed to resolve: com.google.firebase:firebase-core:17.3.4

### ISSUE THREAD

**Issue by canpoyrazoglu** [tipsi/tipsi-stripe#523]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
On iOS I don't have any problem. On Android I'm getting:

`ERROR: Failed to resolve: com.google.firebase:firebase-core:17.3.4` when I try to build my app.

## Environment
* `tipsi-stripe` version: 7.5.1
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): None. I couldn't get it working
* iOS or Android: Android
* OS version: Android 8
* React-Native version: 0.59.9 (I can't update to 0.60.x because of many AndroidX problems with other libraries)
* (Android only) `com.google.firebase:firebase-core` version: 17.3.4
* (Android only) `com.google.android.gms:play-services-base` version: 16.0.0

## Links to logs and sources

* [android/build.gradle] https://gist.github.com/canpoyrazoglu/ef05f547c0cffcb9782e48b213d4a774

* android.compileSdkVersion 28
* android.buildToolsVersion 28.0.3
* android.defaultConfig.minSdkVersion 16
* android.defaultConfig.targetSdkVersion 28
* android.defaultConfig.multiDexEnabled (if exists) (multidex IS enabled in my project but I don't have such setting in my build.gradle)

## Screenshots, GIFs (Must to have)
![Screen Shot 2019-08-12 at 21 04 34](https://user-images.githubusercontent.com/4348413/62886966-e772d880-bd44-11e9-974a-bf0b27d99b45.jpg)

**Comment by PaulGoodDay** [comment]
I'm seeing a similar issue. Where you able to fix this? If so how?
