### ISSUE TITLE
paymentRequestWithCardForm freeze after pressing "Done"

### ISSUE THREAD

**Issue by matthiasleitner** [tipsi/tipsi-stripe#526]
## Before I have submitted the issue 
[ x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
After trying to fill out the payment form on paymentRequestWithCardForm and pressing done a spinner is shown infitely. Dialog can't be exited anymore

## Environment
* `tipsi-stripe` version: experimental branch
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android:  iOS
* OS version: 12 
* React-Native version:  0.59.10

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

## Code To Reproduce Issue (Good To Have)
![Screenshot 2019-08-22 at 14 32 59](https://user-images.githubusercontent.com/2040200/63515106-5a6d1380-c4ea-11e9-9a4d-5f59a2ecf06c.png)

**Comment by macnibblet** [comment]
I had the same problem, it's solved by #521 I modified the files for now, but it's not a good solution.

**Comment by matthiasleitner** [comment]
@macnibblet I already applied those changes, but issue still occurs.

**Comment by matthiasleitner** [comment]
issue here seems that the delegate changed 

from

`- (void)addCardViewController:(STPAddCardViewController *)controller
               didCreateToken:(STPToken *)token
                   completion:(STPErrorBlock)completion {
`

to

`- (void)addCardViewController:
(nonnull STPAddCardViewController *)addCardViewController
       didCreatePaymentMethod:(nonnull STPPaymentMethod *)paymentMethod
                   completion:(nonnull STPErrorBlock)completion {`

**Comment by fbartho** [comment]
Ah! I haven’t been messing with this API on the mistaken assumption that it should have kept working if there were no compilation issues.

The delegate change is a nice catch and I’ll investigate that today.
