### ISSUE TITLE
8.0.0-beta.1 Cannot build Android.

### ISSUE THREAD

**Issue by bramski** [tipsi/tipsi-stripe#527]
## Before I have submitted the issue 
[X] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[X] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[X] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[X] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
`> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/bram/.gradle/caches/transforms-2/files-2.1/259a372d2e2e163405888c7c37769972/res/values/values.xml:431:5-450:11: AAPT: error: style attribute 'attr/viewInflaterClass (aka com.findyourzo.zomobile.debug:attr/viewInflaterClass)' not found.

  /Users/bram/.gradle/caches/transforms-2/files-2.1/259a372d2e2e163405888c7c37769972/res/values/values.xml:497:5-526:11: AAPT: error: style attribute 'attr/viewInflaterClass (aka com.findyourzo.zomobile.debug:attr/viewInflaterClass)' not found.

  /Users/bram/.gradle/caches/transforms-2/files-2.1/259a372d2e2e163405888c7c37769972/res/values/values.xml:527:5-546:11: AAPT: error: style attribute 'attr/viewInflaterClass (aka com.findyourzo.zomobile.debug:attr/viewInflaterClass)' not found.

  /Users/bram/.gradle/caches/transforms-2/files-2.1/259a372d2e2e163405888c7c37769972/res/values/values.xml:613:5-616:11: AAPT: error: style attribute 'attr/viewInflaterClass (aka com.findyourzo.zomobile.debug:attr/viewInflaterClass)' not found.

  error: failed linking references.`

## Environment
* `tipsi-stripe` version: 8.0.0-beta.1
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 7.5.1
* iOS or Android: Android
* OS version: N/A
* React-Native version: 0.59
* (Android only) `com.google.firebase:firebase-core` version: 16.0.9
* (Android only) `com.google.android.gms:play-services-base` version: 16.1.0

## Links to logs and sources
(https://gist.github.com/bramski/d4e71bd0db7aa35a43f19f95112af132)

* [android/build.gradle](https://gist.github.com/bramski/31ed5a26837496ff4e3acc38c2cef590)

**Comment by mindlapse** [comment]
this looks like it might be a third party dependency issue

Does `com.findyourzo.zomobile` appear in your gradle dependencies?

**Comment by bramski** [comment]
That's our app's identifier.

**Comment by mindlapse** [comment]
Would this be an issue with the beta or with an attribute on your side?  We can chat on the tipsi-stripe channel - https://discord.gg/8g6ppq2
