### ISSUE TITLE
Google Pay brand guidelines compliance

### ISSUE THREAD

**Issue by Mirtillo19** [tipsi/tipsi-stripe#531]
## Before I have submitted the issue 
[X] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[X] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[X] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[X] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
By going through Google's [merchant approval process](https://developers.google.com/pay/api/android/guides/test-and-deploy/integration-checklist), my app was rejected because the rendered Google Pay button used wasn't the one provided by Google in its [brand guidelines](https://developers.google.com/pay/api/android/guides/brand-guidelines), although I had recreated the button following the guides.
I was able to render the native button provided by Google but I had to modify this package and that's not something I'd like to do every time a new release comes out :)

How is everyone rendering the Google Pay button to pass Google's production access process?

I think updating the docs with information about this would be helpful, as I haven't found anybody talking about it.

**Comment by datdevboi** [comment]
@Mirtillo19 how were you able to render the native button provided by Google?

**Comment by baugarten** [comment]
@Mirtillo19 I just uploaded a native button wrapped in a react-native package. You can check it out if you want to use it. https://github.com/baugarten/react-native-gpay-button

**Comment by vickean** [comment]
Has anyone had any success getting their app approved by Google?

**Comment by jack828** [comment]
@vickean Mine was approved first time, using a button with the right image in it.
https://www.gstatic.com/instantbuy/svg/light_gpay.svg
https://www.gstatic.com/instantbuy/svg/dark_gpay.svg


![image](https://user-images.githubusercontent.com/6363719/92129591-a3dd8780-edfb-11ea-846c-715a01b1b407.png)

**Comment by vickean** [comment]
@jack828 Oh cool. That's great news. Will use your approach and see how it goes. Thanks!

**Comment by jack828** [comment]
@vickean You're welcome, best of luck. Give me a shout if you need a hand!
