### ISSUE TITLE
Can't add a return type to the keyboard from PaymentCardTextField

### ISSUE THREAD

**Issue by robbert1131** [tipsi/tipsi-stripe#537]
## The problem
In the app we have the option to use an existing card or use a new card. For the new card we use
the PaymentCardTextField input but if the user wants to cancel entering the card details there is no option to close the keyboard. The blur function from the ref only works when the field is filled in fully with valid data. The return type would help us to close the keyboard.

But we can't seem to figure out how to use the return type props on PaymentCardTextField.

[return key type documentation](https://facebook.github.io/react-native/docs/textinput.html#returnkeytype)

## Environment
* `tipsi-stripe` version: 8.0.0-beta.4
* iOS or Android: Both

**Comment by lucienbl** [comment]
Hello :wave: Is there any update on this? I'd also need to allow the user to manually close the keyboard, especially on iOS where there is no "back" button.
