### ISSUE TITLE
Android Build failed Could not determine artifacts for com.github.tipsi:CreditCardEntry:1.5.1

### ISSUE THREAD

**Issue by stanislav-sidorov** [tipsi/tipsi-stripe#540]
Hey, I'm just trying to build a project and get this error Could not determine artifacts for com.github.tipsi:CreditCardEntry:1.5.1

installed, linked and set options according to docs
ios works ok
Android Studio offline work disabled

## Environment
* `tipsi-stripe` version: 7.5.1
* iOS or Android: Android
* OS version: 9
* React-Native version: 0.59.10

 `android/app/build.gradle`:
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"

![image](https://user-images.githubusercontent.com/45631742/64680867-4aac7380-d487-11e9-83cf-0238aff28b06.png)
![image](https://user-images.githubusercontent.com/45631742/64681855-1fc31f00-d489-11e9-8967-277c2d15b83b.png)
![image](https://user-images.githubusercontent.com/45631742/64682244-d4f5d700-d489-11e9-80e1-22fced65adcf.png)

**Comment by stanislav-sidorov** [comment]
seems to me error is gone
comment out

![image](https://user-images.githubusercontent.com/45631742/64691399-3ecaac80-d49b-11e9-9945-e327d2475012.png)

**Comment by acro5piano** [comment]
I have the same error and tried to fix it by adding the following condition, but no luck. still researching.

`android/build.gradle`

```diff
subprojects {
+    if (project.name.contains('tipsi-stripe')) {
+        buildscript {
+            repositories {
+                maven { url "https://jitpack.io" }
+            }
+        }
+    }
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion "28.0.3"
            }
        }
    }
}
```

Ref: https://github.com/react-native-community/react-native-image-picker/issues/1002#issuecomment-445864985

**Comment by acro5piano** [comment]
Seems that another library caused the problem. I found it by adding `--info` option in the build command (starting with `./gradlew` ).

**Comment by johnsaby** [comment]
facing a similar problem since 2 days...  when update to rn 0.59.3
========================================
Could not find com.github.tipsi:CreditCardEntry:1.5.0.
==============================
Any clue guys?

**Comment by stanislav-sidorov** [comment]
I think this error means that tipsi can't download something from the server. So you need to check maven url, without any conditions. 
Here are some instructions how to use tipsi. 
Read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
For an iOS you need to install pods [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
Read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
Before using `tipsi-stripe` you need to set options for the app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)

**Comment by Alincer** [comment]
https://github.com/tipsi/tipsi-stripe/issues/550#issuecomment-533795656
This one solved this issue for me
