### ISSUE TITLE
[Experimental - 8.0.0-beta.8] stripe.deviceSupportsNativePay() crashes in Android on RN 0.59.10

### ISSUE THREAD

**Issue by lalmachado** [tipsi/tipsi-stripe#541]
## Before I have submitted the issue 
[+] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[+] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[+] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[+ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem

in beta.6 the function stripe.deviceSupportsNativePay() crashes on call with error:
```
Could not invoke
StripeModule.deviceSupportsAndroidPay

null
```
all other methods not referring google play are working as expected

**Comment by adarshraj87** [comment]
@lalmachado Did you find any solution for the issue, any help would be appreciated ?

**Comment by lalmachado** [comment]
@adarshraj87 I am still having this issue

**Comment by adarshraj87** [comment]
@lalmachado i got it resolved by following google pay official setup guide

**Comment by rohitkum28** [comment]
@adarshraj87 Can you give more details or link to the guide you followed? I am facing the same issue with 8.0.0-beta.10 and react-native 0.61.5.

**Comment by dani-mp** [comment]
I could fix it following this:
https://developers.google.com/pay/api/android/guides/setup#dependencies

I think the library should take care of it or at least mention this in the docs.
