### ISSUE TITLE
Issue with Android SDK for SCA and Authentication for versions lower than 11

### ISSUE THREAD

**Issue by ejkkan** [tipsi/tipsi-stripe#542]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Stripes android sdk had issues with the authentication of a user when the authentication was made a third party application.
Example:
-a user wants to confirm an intent
-the stripe sdk prompts an authentication screen
-the stripe sdk screen then needs to open another app for authentication (I our case its the service "Bank id")
-the stripe sdk fails to handle the callback from these services

Stripe pushed a solution in Android SDK version 11+
Which has a lot of breaking changes, such as androidX.

We have also created an issue with Stripe about this [here](https://github.com/stripe/stripe-android/issues/1541)

## Environment
* `tipsi-stripe` version: 8.0.0-beta.6
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 8.0.0-beta.6
* iOS or Android: Android
* OS version: All
* React-Native version: All

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion 28
* android.buildToolsVersion 28.0.3
* android.defaultConfig.minSdkVersion 19
* android.defaultConfig.targetSdkVersion 28
* android.defaultConfig.multiDexEnabled true

## Code To Reproduce Issue (Good To Have)
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by ejkkan** [comment]
Still seeing this issue even though we updated the Android SDK to 10.4.4 locally for tipsi-stripe.

**Comment by ejkkan** [comment]
Another release 10.4.5 out hoping to fix this issue

**Comment by mshafrir-stripe** [comment]
@ejkkan hopefully this is resolved now?
