### ISSUE TITLE
null is not an object (evaluating 'StipreModule.init') RN > 60

### ISSUE THREAD

**Issue by Eesssn** [tipsi/tipsi-stripe#543]
Hi.
I have issue when i want to render my app.
I know this problem is for linking but i have no idea for RN > 60 or Expo > 30.
this type of projects linked automatically and didn't have any android or ios directory for link manually at least.
I can't change RN version. did any body have any idea for resolving it.
best regard

**Comment by tmaly1980** [comment]
I had to manually link it with the instructions. Same approach as with < 0.60 . BUT, with AndroidX enabled, you'll need to wait for that to be supported.

**Comment by rizwanatta** [comment]
+1

**Comment by alexpchin** [comment]
I believe that this might be linked to https://github.com/tipsi/tipsi-stripe/issues/551

**Comment by reidkersey** [comment]
Any progress on this? I am having the same issue.

RN 0.60.5
tipsi-stripe 7.5.1

**Comment by janoist1** [comment]
+1
Is this lib dying?

**Comment by cybergrind** [comment]
@janoist1 we're not merging PR's without tests and currently, no one wants to fix tests. So, probably it is dying.

**Comment by janoist1** [comment]
> @janoist1 we're not merging PR's without tests and currently, no one wants to fix tests. So, probably it is dying.

Very sad.

Anyway, the issue got fixed by running `pod install` inside `ios`. I tend to forget about this.
