### ISSUE TITLE
null is not an object (evaluating 'h.init') when adding setOptions

### ISSUE THREAD

**Issue by therhapzody** [tipsi/tipsi-stripe#545]
I ejected from expo, and added the tipsi-stripe package, following the instructions in the documentation.

following is how I have used in the project:

import stripe from 'tipsi-stripe';

//right after import statement
stripe.setOptions({
    publishableKey: 'publishable key',

})

when doing this, app crashes with 'null is not an object (evaluating 'h.init')' error.

Been trying many ways for the last week, including re-ejecting from expo and re-installing tipsi-stripe.

I also, tried moving the setOptions under 'ComponentDidMount', which stopped the app from crashing, but functions did not seem to work.

For example, I tried the following under a try-catch:

const token = await stripe.createTokenWithCard(
            {
                number: '4242424242424242',
expMonth: 11,
expYear: 17,
cvc: '223',
name:'Jack'
}

this threw the following error:
"[TypeError: null is not an object (evaluating 'h.createTokenWithCard')]"

On my Stripe dashboard API log, I did not see any incoming call.

Anybody with the same issue?

**Comment by alexpchin** [comment]
I believe that this might be linked to https://github.com/tipsi/tipsi-stripe/issues/551
