### ISSUE TITLE
iOS build Fails 'Stripe/Stripe.h' not found..

### ISSUE THREAD

**Issue by BhavanPatel** [tipsi/tipsi-stripe#55]
I am able to build on android but in iOS its fails everytime...
tried with `react-native link` and also manually as said in `ReadMe` but still facing this error...

Terminal: 
![ss](https://cloud.githubusercontent.com/assets/7195877/25229968/13010114-25f0-11e7-994a-db6d89cfc114.png)

Xcode:
![screen shot 2017-04-20 at 5 43 57 pm](https://cloud.githubusercontent.com/assets/7195877/25230274/0075b980-25f1-11e7-9e36-d6af25b1242e.png)

podFile:
![screen shot 2017-04-20 at 5 46 18 pm](https://cloud.githubusercontent.com/assets/7195877/25230416/66c354c2-25f1-11e7-9893-edd428cf7a62.png)

Versions:
React: 15.4.1
ReactNative : 0.42.3
Xcode: 8.3
iOS: 10.0
pod: 1.2.1

**Comment by cybergrind** [comment]
@BhavanPatel thank you for the report. We're going to check it

**Comment by dmytrozavgorodniy** [comment]
Please check what target your selected `stripeDemo` scheme use. I guess your target has the name `stripeDemo` (because target and scheme in Xcode have the same names by default).
In Podfile you describe for which targets you want to install dependencies. In your case you choose `example ` target, maybe you should change it to `stripeDemo`.

**Comment by dmytrozavgorodniy** [comment]
@BhavanPatel

**Comment by BhavanPatel** [comment]
@dmytrozavgorodniy 👍  @cybergrind 👍   thank you for help :)

Issues has been sort out :)

1. Removed whole iOS folder from project
2.  `react-native upgrade` only for iOS.
3.  `react-native link`
Steps Worked...!!!

**Comment by jomaint** [comment]
I tried manual and linking it but still doesn't work. Any other solutions?

**Comment by isnifer** [comment]
@jomaint please, show me you *Podfile* and *Linked Frameworks and Libraries* part in your general settings

**Comment by jomaint** [comment]
@isnifer 
<img width="285" alt="screen shot 2017-07-12 at 9 14 36 pm" src="https://user-images.githubusercontent.com/4236680/28119394-4f23145a-6747-11e7-9317-e2ad1d6b8074.png">
<img width="769" alt="screen shot 2017-07-12 at 9 13 19 pm" src="https://user-images.githubusercontent.com/4236680/28119396-4f25bdfe-6747-11e7-8231-837c27328379.png">
<img width="237" alt="screen shot 2017-07-12 at 9 13 47 pm" src="https://user-images.githubusercontent.com/4236680/28119395-4f255972-6747-11e7-8828-d24a0e1bbc0d.png">

**Comment by isnifer** [comment]
@jomaint did you try to install pods via `pod repo --update && pod install` in `ios` folder?

**Comment by jomaint** [comment]
@isnifer I did actually, and i got another error compiling. 
`ld: 19 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by jomaint** [comment]
@isnifer I had another different issue, but it works now. Thanks for your help anyway

**Comment by isnifer** [comment]
@jomaint glad to help you :)
