### ISSUE TITLE
Could not resolve com.github.tipsi:CreditCardEntry:1.5.1.

### ISSUE THREAD

**Issue by tkulpa** [tipsi/tipsi-stripe#550]
Most recently I started getting this error on bitrise, even when I had zero problems with it before
![image](https://user-images.githubusercontent.com/18174866/65136403-cc604c00-da07-11e9-9064-9d5951a3356a.png)

I have maven repository in allprojects

```
allprojects {
    repositories {
        // Add jitpack repository (added by tipsi-stripe)
        maven { url "https://jitpack.io" }
       {...}
    }
}

```

**Comment by Remipbl** [comment]
I have the same issue

**Comment by GuiWukai** [comment]
Similar issue here:
```
> Could not find com.github.tipsi:CreditCardEntry:1.5.1.
     Searched in the following locations:
```

**Comment by wkoutre** [comment]
Same. Any idea?

**Comment by Remipbl** [comment]
Found out that jitpack had some issues around september 12.

I solved the issue by changing jitpack url in the build.gradle https://jitpack.io to https://www.jitpack.io (added www)

`maven { url "https://www.jitpack.io" }`

**Comment by wkoutre** [comment]
@Remipbl Perfect -- resolved. Thanks!

**Comment by johnsaby** [comment]
did everything ... still not working 
==========================================================
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.github.tipsi:CreditCardEntry:1.5.0.
  Required by:
      project :app > project :tipsi-stripe
=====<w working perflecty with rn0.55 .. when upgrage to 0.59.3 get the error

**Comment by acro5piano** [comment]
@Remipbl
Thank you for the solution. It worked!!! You saved my extra few days :)

**Comment by acro5piano** [comment]
@johnsaby You can try to update tipsi-stripe 1.5.1

**Comment by Ilphrin** [comment]
Thanks @Remipbl you just saved me! =D

Now, I would be interested to know why this change was needed, and why it resolves this problem 🤔

**Comment by chrisoname** [comment]
```
        maven { url "https://www.jitpack.io" }
        maven { url "$rootDir/../node_modules/react-native/android" }
```

**Comment by sdlee3** [comment]
I solved this issue by placing the maven { url "https://www.jitpack.io" } first before  maven { url "$rootDir/../node_modules/react-native/android" }
