### ISSUE TITLE
Integrating with Jest - TypeError: Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by alexpchin** [tipsi/tipsi-stripe#551]
## The problem
I'm having an issue using Jest with tipsi-stripe. I have resolved the issue with #104 but I now get:

<img width="617" alt="Screenshot 2019-09-19 at 01 40 32" src="https://user-images.githubusercontent.com/40461/65200387-80042300-da7e-11e9-8d78-67afe545b402.png">

## Environment
`tipsi-stripe` version: 8.0.0-beta.7
* stripe-ios: 16.0.0

**Comment by alexpchin** [comment]
This issue is here: 

Line 21. in `tipsi-stripe`:

```
return StripeModule.init(options, errorCodes)
```

I'm using `jest-expo` because I ejected from a managed Expo project to a bare workflow. Could this be the cause of the issue?

Thank you in advance.

**Comment by alexpchin** [comment]
To get my test to pass in the meantime, I had to:

```
jest.mock('tipsi-stripe', () => {
  return {
    setOptions: jest.fn(),
  };
});
```

But I'd like to know what the actual problem is...

**Comment by IanArko** [comment]
^^^ I'm having the same issue. Tried to use [the advice here](https://tipsi.github.io/tipsi-stripe/docs/troubleshooting-jest.html), but it broke my other tests.

**Comment by oehc123** [comment]
I switch:

`return StripeModule.init(options, errorCodes)`

for:

`return StripeModule && StripeModule.init(options, errorCodes)`

in `node_modules/tipsi-stripe/src/Stripe.js`

and that seems to be working
