### ISSUE TITLE
Transaction declined invalid payment method lean more  OR ccseh-05

### ISSUE THREAD

**Issue by AbubakarMian** [tipsi/tipsi-stripe#553]
i am trying to have simple payment with tipsi-stripe but it keeps me giving 

"Transaction declined invalid payment method lean more  OR ccseh-05" error.

 i tried using with and without gps but no luck. 

i am setting options 

stripe.setOptions({
  publishableKey: 'pk_test_****',
  androidPayMode: 'test', // Android only
}); 

const token = await stripe.paymentRequestWithNativePay({
        total_price: '100.00',
        currency_code: 'USD',
        shipping_address_required: true,
        phone_number_required: true,
        shipping_countries: ['US', 'CA'],
        line_items: [
          {
            currency_code: 'USD',
            description: 'Milk',
            total_price: '50.00',
            unit_price: '50.00',
            quantity: '1',
          },
          {
            currency_code: 'USD',
            description: 'Mobile',
            total_price: '30.00',
            unit_price: '30.00',
            quantity: '1',
          },
          {
            currency_code: 'USD',
            description: 'Tipsi',
            total_price: '20.00',
            unit_price: '20.00',
            quantity: '1',
          },
        ],
      });
      this.setState({loading: false, token});
      console.log('Google account paid token ', token);
    } catch (error) {
      this.setState({loading: false});
    }

please help

**Comment by harshvitra** [comment]
@AbubakarMian did you find any solution to this ?
