### ISSUE TITLE
8.0.0-beta.8 - unable to build on iOS (enumeration not handled)

### ISSUE THREAD

**Issue by NicholasBertazzonAga** [tipsi/tipsi-stripe#558]
## Before I have submitted the issue 
[ x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Can't build on iOS, you can see the problem in the screenshot. Everything works good on beta 7. Once I switch to beta 8, the problem occurs.

## Environment
* `tipsi-stripe` version: 8.0.0-beta.8
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 8.0.0-beta.7
* iOS or Android: iOS
* OS version: Mojave
* React-Native version: 0.61.1

## Screenshots, GIFs (Must to have)
<img width="763" alt="Schermata 2019-09-27 alle 09 47 33" src="https://user-images.githubusercontent.com/33664465/65756043-96f8e400-e114-11e9-883f-541caeed3114.png">

**Comment by bramski** [comment]
You need the newer stripe Pod. Go to your pods directory and do
`pod update Stripe`.

**Comment by andyesp** [comment]
Build succeeds if Stripe dependency in podspec is `~> 16.0.7` instead of `=> 16.0.7`.

**Comment by NichAga** [comment]
@andyesp 
I've seen that a commit has been made about it, we have to stick to 16.0.7 until beta.9 is out
