### ISSUE TITLE
Unable to start activity ComponentInfo{<app_name>/com.gettipsi.stripe.RedirectUriReceiver}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.gettipsi.stripe.StripeModule.processRedirect(android.net.Uri)' on a null object

### ISSUE THREAD

**Issue by gregory-light-it** [tipsi/tipsi-stripe#559]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I don't know how to reproduce, but there is logs and all info you need. I can't use previous stable version cause PaymentIntent is only exist on 8.0.0-beta*. Let me know if you need something else. 

For last 7 days I have 47 crashes for 18 users, that's not big number. But on previous version of tipsi-stirpe I had 0 crashes.

## Environment
* `tipsi-stripe` version: 8.0.0-beta.1
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 7.3.0
* iOS or Android: Android
* OS version: 5, 7, 8, 9
* React-Native version: 0.59.10
* (Android only) `com.google.firebase:firebase-core` version: 16.0.3
* (Android only) `com.google.android.gms:play-services-base` version: 15.0.1

## Links to logs and sources
[crashlytics_errors_on_latest_version_of_app.txt](https://github.com/tipsi/tipsi-stripe/files/3661903/crashlytics_errors_on_latest_version_of_app.txt)

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion 28
* android.buildToolsVersion 28.0.3
* android.defaultConfig.minSdkVersion 19
* android.defaultConfig.targetSdkVersion 28
* android.defaultConfig.multiDexEnabled (if exists) true

## Screenshots, GIFs (Must to have)
Don't have it

## Code To Reproduce Issue (Good To Have)
Don't have it

**Comment by ydecoux** [comment]
For info, it happens also on 7.5.0
