### ISSUE TITLE
Stable SCA Version

### ISSUE THREAD

**Issue by imbudhiraja** [tipsi/tipsi-stripe#561]
When we can except the stable release with SCA support ?

**Comment by mtahiragha** [comment]
Hi, please its an issue, waiting anxiously for the SCA version as the deadline for implementation has already passed. 
Can someone please inform when to expect? My manager is on my ass.

**Comment by cybergrind** [comment]
If you desperately need it - just use beta. If we release a stable version right now - there will be no difference anyway.
When we started the migration of our internal apps it has turned that it isn't that straightforward and there are some issues, so earlier you start using beta - better for you. If you decide to wait for stable release - expect some additional work on your side and at worse - a lot of work.

**Comment by thecookieorg** [comment]
Any news on this?

**Comment by cybergrind** [comment]
Given the lack of interest from contributors to make it merged in stable - probably you shouldn't wait and just use beta.
