### ISSUE TITLE
Apple Pay not Completed

### ISSUE THREAD

**Issue by hugoh59** [tipsi/tipsi-stripe#562]
Using @^8.0.0-beta.7, I get the following error message when trying to complete Apple Pay payment. I have setup Apple Merchant ID and followed all the instructions. This fails on both real device and simulator.

"Apple Pay not Completed" 

I have attached an image of the error message.

<img width="364" alt="Screen Shot 2019-10-01 at 11 36 51 AM" src="https://user-images.githubusercontent.com/25149138/65951172-ca52b000-e43f-11e9-9dc1-40b064f322a6.png">

**Comment by bramski** [comment]
(1) Try beta.8
(2) Double check that you've set everything up correctly as described. We are running this build in production with no problems.

**Comment by gregory-light-it** [comment]
Its better to check on real device

**Comment by andyesp** [comment]
@bramski is it working ok on iOS 13 for you? I'm having "Cancelled by user" error all of a sudden. And I'm seeing errors on production on versions after 12.1.
Testing on beta.8 right now.

**Comment by bramski** [comment]
Yes but it never works in simulator.

**Comment by Sterlingryan** [comment]
@andyesp Did you find the solution to your problem ? I am having the same error

**Comment by hugoh59** [comment]
For me even on real device I still can't make it work.

**Comment by vTrip** [comment]
Hi guys, on a real device using stripe test keys I get "payment not completed"

The device is running iOS 13

**Comment by daxaxelrod** [comment]
Having the same issue on the simulator even though my success callback with the stripe token gets fired. Need to get an adapter for our iphone to test but will report back in a day or two.

**Comment by daxaxelrod** [comment]
Tested on a real device and have the same issue of "payment could not be processed". Stripe has my certificate and the shape of my params matches the validation type check. Will step through the stripe module and report back

**Comment by c9n** [comment]
> For me even on real device I still can't make it work.

did you fix this problem?

**Comment by Haseeb005** [comment]
Hello EveryOne, please try this to add in you code this function will help you yo complete the payment..
i was able to resolved mu issue..
"stripe.completeNativePayRequest();"

**Comment by Haseeb005** [comment]
> > For me even on real device I still can't make it work.
> 
> did you fix this problem?

please try this to add in your code
"stripe.completeNativePayRequest();"

**Comment by yashlinmaistry** [comment]
@Haseeb005 

This is what I have so far. Where would you add it? 

It looks like it throws the error before the promise is resolved

`const stripeToken = await stripe.paymentRequestWithNativePay({
                total_price: '100.00',
                currency_code: 'USD',
                shippingMethods: [{
                    id: 'fedex',
                    label: 'FedEX',
                    detail: 'Test @ 10',
                    amount: '10.00',
                }],
            },
                [{
                    label: 'Whisky',
                    amount: '50.00',
                }, {
                    label: 'Vine',
                    amount: '50.00',
                }])`

**Comment by Haseeb005** [comment]
@yashlinmaistry please Follow this link

https://github.com/tipsi/tipsi-stripe/blob/master/example/src/scenes/ApplePayScreen.js
