### ISSUE TITLE
What is the reason paymentRequestWithCardForm does not show built-in interface components in Stripe’s Android SDK?

### ISSUE THREAD

**Issue by sunshineo** [tipsi/tipsi-stripe#567]
Say when call paymentRequestWithCardForm . It shows this dialog https://github.com/tipsi/tipsi-stripe/blob/master/android/src/main/java/com/gettipsi/stripe/dialog/AddCardDialogFragment.java

And it is very weak. No address input. Not even zip code

Is there a way to use the built-in user interface components in Stripe’s Android SDK? https://stripe.com/docs/mobile/android/standard

**Comment by cybergrind** [comment]
@sunshineo I'm not sure what prevents you from using any form you want, probably you can collect data and use https://tipsi.github.io/tipsi-stripe/docs/createtokenwithcard.html to achieve what do you want

**Comment by sunshineo** [comment]
@cybergrind Thank you for your reply. When I use https://tipsi.github.io/tipsi-stripe/docs/paymentrequestwithcardform.html , it works pretty well on iOS. But on Android, it shows a dialog without address or even zip code. The dialog is from this project (I provided link to the code above). 

My question is, why it is not showing buildt-in user interface components in Stripe’s Android SDK?

**Comment by cybergrind** [comment]
@sunshineo probably we could do that, but right now we don't have any people to implement that.

**Comment by sunshineo** [comment]
@cybergrind May I ask what's your estimation on how easy (or hard) this is likely to be? Is it as simple as expose some function calls?

**Comment by cybergrind** [comment]
@sunshineo probably it can be done similarly to IOS implementation, but I cannot give ETA about how hard it would be. Right now we have 2+ month PR that cannot be merged because there are no people dedicated enough to make it happen and Tipsi doesn't have any people who can switch to this task either.

**Comment by sunshineo** [comment]
@cybergrind Thank you. But you are still the best. That's why Stripe recommended you guys: https://stripe.com/docs/libraries

If I want to help by modify this library, where can I start? What can I read? Is there a development guide?

**Comment by cybergrind** [comment]
@sunshineo you can start by reading existing documentation and try to run tests locally `npm run ci`
There is no development guide, so you can guide yourself by surrounding code. For this particular feature, you can use existing API + IOS part

**Comment by Donhv** [comment]
@sunshineo 
Before, my team develop native code both android & iOS.
I confirm that tipsi use  iOS Stripe SDK UI. and make android same doesn't take much effort. 
one more thing. paymentRequestWithCardForm was missing customer session(Ephemeral_Key).
I really wish tiosi would soon do two things. :(

**Comment by sunshineo** [comment]
@Donhv Is ephemeral key android only? I did not see mentioning of ephemeral key for ios https://stripe.com/docs/mobile/ios

**Comment by Donhv** [comment]
@sunshineo no. both android and iOS. 
https://stripe.dev/stripe-ios/docs/Protocols/STPCustomerEphemeralKeyProvider.html

**Comment by sunshineo** [comment]
@Donhv It looks deprecated to me https://stripe.dev/stripe-ios/docs/Protocols.html#/c:objc(pl)STPEphemeralKeyProvider

**Comment by sunshineo** [comment]
@Donhv I don't get it. It seems I'm using their ios sdk without doing anything with ephemeral key at all. I'm not even aware of this. Is this an optional thing that is only needed if you are doing some crazy operations?

**Comment by Donhv** [comment]
> @Donhv I don't get it. It seems I'm using their ios sdk without doing anything with ephemeral key at all. I'm not even aware of this. Is this an optional thing that is only needed if you are doing some crazy operations?

If you want show recent card of customer, you need implement customer session by ephemeral_key.

**Comment by sunshineo** [comment]
@Donhv Thank you!

**Comment by isidoro98** [comment]
Hi @sunshineo are you aware if tipsi will implement the android card form created by Stripe?

**Comment by sunshineo** [comment]
@isidoro98 I do not know for sure but judging from the progress of things, it's a no. Personally I'm not even sure if Stripe should be the preferred payment solution for a startup anymore. Let along their React Native library from a resource tight small 3rd party
