### ISSUE TITLE
Cannot show apple pay sheet in real iOS 12.4.1 device

### ISSUE THREAD

**Issue by pongponglau** [tipsi/tipsi-stripe#568]
The apple pay sheet can be shown in simulator but not in real device. I have setup testing sandbox visa and mastercard cards successfully in my real iphone device wallet. However, all networks (i.e. AE, Discover, Master card and Visa) are still not available. And no Apple Pay sheet is shown when i call stripe.paymentRequestWithNativePay. 

The tipsi-stripe version is 7.5.1.

Thank you very much for your advice.

**Comment by wayzate** [comment]
Same here

**Comment by lenichols** [comment]
+1

**Comment by dziter** [comment]
Same problem here, button is visible but nothing happens on click.

**Comment by VinitBhavsar** [comment]
Check that your region / country supported for apple pay or not?
Also for test environment.
In emulator for ios 13.6 it work, but for my device 13.6 it's not working.

https://developer.apple.com/apple-pay/sandbox-testing/
https://support.apple.com/en-us/HT207957
