### ISSUE TITLE
New initialization after closing payment modal

### ISSUE THREAD

**Issue by kajocib** [tipsi/tipsi-stripe#571]
Hello guys, i have one question. How i can init again a paymentrequest after i close apple pay request with "close" button or click out of payment modal. I havea wizzard type application. Also doesnt work when i go back and forward and try it again. Do anything.  Im using RN .59, tipsi-stripe beta 8 , and stripe 16.0.7.... thanks for answer! (sorry for my english)

**Comment by Donhv** [comment]
i think it's issue with your back-end

**Comment by kajocib** [comment]
when i close paymentmodal (applepay),doesnt call api method for charge money, i call api method after generate token

**Comment by Donhv** [comment]
i mean issue your back-end and stripe

**Comment by kajocib** [comment]
i fixed it, i had only a wrong branch in condition
