### ISSUE TITLE
null is not an object (evaluating 'StripeModule.init') issue in iOS

### ISSUE THREAD

**Issue by muhammadashfaq** [tipsi/tipsi-stripe#576]
i am trying to integrate Stripe in react native . i have added tipsi stripe and run `react-native link tipsi-stripe`  . it works well on Android but not for iOS

```
stripe.setOptions({
  publishableKey: 'PUBLISH_API_STRIPE_KEY',
});
```

onAndroid it works well but for iOS ,stripe is not initializing 
<img width="505" alt="Screen Shot 2019-10-21 at 2 09 16 PM" src="https://user-images.githubusercontent.com/48868012/67192101-656df280-f40c-11e9-816f-154b470ad517.png">

envoirment

```
 react": "16.8.3",
 react-native": "0.59.9",
 tipsi-stripe": "^7.5.1"
MacOS Catlina 10.15
```
Help will be appreciated

Thanks

**Comment by kajocib** [comment]
cd ios && pod install

**Comment by y7usuf** [comment]
https://github.com/tipsi/tipsi-stripe/issues/349#issuecomment-559145394

**Comment by y7usuf** [comment]
`$ cd ios`

open podfile and add these lines

```
pod 'Stripe', '~> 14.0.0'

pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'
```

save and

```
pod install
cd ..
```

`yarn start -- --reset-cache`
or
`npm run start -- --reset-cache`

**Comment by kaloncheung124** [comment]
Thanks @y7usuf, your comment fixed my build issues! How did you know to add the node module as a pod?

**Comment by y7usuf** [comment]
Actually, linking is not working for iOS somehow. I added it manually. Because dependency is missing.

**Comment by kaloncheung124** [comment]
Oh that's weird, manual linking wasn't working for me for some reason.

**Comment by 7Style** [comment]
@y7usuf  Thank you Yusuf :)

**Comment by parthasarathi95** [comment]
thanks @y7usuf

**Comment by kronix-dev** [comment]
Im having the same issue in Android

**Comment by NiravSony** [comment]
i'm having the same error in both platform .... any solution ??

envoirment

 react": "16.13.1",
 react-native": "0.63.4",
 tipsi-stripe": "^9.0.0"
MacOS big sur 11.1

**Comment by NiravSony** [comment]
i'm having the same error in both platform .... any solution ??

environment

react": "16.13.1",
react-native": "0.63.4",
tipsi-stripe": "^9.0.0"
MacOS big sur 11.1

**Comment by pynner** [comment]
@NiravSony any luck?

**Comment by ZaidQ797** [comment]
> i am trying to integrate Stripe in react native . i have added tipsi stripe and run `react-native link tipsi-stripe` . it works well on Android but not for iOS
> 
> ```
> stripe.setOptions({
>   publishableKey: 'PUBLISH_API_STRIPE_KEY',
> });
> ```
> 
> onAndroid it works well but for iOS ,stripe is not initializing
> <img alt="Screen Shot 2019-10-21 at 2 09 16 PM" width="505" src="https://user-images.githubusercontent.com/48868012/67192101-656df280-f40c-11e9-816f-154b470ad517.png">
> 
> envoirment
> 
> ```
>  react": "16.8.3",
>  react-native": "0.59.9",
>  tipsi-stripe": "^7.5.1"
> MacOS Catlina 10.15
> ```
> 
> Help will be appreciated
> 
> Thanks

Nice larky

**Comment by nvrsantos** [comment]
I just run `react-native link tipsi-stripe` and recompile the app
