### ISSUE TITLE
Question about apple pay and google pay

### ISSUE THREAD

**Issue by tankpower1** [tipsi/tipsi-stripe#579]
Do i need to set up apple and google pay in order to use tipsi-stripe in production, or i can just use the provided api methods?

**Comment by cybergrind** [comment]
@tankpower1 nope, you can just use stripe API for credit cards without supporting apple/google pay

**Comment by tankpower1** [comment]
Ok, so i don't need to add the com.google.android.gms.wallet.api.enabled in AndroidManifest.xml, correct?
