### ISSUE TITLE
Android bundle problem in version 8.0.0-beta.9

### ISSUE THREAD

**Issue by tankpower1** [tipsi/tipsi-stripe#582]
<img width="1515" alt="Screenshot 2019-11-01 at 18 12 56" src="https://user-images.githubusercontent.com/51695269/68038762-51ab7180-fcd3-11e9-81ed-c7beaa74a5df.png">

App works fine in development, but when bundleRelease is called this error comes up.

**Comment by njho** [comment]
Any fix?

**Comment by tankpower1** [comment]
In my project the problem comes from android/app/build.gradle where if minifyenabled is true it crashes on bundleRelease with tipsi-stripe installed, i dont know why, will try to find where the problem comes from.

**Comment by tankpower1** [comment]
assembleRelease also doesn't seem to work with minifyEnabled: true
