### ISSUE TITLE
IOS 8.0.0-beta.9 build fail

### ISSUE THREAD

**Issue by tankpower1** [tipsi/tipsi-stripe#585]
<img width="331" alt="Screenshot 2019-11-05 at 12 08 44" src="https://user-images.githubusercontent.com/51695269/68198651-1fe12600-ffc5-11e9-8a0d-a79496055f2f.png">

**Comment by LMestre14** [comment]
@tankpower1 try deleting yours Pods and your Podfile.lock
pod install in /ios folder and try running again the project

**Comment by tankpower1** [comment]
@LMestre14 I tried that multiple time but it doesn't seem to work.

**Comment by hugoh59** [comment]
I'm getting the same errors.

**Comment by hugoh59** [comment]
Yesterday I managed to make 8.0.0-beta.7 version work, I even added payment methods etc but this morning it stopped working for no reason. So I decided to update to 8.0.0-beta.9, but then getting the same errors as above.

**Comment by hugoh59** [comment]
@tankpower1 I installed 8.0.0-beta.8 and did not follow any of the installation instruction, only installed the pod

`pod 'Stripe', '~> 16.0.7'`

and it works now, hope this helps.

**Comment by tankpower1** [comment]
^ Yes i said the problem is only on 8.0.0-beta.9. Beta.8 works fine.

**Comment by arnaud-zg** [comment]
> ^ Yes i said the problem is only on 8.0.0-beta.9. Beta.8 works fine.

Same for me
