### ISSUE TITLE
UnionPay marked as invalid on Android

### ISSUE THREAD

**Issue by ff-adrian-obando** [tipsi/tipsi-stripe#587]
## Before I have submitted the issue 
[ X] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ X] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ X] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ X] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
When entering a UnionPay card number (e.g 6200000000000005) on Android the form mark it as invalid where on IOS it is marked as valid

## Environment
* `tipsi-stripe` version: 7.5.1
* Android
* OS version: 10
* React-Native version: 0.59.9
* (Android only) `com.google.firebase:firebase-core` version: 16.0.9
* (Android only) `com.google.android.gms:play-services-base` version: 16.0.1

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion: 28
* android.buildToolsVersion: 28.0.3
* android.defaultConfig.minSdkVersion: 19
* android.defaultConfig.targetSdkVersion: 28
* android.defaultConfig.multiDexEnabled: true

## Screenshots, GIFs (Must to have)
Android:
![image](https://user-images.githubusercontent.com/46901552/68400003-e8958500-013c-11ea-9e78-c64019e9ffc1.png)
IOS:
![image](https://user-images.githubusercontent.com/46901552/68400057-04992680-013d-11ea-8798-5809121ba0fd.png)

**Comment by arnaud-zg** [comment]
We use `LiteCreditCardInput` from `react-native-credit-card-input`, it works on Android.
