### ISSUE TITLE
_tipsiStripe.default.createPaymentMethod is not a function

### ISSUE THREAD

**Issue by hugoh59** [tipsi/tipsi-stripe#588]
I'm unable to use this library when I run the createPaymentMethod method I get this error message.

**Comment by AlexandrBol** [comment]
Is there any solutions for this issue ?

**Comment by janoist1** [comment]
+1

**Comment by janoist1** [comment]
A workaround:

```

      const data = {
        'type': 'card',
        'billing_details[address][city]': address.city,
        'billing_details[address][country]': address.country,
        'billing_details[address][line1]': address.line1,
        'billing_details[address][line2]': address.line2,
        'billing_details[address][postal_code]': address.postalCode,
        'billing_details[email]': profile.email,
        'billing_details[name]': `${profile.firstName} ${profile.lastName}`,
        'billing_details[phone]': profile.phoneNumber,
        'card[number]': card.number,
        'card[cvc]': card.cvc,
        'card[exp_month]': card.expMonth,
        'card[exp_year]': card.expYear,
        'key': 'pk_test_gpRZG9FqfabgAW9GuEDApxb500M5zns4uA',
      }
      const result = await axios({
        method: 'POST',
        headers: { 'content-type': 'application/x-www-form-urlencoded' },
        data: qs.stringify(data),
        url: 'https://api.stripe.com/v1/payment_methods',
      })
```

**Comment by mszczech01** [comment]
> A workaround:
> 
> ```js
>       const data = {
>         'type': 'card',
>         'billing_details[address][city]': address.city,
>         'billing_details[address][country]': address.country,
>         'billing_details[address][line1]': address.line1,
>         'billing_details[address][line2]': address.line2,
>         'billing_details[address][postal_code]': address.postalCode,
>         'billing_details[email]': profile.email,
>         'billing_details[name]': `${profile.firstName} ${profile.lastName}`,
>         'billing_details[phone]': profile.phoneNumber,
>         'card[number]': card.number,
>         'card[cvc]': card.cvc,
>         'card[exp_month]': card.expMonth,
>         'card[exp_year]': card.expYear,
>         'key': 'pk_test_gpRZG9FqfabgAW9GuEDApxb500M5zns4uA',
>       }
>       const result = await axios({
>         method: 'POST',
>         headers: { 'content-type': 'application/x-www-form-urlencoded' },
>         data: qs.stringify(data),
>         url: 'https://api.stripe.com/v1/payment_methods',
>       })
> ```

Wouldn't this solution involve sending readable sensitive information over a network?

**Comment by janoist1** [comment]
That’s why it has to go through SSL isn’t it?

**Comment by harshvitra** [comment]
Any other solutions to this ?

**Comment by saadali-esketchers** [comment]
Any update on this?

**Comment by grantgeorge** [comment]
I'm using version `8.0.0-beta.10`

This worked for me:

```
const paymentMethod = await stripe.createPaymentMethod({
        type: 'card',
        card: {
          number: params.number,
          cvc: params.cvc,
          expMonth: params.expMonth,
          expYear: params.expYear
        }
      });
```

**Comment by keyblade95** [comment]
I had the same issue. Solved by installing the last version:
```bash
yarn add tipsi-stripe@8.0.0-beta.10
```

**Comment by Jawad-LiftOff** [comment]
Was facing this issue in tipsi-stripe@8.0.0-beta.10 as well. Clearing react native cache while running the packager solved the issue
