### ISSUE TITLE
Android bundleRelease and assembleRelease don't work on beta.8

### ISSUE THREAD

**Issue by veso-i** [tipsi/tipsi-stripe#590]
On beta version 8 ./gradlew bundleRelease and ./gradlew assembleRelease do not work when buildTypes > release > minifyEnabled: true

**Comment by arnaud-zg** [comment]
Have you tried to give more memory to the Gradle JVM? You can add this environment variable `GRADLE_OPTS=-Xms512m -Xmx1024m`

**Comment by veso-i** [comment]
This fixed the issue! Thanks.
