### ISSUE TITLE
Support Direct Debit in PaymentMethods / SetupIntents

### ISSUE THREAD

**Issue by FlorianPfisterer** [tipsi/tipsi-stripe#591]
As of recently, Stripe [supports](https://stripe.com/docs/payments/sepa-debit-setup-intents) not only credit cards in their PaymentIntents API, but also SEPA direct debit (bank) accounts. However, there exist no methods to submit bank account details to Stripe (what's called [`stripe.confirmSepaDebitSetup`](https://stripe.com/docs/payments/sepa-debit-setup-intents#submit-payment-method) in their own JavaScript API). 

When can we expect support for creating direbt debit accounts PaymentMethods via the SetupIntent API in this framework? Thank you very much!

**Comment by FlorianPfisterer** [comment]
Any news on this?

**Comment by prakashsatani** [comment]
Hi@FlorianPfisterer, did you find any solution for this?

**Comment by FlorianPfisterer** [comment]
@prakashsatani Not really, we are using an embedded web view in the app now, which opens a SEPA web form website we implemented ourselves using the official Stripe.js SDK SEPA form (similar to [this example](https://github.com/stripe-samples/web-elements-sepa-debit-payment)).

The Stripe publishable key and so on are passed via query parameters to the site. Let me know if you have further questions about our solution, happy to help!
