### ISSUE TITLE
undefined is not an object (evaluating 'StripeModule.init') on iOS

### ISSUE THREAD

**Issue by nartydev** [tipsi/tipsi-stripe#596]
## Before I have submitted the issue 
[X ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ X] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ X] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ X] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I am on expo and react native, I have eject expo so I wanted to add the payments, I manually added the import on iOS, as well as the merchant id Apple, I took the example of tipsi stripe for payments with Apple Pay https://github.com/tipsi/tipsi-stripe/blob/master/example/src/scenes/ApplePayScreen.js (for Android I have not looked yet)

## Environment
* `tipsi-stripe` version: 7.5.1
* iOS or Android: iOS
* OS version: 12.4.3
* React-Native version: 0.59.8

## Links to logs and sources
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'StripeModule.init')]

My podfile : https://gist.github.com/nartydev/64010661ece44969d74b035a9f039534
My component : https://gist.github.com/nartydev/07acf7dde58e721004584d97f28487a5

![image](https://user-images.githubusercontent.com/16448382/70328781-253ac600-183a-11ea-9035-a88ac9a62930.png)

Thanks,

**Comment by lenichols** [comment]
+1 same issue im having... on the tipsi-stripe website it states to make a request using:

`const items = [{
  label: 'Whisky',
  amount: '50.00',
}, {
  label: 'Tipsi, Inc',
  amount: '50.00',
}]

const shippingMethods = [{
  id: 'fedex',
  label: 'FedEX',
  detail: 'Test @ 10',
  amount: '10.00',
}]

const options = {
  requiredBillingAddressFields: 'all',
  requiredShippingAddressFields: 'all',
  shippingMethods,
}

try {
  const token = await stripe.paymentRequestWithApplePay(items, options)

  // Client specific code
  // api.sendTokenToBackend(token)

  // You should complete the operation by calling
  stripe.completeApplePayRequest()
} catch (error) {
  // Or cancel if an error occurred
  // stripe.cancelApplePayRequest()
}`


[](https://tipsi.github.io/tipsi-stripe/docs/completeapplepayrequest.html)

**Comment by waleedkhan01** [comment]
I am having the same issue - I have tried manually linking tipsi-stripe by following [the guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) exactly, but continue to receive this error on ios.

**Comment by LivanDiaz** [comment]
----TypeError: undefines is not an object (evaluating 'StripeModule.init') ---- im getting the same error in IOS ... using expo-payments-stripe "version": "8.1.0" ...
in Android it works ....

**Comment by LivanDiaz** [comment]
@waleedkhan01 , @lenichols , @nartydev ... Hello, they finally found a solution to the issue ... it would be very helpful for me I still continue with the same error ... could you help me ??? Thank you ...

**Comment by Mr-Anonymous** [comment]
Did anyhow find a solution for this?
