### ISSUE TITLE
Android createSourceWithParams() redirect to "Open With" with two choices, one of them crash.

### ISSUE THREAD

**Issue by RiusmaX** [tipsi/tipsi-stripe#599]
## Before I have submitted the issue 
[X ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[X ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[X ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[X ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
When I try to launch a payment with createSourceWithParams(), at the time of the redirection, android offers me two identical applications (same package name) one works but the other causes a crash of the application.

Is there anything I didn't understand?

## Environment
* `tipsi-stripe` version: 7.5.1
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: Android 9
* React-Native version: 0.60.5
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version: 

## Links to logs and sources

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)
```
android {
    //...
    defaultConfig {
        //...
        manifestPlaceholders = [onesignal_app_id: "xxx",
                                onesignal_google_project_number: "xxx",
                                tipsiStripeRedirectScheme: "example"]
        //...
    }
    //...
}
```

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion: 28
* android.buildToolsVersion: 28.0.3
* android.defaultConfig.minSdkVersion: 16
* android.defaultConfig.targetSdkVersion: 28
* android.defaultConfig.multiDexEnabled (if exists): true

AndroidManifest.xml : 
```
<application
      android:launchMode="singleTop"
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <meta-data
        android:name="com.google.android.geo.API_KEY"
        android:value="xxx"/>
      <meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true" />
      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
      <activity android:name=".RedirectUriReceiver">
        <intent-filter>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:scheme="${tipsiStripeRedirectScheme}" tools:replace="android:scheme" />
        </intent-filter>
      </activity>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
            <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
        </intent-filter>
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="@string/fb_login_protocol_scheme" />
        </intent-filter>
      </activity>
      <provider android:authorities="com.facebook.app.xxx"
        android:name="com.facebook.FacebookContentProvider"
        android:exported="true" />
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <service
        android:name=".MainMessagingService"
        android:enabled="true"
        android:exported="true">
          <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
      </service>
    </application>
```

## Screenshots, GIFs (Must to have)
![Screenshot_1576576218](https://user-images.githubusercontent.com/10097331/70984798-6729fe80-20bb-11ea-98ba-e57c606d8dd6.png)

## Code To Reproduce Issue (Good To Have)
```
startPaymentWithSource = async () => {
    const params = {
      type: 'alipay',
      amount: 140,
      currency: 'EUR',
      returnURL: 'example://stripe-redirect'
    }

    try {
      const source = await stripe.createSourceWithParams(params)
      // App crash if i select one of the 2 app but not the other.
      console.tron.log(source)
    } catch (e) {
      console.tron.log(e)
    }
  }
```

**Comment by scaralfred** [comment]
Did you solve this?

**Comment by RiusmaX** [comment]
Yes, I've tried with in `AndroidManifest.xml` :

`
<activity android:name="com.gettipsi.stripe.RedirectUriReceiver">
        <intent-filter>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:host="alipay" android:scheme="${tipsiStripeRedirectScheme}" tools:replace="android:scheme" />
        </intent-filter>
</activity>
`
