### ISSUE TITLE
Native component for "TPSCardField" does not exist

### ISSUE THREAD

**Issue by GregTheGreek** [tipsi/tipsi-stripe#60]
I followed the instructions from the readme and got this. Only thing i can think of is I didn't move the folder into the correct location? I put it under the <Porject Name> directory.

**Comment by OrianeInMoon** [comment]
@GregTheGreek can you be more precise about the step to "reset the RN server" please?

**Comment by isnifer** [comment]
@OrianeInMoon `npm start -- --reset-cache`

**Comment by OrianeInMoon** [comment]
(`npm start -- --reset-cache` did not works for me)

**Comment by isnifer** [comment]
@OrianeInMoon why? How did you start RN server typically?

**Comment by PaulBelloc** [comment]
Same issue, restarting did not fix it.
```

"devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^4.19.1",
    "eslint-plugin-flowtype": "2.35.0",
    "eslint-plugin-import": "2.7.0",
    "eslint-plugin-jsx-a11y": "6.0.2",
    "eslint-plugin-prettier": "2.1.2",
    "eslint-plugin-react": "^7.12.3",
    "eslint-plugin-react-native": "3.0.1",
    "flow-bin": "0.52.0",
    "flow-typed": "2.1.5",
    "husky": "0.14.3",
    "jest": "20.0.4",
    "jest-expo": "25.0.0",
    "prettier": "1.5.3",
    "react-native-scripts": "1.11.1",
    "react-test-renderer": "16.2.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "color": "1.0.3",
    "expo": "^26.0.0",
    "lodash": "4.13.1",
    "moment": "2.13.0",
    "native-base": "2.4.1",
    "react": "16.3.0-alpha.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz",
    "react-native-easy-grid": "^0.2.0",
    "react-native-elements": "^0.19.1",
    "react-navigation": "1.5.0",
    "tipsi-stripe": "^7.4.0"
  }
}
```

**Comment by bramski** [comment]
I have no idea why this issue was closed with no resolution. A google search to determine why my android app is crashing led me here.

**Comment by jamesl1001** [comment]
I solved this by running `pod install` inside my ios folder (not sure this was necessary because my problem was with Android), then `yarn start --reset-cache` **and** rebuilding the app with `react-native run-android`.

**Comment by jameslevine** [comment]
> I solved this by running `pod install` inside my ios folder (not sure this was necessary because my problem was with Android), then `yarn start --reset-cache` **and** rebuilding the app with `react-native run-android`.

This did not work for me.
