### ISSUE TITLE
Inconsistent response Android <> iOS for `paymentRequestWithCardForm()` call

### ISSUE THREAD

**Issue by meko-deng** [tipsi/tipsi-stripe#603]
## The problem
The promise's response to `paymentRequestWithCardForm()` is inconsistent across Android and iOS, is this intentional? On Android, the card details are in the `card` object while the on iOS, the details are in the `cardDetails` object

**Android:**
<img width="464" alt="Screen Shot 2020-01-14 at 2 49 11 PM" src="https://user-images.githubusercontent.com/19173529/72378347-313e6100-36df-11ea-8c2a-3553f882899c.png">

**iOS:**
<img width="495" alt="Screen Shot 2020-01-14 at 2 48 38 PM" src="https://user-images.githubusercontent.com/19173529/72378427-57fc9780-36df-11ea-8041-2ef5892a1655.png">

## Environment
* `tipsi-stripe` version: 7.5.1
* iOS or Android: iOS & Android

**Comment by mikedizon** [comment]
@meko-deng is this still happening for you? I'm not seeing a `cardDetails` object, but I do get an extra boolean field `used` in Android.

**Comment by meko-deng** [comment]
This doesn't seem to be a problem anymore! Closing
