### ISSUE TITLE
React native autolinking

### ISSUE THREAD

**Issue by archieherbias** [tipsi/tipsi-stripe#604]
## Before I have submitted the issue 
[/] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[/] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[/] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[/] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
The docs describe how to link automatically using `react-native link` command and manually as describe. But with the new react-native it already have the auto-linking and when you build your app an error message would appear:

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - tipsi-stripe (to unlink run: "react-native unlink tipsi-stripe")
```

The build is still fine and it works as it is but maybe you can support the feature of autolinking?

## Environment
* `tipsi-stripe` version: ^7.5.1
* iOS or Android: Both
* React-Native version: 0.61.5

## Screenshots, GIFs (Must to have)
<img width="1437" alt="Screen Shot 2020-01-16 at 11 23 16 AM" src="https://user-images.githubusercontent.com/9944872/72490601-9ebece80-3852-11ea-8d9c-78c7428c569c.png">

**Comment by alex-mironov** [comment]
any update here?

**Comment by ste001** [comment]
I was thinking the same, since I need to implement this in my app. The docs explicitly say to link it, so I'll probably do it anyway, but since RN 0.60 the autolinking should be implemented in this library.

**Comment by shawnFallon** [comment]
Has there been any updates on this?

**Comment by martimarkov** [comment]
Given this message: ```warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.```

Should this be reopened?
