### ISSUE TITLE
Apple Pay w/ Payment Intents API

### ISSUE THREAD

**Issue by Findiglay** [tipsi/tipsi-stripe#605]
Is it possible to use Apple Pay with the Payment Intents API or is it only currently implemented for the Charges API?

**Comment by alexpchin** [comment]
I believe you can use a combination of the stripe api and this library to achieve the result.

**Comment by guanhuay** [comment]
@alexpchin Hi Alex, by using stripe API, are you referring to using the [Payment Request Button](https://stripe.com/docs/stripe-js/elements/payment-request-button) (like wrapping it in a webview) or using[ stripe v3 ](https://stripe.com/docs/js/payment_request/can_make_payment#payment_request_can_make_payment-applePay) (like wrapping it in a webview as well)?

Thank you for your help and looking forward to hear from you :)

**Comment by Clonescody** [comment]
@guanhuay 
Hi Torres, I believe he's wondering the same thing as I am : 
Can you use the token created by paymentRequestWithNativePay() as a token for a paymentIntent ? 

Right now my backend is creating the PaymentIntent for me at the end of my user's subscription tunnel, however I have no idea on how to use that info for/with Apple Pay. 

I was following this guide, which looked exactly like what I needed : https://gist.github.com/mindlapse/72139f022d6e620e4f0d59dc50c1797e

but I can't figure it out.

Thanks for any help 🙏

**Comment by maxb94** [comment]
@Clonescody @guanhuay I'm wondering the same. The `tokenId` returned from  `stripe.paymentRequestWithNativePay` (on iOS) is able to create a `PaymentMethod` object via

`const paymentMethod = await stripe.createPaymentMethod({ card: tokenId })`

However attempting to use this PaymentMethod along with the client secret returned from my backend with

```
const intent = await stripe.confirmPaymentIntent({
        paymentMethod,
        clientSecret,
        savePaymentMethod: false,
})
```

results in the stripe error

```
"message": "Missing required param: payment_method_data[card][number]."
"type": "invalid_request_error"
```

**Comment by guanhuay** [comment]
> @Clonescody @guanhuay I'm wondering the same. The `tokenId` returned from `stripe.paymentRequestWithNativePay` (on iOS) is able to create a `PaymentMethod` object via
> 
> `const paymentMethod = await stripe.createPaymentMethod({ card: tokenId })`
> 
> However attempting to use this PaymentMethod along with the client secret returned from my backend with
> 
> ```
> const intent = await stripe.confirmPaymentIntent({
>         paymentMethod,
>         clientSecret,
>         savePaymentMethod: false,
> })
> ```
> 
> results in the stripe error
> 
> ```
> "message": "Missing required param: payment_method_data[card][number]."
> "type": "invalid_request_error"
> ```

I didn't dig into this problem, but I would suggest you debug[ this function](https://github.com/tipsi/tipsi-stripe/blob/7ae12e4f8ef86e65bde032c5ffd32f5ee80c7e86/ios/TPSStripe/TPSStripeManager.m#L388) on the ios side to get more info, and customize it for your own benefit.

BTW, looks like this repo is no longer maintain, and we probably should wait for official support from Stripe.
