### ISSUE TITLE
Experimental branch moved into master?

### ISSUE THREAD

**Issue by trag-stripe** [tipsi/tipsi-stripe#608]
Hi @cybergrind - when will the SCA work go from the experimental branch back into master? Many users think Tipsi is out of date and miss that the updates are there but hiding over in https://github.com/tipsi/tipsi-stripe/tree/experimental

**Comment by cybergrind** [comment]
@trag-stripe, unfortunately, it isn't going to happen (at least in this repo). There are no people to support it, tests aren't working and no one from the community really finished it with all requirements done. Tipsi itself moved away from RN and not going to pay for any open source development any time soon (and I'm not working for them too).
So, probably, the best course of action is to hard-fork this repo under the Stripe umbrella, hire/assign someone to support it or change the standards (by removing requirements for tests) and run it under community-only development. I still have merge access to this repo, so I can put any type of notification here or in npm package or provide any other help.

**Comment by juddey** [comment]
@trag-stripe I'm probably going to regret this, but:
* it seems like _a lot_ of effort has already gone in to make this library work, and it would be a shame to lose it
* are there a set of standards that Stripe have for their open-source libraries (and does this include compliance?)
* is there anyone from Stripe available/assigned to helping with this sort of endeavor?

**Comment by juddey** [comment]
@cybergrind Thanks for your work! When you say:
>   no one from the community really finished it with all requirements done.

Pardon the silly question, but what is still to be done?

**Comment by cybergrind** [comment]
@juddey the most important thing is to fix tests and make them working at least on the local machine.
it was partially done for android but never finished. It is 100% possible but requires deep delving into appium testing stack and probably will require updates to some of the underlying libraries.
From my previous experience, this probably will take 2+ weeks of full-time work and I really understand that no-one has the intention to spend so much time on that.
All current changes in `experimental` branch were implemented without tests and were tested only manually. That would be a viable solution only if we had some dedicated QA person who would test/approve changes before merging but we don't have any.

**Comment by juddey** [comment]
Thanks for the update @cybergrind; that makes sense now. I've taken a look at the appium tests and am thinking about a way forward. I'm planning to write some detox tests so they may have some use.

**Comment by fbartho** [comment]
@cybergrind has accurately summarized. Getting CI working has been a lift that was beyond what those of us who were coding on the experimental branch were able to donate to the OSS community at the time.

Ideally, Stripe would fold this project in internally, as the new changes to their API make it extremely difficult for the OSS community to build an easy to test API wrapper. -- This would be much easier if this project was part of Stripe's OSS offerings just like their underlying iOS/Android SDKs. This would also fold in nicely so that the unit tests for this project can take advantage of Stripe's official backend test servers.

**Comment by cybergrind** [comment]
@fbartho you and Dave and rest of contributors have done a great job, no issues with it at all! 
I have no desire to leave the project to die so I believe we will solve this in one or another way.

**Comment by cybergrind** [comment]
Right now we still can publish all updates in the experimental branch and release in beta releases as before. 
So there are no major issues with tests that prevent us from publishing updates. It is just less testing, stability guarantees and no ability to release stable release.
