### ISSUE TITLE
Unable to handle the error when stripe does not support some cards

### ISSUE THREAD

**Issue by vyasishanatc194** [tipsi/tipsi-stripe#609]
Unable to handle the error when stripe does not support some cards,
I entered Card number '6200 0000 0000 0005' ,
Month: 04/2025
CVC: 1214.

Unable to create token, error logs that Your card was not supported by Stripe with CardException.

How to handle this kind of error when Stripe does not support some cards. It working fine with Debug mode, but give Crash in release mode.

* `tipsi-stripe` version: ^7.5.1
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: Mac Mojave 10.14.4
* React-Native version: 0.60.4
* (Android only) `com.google.firebase:firebase-core` version: 17.2.2
* (Android only) `com.google.android.gms:play-services-base` version: 17.0.0

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion : 28
* android.buildToolsVersion : --
* android.defaultConfig.minSdkVersion : 16
* android.defaultConfig.targetSdkVersion : 28
* android.defaultConfig.multiDexEnabled (if exists) : true

- Video : 
[https://www.loom.com/share/0315ae1cd3d34fb1b07c2f2b2cb4ec0d
](https://www.loom.com/share/0315ae1cd3d34fb1b07c2f2b2cb4ec0d
)

`var regex = /(\d+)/g;
      var cardNumberNew =
        cardNumber.split(/[0-9]+/).join("") +
        cardNumber
          .match(regex)
          .join("")
          .trim();
      var expirationNew = expiration.split("/");
      var month = expirationNew[0];
      var year =
        expirationNew[1].split(/[0-9]+/).join("") +
        expirationNew[1].match(regex).join("");
      const params = {
        // mandatory
        number: cardNumberNew,
        expMonth: parseInt(month),
        expYear: parseInt(year),
        cvc: cardCvv
      };
      if (!this.state.isConnected) {
        this.showErrorMessage(
          getLangValue(strings.NO_INTERNET_CONNECTION, this.state.currentLang)
        );
        return;
      }
      this.setState({ loading: true });
      let token = undefined;
      try {
        token = await stripe.createTokenWithCard(params);
      } catch (error) {
        if (error && error !== undefined) {
          if (error.message && error.message !== undefined) {
            this.setState({ errExpiration: error.message });
          } else {
            this.showErrorMessage(
              getErrorValue(errors.YOUR_CARD_DECLINED, this.state.currentLang)
            );
          }
        } else {
          this.showErrorMessage(
            getErrorValue(errors.YOUR_CARD_DECLINED, this.state.currentLang)
          );
        }
      }`

![gochiso](https://user-images.githubusercontent.com/5519279/73058163-0dd29d80-3eb9-11ea-9795-801a8bf769d9.gif)

**Comment by fbartho** [comment]
Please check out the `tipsi-stripe@8.0.0-beta.10` release to see if this improves things for you!
