### ISSUE TITLE
We need to upgrade our react-native version and add support for androidx which is currently not supported.

### ISSUE THREAD

**Issue by HiteshR90** [tipsi/tipsi-stripe#612]
## Before I have submitted the issue 
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
We need to upgrade our react-native version and add support for androidx which is currently not supported.

## Environment
* `tipsi-stripe` version: 8.0.0-beta.9
* iOS or Android: Android
* React-Native version: 0.61.5

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion = 28
* android.buildToolsVersion = 28.0.3
* android.defaultConfig.minSdkVersion = 21
* android.defaultConfig.targetSdkVersion = 28

**Comment by bramski** [comment]
What's broken for androidx?

**Comment by toddpi314** [comment]
On androidX projects, one major one is support for `package android.support.annotation does not exist` missing.

**Comment by luskin** [comment]
@toddpi314 would you mind expanding on how to use jetifier to easily resolve these? We are on RN 0.63.3 (which should by default use Jetifier i think) and when we try and build we get the following errors from `tipsi-stripe`:

```
> Task :tipsi-stripe:compileReleaseJavaWithJavac FAILED
/Users/runner/work/1/s/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/RedirectUriReceiver.java:5: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/runner/work/1/s/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:3: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/runner/work/1/s/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/util/Converters.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/runner/work/1/s/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/GoogleApiPayFlowImpl.java:5: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/runner/work/1/s/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/Errors.java:3: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/runner/work/1/s/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/PayFlow.java:5: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/runner/work/1/s/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/StripeModule.java:7: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/runner/work/1/s/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/StripeModule.java:8: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/runner/work/1/s/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/dialog/AddCardDialogFragment.java:9: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
/Users/runner/work/1/s/node_modules/tipsi-stripe/android/src/main/java/com/gettipsi/stripe/OpenBrowserActivity.java:7: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
```

**Comment by nikolaigeorgie** [comment]
@luskin to answer your question, run `npx jetify` from your project root directory.

Also, assuming your running the latest tipsi-stripe `7.5.3` it may be helpful to ensure your minSdkVersion, androidx version ect.. matches https://github.com/stripe/stripe-android#installation

Lastly, I had issues with tipsi-stripe for auto linking, even on a fresh project. I manually linked this dependency.
