### ISSUE TITLE
confirmCardPayment via client_secret and payment method token from back-end

### ISSUE THREAD

**Issue by 0x01Brain** [tipsi/tipsi-stripe#615]
## The problem

Hi, I am working on an app that I would like to add Stripe to it, and I found this library thank you for this I've been looking for it. But I have a question regarding confirming a payment using a client secret and payment method token that is retrieved from back-end after creating payment intent in the back-end. Does this package has this feature yet?
I read the documentation but I did not find any.

This is what I am trying to achieve something similar to the Stripe Javascript SDK:
https://stripe.com/docs/js/payment_intents/confirm_card_payment#stripe_confirm_card_payment-existing

**Comment by cybergrind** [comment]
@0x01Brain if it is not part of the experimental branch and https://github.com/tipsi/tipsi-stripe/blob/experimental/website/docs-md/paymentIntents.md, probably it isn't supported yet.

**Comment by 0x01Brain** [comment]
@cybergrind Thank you, could it be supported in the future?

**Comment by cybergrind** [comment]
@0x01Brain right now we don't have any active development on this library, so I cannot give any ETA or plans.

**Comment by 0x01Brain** [comment]
@cybergrind okay thank you for replying, closing this.
