### ISSUE TITLE
ios: install without cocoa pods

### ISSUE THREAD

**Issue by fabriziomoscon** [tipsi/tipsi-stripe#62]
Hi guys,
thank you for the amazing project. I am using it successfully in my Android react-native build.
Now I am working on the ios and I am facing huge problems making all the dependencies right, not just because of the installation of this library.
As far as I understand using pods requires you to open xcode from `proj.xcworkspace` rather than `proj.pbxproj`, which for a newbie is a gotcha that doesn't come naturally. Then it is not clear which files need to be committed and which ones need to be ignore. There are debates in the community itself about this topic. And I find out that other react-native libraries don't use pods - at least the other 12 I am using - it seems to me that the installation of these other libraries conflicts with this one, because every time I execute a `react-native link *` command the code doesn't compile anymore. I received lots of different errors, but the last error I can see today is:

```bash
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

It would be great if you could shed some lights and help me understand what would be the best practise to include this library on iOS so that it doesn't conflict with others, or at least is intuitive for newbies.

Thanks again

**Comment by dmytrozavgorodniy** [comment]
Hi @fabriziomoscon! Let's try reinstall pod dependencies:
1. Open your ./ios folder
2. Remove ./Podfile.lock file, ./Pods folder
3. Run pod install

**Comment by fabriziomoscon** [comment]
Eventually I made it work. I had to:
- `react-native unlink tipsi-stripe`
- installed the other library pods
- `react-native link tipsi-stripe`
- add `pod 'Stripe', '~> 9.2.0'` to the `Podfile`
- `cd ios && pod install`

I will reopen if I find something not working.

Thanks

**Comment by jeremypagley** [comment]
@fabriziomoscon I cannot get this app working on iOS for anything is there a way you could help me see how you got it working?
