### ISSUE TITLE
After using paymentRequestWithCardForm several times, its not working anymore and loading endless

### ISSUE THREAD

**Issue by ElliDy** [tipsi/tipsi-stripe#621]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I create a cardToken with tipsi stripe method paymentRequestWithCardForm. Because of developping I need to do this several times. After around 10 times, the card token creation is not possible anymore. It gives me no error, but the form is showing me an endless loading circle.

## Environment
* tipsi-stripe version: ^7.5.1
* iOS or Android: Android
* React-Native version: 0.60.4
* com.google.firebase:firebase-core version: 16.0.0
* com.google.android.gms:play-services-base version: 16.0.0

## Screenshots, GIFs 
![Screenshot_20200306-085005_chargeIT everywhere](https://user-images.githubusercontent.com/3762504/76063497-1faf6200-5f88-11ea-9204-9a477ef4e34b.jpg)

## Code To Reproduce Issue
`const token = await stripe.paymentRequestWithCardForm();`

**Comment by m-arch** [comment]
Hello, found any solution for the issue? 
I am not even being prompted for the card info. In debug mode everything is working fine but in testflight pressing the payment button (ie calling `stripe.paymentRequestWithCardForm()`) is not even opening the card info form.

**Comment by marioDropStudio** [comment]
@cybergrind what is the solution to this problem?

**Comment by m-arch** [comment]
Just upgrade to newer version of tipsi-stripe
