### ISSUE TITLE
Diners Club card number (16 digits) support

### ISSUE THREAD

**Issue by ferranuap** [tipsi/tipsi-stripe#624]
## The problem
The Diners Club card number (16 digits) example from the stripe test cards is invalid when introducing it into PaymentCardTextField. Works fine for 14 digit format.
[Stripe URL containing test cards](https://stripe.com/docs/testing)

## Environment
* `tipsi-stripe` version: 8.0.0-beta.9
* iOS or Android: iOS (not tested on android)
* React-Native version: 0.61.4

## Screenshots, GIFs (Must to have)
<img width="346" alt="Screenshot 2020-03-23 at 16 32 36" src="https://user-images.githubusercontent.com/62557950/77333579-f03c7b80-6d23-11ea-9577-6d7ff4fda6c1.png">

Thanks for your support.

**Comment by Mavenic** [comment]
@ferranuap how do you managed to remove zipCode from PaymentCardTextField ?

**Comment by DanGDroid** [comment]
@ferranuap 
hi
if you enter the other Diners card number in the test cards - do succeed confirmation
i got an error card declined
