### ISSUE TITLE
Stripe does not build in XCode 11.4

### ISSUE THREAD

**Issue by mikedizon** [tipsi/tipsi-stripe#625]
## The problem

Stripe pod does not build in XCode 11.4

## Environment
* `tipsi-stripe` version: 7.5.1

## Links to logs and sources
https://github.com/stripe/stripe-ios/pull/1524

**Comment by ekegodigital** [comment]
Same here

**Comment by arinconc** [comment]
Help please!

**Comment by JB-CHAUVIN** [comment]
Same here

**Comment by landreup** [comment]
Same here

**Comment by mikedizon** [comment]
Using 19.0.1 doesn’t compile either.

**Comment by auseika** [comment]
We're stuck because of this. And the package doesn't look like properly maintained.

Any solutions?

**Comment by mikedizon** [comment]
Might be a few weeks before they get around to updating it. Might need to fork it. v14 uses some classes that are deprecated in v19. No easy solution. 

If it goes beyond today without an update from the maintainers, best solution might be to abandon tipsi and roll your own solution.

**Comment by mikedizon** [comment]
https://github.com/stripe/stripe-ios/pull/1534

https://github.com/mikedizon/stripe-ios/tree/fix_xcode_11.4_v14.0.0

**Comment by azai91** [comment]
How do we go about using your version?

**Comment by mikedizon** [comment]
Until it gets approved, you'll have to clone the repo, switch branches and then add it to your project manually.

**Comment by zachandblue** [comment]
Same issue here.  Pretty big blocker for me.  Can the folks at Tipsi let us know if/when we might expect a fix?

**Comment by quachdev** [comment]
I updated my `Podfile.lock` Stripe version from `14.0.0` to `14.0.1` and ran `pod update Stripe` and was able to get rid of the error.

Hopefully the repo gets updated soon. Is this still being maintained?

**Comment by cybergrind** [comment]
@quachdev probably you need to use beta version it doesn't have hardcoded Stripe version.
The latest beta is  tipsi-stripe@8.0.0-beta.9

**Comment by cybergrind** [comment]
Also I've updated original podspec to use it.

**Comment by maxkomarychev** [comment]
@cybergrind where one can find code that is being published as beta version?

**Comment by cybergrind** [comment]
@maxkomarychev it is located in experimental branch

**Comment by augustosamame** [comment]
> I updated my `Podfile.lock` Stripe version from `14.0.0` to `14.0.1` and ran `pod update Stripe` and was able to build my app again.
> 
> Hopefully the repo gets updated soon. Is this still being maintained?

Looking at stripe-ios Github issues, maintainers have fixed this and backported it to Stripe 14.0.1.
Manually modifying 'Podfile.lock' and running 'pod update Stripe' totally worked for me. Don't know about the downvote.
