### ISSUE TITLE
[Request] Please add types for Typescript

### ISSUE THREAD

**Issue by johnnyasantoss** [tipsi/tipsi-stripe#626]
Maybe a good start would be https://github.com/DefinitelyTyped/DefinitelyTyped?

**Comment by acro5piano** [comment]
Duplication: https://github.com/tipsi/tipsi-stripe/pull/384

I'm using the type definitions of this PR by creating `.d.ts` file in my project.

**Comment by johnnyasantoss** [comment]
I have created manually too but I'm sure with time it will be holding types that don't match the actual JS API of this package. :/

**Comment by acro5piano** [comment]
Yes sure. Official type definitions are much better.

**Comment by cybergrind** [comment]
There are no reasons for them to match the actual js API without having some way to test it, which requires a test demo application in TS.
If someone can do that - probably we could merge it after that.

**Comment by acro5piano** [comment]
So you mean there should be a demo of written in TypeScript?
If you think we add the demo, I'll try to create it.

**Comment by cybergrind** [comment]
Yes, @acro5piano . Demo app in TS + TS definitions.

**Comment by acro5piano** [comment]
Which are you expecting?

- Add ts to the current example project
- Add a new example project such as `example-ts`

 In either case, we can use the type definitions proposed here https://github.com/tipsi/tipsi-stripe/pull/384

**Comment by cybergrind** [comment]
Probably the second variant.
It should use max number of methods and should assemble for android and ios platforms without lot of steps.
