### ISSUE TITLE
Update Stripe-ios Pod version

### ISSUE THREAD

**Issue by jlariza** [tipsi/tipsi-stripe#631]
Stripe pod does not compile on Xcode 11.4. According to https://github.com/stripe/stripe-ios/issues/1525 they already fixed the issue in stripe ` 14.0.1`. However, when I tried to install this pod version, I got the following error:

```
tipsi-stripe (from `../node_modules/tipsi-stripe`) was resolved to 7.5.1, which depends on
      Stripe (~> 14.0.0)
```

Please, Update Stripe Pod dependency to be able to compile using Xcode latest version.

Thank you

**Comment by bramski** [comment]
Fixed by: https://github.com/tipsi/tipsi-stripe/pull/563

**Comment by jlariza** [comment]
I just saw #625 so I am closing this issue
