### ISSUE TITLE
Stripe iOS SDK - Incompatible block pointer types sending

### ISSUE THREAD

**Issue by aevaldas** [tipsi/tipsi-stripe#632]
## The problem
XCode 11.4 broke the stripe pod
https://stackoverflow.com/questions/60841771/stripe-ios-sdk-incompatible-block-pointer-types-sending

Stripe pods v16 does not have a fixed version.

## Environment
* `tipsi-stripe` version: 8.0.0-beta.9

## Possible solution
Upgrade Stripe pod to v17.0.3.

`tipsi-stripe.podspec`:

 ` s.dependency 'Stripe', '>= 16.0.7'` -> ` s.dependency 'Stripe', '>= 17.0.3'`

**Comment by kyytiPetteri** [comment]
Getting same error

**Comment by alexfoxy** [comment]
I also have this issue. Stripe pod version 19.0.1 is meant to fix it.

**Comment by aevaldas** [comment]
`v14.0.1`, `v15.0.2`, `v17.0.3`, and `v19.0.1` Stripe pods have these fixes

**Comment by nescroft** [comment]
I was getting the same error with tipsi-stripe@7.5.3

Changing the tipsi-stripe podspec file like this seems to have fixed it for me
s.dependency 'Stripe', '>= 14.0.1' -> s.dependency 'Stripe', '>= 15.02'
