### ISSUE TITLE
need property "metadata" for createSourceWithParams as in stripe js sdk

### ISSUE THREAD

**Issue by AnuragTiwari1** [tipsi/tipsi-stripe#636]
## The problem
i am using createSourceWithParams for alipay and on web we have something like this
const { source, error } = await stripe.createSource({
        type: 'alipay',
        amount: amount * 100,
        currency,
        redirect: {
          return_url: 'some url'
        },
        metadata: {
          ...apiData,
          wsToken: "someToken"
        }
      })
but createSourceWithParams does not accept "metadata"

**Comment by AnuragTiwari1** [comment]
i looked around docs and found the stripe-android already supports it so i have patched it if anyone intrested can look here
https://github.com/vrlab-tech/tipsi-stripe

**Comment by ShawnWu33** [comment]
Same issue encountered, And I think your solution would put IOS part works fine
