### ISSUE TITLE
Cannot able to generate the token for Android

### ISSUE THREAD

**Issue by Renish-Vrinsofts** [tipsi/tipsi-stripe#637]
## The problem
Cannot able to generate the token for Android using stripe.createTokenWithCard() method.
The execution is not reaching there.

## Environment
* `tipsi-stripe` version: ^7.5.3
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: 7.0
* React-Native version: 0.60.5

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion : rootProject.ext.compileSdkVersion
* android.buildToolsVersion : 28.0.3
* android.defaultConfig.minSdkVersion : 16
* android.defaultConfig.targetSdkVersion : 28
* android.defaultConfig.multiDexEnabled : true

**Comment by Renish-Vrinsofts** [comment]
Still the problem is exists in my project, please anyone reply on how to generate the token for android

**Comment by fbartho** [comment]
@Renish-Vrinsofts -- We are working on tipsi-stripe@8.0.0-beta in the #experimental branch if you want to take a look.

But here's my reply to a similar issue:
>All the `*Token*` APIs are severely deprecated by Stripe (in person, I asked their developer advocates about this last July). Stripe wants you to move to the `SetupIntent | PaymentIntent` family of APIs -- (`PaymentMethod` also still works in many cases -- just not related to `*Token*` APIs).
>
>I can't test any of them that might still work.
>
>Some of the APIs were deleted by the minimum stripe-ios/stripe-android versions that we have to use in `8.0.0-beta.*` -- this actually broke or removed some codepaths in methods that otherwise still exist in tipsi-stripe.
>
>As a result -- I'm not currently planning on fixing any issues related to them, and I think it's probably going to be very difficult to do so, if it's even possible.

Because of these changes, we're probably not going to fix the 7.x branch, so you may need to investigate the `*Intent` series of APIs from Stripe and plan your migration.
