### ISSUE TITLE
xCode 11.4 Problem Stripe

### ISSUE THREAD

**Issue by lillogoal** [tipsi/tipsi-stripe#638]
Hi,
there is a problem with last version of xCode 11.4, stripe version used by tipsi-stripe has a bug.

Incompatible block pointer types sending '__strong STPAPIResponseBlock _Nonnull' (aka 'void (^__strong)(__strong ResponseType, NSHTTPURLResponse *__strong, NSError *__strong)') to parameter of type 'void (^)(STPSource *__strong, NSHTTPURLResponse *__strong, NSError *__strong)'

This solved: https://github.com/stripe/stripe-ios/issues/1525

**Comment by cybergrind** [comment]
@lillogoal from what I can see it was solved in 14.0.1 and we've updated it here https://github.com/tipsi/tipsi-stripe/blob/master/tipsi-stripe.podspec#L22

**Comment by lillogoal** [comment]
Solved thanks @cybergrind
