### ISSUE TITLE
Unable to supply custom font

### ISSUE THREAD

**Issue by pmcguane** [tipsi/tipsi-stripe#64]
Hi
I was looking at a way to achieve a custom font with the standard card form, but haven't been able to work this out using the theme options
Thanks

**Comment by itsmepetrov** [comment]
Hi @pmcguane 

Could you please provide your example?

**Comment by isnifer** [comment]
@pmcguane did you solve this issue?

**Comment by pmcguane** [comment]
Hi, I was never able to work this out
