### ISSUE TITLE
Remove Zip code field on <PaymentCardTextField />

### ISSUE THREAD

**Issue by AntonOtaner** [tipsi/tipsi-stripe#641]
## Before I have submitted the issue 
[ x ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ x ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ x ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ x ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
As of later versions of Stripe (I am using version 19.0.1), there is a new Zipcode field in <PaymentCardTextField />. I looked around Stripe documentation on how to get it removed but it seems like I have to dig into the Stripe pods to get this working. Is there a way to get this working with the tipsi-stripe?

I read about it in the [Stripe docs](https://stripe.dev/stripe-ios/docs/Classes/STPPaymentCardTextField.html#/c:objc(cs)STPPaymentCardTextField(py)postalCodeEntryEnabled).

## Environment
* `tipsi-stripe` version: 8.0.0-beta.10
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: 13.4.1
* OS version: 10.15.4
* React-Native version: 0.62

## Screenshots, GIFs (Must have)
![Screen Shot 2020-04-23 at 6 24 04 PM](https://user-images.githubusercontent.com/54222574/80155397-a5668b80-858f-11ea-844e-8ebea2278f03.png)

**Comment by axelinternet** [comment]
Stuck on this issue too. Problematic for our users as they have most likely never had to enter their zip code in a credit card field before. 

@AntonOtaner have you found any workaround in the meantime? I tried to find a way to at least localize the field but with no success

**Comment by nchase** [comment]
@axelinternet FYI we patched this in our code. Our patch looked something like this:

```patch
--- a/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.m
+++ b/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.m
@@ -24,6 +24,7 @@ - (instancetype)initWithFrame:(CGRect)frame {
         _isFirstResponder = NO;
         _paymentCardTextField = [[STPPaymentCardTextField alloc] initWithFrame:self.bounds];
         _paymentCardTextField.delegate = self;
+        _paymentCardTextField.postalCodeEntryEnabled = NO;
         [self addSubview:_paymentCardTextField];
         self.backgroundColor = [UIColor clearColor];
     }
```

**Comment by AntonOtaner** [comment]
No success on my end @axelinternet but I think trying the solution of @nchase is the best possible solution up to now.

**Comment by axelinternet** [comment]
@nchase Thanks that works great, at least for our specific case.

**Comment by fbartho** [comment]
@nchase -- if you want to patch this against the `experimental` branch, I'd be happy to ship this as part of `beta.11`?

**Comment by An0r4k** [comment]
@fbartho Is this released as part of beta.11?

**Comment by nchase** [comment]
@An0r4k based on the code, I don't think this made it into beta.11, but it's also not clear if there's some change there that makes this unnecessary.

Sorry I didn't see this comment for so many months, @fbartho. See this PR, if this is still useful: https://github.com/tipsi/tipsi-stripe/pull/690

**Comment by pynner** [comment]
Tossing the keyword Postal Code for all the non-americans out there, took me a hot second to find this thread.

**Comment by bc-bane** [comment]
why was this closed?
