### ISSUE TITLE
stripe.confirmPaymentIntent is deprecated in 8.0.0-beta.10,   Is there an updated plan?

### ISSUE THREAD

**Issue by wenjianli92** [tipsi/tipsi-stripe#642]
![image](https://user-images.githubusercontent.com/29296692/80202540-5d5f6b80-8658-11ea-9548-64019d38c83f.png)

**Comment by cybergrind** [comment]
@wenjianli92 you're looking on JS documentation. tipsi-stripe is using SDK methods and I don't see any deprecations in android API, so, probably it is ok

**Comment by alexanderwallin** [comment]
It looks like they (Stripe) are calling it [`confirmPayment` on Android](https://github.com/tipsi/tipsi-stripe/blob/8.0.0-beta.11/android/src/main/java/com/gettipsi/stripe/StripeModule.java#L372) and [`confirmPaymentIntentWithParams:completed:` on iOS](https://github.com/tipsi/tipsi-stripe/blob/8.0.0-beta.11/ios/TPSStripe/TPSStripeManager.m#L383). Indeed a little confusing. I guess it makes sense this library aligns more with the native SDKs than with the JS one.
