### ISSUE TITLE
Apple Pay last item amount can't be 0

### ISSUE THREAD

**Issue by john-harding** [tipsi/tipsi-stripe#645]
## Before I have submitted the issue 
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
As of iOS 12.0, the last item in the array of items for Apple Pay (`paymentRequestWithNativePay`) can be 0.  This is the case in the stripe-ios 19.1.0 release, however, even after upgrading to this, it doesn't work.

tipsi-stripe appears to instead be using the function `canSubmitPaymentRequest` in file `./ios/TPSStripe/TPSStripeManager.m` on line `1185`.  The issue is on line `1201`:
https://github.com/tipsi/tipsi-stripe/blob/926fddf85329caa52414cbc21924cd29f6c684a9/ios/TPSStripe/TPSStripeManager.m#L1185

You can see here that stripe-ios is updated: https://github.com/stripe/stripe-ios/pull/1499/files#diff-6ce78242d6db3a6591d35c527d8dff93

## Environment
* `tipsi-stripe` version: 8.0.0-beta.10
* iOS or Android: iOS
* OS version: 13.3
* React-Native version: 0.61.5

## Code To Reproduce Issue (Good To Have)
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.
```
        const items = [
            {
                label: "Monthly subscription",
                amount: "10",
                type: "final",
            },
            {
                label: "My company",
                amount: "0",
                type: "final",
            },
        ];
        const options = {};

        stripe
            .paymentRequestWithNativePay(options, items)
            .then((result) => {
            })
            .catch((err) => {
                // always caught here saying amount must be greater than 0
                console.log(err);
            });
```

**Comment by jack828** [comment]
Hey, I had the same issue - not sure if you are still, but maybe this will help someone. 
I figured it out after cloning the repo locally and viewing the docs that way, as the ones on the site are not for v8.

I use this code for both apple and google pay - YMMV:
```js
  const totalPricePence = calculateTotalPrice(items)
  const totalPrice = (totalPricePence / 100).toFixed(2)
  const lineItems = items.map(({ name, price }) => {
    const itemPrice = (price / 100).toFixed(2)
    return {
      // Android
      description: name,
      currency_code: 'GBP',
      item_price: itemPrice,
      total_price: itemPrice,
      quantity: '1',
      // iOS
      label: name,
      amount: itemPrice,
      type: 'final'
    }
  })

  if (Platform.OS === 'ios') {
    lineItems.push({
      label: 'YourCompany Ltd',
      amount: totalPrice
    })
  }

  let token
  try {
    token = await stripe.paymentRequestWithNativePay(
      {
        // Android
        currency_code: 'GBP',
        total_price: totalPrice,
        line_items: lineItems,
        // iOS
        currencyCode: 'GBP',
        countryCode: 'GB'
      },
      lineItems // iOS
    )
```

**Comment by john-harding** [comment]
@jack828 hey thanks, but I want to set the last item to 0 for the purpose of subscriptions when there is no payment to be collected today.  So there is unfortunately no workaround aside from patching the package itself right now.
