### ISSUE TITLE
Incompatible pod versions in 8.0.0-beta.10 example

### ISSUE THREAD

**Issue by eduludi** [tipsi/tipsi-stripe#651]
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Documentation point to the Podfile in the `example` app, but there `platform` is set to `:ios, '9.0'`. Thats is incompatible with `Stripe >= 19.0.1` that requires platform to be at least `:ios, 10.0`

This causes an error during install, as there is no higher version that `17.0.3` available for iOS 9:

```
[!] CocoaPods could not find compatible versions for pod "Stripe":
  In Podfile:
    Stripe (~> 17.0.0)

    tipsi-stripe (from `../node_modules/tipsi-stripe`) was resolved to 8.0.0-beta.10, which depends on
      Stripe (>= 19.0.1)

Specs satisfying the `Stripe (~> 17.0.0), Stripe (>= 19.0.1)` dependency were found, but they required a higher minimum deployment target.
```

## Environment

* `tipsi-stripe` version: 8.0.0-beta.10
* iOS or Android: iOS
* OS version: 13.5
* React-Native version: 0.62

## Links to logs and sources

- Since 18.0.0 "Dropped support for iOS 9. Please continue to use 17.0.2 if you need to support iOS 9" : https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md#1800-2019-10-04
- https://github.com/stripe/stripe-ios/issues/1455#issuecomment-562672935

**Comment by sgript** [comment]
Same issue, did you fix this in the end @eduludi?

**Comment by iDuuck** [comment]
Which Cocoapods version do you use? A colleague of mine had the same problem, and I think he fixed it using the `pod update` command.

**Comment by spyrocash** [comment]
@eduludi Any update?
