### ISSUE TITLE
How to use on the web ios android without ejecting?

### ISSUE THREAD

**Issue by kopax** [tipsi/tipsi-stripe#655]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem

I am reading 
 - https://docs.expo.io/versions/latest/sdk/payments/
 - https://github.com/tipsi/tipsi-stripe/

It seems that I need to eject, while I really don't want to eject.

IF stripe use an http API, why do I need more than just an http client like fetch, that does not require to eject?

## Environment
* `tipsi-stripe` version: latest
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: ios / android /web
* OS version:  debian stretch
* React-Native version:  expo sdk 36

How to use on the web ios android without ejecting?

**Comment by kopax** [comment]
@cybergrind may I know why this was tagged as https://github.com/tipsi/tipsi-stripe/labels/wont-fix ?

Was this implemented yet properly for expo application already?

**Comment by cybergrind** [comment]
@kopax Stripe team is going to provide their own RN library, and we all want to move to it ASAP
this library is here to stay only for historical reasons
