### ISSUE TITLE
build.gradle requires an update with latest Android Studio (4.0) - Workaround Included

### ISSUE THREAD

**Issue by 99darwin** [tipsi/tipsi-stripe#656]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Briefly describe the issue you are experiencing (or the feature you want to see added to `tipsi-stripe`). 
Tell us what you were trying to do and what happened instead. 

After updating Android Studio to the latest build `tipsi-stripe` caused compilation errors, throwing the following:

```
* What went wrong:
A problem occurred configuring project ':tipsi-stripe'.
> Could not resolve all artifacts for configuration ':tipsi-stripe:classpath'.
   > Could not find org.jetbrains.trove4j:trove4j:20160824.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
     Required by:
         project :tipsi-stripe > com.android.tools.build:gradle:4.0.0 > com.android.tools.build:builder:4.0.0 > com.android.tools:sdk-common:27.0.0
```

## Workaround
After a lot of digging, I found that the maven dependency repository had been moved. Changing the `tipsi-stripe` `build.gradle` under `node_modules` to the following configuration resolves the issue. 

```
buildscript {
  repositories {
    google()
    // ADD THIS
    jcenter()
    // REMOVE THIS
    // mavenCentral()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:4.0.0'
  }
}
```
## Android Studio Info

```
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins:
```

## Environment
* `tipsi-stripe` version: `^8.0.0-beta.10`
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: Android Nougat / macOS 10.15.4
* React-Native version: `~0.61.5`
* (Android only) `com.google.firebase:firebase-core` version: `17.4.2`
* (Android only) `com.google.android.gms:play-services-base` version: `18.0.0`

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!
[Error log](https://gist.github.com/99darwin/dfbfb4251c04c7b9e3caba5b224bdb33)

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/99darwin/dfbfb4251c04c7b9e3caba5b224bdb33#file-build-gradle)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion `28`
* android.buildToolsVersion `4.0.0`
* android.defaultConfig.minSdkVersion `21`
* android.defaultConfig.targetSdkVersion `28`
* android.defaultConfig.multiDexEnabled (if exists) `true`

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

## Code To Reproduce Issue (Good To Have)
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by fbartho** [comment]
Does anybody have a link to documentation from one of?:
- Google
- Android Studio
- Gradle
- Maven or Apache

I'm concerned about backwards compatibility issues for people that use older versions of Android Studio.

If this change works on older Android Studio or older Gradle Versions, then I'd be thrilled to review a PR implementing this change

**Comment by fbartho** [comment]
One link: https://blog.bintray.com/2015/02/09/android-studio-migration-from-maven-central-to-jcenter/
