### ISSUE TITLE
Cannot test Apple Pay on real devices but it works in emulator

### ISSUE THREAD

**Issue by nhht77** [tipsi/tipsi-stripe#659]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Briefly describe the issue you are experiencing (or the feature you want to see added to `tipsi-stripe`). 
Hi,

I cannot test Apple Pay in real devices. We test internally with many Iphone but it just did not work. 

We try to follow these docs on make it working:
1. https://tipsi.github.io/tipsi-stripe/docs/running-apple-pay-on-a-real-device.html
2. https://developer.apple.com/library/archive/ApplePay_Guide/Configuration.html#//apple_ref/doc/uid/TP40014764-CH2-SW1

3. replace `.paymentRequestWithApplePay()`  with `paymentRequestWithNativePay()`.

## Environment
* platform :ios, '10.0'
* pod 'Stripe', '~> 19.0.1'
*  "react-native": "0.61.5",
* "tipsi-stripe": "^8.0.0-beta.10",

## Links to logs and sources
No LOG

## Screenshots, GIFs (Must to have)

**On emulator:**

![working-version](https://user-images.githubusercontent.com/35263094/84381328-8aa8ae80-abf1-11ea-9458-ab30746cfbd5.gif)

**On real device:**

![broken-version](https://user-images.githubusercontent.com/35263094/84381348-95634380-abf1-11ea-9af0-4fb167c3c442.gif)

## Code To Reproduce Issue (Good To Have)

```
  handleApplePayPress = async () => {
    const price = this.state.activity_center_schedule.price
    const items = [{
      label: this.state.activity_center_schedule.activity_name,
      amount: price.toString(),
    }, {
      label: 'Buffalo',
      amount: price.toString(),
      // amount: this.state.price,
    }]

    // const shippingMethods = [{
    //   id: 'fedex',
    //   label: 'FedEX',
    //   detail: 'Test @ 10',
    //   amount: '10.00',
    // }]

    const options = {
      requiredBillingAddressFields: ['all'],
      // requiredShippingAddressFields: ['phone', 'postal_address'],
      // shippingMethods,
    }

    try {
      const token = await stripe.paymentRequestWithApplePay(items, options)
      console.log("Token is=>", token)
      // Client specific code
      // api.sendTokenToBackend(token)


      // You should complete the operation by calling
      await stripe.completeApplePayRequest()
      await this.handleTokenToWeb(token.tokenId);
    } catch (error) {
      // Or cancel if an error occurred
      // stripe.cancelApplePayRequest()
    }

    // const token = await stripe.paymentRequestWithApplePay(items, options)
    // const token = await stripe.paymentRequestWithNativePay( options,items)
    // console.log("Token is=>", token)

  }
```

**UI code**:
```
 <TouchableOpacity
          onPress={() =>
            Platform.OS == 'ios' ?
              this.handleApplePayPress() :
              null
          }
          style={[styles.firstPaymentBox, { backgroundColor: '#ffffff' }]}>
            <View style={{ justifyContent: 'flex-end' }}>
            <Image
              style={styles.firstPaymentBoxImage}
              source={require('../../images/payment/apple-pay-icon.png')}
              resizeMode={'contain'}
            />
            <Text style={[styles.firstPaymentBoxText, { color: '#999999' }]}>
              {I18n.t('paymentScreen.tapToConfirm')}
            </Text>
          </View>
        </TouchableOpacity>
```

**Comment by intsgraveris** [comment]
It could be, that on real device you have higher iOS => 
Some research with multiple simulators running different iOS versions:

iPhone 8 - iOS 11
✅ Apple Pay works in Simulator as expected.

iPhone 8 - iOS 12
⚠️ Apple Pay confirmation modal appears, click "Pay with Passcode", errors out with "Cancelled by User".

iPhone 8 - iOS 13
🔴 Apple Pay confirmation modal never appears. "Cancelled by User" error is thrown after 1-2 seconds.

**Comment by raviganwal** [comment]
Facing the same issue, How did you fix this?

**Comment by VinitBhavsar** [comment]
Check that your region / country supported for apple pay or not?
Also for test environment.
In emulator for ios 13.6 it work, but for my device 13.6 it's not working.
Emulator Region : US

https://developer.apple.com/apple-pay/sandbox-testing/
https://support.apple.com/en-us/HT207957

Check This @raviganwal

**Comment by Sterlingryan** [comment]
Did anyone fix this please ?

**Comment by prakashsatani** [comment]
Hi @nhht77, 
I'm facing the same issue, how did you fix it? can you please give guidance?

**Comment by VinitBhavsar** [comment]
Check that your region / country supported for apple pay or not?
Also for test environment.
In emulator for ios 13.6 it work, but for my device 13.6 it's not working.
Emulator Region : US

https://developer.apple.com/apple-pay/sandbox-testing/
https://support.apple.com/en-us/HT207957

Check This @prakashsatani

**Comment by prakashsatani** [comment]
Yes I changed the region to Australia and using client Id in my device but It's still not working
