### ISSUE TITLE
Pre-fill card number, cvc and expiration

### ISSUE THREAD

**Issue by rheilgm** [tipsi/tipsi-stripe#66]
is it possible to pre-fill those fields automatically? 
say for example: 
- scan a card using https://github.com/Kerumen/react-native-awesome-card-io
- then call stripe.paymentRequestWithCardForm(options)
- with params `const options = {data: {cardNumber: 'xxxxxxxxxxx', cvc: '123', expiry: '10/20'}}`

**Comment by itsmepetrov** [comment]
Hi @rheilgm, currently `stripe.paymentRequestWithCardForm` does not support pre-fill card params.

But you can use your own view with [`<PaymentCardTextField />`](https://github.com/tipsi/tipsi-stripe#paymentcardtextfield-component) which support setup [initial params](https://github.com/tipsi/tipsi-stripe#initial-params).

> To set inital params you can use <instance>.setParams(params) method which is available via ref. For example, if you’re using another library to scan your user’s credit card with a camera, you can assemble that data into an object and set this property to that object to prefill the fields you’ve collected.

**Comment by balesz** [comment]
Sadly the PaymentCardTextField can't set initial params on Android. No setParams function in PaymentCardTextField.android.js. Please add setParams support to Android too! Thanks a lot.

**Comment by itsmepetrov** [comment]
Hi @balesz 

Yes, `PaymentCardTextField` on Android currently does no support `setParams`, but we have plan to replace `CreditCardEntry` with the official [input widget](https://stripe.com/docs/mobile/android#card-input-widget) and also add support for `setParams`.

**Comment by rheilgm** [comment]
@itsmepetrov thanks for the info
yeah figured out i have to use <PaymentCardTextField /> for this, but i really like that card animation  on stripe.paymentRequestWithCardForm :)

will it be possible to support this kind of feature in future releases?

**Comment by itsmepetrov** [comment]
@rheilgm 

As I said in the previous issue #17:

> We use [STPAddCardViewController](https://stripe.github.io/stripe-ios/docs/Classes/STPAddCardViewController.html) from Stripe iOS API for drawing this view and we can change only those parameters which are provided by Stripe API.

Unfortunately, `STPAddCardViewController` does not support to pre-fill card fields. It has ability to specify [`prefilledInformation`](https://stripe.github.io/stripe-ios/docs/Classes/STPUserInformation.html) field, which can contain only `email`, `phone` and `billingAddress`.

To support pre-fill card fields we will need to write our own `AddCardViewController`, but we do not have plans for that in the near future.

**Comment by itsmepetrov** [comment]
@rheilgm 

I think the better way is to create the same issue in [`stripe-ios`](https://github.com/stripe/stripe-ios). If the Stripe team adds support for this kind of feature, then we can add it too without any problems.

Feel free to reopen this issue if you have any other suggestions.
