### ISSUE TITLE
Apple pay redirects to Apple Wallet not to Apple pay on Real device

### ISSUE THREAD

**Issue by Bogdan0810** [tipsi/tipsi-stripe#665]
## The problem
If I click Apple pay button, it should redirects to Apple pay but it redirects to Apple wallet on Real device.
But it works properly on simulator.
## Environment
* `tipsi-stripe` version: 7.5.3
* iOS or Android: iOS
* OS version: iOS 13
* React-Native version: 0.61.5

![Screen Shot 2020-07-16 at 3 55 38 PM](https://user-images.githubusercontent.com/59910709/87730500-d1ec0700-c77c-11ea-8875-478a31f3c21c.png)

Here is my code:
    const items = [
      {
        label: "Order",
        amount: 10,
      },
    ];

    const shippingMethods = [
      {
        id: "fedex",
        label: "FedEX",
        detail: "Order",
        amount: 10,
      },
    ];

    const options = {
      requiredBillingAddressFields: ["all"],
      requiredShippingAddressFields: ["phone", "postal_address"],
      shippingMethods,
    };

const token = await stripe.paymentRequestWithNativePay(options, items);

**Comment by VinitBhavsar** [comment]
I've ios 13.6, and it's giving me error This device is not supported for apple pay.
But deviceSupportsApplePay() this return true.

**Comment by jinkalr-itpath** [comment]
Hello Guys

I am facing same issue, its redirecting to wallet
@Bogdan0810 please let me know if you got solution for this

**Comment by Bogdan0810** [comment]
Hey @jinkalr-itpath ,

Could you provide your codebase?

**Comment by jinkalr-itpath** [comment]
Sorry I didn't get you

**Comment by Bogdan0810** [comment]
Just part of your code I mean. From setting options to request etc.

**Comment by jinkalr-itpath** [comment]
tipsi-stripe version: 7.5.3
React-Native version: 0.60.5

`
          stripe.setOptions({
                publishableKey: STRIPE_PUBLISHABLE_KEY,
                merchantId: 'merchant.com.bruyouapp.bruyou.test',
            });
            stripe.openNativePaySetup();
            try {
                stripe.deviceSupportsNativePay()
                    .then(response => {
                        if (response == true) {
                            stripe.canMakeApplePayPayments()
                                .then(responsed => {
                                    if (responsed == true) {
                                        const items = [{
                                            label: 'my drink',
                                            amount: '5.00',
                                        }]
                                        const options = {

                                        }
                                        try {
                                            stripe.paymentRequestWithApplePay(items, options)
                                                .then(token => {
                                                   //token
                                                    // You should complete the operation by calling

                                                    stripe.completeNativePayRequest()
                                                });


                                        } catch (error) {

                                            var err = error
                                            // Or cancel if an error occurred
                                            stripe.cancelNativePayRequest()
                                        }
                                    }
                                });
                        }
                    });
            }
            catch (error) {

                var err = error
            

            }`

**Comment by Bogdan0810** [comment]
Please remove
 `stripe.openNativePaySetup();` 

It will work. :)

**Comment by jinkalr-itpath** [comment]
Have tried :(

**Comment by jinkalr-itpath** [comment]
Then its opening nothing

**Comment by Bogdan0810** [comment]
Oh. `paymentRequestWithApplePay` has been deprecated.
Please use `paymentRequestWithNativePay` with shipping method.
`
   const items = [
      {
        label: "Order",
        amount: amountDue.toFixed(2).toString(),
      },
    ];

    const shippingMethods = [
      {
        id: "fedex",
        label: "FedEX",
        detail: "Order",
        amount: amountDue.toFixed(2).toString(),
      },
    ];

   const options = {
      requiredBillingAddressFields: ["all"],
      requiredShippingAddressFields: ["phone", "postal_address"],
      shippingMethods,
    };

      const token = await stripe.paymentRequestWithNativePay(options, items);
...
...

`

**Comment by jinkalr-itpath** [comment]
const options = {
requiredBillingAddressFields: ["all"],
requiredShippingAddressFields: ["phone", "postal_address"],
shippingMethods,
};

this is required?
As my customer don't want to ask for shipping thing.

**Comment by Bogdan0810** [comment]
I am not sure why your customer doesn't want. :)
But I think it should be required.
Please try it on your side for making sure if it's the reason.

**Comment by jinkalr-itpath** [comment]
ok, and is there any reason why I am not getting response from canMakeNativePayPayments method?

**Comment by Bogdan0810** [comment]
I used it like this.

`const supported = await stripe.deviceSupportsNativePay();`
`const canMakeApplePayPayments = await stripe.canMakeNativePayPayments();`
`if(supported && canMakeApplePayPayments) { ... }`

And always get response! But not sure if it will work on your side.

**Comment by jinkalr-itpath** [comment]
ok thanks for you help !!

**Comment by Bogdan0810** [comment]
You are welcome. Let me know if it works.

**Comment by VinitBhavsar** [comment]
In my case isNativePayment supported is true and canMakeNativePayment false, then I do some R&D then I found that Country does not support Apple Pay Yet. Not even for Sandbox Testing.

Emulator default set to US.

**Comment by jinkalr-itpath** [comment]
Hello @VinitBhavsar 

I am in India, in Ahmedabad
I am getting `canMakeNativePayPayments` as false 
So if I want to test then what I need to do can you please guide me. I need to submit today Anyhow.
Thanks in advance

**Comment by VinitBhavsar** [comment]
@jinkalr-itpath Have you tried by VPN? I'm just suggesting . 
I have tried but not worked.

**Comment by jinkalr-itpath** [comment]
So I just wanted to know if this package will work or not?

**Comment by VinitBhavsar** [comment]
For us, It can be only tested in simulator only. Not in device.

**Comment by jinkalr-itpath** [comment]
ok but the client is in US still not working, Can I get your contact number or something so I can explain you easily, As I have tried for two weeks but no success :(

**Comment by VinitBhavsar** [comment]
https://support.apple.com/en-in/HT207957
https://developer.apple.com/apple-pay/sandbox-testing/

**Comment by jinkalr-itpath** [comment]
It should work in US with a sandbox?

**Comment by VinitBhavsar** [comment]
> It should work in US with a sandbox?

Yes

**Comment by jinkalr-itpath** [comment]
if Client needs to take care of any steps ?
