### ISSUE TITLE
How to do payment with card details saved in backend?

### ISSUE THREAD

**Issue by mulayam1005** [tipsi/tipsi-stripe#670]
## Before I have submitted the issue 
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I have some confusion with methods

I want to use credentials saved in backend and i can do like this:

const params = {
  // mandatory
  number: '4242424242424242',
  expMonth: 11,
  expYear: 17,
  cvc: '223',
  // optional
  name: 'Test User',
  currency: 'usd',
  addressLine1: '123 Test Street',
  addressLine2: 'Apt. 5',
  addressCity: 'Test City',
  addressState: 'Test State',
  addressCountry: 'Test Country',
  addressZip: '55555',
}

const token = await stripe.createTokenWithCard(params)

then after getting token, how will i do payment?

## Environment
* `tipsi-stripe` ^7.5.3: 
* Last `tipsi-stripe` ^7.5.3 where the issue was not reproduced (if applicable): 
* iOS or Android: iOS
* OS version: 13.5
* React-Native version: 0.60.5
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version: 

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion
* android.buildToolsVersion
* android.defaultConfig.minSdkVersion
* android.defaultConfig.targetSdkVersion
* android.defaultConfig.multiDexEnabled (if exists)

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

## Code To Reproduce Issue (Good To Have)
 Assume that i have details for card from backend and i want to do payment with prefilled information.

**Comment by cybergrind** [comment]
Hi, @mulayam1005 ! It isn't part of the functionality of this library, but we have a brief description of how it can be achieved here https://github.com/tipsi/tipsi-stripe/blob/experimental/website/docs-md/createCardOrSubscription.md

**Comment by mulayam1005** [comment]
ok thanks
