### ISSUE TITLE
Instacrash on Android

### ISSUE THREAD

**Issue by thezenvan** [tipsi/tipsi-stripe#673]
## The problem
Added tipsi-stripe to a React-Native project and ran it, it crashes on launch (doesn't reach main screen). [Here is the logcat excerpt](https://gist.github.com/thezenvan/a5ead2d9a81edf724f56cfc191e8d5d4)

## Environment
* `tipsi-stripe` version: 7.5.3
* Android version: 9
* React-Native version: 0.62.2
* (Android only) `com.google.firebase:firebase-core` version: 11.8.0
* (Android only) `com.google.android.gms:play-services-base` version: 11.8.0

## Links to logs and sources
[logcat](https://gist.github.com/thezenvan/a5ead2d9a81edf724f56cfc191e8d5d4)

* [android/build.gradle](https://gist.github.com/thezenvan/76c66743a09a10957b6f917d975140a8)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion 29
* android.buildToolsVersion 29.0.2
* android.defaultConfig.minSdkVersion 24
* android.defaultConfig.targetSdkVersion 29

**Comment by CharlyPoppins** [comment]
Try : https://github.com/idehub/react-native-google-analytics-bridge/wiki/Solution-for-Android-build-failure-issues

```
1. added `googlePlayServicesVersion=12.0.1` to `gradle.properties` (I guess it's unnecessary)

2. added following to `android/build.gradle`:
 allprojects {
    repositories {
    //start here
    configurations.all {
 resolutionStrategy.eachDependency { DependencyResolveDetails details ->
   def requested = details.requested
       if (requested.group == 'com.google.android.gms') {
          details.useVersion '12.0.1'
       }
       if (requested.group == 'com.google.firebase') {
          details.useVersion '12.0.1'
         }
       }
     }
    //end
     jcenter()
       maven {
         url "https://maven.google.com"
       }
     }
 }
```

worked for me

**Comment by debianw** [comment]
@CharlyPoppins This worked for me with React Native 0.60.5. But just confirmed that this is not working on the new React Native 0.63.2
