### ISSUE TITLE
Stripe officially said that it does not support Tipsi Stripe. 

### ISSUE THREAD

**Issue by greatapps** [tipsi/tipsi-stripe#677]
## Before I have submitted the issue I have read the SDK 10 times.
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
There is no way where I can upload the Identity Documents Stripe and link them to the Bank account person Id. There is no way to create Customer and Create a Bank Account. Why it's not even mentioned. Also I have contacted Stripe and they said they don't even know any such library did exists so clearly they don't support Tipsi.

## Environment
* `tipsi-stripe` version Latest: 
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: 
* OS version: 
* React-Native version: Issue is with React Native
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version: 

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion
* android.buildToolsVersion
* android.defaultConfig.minSdkVersion
* android.defaultConfig.targetSdkVersion
* android.defaultConfig.multiDexEnabled (if exists)

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

## Code To Reproduce Issue (Good To Have)
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by cybergrind** [comment]
@greatapps if it isn't part of native SDK, probably there is no place for it in `tipsi-stripe` too. `tipsi-stripe` is just a wrapper around native SDKs so we don't use any js SDK calls here.

> Howver I have tried to integrate that in React native but it didn't worked as it needs some sort of Browser Enviroment.

You can use mobile browser if you need it. But it is out of scrope for current library
