### ISSUE TITLE
[Android] Replace CreditCardEntry with the official input widget

### ISSUE THREAD

**Issue by itsmepetrov** [tipsi/tipsi-stripe#68]
Since `Stripe` introduced the official  [input widget](https://stripe.com/docs/mobile/android#card-input-widget), we need to get rid off external `CreditCardEntry` library.

Also, we need to add support for [`setParams`](https://github.com/tipsi/tipsi-stripe#initial-params) (like on iOS).

Related to #66

**Comment by paynd** [comment]
Got [problem](https://github.com/stripe/stripe-android/issues/250) with internal widget animation/

**Comment by hannta** [comment]
Is there any updates to this? Switching to official Strip input widget would help a lot, no need to maintain own android input UI etc.

**Comment by sregg** [comment]
Any news on this?
