### ISSUE TITLE
currentlyFocusedField is deprecated and will be removed in a future release.

### ISSUE THREAD

**Issue by preflower** [tipsi/tipsi-stripe#680]
## Before I have submitted the issue 
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
when i use PaymentCardTextField's component, console error: currentlyFocusedField is deprecated and will be removed in a future release.
so i hope it be updated use currentlyFocusedInput

## Environment
* `tipsi-stripe` version: ^8.0.0-beta.10
* React-Native version: 0.63.0

## Code To Reproduce Issue (Good To Have)
<PaymentCardTextField />

**Comment by Dastan4r** [comment]
Same issue

**Comment by rkrueger11** [comment]
Any progress on this?
