### ISSUE TITLE
PaymentCardTextField Android loose focus on first touch - opens and closes keyboard

### ISSUE THREAD

**Issue by DanGDroid** [tipsi/tipsi-stripe#682]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

###  `PaymentCardTextField` looses focus on first touch
I am using `PaymentCardTextField` to collect card info.
When i first focus on the TextInput: keyboard opens and closes right away
only after a second touch/focus the keyboard stayes open

see Demo:
![key](https://user-images.githubusercontent.com/10976856/91983397-47636500-ed34-11ea-8858-95c466d86638.gif)

## Environment
* `tipsi-stripe` version: 8.0.0-beta.10
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 124.98 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 22.0.1, 23.0.1, 23.0.3, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-23 | Android TV ARM EABI v7a, android-23 | Android TV Intel x86 Atom, android-23 | Android Wear ARM EABI v7a, android-23 | Android Wear Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Android TV Intel x86 Atom, android-24 | ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-25 | Android Wear ARM EABI v7a, android-25 | Android Wear Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-25 | Google Play Intel x86 Atom, android-26 | Android Wear Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-P | Google APIs Intel x86 Atom
      Android NDK: 16.1.4479499
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Code To Reproduce Issue (Good To Have)
```javascript
  render() {
    const { name, holderInputState, cardInputEnabled } = this.state;
    return (
      <View style={styles.main}>
        <View
          style={[
            styles.frameView,
            {
              borderColor: holderInputState === 'error' ? '#B51D29' : '#313131',
            },
          ]}>
          <Image
            source={require('../../Images/holder_avatar.png')}
            style={styles.avatar}
          />
          <TextInput
            autoFocus
            returnKeyType={'next'}
            autoCapitalize={'words'}
            selectionColor={'#F36F21'}
            style={styles.inputStyle}
            numberOfLines={1}
            autoComplete={'off'}
            autoCorrect={false}
            allowFontScaling={false}
            value={name ? name : ''}
            onChangeText={this.setName}
            onBlur={() =>
              this.props.setPaymentParams({ holderName: this.state.name })
            }
            onSubmitEditing={() => {
              if (!_.isEmpty(this.state.name)) {
                this.paymentCardInput && this.paymentCardInput.focus();
              }
            }}
            placeholder={I18n.t('AddPayment_CardholdersName')}
            placeholderTextColor={'#ADADAD'}
            underlineColorAndroid={'transparent'}
          />
        </View>
        <PaymentCardTextField
          ref={ref => {
            this.paymentCardInput = ref;
          }}
          style={styles.addCardView}
          cursorColor={'#F36F21'}
          textErrorColor={'#B51D29'}
          placeholderColor={'#929292'}
          accessible={false}
          onParamsChange={this.handleFieldParamsChange}
          numberPlaceholder="XXXX XXXX XXXX XXXX"
          expirationPlaceholder="MM/YY"
          cvcPlaceholder="cvc"
          disabled={!cardInputEnabled}
          enabled={cardInputEnabled}
        />
        {renderFramedView(
          undefined,
          <Text style={styles.disclaimerText}>
            {I18n.t('stripe_add_card_disclaimer')}
          </Text>,
          { marginTop: 8 },
        )}
      </View>
    );
  }

  handleFieldParamsChange = (valid, params) => {
    this.props.setPaymentParams({ valid, params });
  };
```

**Comment by Donhv** [comment]
i think we should use CreditCardForm

**Comment by DanGDroid** [comment]
i would like to have customization as much as possible

**Comment by Donhv** [comment]
It will be more trustworthy for the user.

**Comment by Osamasomy** [comment]
I have  similar problem with PaymentCardTextField  in IOS. not focusing on CardNumber.
or its crash the app on IOS build.
any Help?

**Comment by DanGDroid** [comment]
@cybergrind 
can you provide any explanation for closing?

**Comment by cybergrind** [comment]
@DanGDroid Stripe team now has their own RN library, and we don't have any resources to continue support for this library.
