### ISSUE TITLE
Google Pay line items do not show when testing in emulator

### ISSUE THREAD

**Issue by jcohenho** [tipsi/tipsi-stripe#688]
## Before I have submitted the issue 
[✓] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[✓] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[✓] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[✓] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Briefly describe the issue you are experiencing (or the feature you want to see added to `tipsi-stripe`). 
Tell us what you were trying to do and what happened instead. 

After integrating a Google Pay button in my app using `paymentRequestWithNativePay(options, items)`, there are no line items or a price shown in the Google Pay pop-up modal. I have created my options correctly as defined here in the documentation for [paymentRequestWithNativePay()](https://tipsi.github.io/tipsi-stripe/docs/paymentrequestwithandroidpay.html).

![Screen Shot 2020-10-05 at 9 50 00 AM](https://user-images.githubusercontent.com/912154/95109337-55205780-06f1-11eb-8afa-d4dc25efb1e2.png)

Note: I'm aware that the app may need to be approved first for some things to work, but as it is now, after clicking 'continue' I can successfully complete test charges via Stripe with this Google Pay modal. I'm just confused why no pricing or line items are displaying at all. 

## Environment
* `tipsi-stripe` version: 8.0.0-beta.10
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: 
* React-Native version: ~0.61.4
* (Android only) `com.google.firebase:firebase-core` version: 16.0.7
* (Android only) `com.google.android.gms:play-services-base` version:  com.google.android.gms:play-services-wallet:18.0.0

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion
* android.buildToolsVersion
* android.defaultConfig.minSdkVersion
* android.defaultConfig.targetSdkVersion
* android.defaultConfig.multiDexEnabled (if exists)

## Screenshots, GIFs (Must to have)
![Screen Shot 2020-10-05 at 9 50 00 AM](https://user-images.githubusercontent.com/912154/95109337-55205780-06f1-11eb-8afa-d4dc25efb1e2.png)

## Code To Reproduce Issue (Good To Have)
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by jcohenho** [comment]
@cybergrind Why was this closed without any explanation?

**Comment by cybergrind** [comment]
@jcohenho I'm sorry, I couldn't comment on all 200 closed issues. Stripe now has their own RN library and we want to encourage everyone to use it.

**Comment by jcohenho** [comment]
Oh that’s wonderful I had no idea. Thanks for letting me know.

**Comment by zhahaoyu** [comment]
Hi @cybergrind could you provide the link to the stripe official version? I couldn't find it.

**Comment by ljesus** [comment]
> Hi @cybergrind could you provide the link to the stripe official version? I couldn't find it.

same
