### ISSUE TITLE
Create subscriptions with Google Pay

### ISSUE THREAD

**Issue by Clonescody** [tipsi/tipsi-stripe#689]
## Before I have submitted the issue 
[ x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I did my integration with tipsi-stripe for my app, but I am getting rejected by Google Pay for the following reason : 

```
The Google Pay API doesn’t support digital goods based on our Terms of Service - which requires that the purchases be for non-digital goods on Android. Purchases with the Google Pay API must be for physical goods and services that can be consumed outside of the application. For your use case we recommend In-App Billing. 
```

I am indeed selling a service with recurring payments, however I thought that Stripe was handling this and not Google Pay. 

## Environment
* `tipsi-stripe` version: 8.0.0-beta.10
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: Happens on store validation
* React-Native version: 0.63.3
* (Android only) `com.google.firebase:firebase-core` version: 16.0.7
* (Android only) `com.google.android.gms:play-services-base` version: 
* (Android only) `com.google.android.gms:play-services-wallet` version: 18.0.0

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!

* [ios/Podfile](https://gist.github.com/link_to_podfile)

My podfile : 
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MyApp' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```
* [android/build.gradle](https://gist.github.com/link_to_podfile)

My build.gradle : 
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        firebaseVersion = "17.0.0"
        googlePlayServicesVersion = "18.0.0"
        googlePlayServicesVisionVersion = "17.0.2"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

```
For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion : 29
* android.buildToolsVersion : 29.0.2
* android.defaultConfig.minSdkVersion : 21
* android.defaultConfig.targetSdkVersion : 29
* android.defaultConfig.multiDexEnabled (if exists)

## More infos on the issue

What I am doing in my payment flow for native payments : 

- Use `paymentRequestWithNativePay()` to retrieve a token.
- Send that token to `createPaymentMethod()` so I can get a usable token.
- Send that second token to my backend so I can create my Subscriptions, and reference the Customer.

Everything is working fine in dev mode, with ANDROID_MODE = "test" I get the Google Pay screen, my backend replies well, and everything is created on Stripe Dashboard. 

Uploading my builds to the **Google Play Console** works fine, I can also distribute them to my team, but the "Integration" part of **Google Pay** is my issue. I am aware that the Google Pay team must "validate" my first payment ( as stated in [the doc](https://tipsi.github.io/tipsi-stripe/docs/google-pay.html) ), however I'm getting the issue I added at the top but have no clue on how to fix this.

Thanks by advance guys 🙏

**Comment by cybergrind** [comment]
@Clonescody hi. apparently, you cannot sell in-app subscriptions via google payment and should use in-app billing.
tipsi-stripe doesn't support it, probably you need google something like "react native google in-app subscription"
I found https://www.npmjs.com/package/react-native-iap but probably there are some better solutions.

**Comment by Clonescody** [comment]
Hi, thanks for the recommandation @cybergrind, I took a look at it but I'm not sure I can achieve what I'm looking for with this. 

I guess this issue can be closed if tipsi-stripe doesn't support it. It should be noted in the documentation thought, I worked with this module all the way thinking it could do it only to realize only at the end that it can't.
