### ISSUE TITLE
Map alread consumed - Android native crash (dev & release bundle...)

### ISSUE THREAD

**Issue by JB-CHAUVIN** [tipsi/tipsi-stripe#693]
## The problem
On Android only, when I type a number in the <PaymentCardTextField /> component, I have the following native crash : Map already consumed
![image](https://user-images.githubusercontent.com/8957878/96841292-e579ce80-144b-11eb-8c39-bfd487ac5eaa.png)
I tried in an empty component, so that's not because of my code. I am using the PaymentCardTextField component without overriding anything.

## Environment
* `tipsi-stripe` version: 8.0.0-beta.10 or8.0.0-beta.11 (tried both)
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable):  N/A
* iOS or Android: Any Android version
* React-Native version: 0.63.3
* (Android only) `com.google.firebase:firebase-core` version: 17.2.0
* (Android only) `com.google.android.gms:play-services-base` version: 16.1.0

For `Android`, please provide the following sections from `android/app/build.gradle`:
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"
        kotlinVersion = '1.3.61'

## Screenshots, GIFs (Must to have)
![ezgif-3-1f041fc3b0ad](https://user-images.githubusercontent.com/8957878/96841654-54572780-144c-11eb-93f6-9bf711989434.gif)

## Code To Reproduce Issue (Good To Have)
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.
`const Home = (p: Props) => {
  return <PaymentCardTextField />;
};`

**Comment by flobady** [comment]
Hello,
I have the exact same problem. Can you please guys help?
Thank you very much

**Comment by Ghya** [comment]
Same problem with the same configuration ... Do you have any clue ? Thank you !!!

**Comment by kyle-ssg** [comment]
@cybergrind Are you able to provide a bit of clarity here? I'm getting the same issue and it seems to have been closed without explanation.

**Comment by jp928** [comment]
@kyle-ssg @flobady 
Same here, I had worked out a workaround like below:

In the CreditCardFormOnChangeEvent.java
```
    private WritableMap serializeEventData() {
        WritableMap eventData = Arguments.createMap();
        try {
            eventData.putBoolean("valid", isValid);
            eventData.putMap("params", params);
        } catch (Exception e) {
            Log.d("Tipsi", "Exception --" + e);
            eventData.putMap("params", cloneParams(params));
        }

        return eventData;
    }

    private WritableMap cloneParams(WritableMap originParam) {
        WritableMap clonedParams = Arguments.createMap();
        clonedParams.putString("number", originParam.getString("number"));
        clonedParams.putString("expMonth", originParam.getString("expMonth"));
        clonedParams.putString("expYear", originParam.getString("expYear"));
        clonedParams.putString("cvc", originParam.getString("cvc"));

        return clonedParams;
    }
```

**Comment by pehagg** [comment]
We have the same exact issue. Why was this issue closed?

**Comment by smolster** [comment]
@cybergrind why did you close this issue?

**Comment by Aayush19** [comment]
Please Reopen this thread as this issue still exits

**Comment by muja555** [comment]
It worked after removing `react-native-reanimated` 🎉

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
