### ISSUE TITLE
framework not found Stripe3DS2  Error when I run the app in iOS 

### ISSUE THREAD

**Issue by amralkhayat** [tipsi/tipsi-stripe#694]
Error show to me when I run the app  tell me framework not found Stripe3DS2  after I have updated the pod I am using Xcode 12 and also appear in Xcode 11 
![Screen Shot 2020-10-26 at 2 42 07 AM](https://user-images.githubusercontent.com/33759960/97123629-66c7ae80-1735-11eb-9581-11fa36e987ec.png)

## Environment
* `tipsi-stripe` version: 20.1.1

* iOS 14&13: 
* OS version: 10.15.4

**Comment by tgensol** [comment]
I does not happen with 19.0.1, but It happens with 20

**Comment by CripyIce** [comment]
Same here... downgrading to version 19.0.1 did help.

**Comment by vishnuharidas** [comment]
Stripe recommends upgrading Cocoapods to 1.10 - https://github.com/stripe/stripe-ios/issues/1698#issuecomment-717564117

**Comment by Rana-Muhammad-Amir** [comment]
Have some problem, using -> pod 'Stripe', '19.0.1' did the trick.
