### ISSUE TITLE
NSPersonNameComponentsFormatter not supported in iOS 8.0

### ISSUE THREAD

**Issue by threesquared** [tipsi/tipsi-stripe#70]
I am getting the following error when trying to run my app on an iPhone 4s iOS 8.3 simulator:

```
dyld: Symbol not found: _OBJC_CLASS_$_NSPersonNameComponentsFormatter
  Referenced from: /Users/ben/Library/Developer/CoreSimulator/Devices/2C531502-13CE-4298-80A7-692D7661AFD4/data/Containers/Bundle/Application/15795C11-DE78-4662-AB4B-359CF99CCC45/MyAPP.app/MyAPP
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.3.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
 in /Users/ben/Library/Developer/CoreSimulator/Devices/2C531502-13CE-4298-80A7-692D7661AFD4/data/Containers/Bundle/Application/15795C11-DE78-4662-AB4B-359CF99CCC45/MyAPP.app/MyAPP
(lldb) 
```

It seems to be related to [this line](https://github.com/tipsi/tipsi-stripe/blob/master/ios/TPSStripe/TPSStripeManager.m#L368) as the app runs fine when it is removed and the [PersonNameComponentsFormatter](https://developer.apple.com/reference/foundation/personnamecomponentsformatter) seems to have a minimum sdk of 9.0+

Is there any chance this can be reworked to support iOS 8.0+ ? Related to #41

**Comment by itsmepetrov** [comment]
Hi @threesquared, thank you for your feedback. I think we can fix this issue on iOS 8.

@dmytrozavgorodniy please take a look.
