### ISSUE TITLE
Some Test Stripe cards are not working on Android with version ^8.0.0-beta.11

### ISSUE THREAD

**Issue by sureshgurunath12** [tipsi/tipsi-stripe#701]
We are using the stripe integration on our project, below is the version we are using.

    "tipsi-stripe": "^8.0.0-beta.11",

We use <PaymentCardTextField /> for the card input on the form.  "https://tipsi.github.io/tipsi-stripe/docs/paymentcardtextfield.html"

When using the PaymentCardTextField we are facing an issue that out of test cards provided from below link. 2223003122003222 and 6200000000000005 cards are not acceptable in android. It throws the validation error. It works fine on iOS. 
https://stripe.com/docs/testing

Can anyone help in some insights why only these 2 test cards are not working on Android.

**Comment by imcyee** [comment]
This is because tipsi stripe is using 'com.stripe:stripe-android:10.4.6' in android build.gradle. 
And the issue was fixed with stripe-android 14.5.0.
https://github.com/stripe/stripe-android/issues/2465

**Comment by imcyee** [comment]
Hi~ found out that tipsi-stripe depends on CreditCard entry which has outdated regex.
`static final String REGX_MC = "^5[1-5][0-9]{14}$"; // MC 16`

**Comment by imcyee** [comment]
I guess you are using the modal, tipsi depends on creditCardEntry that has outdated regex.

You can replace that library by folking tipsi-stripe, then replace:
CreditCardEntry with my fork,
In your tipsi-stripe/android/build.gradle:
```
dependencies {
 ....
// remove  implementation 'com.github.tipsi:CreditCardEntry:1.5.1'
 implementation 'com.github.imcyee:CreditCardEntry:1.5.5'
}
```

**Comment by imcyee** [comment]
Or you can use my fork. 
https://github.com/imcyee/tipsi-stripe/tree/experimental

Changelog:
- Replaced android creditCardInput to official Stripe.CardInputWidget
- Removed createTokenWithBankAccount
- Bump stripe-android from 10x to 14.5
- Fix invalid master card series 2, and UnionPay 67xx

Note:
- Behaviour change:  Previously, the `done` button will be disable, if any of the input is incomplete or wrong, now it will enable when the input is complete, but won't disable by itself if user makes any changes.

**Comment by imcyee** [comment]
Also found this library that wants to solve this problem: 
https://github.com/Agaweb/react-native-stripe
