### ISSUE TITLE
This library is deprecated. Please use the official Stripe's library. Don't create new issues or PRs

### ISSUE THREAD

**Issue by cybergrind** [tipsi/tipsi-stripe#708]
Apply here: https://app.smartsheet.com/b/form/b1a1053eaac7496eb0ae7892ebd68973

**Comment by joshua-hester** [comment]
I am guessing this is access to a Private Repo provided by the Stripe Dev team?

**Comment by scott-massey** [comment]
One of the engineers at my company reached out to Stripe and they said that their library is not ready and suggested this library got deprecated "early". I don't know enough about what's going on here to argue or anything, just reporting what I heard

**Comment by teamzz111** [comment]
Too early.

**Comment by Tinmania2018** [comment]
I haven't heard back from Stripe, @scott-massey did you use the form that Cybergrind mentioned in the OP?

**Comment by cybergrind** [comment]
We didn't have any update for 2 years so it was already dead. And I cannot recommend using something that outdated for financial operations.

If someone really wants to "undeprecate" it - you can start with PR that fixes CI, then we could decide what to do next :D

**Comment by NicholasBertazzonAga** [comment]
@cybergrind I made one if you're interested https://github.com/Agaweb/react-native-stripe

**Comment by pvinis** [comment]
Could this be pinned?

**Comment by gran33** [comment]
Any roadmap from Stripe to build the react-native library?
We're hanging on the air with this issue :(

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
