### ISSUE TITLE
Stripe RN bindings timeline.

### ISSUE THREAD

**Issue by noumantahir** [tipsi/tipsi-stripe#709]
## The problem
I am migrating my app to use the new Stripe SCA model and since tipsi is recommended to apply for RN binding in stripe instead of using this package. I skeptical of the timeline and stability for the new package as I am on a pretty tight schedule.

What would be community suggestion, should I still use tipsi-stripe's SCA handlers or wait for stripe's official package.?

## Environment
* `tipsi-stripe : 7.5.3`
* `React-Native : 0.61.5`

**Comment by cybergrind** [comment]
@noumantahir, if you're going to use the most recent tipsi-stripe beta package, it probably will work in the near term.

But I still would recommend getting access to Stripe's official library.

**Comment by noumantahir** [comment]
@cybergrind thanks, I am waiting for their response, if they don't get back by tomorrow, I will have to use tipsi as the SCA regulations apply as early as 31st Dec in Europe.

**Comment by joshua-hester** [comment]
@noumantahir Did you receive access? It it worth just using tipsi-stripe until Stripe is official?

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
