### ISSUE TITLE
post_install.sh fails on `require 'xcodeproj'`

### ISSUE THREAD

**Issue by scottyantipa** [tipsi/tipsi-stripe#72]
When running react-native-link I get the following error:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/scottantipa/dev/GiveCrewNative/node_modules/tipsi-stripe/scripts/post-link-ios.rb:3:in `<main>'

```

This causes a build failure when running on iOS. 

To get around this I
1) manually installed the `xcodeproj` gem that the post_install script was trying to require
2) re-ran the post_install script

This seemed generated a Podfile and seemed to properly install Stripe, although I'm still having issues related to https://github.com/tipsi/tipsi-stripe/issues/29

**Comment by itsmepetrov** [comment]
Hi @scottyantipa, thank you for your comment. We will try to reproduce this error later.

**Comment by atomicleopard** [comment]
@scottyantipa - I assume by manually installing the gem, you mean `sudo gem install xcodeproj`?

I'm having this issue, but am unable to do this - it conflicts with 

    /usr/local/bin/xcodeproj -> ../Cellar/cocoapods/1.2.1/bin/xcodeproj

This is a brew installed cocoapods

To resolve this, i had to export my ruby gems path into my console. In my case:

    set -x GEM_HOME "/usr/local/Cellar/cocoapods/1.2.1/libexec"
    react-native link

(Note: I use fish, so you may have to set/export GEM_HOME differently)

I found the above path from the content of the existing brew installed xcodeproj. i.e.

    cat /usr/local/bin/xcodeproj        

    > #!/bin/bash
    > GEM_HOME="/usr/local/Cellar/cocoapods/1.2.1/libexec" exec 
    > "/usr/local/Cellar/cocoapods/1.2.1/libexec/bin/xcodeproj" "$@"

I hope this helps (someone)

**Comment by devLaaziz** [comment]
+1

**Comment by bwoodlt** [comment]
I'm having this issue. Any idea how to fix?

**Comment by smisaacs** [comment]
had the same issue.  Installing the gem fixed it. I'm running rbenv with ruby version 2.4.2:

```
/Users/smisaacs/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj (LoadError)
	from /Users/smisaacs/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from node_modules/tipsi-stripe/scripts/post-link-ios.rb:3:in `<main>'
```

**Comment by isnifer** [comment]
@devLaaziz @bwoodlt @smisaacs did you solve your issue?
