### ISSUE TITLE
Unable to build the app on Android

### ISSUE THREAD

**Issue by Billmike** [tipsi/tipsi-stripe#723]
## Before I have submitted the issue 
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Trying to run the app on Android, and it fails to build. App runs fine on iOS

## Environment
* `tipsi-stripe` version: 8.0.2
* iOS or Android: Android
* OS version: 8
* React-Native version: 0.62.2
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version: 

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion - 29
* android.buildToolsVersion - 28.0.3
* android.defaultConfig.minSdkVersion - 19
* android.defaultConfig.targetSdkVersion - 29
* android.defaultConfig.multiDexEnabled (if exists)

## Screenshots, GIFs (Must to have)

![Screenshot 2021-01-23 at 09 28 56](https://user-images.githubusercontent.com/24798364/105573440-e4638080-5d5d-11eb-8887-004ec522eef9.png)

**Comment by Billmike** [comment]
It seems to be dependent on Firebase-core, but from the [docs here](https://firebase.google.com/support/release-notes/android#latest_sdk_versions), Firebase-core is no longer needed

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
