### ISSUE TITLE
Tipsi breaks Android

### ISSUE THREAD

**Issue by macutko** [tipsi/tipsi-stripe#724]
## Before I have submitted the issue 
[X ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ X] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[X ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[X] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Briefly describe the issue you are experiencing (or the feature you want to see added to `tipsi-stripe`). 
Tell us what you were trying to do and what happened instead. 

After running install the app keeps stopping. It does not even start on the android device.

## Environment
* `tipsi-stripe` version:  npm latest (8.02)
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: 
* React-Native version: 0.64
* (Android only) `com.google.firebase:firebase-core` version: ?
* (Android only) `com.google.android.gms:play-services-base` version: ?

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion
* android.buildToolsVersion
* android.defaultConfig.minSdkVersion
* android.defaultConfig.targetSdkVersion
* android.defaultConfig.multiDexEnabled (if exists)

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

![image](https://user-images.githubusercontent.com/33177634/106150642-d063b880-617b-11eb-8889-a42aab249aaa.png)

## Code To Reproduce Issue (Good To Have)
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by macutko** [comment]
In hindsight, the screenshot is just before metro is restarted. After metro is restarted post install, the app builds but never gets sent to metro only comes up with 'App keeps stopping' on the emulator.

**Comment by cybergrind** [comment]
Probably this is the old windows issue

![image](https://user-images.githubusercontent.com/192182/106178105-67e00000-61aa-11eb-904e-e6c92131b4ef.png)

**Comment by macutko** [comment]
@cybergrind ah, thanks! Is there a manual way to link? Or is there someone working on a fix already? Or someplace I could find more details? 

...I cant be the only one using windows...

**Comment by cybergrind** [comment]
@macutko I didn't get any followups regarding this. Probably people figured it out without providing any PR with steps to fix it
If you find a solution - feel free to submit PR

**Comment by macutko** [comment]
@cybergrind Thanks, i'll close this then.
