### ISSUE TITLE
stripe-react-native is coming, go sign up as beta developer using the interest form!!

### ISSUE THREAD

**Issue by nobodyabcd** [tipsi/tipsi-stripe#733]
N/A

**Comment by stueynet** [comment]
> N/A

Sign up where?

**Comment by Wallow17** [comment]
> > N/A
> 
> Sign up where?

https://app.smartsheet.com/b/form/b1a1053eaac7496eb0ae7892ebd68973

**Comment by stueynet** [comment]
> > > N/A
> > 
> > 
> > Sign up where?
> 
> https://app.smartsheet.com/b/form/b1a1053eaac7496eb0ae7892ebd68973

May I ask what is the source of this form?

**Comment by raajnadar** [comment]
The Readme of this repository @stueynet

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
