### ISSUE TITLE
After install package application on android keeps stopping

### ISSUE THREAD

**Issue by IvanTrutnev** [tipsi/tipsi-stripe#735]
<img width="327" alt="Снимок экрана 2021-03-17 в 12 09 00" src="https://user-images.githubusercontent.com/12071109/111442590-90e83000-8719-11eb-84c2-12aeef71ed06.png">
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Briefly describe the issue you are experiencing (or the feature you want to see added to `tipsi-stripe`). 
Tell us what you were trying to do and what happened instead. 

After running install the app keeps stopping. It does not even start on the android device. On ios everything fine.

## Environment
* `tipsi-stripe` version: npm latest 8.0.2
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: 
* React-Native version: 0.63.4
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version: 

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion 29
* android.buildToolsVersion 29.0.2
* android.defaultConfig.minSdkVersion 21
* android.defaultConfig.targetSdkVersion 29
* android.defaultConfig.multiDexEnabled (if exists) true

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

## Code To Reproduce Issue (Good To Have)
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by ArkaneKhan** [comment]
same is happening to me.

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
