### ISSUE TITLE
The connection to Google Play services was lost 

### ISSUE THREAD

**Issue by samzmann** [tipsi/tipsi-stripe#737]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I'm seeing in my Sentry logs that `stripe.deviceSupportsNativePay()` is failing with the error:
```
Error: 8: The connection to Google Play services was lost
```
The only report I got came from Android 8.0.0. After googling a bit and finding various issues related to "google play services" I get the feeling maybe the user needs to install the [Google Play services app](https://play.google.com/store/apps/details?id=com.google.android.gms). But that's just a hunch... So do you have any better insight on where this error might come from?

## Environment
* `tipsi-stripe` version: 8.0.0-beta.11
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: 8.0.0
* React-Native version: 0.63.4
* (Android only) `com.google.firebase:firebase-core` version: 16.0.9
* (Android only) `com.google.android.gms:play-services-base` version: not declared in android/app/build.gradle (should it be?)

## Links to logs and sources
No more logs than the error posted above

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion: **29**
* android.buildToolsVersion: **29.0.2**
* android.defaultConfig.minSdkVersion: **21**
* android.defaultConfig.targetSdkVersion: **29**
* android.defaultConfig.multiDexEnabled: **true**

## Screenshots, GIFs (Must to have)
N/A

## Code To Reproduce Issue (Good To Have)
Could not reproduce.

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
