### ISSUE TITLE
Android 10 Crash app after click on Pay Button 

### ISSUE THREAD

**Issue by abramovks** [tipsi/tipsi-stripe#738]
Android 10
Crash app after click on Pay Button 

stripe.setOptions({
      publishableKey: publishableKey,
      merchantId: 'MYID', // Optional
      androidPayMode: 'test', // Android only
    }); 

03-19 15:54:52.842 25716 25716 E AndroidRuntime: java.lang.NoSuchMethodError: No static method fromString(Ljava/lang/String;)Lcom/stripe/android/model/Token; in class Lcom/stripe/android/model/Token; or its super classes (declaration of 'com.stripe.android.model.Token' appears in /data/app/com.corpo_mobile-OdKuBmBTgevFsIk1OgQdWA==/base.apk!classes3.dex)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at com.gettipsi.stripe.GoogleApiPayFlowImpl.onActivityResult(GoogleApiPayFlowImpl.java:233)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at com.gettipsi.stripe.StripeModule$1.onActivityResult(StripeModule.java:112)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:308)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:758)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
03-19 15:54:52.842 25716 25716 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
03-19 15:54:52.850  2034  7153 W ActivityTaskManager:   Force finishing activity com.corpo_mobile/.MainActivity
03-19 15:54:52.842  2034 11315 I chatty  : uid=1000(system) Binder:2034_20 identical 8 lines
03-19 15:54:52.843  2034 11315 W InputReader: Device has associated, but no associated display id.
03-19 15:54:52.846 12552 12552 E Parcel  : Class not found when unmarshalling: m.cns
03-19 15:54:52.846 12552 12552 E Parcel  : java.lang.ClassNotFoundException: m.cns

 
"tipsi-stripe": "^8.0.2" 

    implementation 'com.google.firebase:firebase-core:16.0.7'
    implementation 'com.google.android.gms:play-services-wallet:18.1.1'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.stripe:stripe-android:16.2.0'
 

buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29

**Comment by abramovks** [comment]
Downgrade to the version from Example folder solved my exeptions.

implementation 'com.stripe:stripe-android:16.2.0'
=>
implementation 'com.stripe:stripe-android:10.4.6'

Java files in "tipsi-stripe": "^8.0.2" uses a lot of deprecated methods. 
such as Token. fromString, Card.getCVC.

**Comment by prodev-alt** [comment]
@abramovks I am still getting the same error even though I downgraded to 10.4.6
Please help me!
