### ISSUE TITLE
CocoaPods could not find compatible versions for pod "tipsi-stripe":

### ISSUE THREAD

**Issue by williamgoodhew** [tipsi/tipsi-stripe#748]
Thanks for creating this library.
I am having a bit of trouble getting set up.

I am getting the following error when I run pod install.

```
`[!] CocoaPods could not find compatible versions for pod "tipsi-stripe":
  In Podfile:
    tipsi-stripe (from `../node_modules/tipsi-stripe`)

Specs satisfying the `tipsi-stripe (from `../node_modules/tipsi-stripe`)` dependency were found, but they required a higher minimum deployment target.`

```
here is my podfile

```
`require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'athalens' do
  config = use_native_modules!
  pod 'Stripe', '~> 19.4.0'
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'athalensTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end`
```

and here is my package.json

```
`{
  "name": "athalens",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-firebase/app": "^11.1.2",
    "@react-native-firebase/auth": "^11.1.2",
    "@react-native-firebase/firestore": "^11.1.2",
    "country-codes-list": "^1.6.8",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-circular-progress": "^1.3.7",
    "react-native-device-info": "^8.0.6",
    "react-native-elements": "^3.3.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-haptic-feedback": "^1.11.0",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-modal": "^11.7.0",
    "react-native-reanimated": "^1.13.2",
    "react-native-redash": "^14.2.1",
    "react-native-router-flux": "^4.3.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.18.1",
    "react-native-skeleton-content": "^1.0.20",
    "react-native-vector-icons": "^8.1.0",
    "react-redux": "^7.2.3",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "tipsi-stripe": "^9.0.0",
    "validator": "^13.5.2"
  },
  "devDependencies": {
    "@babel/core": "7.13.10",
    "@babel/runtime": "7.13.10",
    "@react-native-community/eslint-config": "2.0.0",
    "babel-jest": "26.6.3",
    "eslint": "7.14.0",
    "jest": "26.6.3",
    "metro-react-native-babel-preset": "0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

```

**Comment by pzehle** [comment]
Having the same problem...

**Comment by Blueeyer27** [comment]
In your Podfile set
**platform :ios, '11.0'**
And in xCode set iOS Deployment Target to **11.0**
This should do the trick

**Comment by michaellu716** [comment]
thank you! this helped us a lot

**Comment by ummay-sk** [comment]
Hi,

I've set 
`platform :ios, '11.0'`
 
and my iOS deployment target is set to `11.0`

And I'm still getting this error. Any idea where I'm going wrong?

**Comment by nitishkumar347** [comment]
i try this but still got same error

**Comment by nitishkumar347** [comment]
thanks its working now

**Comment by anuragfexle** [comment]
thanks for save my day.

**Comment by nitin251298** [comment]
here is my podfile

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'AStar8' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  
  

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'AStar8Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!() # update this part

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  
end



and here is my package.json


{
  "name": "AStar8",
  "version": "1.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "clean": "react-native clean-project",
    "clean:auto": "react-native clean-project-auto",
    "postinstall": "npm-install-peers"
  },
  "dependencies": {
    "@lowkey/react-native-gif": "^3.1.0",
    "@react-native-async-storage/async-storage": "^1.17.7",
    "@react-native-community/checkbox": "^0.5.12",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/push-notification-ios": "^1.11.0",
    "@react-native-firebase/app": "^17.4.2",
    "@react-native-firebase/messaging": "^17.4.2",
    "@react-native-masked-view/masked-view": "^0.2.8",
    "@react-native-picker/picker": "^2.4.2",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/stack": "^6.2.2",
    "@stripe/stripe-react-native": "^0.23.3",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "assert": "^1.1.1",
    "axios": "^0.27.2",
    "i": "^0.3.7",
    "lottie-react-native": "^5.1.3",
    "moment": "^2.29.4",
    "npm": "^9.6.4",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.0",
    "react-native-animatable": "^1.3.3",
    "react-native-apple-payment": "^1.1.1",
    "react-native-bouncy-checkbox": "^3.0.4",
    "react-native-calendar-picker": "^6.1.5",
    "react-native-circles": "^1.0.1",
    "react-native-circular-action-menu": "^0.5.0",
    "react-native-circular-progress-indicator": "^4.4.2",
    "react-native-collapsible": "^1.6.0",
    "react-native-cool-speedometer": "^1.1.5",
    "react-native-credit-card-input": "^0.4.1",
    "react-native-crypto": "^2.1.0",
    "react-native-date-picker": "^4.2.5",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-image-crop-picker": "^0.38.0",
    "react-native-image-picker": "^4.8.5",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-modal": "^13.0.1",
    "react-native-otp-textinput": "^0.0.9",
    "react-native-paper": "^4.12.4",
    "react-native-payments": "^0.8.4",
    "react-native-popup-menu": "^0.15.12",
    "react-native-radial-gradient": "^1.1.2",
    "react-native-reanimated": "^2.14.4",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screen": "^1.0.1",
    "react-native-screens": "^3.20.0",
    "react-native-simple-gradient-progressbar-view": "^0.2.0",
    "react-native-sqlite-storage": "^6.0.1",
    "react-native-stripe-api": "^0.1.0",
    "react-native-stripe-checkout": "^0.0.15",
    "react-native-super-grid": "^4.4.2",
    "react-native-svg": "^13.9.0",
    "react-native-table-component": "^1.2.2",
    "react-native-vector-icons": "^9.2.0",
    "react-native-video": "^5.2.0",
    "react-native-video-player": "^0.14.0",
    "react-native-webview": "^11.23.1",
    "react-native-youtube-iframe": "^2.2.2",
    "react-redux": "^7.2.8",
    "redux": "^4.2.0",
    "redux-persist": "^6.0.0",
    "stripe": "^11.9.1",
    "svg": "^0.1.0",
    "toggle-switch-react-native": "^3.3.0",
    "yarn": "^1.22.19"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@babel/runtime": "^7.18.6",
    "@react-native-community/eslint-config": "^3.0.3",
    "babel-jest": "^28.1.2",
    "babel-plugin-module-resolver": "^4.1.0",
    "deprecated-react-native-prop-types": "^4.0.0",
    "eslint": "^8.19.0",
    "jest": "^28.1.2",
    "metro-react-native-babel-preset": "^0.71.3",
    "react-native-clean-project": "^4.0.1",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts"
    ]
  },
  "react-native": {
    "zlib": "browserify-zlib",
    "console": "console-browserify",
    "constants": "constants-browserify",
    "crypto": "react-native-crypto",
    "dns": "dns.js",
    "net": "react-native-tcp",
    "domain": "domain-browser",
    "http": "@tradle/react-native-http",
    "https": "https-browserify",
    "os": "react-native-os",
    "path": "path-browserify",
    "querystring": "querystring-es3",
    "fs": "react-native-level-fs",
    "_stream_transform": "readable-stream/transform",
    "_stream_readable": "readable-stream/readable",
    "_stream_writable": "readable-stream/writable",
    "_stream_duplex": "readable-stream/duplex",
    "_stream_passthrough": "readable-stream/passthrough",
    "dgram": "react-native-udp",
    "stream": "stream-browserify",
    "timers": "timers-browserify",
    "tty": "tty-browserify",
    "vm": "vm-browserify",
    "tls": false
  },
  "browser": {
    "zlib": "browserify-zlib",
    "console": "console-browserify",
    "constants": "constants-browserify",
    "crypto": "react-native-crypto",
    "dns": "dns.js",
    "net": "react-native-tcp",
    "domain": "domain-browser",
    "http": "@tradle/react-native-http",
    "https": "https-browserify",
    "os": "react-native-os",
    "path": "path-browserify",
    "querystring": "querystring-es3",
    "fs": "react-native-level-fs",
    "_stream_transform": "readable-stream/transform",
    "_stream_readable": "readable-stream/readable",
    "_stream_writable": "readable-stream/writable",
    "_stream_duplex": "readable-stream/duplex",
    "_stream_passthrough": "readable-stream/passthrough",
    "dgram": "react-native-udp",
    "stream": "stream-browserify",
    "timers": "timers-browserify",
    "tty": "tty-browserify",
    "vm": "vm-browserify",
    "tls": false
  }
}

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
