### ISSUE TITLE
How to confirm payment by Alipay/Bancontact/Giropay/iDeal with my clientSecret pi_a56sd_secret_ashdg ?

### ISSUE THREAD

**Issue by carlosq-ordering** [tipsi/tipsi-stripe#749]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
I need to confirm payments from banks as Alipay/Bancontact/Giropay/iDeal, but I can use the `.createSourceWithParams(params) ` method because I can create payments from the frontend, the backend response the clientSecret (pi_asdakjhgsd_secret_asdkjha), the type (bancontact, alipay, giropay, ideal), and the owner data (name, email).

So, I need to confirm this payment using the clientSecret and maybe using the bank type and owner data. 

## Environment
* `tipsi-stripe` version: ^9.0.0
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: Windows 10 Home single language
* React-Native version: 0.63.3
* (Android only) `com.google.firebase:firebase-core` version: 16.0.7
* (Android only) `com.google.android.gms:play-services-base` version: 17.2.1

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
