### ISSUE TITLE
IOS build error "no visible @interface" for "setBillingAddress".

### ISSUE THREAD

**Issue by MobiusHorizons** [tipsi/tipsi-stripe#75]
## Error:
I get the following build error in Xcode:
```
no visible @interface for 'STPUserInformation' declares the selector 'setBillingAddress:'
``` 
on line `597` of `TPSStripeManager.m`

## Steps to reproduce
I had Tipsi-Stripe installed and working correctly on a version prior to 3.10 (I installed originally around the middle of May). After the Ios bank account tokenization was merged I updated the library, and encountered build failures on IOS. However the library is working as expected on Android. 

## Debugging Steps Taken:
I have 
- upgraded react-native
- cleared the build cache
- deleted and re-installed /re-linked my node-modules.
- re-run `pod install`

I can't think of anything else to try, but it seems like an issue local to my system, since other people haven't reported it.

I would appreciate any help debugging this issue.

**Comment by itsmepetrov** [comment]
@MobiusHorizons  Could you please provide your `Podfile`? What version of `Stripe` are you using?

**Comment by MobiusHorizons** [comment]
my Podfile looks like so

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for MyProject
  pod 'Firebase/Messaging'
  pod 'Stripe', '~> 9.2.0'
  #inherit! :search_paths

end
```

The result of calling `pod install` is below:
```
Analyzing dependencies
Downloading dependencies
Using Firebase (3.15.0)
Using FirebaseAnalytics (3.7.0)
Using FirebaseCore (3.5.2)
Using FirebaseInstanceID (1.0.9)
Using FirebaseMessaging (1.2.2)
Using GoogleToolboxForMac (2.1.1)
Using Protobuf (3.2.0)
Using Stripe (9.2.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 8 total pods installed.
```

As you can see it's using Stripe 9.2.0.

**Comment by isnifer** [comment]
@MobiusHorizons please, update Stripe pod to:
```
pod 'Stripe', '10.1.0'
```

**Comment by MobiusHorizons** [comment]
@isnifer, thanks, I don't know how I missed that. That seems to have fixed it.

As a side note when running `react-native link` it says it's modifying the pod file to the new version, but no change is made. This may have led to my confusion.

**Comment by isnifer** [comment]
@MobiusHorizons glad to help you)
