### ISSUE TITLE
How to change currency in apple pay???

### ISSUE THREAD

**Issue by ignivarahulsaini** [tipsi/tipsi-stripe#76]
Apple pay showing amount in USD($). But I need to show in GBP

**Comment by itsmepetrov** [comment]
Hi @ignivarahulsaini, try to use `currencyCode` option in `paymentRequestWithApplePay`:

```js
stripe.paymentRequestWithApplePay(items, {
  currencyCode: 'GBP',
})
```

Unfortunately, this option is missing in docs, but I found it in the [code](https://github.com/tipsi/tipsi-stripe/blob/aa8bad263fdcd883457f2bff96b9be0925e6ecfe/ios/TPSStripe/TPSStripeManager.m#L274). We will update documentation later.

**Comment by itsmepetrov** [comment]
Docs updated in #94
