### ISSUE TITLE
Build error on Xcode 12.5 

### ISSUE THREAD

**Issue by vittoriozzo** [tipsi/tipsi-stripe#762]
Error: 'new' is unavailable: You cannot directly instantiate an STPIssuingCardPin

Since xCode has been updated to 12.5 it returns this problem.
How to solve?
thank you

**Comment by renatomiguelsantos** [comment]
I faced the same issue but was able to solve it by upgrading tipsi-stripe to 9.0.0 and updating the Stripe version in Podfile with:
`pod 'Stripe', '~> 21.4'`

**Comment by phithu** [comment]
I upgraded Stripe to 21.4. But I can not build on Xcode 12.5

**Comment by minhas-tech** [comment]
I got this error when I am trying to upgrade strip to 21.4

<img width="887" alt="Screenshot 2021-05-06 at 2 56 06 PM" src="https://user-images.githubusercontent.com/80686316/117282663-6e9fa280-ae7e-11eb-8f56-2f3b24126c01.png">

**Comment by minhas-tech** [comment]
After updating I encounter this error. 

<img width="607" alt="Screenshot 2021-05-06 at 5 50 33 PM" src="https://user-images.githubusercontent.com/80686316/117300971-90575480-ae93-11eb-962d-9693410b6db1.png">

**Comment by Savinvadim1312** [comment]
> updating to `pod 'Stripe', '~> 21.5.1'` and `platform :ios, '12.0'` in the `Podfile`
> 
> and updating`tipsi-stripe` to `9.0.0` in `package.json`
> 
> fixes/works around the issue in XCode 12.5
> 
> annoying to also have to update the minimum supported version (`10` -> `12`) on a `minor` Pod update to avoid:
> 
> `Specs satisfying the `Stripe (~> 21.5.1)` dependency were found, but they required a higher minimum deployment target.`

Worked for me. Thanks

**Comment by zhahaoyu** [comment]
I tried to upgrade the dependencies as suggested above, but got the following build errors:

![Screen Shot 2021-05-18 at 12 32 41 AM](https://user-images.githubusercontent.com/13268361/118610444-9e995080-b770-11eb-9f5c-a74b81cba7ac.png)

Any idea how to fix this?

**Comment by usamaabutt** [comment]
> updating to `pod 'Stripe', '~> 21.5.1'` and `platform :ios, '12.0'` in the `Podfile`
> 
> and updating`tipsi-stripe` to `9.0.0` in `package.json`
> 
> fixes/works around the issue in XCode 12.5
> 
> annoying to also have to update the minimum supported version (`10` -> `12`) on a `minor` Pod update to avoid:
> 
> `Specs satisfying the `Stripe (~> 21.5.1)` dependency were found, but they required a higher minimum deployment target.`

It works!!! Thanks a lot.

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: 
- https://github.com/tipsi/tipsi-stripe/issues/779
- https://github.com/tipsi/tipsi-stripe/issues/842
