### ISSUE TITLE
deviceSupportsApplePay() returns true on simulator, but false on real device

### ISSUE THREAD

**Issue by SuhairZain** [tipsi/tipsi-stripe#77]
Hi,
For our app, the deviceSupportsApplePay() returns false on real devices. Should I be doing any additional setup via XCode or iTunes connect in order to get it working other than the steps mentioned in the README for this library?

**Comment by itsmepetrov** [comment]
@dmytrozavgorodniy please take a look

**Comment by pongponglau** [comment]
I encounter the same issue in a real iphone 7. Nonetheless, this function returns true in simulator.

Thanks for your advice.

**Comment by pongponglau** [comment]
I have solved the issue. My fault. Sorry about that.

**Comment by isnifer** [comment]
@pongponglau tell us what wrong did you do?

**Comment by jeff-da** [comment]
@isnifer This isn't mentioned in the README.md, but you need to go into XCode > Project > Capabilities and enable Apple Pay to fix the issue.

**Comment by jeff-da** [comment]
![tipsiapplepay](https://user-images.githubusercontent.com/24738825/28348524-4bbd78e6-6bf2-11e7-97ed-b6e4b4ee0f0e.png)
