### ISSUE TITLE
Missing tokenId in paymentRequestWithCardForm response

### ISSUE THREAD

**Issue by poorvasingh04** [tipsi/tipsi-stripe#773]
## The problem
I am trying to use stripe.paymentRequestWithCardForm in order to process the payment with card but it doesn't return tokenId. So, I tried to use stripe.createTokenWithCard with the card information returned from paymentRequestWithCardForm but createTokenWithCard needs full number. How can I achieve this? I need tokenId to process payment.

## Environment
* `tipsi-stripe` version: 9.0.0
* iOS or Android: iOS
* OS version: Any
* React-Native version: 0.63.2

**Comment by Jebasuthan** [comment]
As a workaround, provide a complete theme.

```
stripe.paymentRequestWithCardForm({
    theme: {
        primaryBackgroundColor: 'white',
        secondaryBackgroundColor: 'white',
        primaryForegroundColor: 'black',
        secondaryForegroundColor: 'black',
        accentColor:'blue',
        errorColor:'red'
    }
});

```

**Comment by poorvasingh04** [comment]
@Jebasuthan I am passing theme, still I don't get tokenId in response:
stripe
                                      .paymentRequestWithCardForm({
                                        theme: {
                                            primaryBackgroundColor: 'white',
                                            secondaryBackgroundColor: 'white',
                                            primaryForegroundColor: 'black',
                                            secondaryForegroundColor: 'black',
                                            accentColor:'blue',
                                            errorColor:'red',
                                        },
                                        requiredBillingAddressFields: 'full',
                                        prefilledInformation: {
                                          billingAddress,
                                        },
                                    })

where billingAddress is also populated from my previous which I am not sharing here. I get the following response:
`{
      "card": {
        "funding": "credit",
        "expYear": 2025,
        "expMonth": 2,
        "last4": "4242",
        "country": "US",
        "brand": "visa"
      },
      "id": "pm_1IoXcgBvOfL7QDd3ZwggoX7d",
      "billingDetails": {
        "address": {
          "state": "Chhattisgarh",
          "line2": "aa",
          "line1": "dsfsf",
          "country": "IN",
          "city": "Baikunthpur",
          "postalCode": "223423"
        },
        "phone": null,
        "name": "p.s@gmail.com",
        "email": null
      },
      "customerId": null,
      "livemode": false,
      "created": 1620409079,
      "type": "card",
      "metadata": null
    }`

**Comment by nicholasmarais1158** [comment]
@poorvasingh04 

The `id` in the response (`pm_1IoXcgBvOfL7QDd3ZwggoX7d`) is a payment method id which can be used to confirm the payment.

```
stripe.confirmPaymentIntent({
  clientSecret: 'From your server after creating a payment intent',
  paymentMethodId: 'pm_1IoXcgBvOfL7QDd3ZwggoX7d',
});
```

When you use native pay (`stripe.paymentRequestWithNativePay()`), you will get back a`tokenId` which you should instead use like this;

```
stripe.confirmPaymentIntent({
  clientSecret: 'From your server after creating a payment intent',
  paymentMethod: {
    card: {
      token: 'Token_id from the result of Apple Pay or Google Pay',
    }
  },
});
```

See https://stripe.com/docs/api/payment_intents/confirm

**Comment by nicholasmarais1158** [comment]
> @nicholasmarais1158 So, As I understood, these are the steps:
> 
> 1. In client - call paymentRequestWithCardForm which will return paymentMethodId
> 2. In server - create paymentIntent in backend which will return client_secret
> 3. In client - confirm payment intent with paymentMethodId returned in step 1 and client_secret returned in step 2
> 
> What's next? Is there some documentation that I can follow?
> Thanks!

That's correct. Although steps 1 and 2 can be in any order.

Once the payment is successful you will receive (server-side) an event via Webhooks from Stripe (payment_intent.succeeded) which you can use to continue the transaction (e.g. send an order for fulfilment, or transfer a digital asset).

The overall process is nicely explained here; https://stripe.com/docs/payments/payment-intents

**Comment by poorvasingh04** [comment]
@nicholasmarais1158 Thanks for sharing this. is there a documentation from tipsi-stripe? Also, is there any synchronous way of knowing if payment succeeded like we do in native iOS and android sdks with confirmPayment as last step.
Using native sdk, there are following steps:
1. Create ephemeral key in server with api version sent from client sdk
2. Create payment intent in server
3. Confirm payment intent in client

Last step confirms if payment is successful. We don't need webhooks here.

How can we do the same process with tipsi-stripe?

**Comment by poorvasingh04** [comment]
@mindroittech I have the same problem unfortunately. @nicholasmarais1158 suggested a solution with webhooks but I am looking for something synchronous like native sdk.

**Comment by mindroittech** [comment]
> @mindroittech I have the same problem unfortunately. @nicholasmarais1158 suggested a solution with webhooks but I am looking for something synchronous like native sdk.

Hi thanks for the reply, I have changed the approach. now i will be using _stripe.createTokenWithCard()_ using this i am able to get the token and complete the payment.

**Comment by poorvasingh04** [comment]
@mindroittech But how are you using createTokenWithCard. Where are you getting card details from?

**Comment by mindroittech** [comment]
I am saving the card information in the app. tipsi-stripe has an option to save the card/subscription.

**Comment by poorvasingh04** [comment]
@mindroittech When possible, please share the code if you can.

**Comment by poorvasingh04** [comment]
@mindroittech So, I got it working. Finally! Here are the steps that I followed:

1. In client - call paymentRequestWithCardForm which will return paymentMethodId
2. In server - create paymentIntent in backend which will return client_secret
3. In client - confirm payment intent with paymentMethodId returned in step 1 and client_secret returned in step 2

This is it. As per the documentation here: [Stripe Confirm Payment Intent](https://stripe.com/docs/api/payment_intents/confirm)

`If the selected payment method requires additional authentication steps, the PaymentIntent will transition to the requires_action status and suggest additional actions via next_action. If payment fails, the PaymentIntent will transition to the requires_payment_method status. If payment succeeds, the PaymentIntent will transition to the succeeded status (or requires_capture, if capture_method is set to manual).`

So, I wait for succeeded status here if payment is successful.

**Comment by poorvasingh04** [comment]
But there is still one thing missing paymentRequestWithCardForm always start a fresh page. I want to save card information.

**Comment by mindroittech** [comment]
> 3\. paymentMethodId

That is great. I will take a look at this. thanks

**Comment by poorvasingh04** [comment]
@mindroittech The document also says that you can attach a payment method to customer in server and later fetch list of payment methods. I will work on it later. closing it for now as this is working for me.
