### ISSUE TITLE
linking problem

### ISSUE THREAD

**Issue by cltsang** [tipsi/tipsi-stripe#78]
Greetings.
After installing and linking the library, when i try to run the project via react-native, I have the same issue as #53 . However, if i run it via xcode, it works just fine.
It's linked by react-native link. I've checked the project settings, and they are all modified just as described in the [manual steps](https://github.com/tipsi/tipsi-stripe#manual) .
Do you have any idea what else i should check?
I'm using the latest version of react native cli, xcode, and tipsi-stripe.
Thank you.

**Comment by isnifer** [comment]
@cltsang just to be clear, inside project root:
```bash
$ react-native -v
react-native-cli: 2.0.1
react-native: 0.45.1
```
Yes?

**Comment by cltsang** [comment]
Yes

**Comment by isnifer** [comment]
@cltsang I've created a repo with clean installation of react-native 0.45.1, successfully run it via `react-native run-ios`. Please, help to understand, what wrong with `tipsi-stripe` on your project - https://github.com/isnifer/tipsi-stripe-issue/commit/a5196640e4ebe21bc2db90823ad36d27ff610399
This commit includes only `tipsi-stripe link` changes

**Comment by cltsang** [comment]
I tried cloning my project on another machine to run and there was no problem. Turned out clicking clean in XCode is not enough; I needed to remove the ios build folder. After that it's fine.
Since the ios build folder is ignored by git, i cannot trace what caused the invalid build cache.
I guess it's better to remove the ios build folder after each react-native link.
Thank you for your time.

**Comment by isnifer** [comment]
@cltsang glad to help you, thank you for your story
