### ISSUE TITLE
Android: Keys for idempotent requests can only be used with the same parameters they were first used with

### ISSUE THREAD

**Issue by hariantara** [tipsi/tipsi-stripe#799]
## Step why I got the issue
1. I have upgrade stripe SDK from 10.4.6 to 16.9.0
2. and try to update on Java android by following this step https://github.com/tipsi/tipsi-stripe/issues/785#issuecomment-861289460
3. And try to get token by stripe.createTokenWithCard
4. after hit that stripe API, I got error response like :
    
`idempotency_error
Keys for idempotent requests can only be used with the same parameters they were first used with. Try using a key other than 'Publishable Key Stripe' if you meant to execute a different request.`

## Environment
1. "tipsi-stripe": "^9.0.0"
2. Stripe SDK : 16.9.0

I need your solution how to solve this issue

**Comment by suseendiran** [comment]
Removing line number 209 in following file can fix this issue.
[https://github.com/tipsi/tipsi-stripe/blob/master/android/src/main/java/com/gettipsi/stripe/StripeModule.java](StripeModule.java)

Passing publicKey as idempotentKey cause this error.

**Comment by ziga-hvalec** [comment]
I have the same problem. Can't add new cards, but can still use them for payment. After removing mPublicKey I can now add cards and everything works. But I don't know if this might break something else. Is this the correct solution? And when will this be fixed? Last update with the 16.10.0 android sdk was on 2021-06-18 almost a month ago? Does no one else have this problem?

**Comment by suseendiran** [comment]
I hope it doesn't break something, because that is an optional parameter and that parameter is specifically for idempotency key and it must be unique for every different request. So we can't pass public key(same key) for all requests.

You can check the use of idempotency key.

**Comment by hariantara** [comment]
> Removing line number 209 in following file can fix this issue.
> [StripeModule.java](https://github.com/tipsi/tipsi-stripe/blob/master/android/src/main/java/com/gettipsi/stripe/StripeModule.java)
> 
> Passing publicKey as idempotentKey cause this error.
> 
> Existing code:
> `mStripe.createCardToken( createCard(cardData), mPublicKey, new ApiResultCallback<Token>() { public void onSuccess(Token token) { promise.resolve(convertTokenToWritableMap(token)); } public void onError(Exception error) { error.printStackTrace(); promise.reject(toErrorCode(error), error.getMessage()); } }); `
> 
> New code: (Removed mPublicKey)
> `mStripe.createCardToken( createCard(cardData), new ApiResultCallback<Token>() { public void onSuccess(Token token) { promise.resolve(convertTokenToWritableMap(token)); } public void onError(Exception error) { error.printStackTrace(); promise.reject(toErrorCode(error), error.getMessage()); } });`
> 
> Referral link:
> https://stripe.dev/stripe-android/stripe/com.stripe.android/-stripe/create-card-token.html

Thanks for your help, I will try first to update tipsi node module first on android side, for first attempt I did add card, and then remove the and, and next once I want to re add again, thats the Idempotency comes out

but currently I move that stripe to Server Side that use uuid v4 to avoid idempotency, it just temporary solution for me

**Comment by cybergrind** [comment]
Should work in 9.1.4

**Comment by mintheinwin** [comment]
> I have the same problem. Can't add new cards, but can still use them for payment. After removing mPublicKey I can now add cards and everything works. But I don't know if this might break something else. Is this the correct solution? And when will this be fixed? Last update with the 16.10.0 android sdk was on 2021-06-18 almost a month ago? Does no one else have this problem?

I had the same this issues in  implementation 'com.stripe:stripe-android:20.8.0' version.
But in implementation ('com.stripe:stripe-android:1.0.4@aar'){
        transitive=true
    } version is fine. What have the problem in the lasted version?
