### ISSUE TITLE
After upgrade 8.0.2 to 9.0.0 version error showing in ios

### ISSUE THREAD

**Issue by vishalcodiant** [tipsi/tipsi-stripe#807]
Google Play store not accept stripe SDK version 10.5.2, They need stripe SDK verison 16.9.0 or higher. After update npm package to 8.0.2 to 9.0.0. it is showing error in IOS.

![image](https://user-images.githubusercontent.com/73869553/124772372-992eda00-df59-11eb-82da-fd4ea253f1e4.png)

React Native Version 0.64.0
Xcode version 12.5
tipsi-stripe 9.0.0

**Comment by chetanparmar95** [comment]
Were you able to fix this? I'm facing the same issue with version 9.1.4

**Comment by vishalcodiant** [comment]
Hi,


Resolved this issue by changing swift version 5.0 to 5.2.
You can also check this link.

https://github.com/facebook/react-native/issues/30234 <https://github.com/facebook/react-native/issues/30234>



Regards,

Vishal Dhanotiya | Software Developer
Codiant - A YASH Technologies Company | Certified: ISO 9001:2008 & ISO/IEC 27001:2013 
455 Avenue of the Cities, East Moline, IL- 61244, USA
USA: +1-309-278-0633, +1-872-444-3361
IND:  0731-4291704
Codiant <http://www.codiant.com/> | Twitter <https://twitter.com/CodiantInc> | LinkedIn <https://www.linkedin.com/company/codiant-a-yash-technologies-company/> | Facebook <https://www.facebook.com/Codiant/> | Instagram <https://www.instagram.com/codiant/>

**Comment by rncodiant** [comment]
Resolved this by changing swift version inside LIBRARY_SEARCH_PATHS

https://github.com/facebook/react-native/issues/30234

![image](https://user-images.githubusercontent.com/87758966/128024787-38c27266-16d9-4870-8f0c-04e35af42e31.png)

**Comment by vishalcodiant** [comment]
Resolved this issue by changing swift version inside LIBRARY_SEARCH_PATHS

Please check the following link
facebook/react-native#30234

![128024787-38c27266-16d9-4870-8f0c-04e35af42e31](https://user-images.githubusercontent.com/73869553/128026299-35a6fb42-ecf0-4fe1-873e-406f1367cb89.png)
