### ISSUE TITLE
Archive failed with ld: library not found for -lPods-*** after upgrading from 8.0.0 to 9.1.0

### ISSUE THREAD

**Issue by manohar-octifi** [tipsi/tipsi-stripe#808]
## The problem
After updating from 8.0.0 to 9.1.0 I'm getting this error on Archive
```
ld: library not found for -lPods-OneSignalNotificationServiceExtension-SIT
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Environment
tipsi-stripe 9.1.1
XCODE 12.4
Stripe 21.3.1
iOS 14.4
react-native 0.64.0

## Tried
excluding arm64, pod deintegrate

## podfile
```
platform :ios, '11.0'

target 'AppName' do

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'Stripe', '~> 21.3.1'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'
  pod 'CardScan'

  target 'AppTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
  use_unimodules!

end

target 'OneSignalNotificationServiceExtension-SIT' do
  pod 'OneSignal', '>= 3.0', '< 4.0'
end

post_install do |installer|
  react_native_post_install(installer)
end
```

**Comment by jopac** [comment]
Change `iOS Deployment Target` to `11.0` might solve your problem

**Comment by manohar-octifi** [comment]
> Change `iOS Deployment Target` to `11.0` might solve your problem

Yeah It is already 11.0 you can see it in Podfile
```
platform :ios, '11.0'
```

**Comment by jopac** [comment]
> > Change `iOS Deployment Target` to `11.0` might solve your problem
> 
> Yeah It is already 11.0 you can see it in Podfile
> 
> ```
> platform :ios, '11.0'
> ```

I mean `iOS Deployment Target` from xcode, check the following settings:
1. Project > Info > Deployment Target > iOS Deployment Target = 11.0
2. Tagets > Your app > General > Deployment Info = iOS 11.0

**Comment by manohar-octifi** [comment]
Archive succeeded I feel so stupid for raising the issue
Thanks a lot @jopac 
I'll close the issue
