### ISSUE TITLE
undefined is not an object (evaluating 'TPSStripeManager.init')

### ISSUE THREAD

**Issue by d7laungani** [tipsi/tipsi-stripe#81]
This is my test data

```
 Stripe.init({
            publishableKey: 'pk_test_xxxxxxxxxxxxxxxx',
            merchantId: null,
        });
        Stripe.createTokenWithCard({
            number: 4242424242424242,
            expMonth: 10,
            expYear: 19,
            cvc: 345,
        }).then((token) => {
            console.log(token)
        });
```

import Stripe from 'tipsi-stripe'

I am having this issue in the iOS simulator.

**Comment by itsmepetrov** [comment]
@d7laungani hi, see related issues: #53 #78

**Comment by d7laungani** [comment]
Thank you. One solution was to use react-native link command. I do not have the option of individually modify the ios and android project manually as I am using Expo. However when I run the react-native link command I get and error saying
```
Error: Error occured during executing "node_modules/tipsi-stripe/scripts/post-link.sh" command
    at ChildProcess.prelink (/Users/deveshlaungani/Desktop/mobile-app/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
WorkMeNows-MacBook-Pro:mobile-app deveshlaungani$ 

```

**Comment by itsmepetrov** [comment]
I think you should detach your project before using `react-native link`, docks: https://docs.expo.io/versions/v18.0.0/guides/detach.html related issue: https://github.com/expo/expo/issues/56

**Comment by d7laungani** [comment]
Thank you for guiding me in the right direction

**Comment by itsmepetrov** [comment]
@d7laungani glad to help you

**Comment by duranmla** [comment]
![fizios_ _hashlabs_alexis_ _-zsh_ _119x52_and_glass](https://user-images.githubusercontent.com/1425162/30038870-78204466-9197-11e7-913c-bcf904605191.jpg)

I have already linked the dependencies but it still shows me the error, not sure what to do, besides, I have also added the TPSStripe folder into my XCode project (maybe in a wrong place) but I still have the issue. 

It is after ejecting from CRNA using RN 0.47 and Expo 19

**Comment by duranmla** [comment]
Sorry, It was my first time with an iOS project using react native, the thing was that I needed to rebuild the project by running `react-native run-ios` besides, the folder TPSStripe I move it within "Libraries".
