### ISSUE TITLE
card.brand not returned in createTokenWithCard on Android

### ISSUE THREAD

**Issue by JakyChen** [tipsi/tipsi-stripe#816]
## Before I have submitted the issue 
[ X] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ X] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ X] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ X] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
We upgraded from tipsi-stripe 9.0.0 to 9.1.4 and noticed that in an Android environment, providing credit card information to createTokenWithCard passes back a token with the below data set. Livemode is false.

addressCity: null
addressCountry: null
addressLine1: null
addressLine2: null
addressState: null
addressZip: null
cardId: <credit-card-id>
country: <country>
currency: null
cvc: null
expMonth: <exp-month>
expYear: <exp-year>
fingerprint: null
last4: <last-4>
name: null
number: null

This data set does not include brand and is no longer present in card details for Android (but is still present in iOS).

## Environment
* `tipsi-stripe` version: 9.1.4
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 9.0.0
* iOS or Android: Android
* OS version: 10 (Q)
* React-Native version: 0.63.2

## Links to logs and sources
Documentation for the expected data set: https://tipsi.github.io/tipsi-stripe/docs/createtokenwithcard.html

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion 29
* android.buildToolsVersion 29.0.2
* android.defaultConfig.minSdkVersion 25
* android.defaultConfig.targetSdkVersion 29

## Screenshots, GIFs (Must to have)

![Screen Shot 2021-08-10 at 3 41 24 PM](https://user-images.githubusercontent.com/13457163/128924617-7005a5e1-37d8-4b8b-ad5c-76c913501e1e.png)

## Code To Reproduce Issue (Good To Have)
import stripe from 'tipsi-stripe';
const token = await stripe.createTokenWithCard(cardData);
console.log(token);

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: https://github.com/tipsi/tipsi-stripe/issues/842
