### ISSUE TITLE
Google Pay Integration

### ISSUE THREAD

**Issue by HardikDG** [tipsi/tipsi-stripe#818]
## Before I have submitted the issue 
[] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
As per the reference [doc](https://tipsi.github.io/tipsi-stripe/docs/google-pay.html), I think in Tipsi it is not using the Google Pay integration from the Stripe. It is using Google Pay official API implementation, which has nothing to do with Stripe. 

Is it correct? 
As per my discussion with Stripe team they are asking for Payment of GooglePay which is not mentioned anywhere in the tipsy doc 

## Environment
* `tipsi-stripe` version: 9.1.4
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): 
* iOS or Android: Android
* OS version: 
* React-Native version: 0.60
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version:

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: https://github.com/tipsi/tipsi-stripe/issues/842
