### ISSUE TITLE
Task :tipsi-stripe:processDebugAndroidTestManifest FAILED

### ISSUE THREAD

**Issue by rutvikER1999** [tipsi/tipsi-stripe#826]
## Before I have submitted the issue 
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem

hello, i have completed "detox" automated testing  setup and trying to make build using "cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd .." command but getting following error

> Task :tipsi-stripe:processDebugAndroidTestManifest FAILED
D:\Projects\react-native\app3\callboats-mobile-app\app-client-mobile\node_modules\tipsi-stripe\android\build\intermediates\tmp\manifest\androidTest\debug\manifestMerger6347168199338246734.xml:5:5-74 Error:
        uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.stripe:stripe-android:16.10.0] C:\Users\pcs44\.gradle\caches\transforms-2\files-2.1\733c7fb78c246da430f66ad8d6f05501\jetified-stripe-android-16.10.0\AndroidManifest.xml as the library might be using APIs not available in 19
        Suggestion: use a compatible library with a minSdk of at most 19,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.stripe.android.payments" to force usage (may lead to runtime failures)

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tipsi-stripe:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.stripe:stripe-android:16.10.0] C:\Users\pcs44\.gradle\caches\transforms-2\files-2.1\733c7fb78c246da430f66ad8d6f05501\jetified-stripe-android-16.10.0\AndroidManifest.xml as the library might be using APIs not available in 19       
        Suggestion: use a compatible library with a minSdk of at most 19,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.stripe.android.payments" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
 

## Environment
* `tipsi-stripe` version: 19.2.0
* iOS or Android: Android
* OS version:  windows11
* React-Native version: 0.61.5
* (Android only) `com.google.firebase:firebase-core` version: 
* (Android only) `com.google.android.gms:play-services-base` version: 16.0.1

## Links to logs and sources
Create a [GIST](https://gist.github.com) which is a paste of your _full_ logs or sources, and link them here. 
If you are reporting a bug, _always_ include build or error logs!

[everything you need](https://gist.github.com/rutvikER1999/e8fa3469fd99e1f39f80920795a91add)
##all logs, manifest, gradle file mention above
all files have included in link provided above...

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

## Code To Reproduce Issue (Good To Have)
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

**Comment by amitdadon** [comment]
this project is using `minsdk=16` (app/build.gradle), and your project requires at least `21`. 
since this repo is no longer maintained, it is recommended to move to the official stripe sdk (as mentioned [here](https://github.com/tipsi/tipsi-stripe#tipsi-stripe)). 
another option is to patch the `build.gradle` and replace the minsdk to 21 (but patching is generally not a good habit)
