### ISSUE TITLE
Showing "Manifest merge failed error"

### ISSUE THREAD

**Issue by Hari-krish-v** [tipsi/tipsi-stripe#837]
When I installed tipsi-stipe package and run the project I get the below error message 
"Manifest merger failed : android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined"

Added android:exported="true" on Main/AndroidManifest.xml file inside activity tag

Below are the versions details.
      "react": "17.0.2",
      "react-native": "0.68.0",
       "tipsi-stripe": "^9.2.0"

        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"

**Comment by imariic** [comment]
@Hari-krish-v Have you managed to fix it?

**Comment by imariic** [comment]
Okay, I've managed to fix it by using `tipsi-stripe:9.0.0`

**Comment by Hari-krish-v** [comment]
> 

I have updated to the latest version then also it showing the same error "Manifest merge failed"

**Comment by felexx90** [comment]
@Hari-krish-v I added this as workaround to my AndroidManifest.xml 
```
 <activity
      android:name="com.stripe.android.payments.StripeBrowserLauncherActivity" android:exported="true" 
       tools:node="merge"/>
```

**Comment by mtr1012** [comment]
> @Hari-krish-v I added this as a workaround to my AndroidManifest.xml
> 
> ```
>  <activity
>       android:name="com.stripe.android.payments.StripeBrowserLauncherActivity" android:exported="true" 
>        tools:node="merge"/>
> ```

Thank you so much. Save me a lot of time

**Comment by gabriellend** [comment]
> @Hari-krish-v I added this as a workaround to my AndroidManifest.xml
> 
> ```
>  <activity
>       android:name="com.stripe.android.payments.StripeBrowserLauncherActivity" android:exported="true" 
>        tools:node="merge"/>
> ```

I was trying to find a solution for a week for this, THANK YOU BLESS YOU!

**Comment by itsAyyazdev** [comment]
> <activity
>       android:name="com.stripe.android.payments.StripeBrowserLauncherActivity" android:exported="true" 
>        tools:node="merge"/>

You are a lifesaver bro, I was struggling to fix this for the last 4 days. Your solution worked. Thank you.

**Comment by RaviPrakash040398** [comment]
> @Hari-krish-v I added this as a workaround to my AndroidManifest.xml
> 
> ```
>  <activity
>       android:name="com.stripe.android.payments.StripeBrowserLauncherActivity" android:exported="true" 
>        tools:node="merge"/>
> ```

Thank you.

**Comment by GabrielJorge94** [comment]
> @Hari-krish-v I added this as a workaround to my AndroidManifest.xml
> 
> ```
>  <activity
>       android:name="com.stripe.android.payments.StripeBrowserLauncherActivity" android:exported="true" 
>        tools:node="merge"/>
> ```

I only had to add the xmlns:tools="http://schemas.android.com/tools" into my AndroidManifest.xml and it worked just perfect! Thanks @felexx90 you saved me a lot of time.

**Comment by kavindadilshan** [comment]
> @Hari-krish-v I added this as a workaround to my AndroidManifest.xml
> 
> ```
>  <activity
>       android:name="com.stripe.android.payments.StripeBrowserLauncherActivity" android:exported="true" 
>        tools:node="merge"/>
> ```

You are a hearo brother.You saved my time

**Comment by aharodnikau** [comment]
@felexx90, app builds success, but crashes on entering. Which place should I add this activity in? Maybe I do smth wrong

**Comment by fbartho** [comment]
Closing this ticket, so that new users don't think this project is still active.

Stripe does not want you using this, and you will find pain if you do; Please migrate to the official [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native) package, for your user's safety, and your developer's sanity!

See more: https://github.com/tipsi/tipsi-stripe/issues/842

**Comment by ShoaibVirk008** [comment]
I was facing the same error and tried this

`<activity
      android:name="com.stripe.android.payments.StripeBrowserLauncherActivity" android:exported="true" 
       tools:node="merge"/>`

But then got another error, after some research found the solution, which was same above line of code but without "tools:node="merge"", 

Like this

`<activity
      android:name="com.stripe.android.payments.StripeBrowserLauncherActivity" 
      android:exported="true" 
       />`

**Comment by fbartho** [comment]
I can’t emphasize enough how you should move off of tipsi-stripe @ShoaibVirk008. This is a security vulnerability, and I hope I never again use an app that still uses tipsi-stripe today, as of 2023.
