### ISSUE TITLE
Why in android pay it is impossible to set ShippingAddressRequired in false

### ISSUE THREAD

**Issue by sedruid** [tipsi/tipsi-stripe#84]
I tried to use android pay and I do not need an address when making a payment, I read the stripe documentation and it says how to do it, I read the source code tipsi-stripe and saw [that](https://github.com/tipsi/tipsi-stripe/blob/master/android/src/main/java/com/gettipsi/stripe/StripeModule.java#L300)
```
 // You want the shipping address:
 .setShippingAddressRequired(true)
```
it can not be done, can you fix it?

**Comment by isnifer** [comment]
@sedruid thank you for your issue, please share a link to this article. @paynd take a look when you'll be available

**Comment by oowl** [comment]
According to [this part of official guide](https://stripe.com/docs/mobile/android/android-pay#stripe-android-pay-wrapper) this param should be customizable.
