### ISSUE TITLE
Why android is not using CardInputWidget from Stripe library

### ISSUE THREAD

**Issue by magrinj** [tipsi/tipsi-stripe#85]
Hello, I don't really understand why android side use a custom library instead of stripe input widget for the custom text field ?
This part of Stripe doens't exist before ?

**Comment by isnifer** [comment]
Hi @magrinj, I think yes, cause we started develop module about ome year ago. @itsmepetrov can describe better. But I’m sure we will solve this issue in the future releases

**Comment by magrinj** [comment]
@isnifer Ok thanks a lot! :) It's because actually the props are not really the same on both, so it's a little bit hard to make some change on it, I will create a PR because the props for placeholder are not set on the iOS side and I actually need it

For the android side, maybe I will take a look later, but I don't have time at this moment, thanks for library!

**Comment by cybergrind** [comment]
will be done (or not) in #68
