### ISSUE TITLE
TPSStripe/TPSCardField.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'tipsi-stripe' from project 'Pods')

### ISSUE THREAD

**Issue by ruslan-andersen** [tipsi/tipsi-stripe#865]
## Before I have submitted the issue 
[ x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem

I have this error with tipsy-stripe, during build process.
`TPSStripe/TPSCardField.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'tipsi-stripe' from project 'Pods')`

**Comment by fbartho** [comment]
@ruslan-andersen this project is no longer maintained. It is not compatible with current versions of react-native, and it is not compatible with current versions of `Stripe`.

Stripe has removed old versions of Stripe's cocoapods for security and compatibility reasons.

I recommend you migrate to the official package from Stripe!

See more: https://github.com/tipsi/tipsi-stripe/issues/842
