### ISSUE TITLE
Android Pay Error: You must provide a value for 'cvc'

### ISSUE THREAD

**Issue by ignivaparshant** [tipsi/tipsi-stripe#91]
Hi, I am getting this error error during using android pay with this configuration:
Android Pay Environment: ENVIRONMENT_TEST,
Stripe Key: Test Key,

` "error": {
  "message": "You must provide a value for 'cvc'.",
  "type": "card_error",
 "param": "cvc",
 "code": "invalid_cvc"}`

**Comment by isnifer** [comment]
@ignivaparshant so, did you provide cvc value for card?

**Comment by ignivaparshant** [comment]
I already added my card in android pay app and card is already verified.After that when we pay with android pay then I don't see any area where we can insert cvc.
When I click on pay button(sometime Continue button is coming) from android pay(pop up) then above error is coming on fullwallet api

**Comment by isnifer** [comment]
@ignivaparshant not sure, but I need to check that we've implemented all required features for Android Pay. As we mentioned in README support for Android Pay under active development

**Comment by isnifer** [comment]
@ignivaparshant how did you solve this issue?
