### ISSUE TITLE
Android Pay Error: You have not registered to use this API.

### ISSUE THREAD

**Issue by ignivaparshant** [tipsi/tipsi-stripe#92]
Hi, I am getting this error...I am using this configuration:
AndroidPay Environment: ENvironment_Production,

Error: WalletMerchantError: Error in loadMaskedWallet: You have not registered to use this API.

**Comment by isnifer** [comment]
@ignivaparshant Have you signed up to be an Android Pay merchant using this form: https://support.google.com/androidpay/merchant/contact/api_interest?rd=1 ?

**Comment by ignivaparshant** [comment]
No I didn't signup with that form before. 
I just submitted this. Could you please tell me the further steps after submitting the form. 
Is they give me a key, if yes then where should I put this. If no then how they know that we have registered or not?   Thankyou so much........:)

**Comment by ignivaparshant** [comment]
Apart from the form you provide is there any need for filling these two  forms https://support.google.com/androidpay/merchant/contact/interest?visit_id=1-636362105441485994-2774922519&rd=1
https://support.google.com/androidpay/merchant/contact/android_pay?hl=en&ec=specialist_contact&cfsi=specialist_contact&cfnti=6058724&cft=3
 i actually fill these forms

**Comment by isnifer** [comment]
@ignivaparshant I just found it on github at Android Pay and repo. Sure, that it is not tipsi-stripe issue
