### ISSUE TITLE
return email address from paymentRequestWithCardForm?

### ISSUE THREAD

**Issue by ronitslyper** [tipsi/tipsi-stripe#93]
Hi, great module!

Can I get the email address back from paymentRequestWithCardForm? (Looks like not?) Is the email address that the user enters in the card form, used for anything? I need an email address to set the stripe.charge.receipt_email on my server ... and would rather not ask the user to enter their email twice on android.

**Comment by ronitslyper** [comment]
Never mind, just ran it on the android simulator too and realized android doesn't ask for email

**Comment by isnifer** [comment]
@ronitslyper what did you change? Just ran on Emulator? Is real device asking you enter email?

**Comment by ronitslyper** [comment]
This was my bad for not checking on android - android is not asking for email in stripe screen on either emulator or real device. My flow can then be email screen followed by stripe screen on both OS's, on iphone I can prefill the email in the stripe screen using the options object, in android there is no email to prefill. Good to go :).

**Comment by isnifer** [comment]
@ronitslyper thanks!
