### ISSUE TITLE
ld: library not found for -lStripe

### ISSUE THREAD

**Issue by apolishch** [tipsi/tipsi-stripe#95]
I have followed the manual installation instructions as listed in the README (added `TPSStripe.xcodeproj` to Libraries, etc) and run `react-native link` as well as `react-native link tipsi-stripe` (succesfully I might add)

However when I run `react-native run-ios`, or build with xcode I get:

```
ld: library not found for -lStripe
clang: error: linker command failed with exit code 1 (use -v to see invocation)



** BUILD FAILED **


The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/myApp.app/myApp normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/myApp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/flockCover.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by isnifer** [comment]
Hi @apolishch, show me your Podfile. Also did you install Stripe pod?

**Comment by apolishch** [comment]
I did not install stripe directly, I instead followed the manual installation instructions from the Readme:

https://github.com/tipsi/tipsi-stripe#manual

having said that, the following is the contents of my podfile (in its entirety):
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flockCover' do
  pod 'Stripe', '~> 10.1.0'
  inherit! :search_paths
end
```

**Comment by isnifer** [comment]
@apolishch anyway, there is [Cocoapods](https://github.com/tipsi/tipsi-stripe#cocoapods) sections

**Comment by isnifer** [comment]
@apolishch Please, follow this guide and tell me result :)

**Comment by apolishch** [comment]
@isnifer I didn't end up having to change the podfile at all (it was already correct as pasted above)
I ran `cd ios && pod install`
It installed succesfully:

```
pod install
Analyzing dependencies
Downloading dependencies
Using Stripe (10.1.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] Automatically assigning platform ios with version 8.0 on target myApp because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

I wasn't sure what the instruction to "drag the folder in " meant so I right clicked on my project, selected Add files to "myApp", and then selected the folder specified (`node_modules/tipsi-stripe/ios/TPSStripe`)

I then ran `react-native run-ios` and had the same result - `ld: library not found for -lStripe`

**Comment by isnifer** [comment]
@apolishch you're welcome! Please, find in ios folder file `%YOUR_PROJECT_NAME%.xcworkspace` and open it. Try to run project via xcode and tell me result

**Comment by apolishch** [comment]
`Apple Mach-O Linker Error`

`Linker command failed with exit code 1 (use -v to see invocation)`

Right click -> Reveal in Log:

```
Ld /Users/abrahampolishchuk/Library/Developer/Xcode/DerivedData/myApp-enjsbnsiwwzbxgcfkihfeqjuobll/Build/Products/Debug-iphonesimulator/myApp.app/myApp normal x86_64
    cd /Users/abrahampolishchuk/github/flock/my-react-app/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
```
... truncated for brevity ....
```
ld: library not found for -lStripe
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by isnifer** [comment]
@apolishch hmmm, please remove `ios/build` folder and try to run again, tell me result

**Comment by apolishch** [comment]
@isnifer 
same result :/

interestingly on CircleCi the build still fails, but with a different error:
```
/Users/distiller/flock-react-app/node_modules/tipsi-stripe/ios/TPSStripe/TPSStripeManager.h:11:9: 'Stripe/Stripe.h' file not found

#import <Stripe/Stripe.h>
        ^


▸ Compiling TPSCardField.m

❌  /Users/distiller/flock-react-app/node_modules/tipsi-stripe/ios/TPSStripe/TPSCardField.h:10:9: 'Stripe/Stripe.h' file not found

#import <Stripe/Stripe.h>
```

Not sure if that is a different symptom of the same problem

**Comment by isnifer** [comment]
@apolishch As I can see on CircleCI pods didn't install.
So, on your local environment, please do:
```sh
rm -rf /Users/abrahampolishchuk/Library/Developer/Xcode/DerivedData/myApp-enjsbnsiwwzbxgcfkihfeqjuobll
```
In your project root:
```sh
rm -rf node_modules && npm i && react-native run-ios
```

Also, please tell me, did you check this step:
`Double click the text to the right of Header Search Paths and verify that it has $(SRCROOT)/../../react-native/React as well as ${SRCROOT}/../../../ios/Pods/Headers/Public - if they aren't, then add them.`

**Comment by apolishch** [comment]
@isnifer On localhost that had no effect. Adding `cd ios && pod install` on circleci does make circleci fail in the same way as localhost

**Comment by isnifer** [comment]
@apolishch you should care about cocoapods on CircleCI.
```sh
brew install cocoapods
```
for example, on your CI script

**Comment by isnifer** [comment]
@apolishch or like this - https://github.com/tipsi/tipsi-stripe/blob/master/.travis/before-install.sh#L37

**Comment by apolishch** [comment]
No effect:

Also, to answer your previous question:

Header Search path is set as: 
```
$(SRCROOT)/../../../React
$(SRCROOT)/../../react-native/React
$(SRCROOT)/../../../ios/Pods/Headers/Public
```

**Comment by isnifer** [comment]
@apolishch ok, so I will create a repo with a clean installation. Will follow instructions for manual linking and we will check that project to find what wrong

**Comment by apolishch** [comment]
@isnifer Thanks so much! Is there anything else I can provide to help you debug this?

**Comment by isnifer** [comment]
@apolishch I want to stream video of installation to twitch, maybe you will see where you were wrong or I will found our mistake

**Comment by apolishch** [comment]
@isnifer that would be amazing.
I have a meeting with some a remote team at 2 UTC (in 3 minutes). What time were you thinking of doing this?

**Comment by isnifer** [comment]
@apolishch haha, me to! Ok, let's try in an hour!

**Comment by apolishch** [comment]
Perfect! Again, thank you so much for your help.

**Comment by isnifer** [comment]
You're welcome!

**Comment by isnifer** [comment]
@apolishch so, do you ready for streaming?

**Comment by apolishch** [comment]
yup. I've never actually used Twitch before. How is this going to work? You going to give me a link?

**Comment by isnifer** [comment]
@apolishch yep

**Comment by isnifer** [comment]
so @apolishch https://www.twitch.tv/tr3m0r1ty

**Comment by apolishch** [comment]
great! I'm in.

**Comment by isnifer** [comment]
@apolishch so, where did you wrong?

**Comment by apolishch** [comment]
I still don't know tbh. The one thing that jumps out at me is that I do not seem to have a libStripe.a even available

**Comment by isnifer** [comment]
@apolishch may be I can help you via skype call, or zoom. You will share screen - I will help you)

**Comment by apolishch** [comment]
That would be amazing!  I am @ apolishch on Skype also

**Comment by apolishch** [comment]
or I can install zoom if you prefer

**Comment by isnifer** [comment]
@apolishch I will call you in skype)

**Comment by isnifer** [comment]
@apolishch is it works?

**Comment by apolishch** [comment]
Sorry had a retrospective to go to. I don't know. Will let you know shortly

**Comment by isnifer** [comment]
ok, thank you

**Comment by apolishch** [comment]
Thanks for all your help! It eventually just kind started working through `react-native run-ios`. The issue still occurs within XCode. This doesn't particularly bother me, at least not right now, as I can build through `fastlane`, and run through `react-native` without issue.

I will let you decide whether this should be closed or not.

**Comment by anmolmayank** [comment]
How did you solve the above issue?
can you please guide me through or can you plz share me a link for reference?

**Comment by anmolmayank** [comment]
@apolishch can you please help me out to solve the above issue,
I have tried all the above steps mentioned still i am facing this issue in my xcode.

**Comment by divsbhalala** [comment]
I am getting same error 
![image](https://user-images.githubusercontent.com/12185309/30976343-3006d6e6-a492-11e7-9f12-645bbea21920.png)

**Comment by crawler** [comment]
Had same error, but realized that i worked in AppName.xcodeproj when should open AppName.xcworkspace. Hope it helps someone.

**Comment by divsbhalala** [comment]
Yes that's work for me as well

**Comment by ikhsanalatsary** [comment]
what's the difference *.xcodeproj with *.xcworkspace?

**Comment by densa** [comment]
@ikhsanalatsary 

> A workspace is an Xcode document that groups projects and other documents so you can work on them together. A workspace can contain any number of Xcode projects, plus any other files you want to include. In addition to organizing all the files in each Xcode project, a workspace provides implicit and explicit relationships among the included projects and their targets.

[https://developer.apple.com/library/content/featuredarticles/XcodeConcepts/Concept-Workspace.html](url)

 CocoaPods, which automatically handles 3rd party libraries for you, uses workspaces. Therefore, you have to use them, too, when you use CocoaPods

**Comment by keithdmoore** [comment]
@crawler I want to buy you a cup of coffee or a beer!  The workspace worked for me too!  Thanks for posting!

**Comment by GituBojan** [comment]
Hey! 

I have followed all steps and opened xcworkspace too. Unfortunately I get a bit different error: 

```
ld: warning: directory not found for option '-L/Users/XYX/Documents/ReactNative/appNative/ios/app'
ld: framework not found Stripe
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The strange thing: my package etc. is called appNative and it looks for the app folder /ios. But there is of course only a appNative folder in /ios.

Thanks for your help!

**Comment by isnifer** [comment]
@GituBojan Hi! Did you install pods?

**Comment by GituBojan** [comment]
@isnifer 

Step 1:
I changed the workspace name from workspace 'app' to 'appNative'. 
Step 2:
I installed pod again - no change - still same error
Step 3:
I deleted the pod folder and pod file and installed pod again - still same error
Step 4:
deleted pod folder and build folder. Cleaned before build - still same error. 
Step 5:
checked all linkings etc. - still same error. 

Thanks for your really fast answer! And help of course :)

**Comment by isnifer** [comment]
@GituBojan show me your Podfile and `ios` folder sctructure

**Comment by GituBojan** [comment]
Podfile
```
# Use iOS 8 and above
platform :ios, '8.0'

# Specify Workspace
workspace 'appNative'

target 'appNative' do
  # Stripe
  pod 'Stripe', '~> 11.2.0'

  # Install additional dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'
end
```

**ios structure:**
/appNative
     /appNative/AppDelegate.h
     /appNative/AppDelegate.m
     /appNative/Base.Iproj
     /appNative/Images.xcassets
     /appNative/Info.plist
     /appNative/main.m
/appNative.xcodeproj
/appNative.xcworkspace
/Podfile
/Podfile.lock
/Pods
     /Pods/BoringSSL
     /Pods/Firebase
     /Pods/FirebaseAnalytics
     /Pods/FirebaseAuth
     /Pods/FirebaseCore
     /Pods/FirebaseCrash
     /Pods/FirebaseDatabase
     /Pods/FirebaseFirestore
     /Pods/FirebaseInstanceID
     /Pods/FirebaseMessaging
     /Pods/FirebasePerformance
     /Pods/FirebaseStorage
     /Pods/FirebaseSwizzlingUtilities
     /Pods/GoogleToolboxForMac
     /Pods/gRPC
     /Pods/gRPC-Core
     /Pods/gRPC-ProtoRPC
     /Pods/gRPC-RxLibrary
     /Pods/GTMSessionFetcher
     /Pods/Headers
     /Pods/leveldb-library
     /Pods/Local Podspecs
     /Pods/Manifest.lock
     /Pods/nanopb
     /Pods/Pods.xcodeproj
     /Pods/Protobug
     /Pods/Stripe
     /Pods/Target Support Files

@isnifer

**Comment by densa** [comment]
@GituBojan do you have appNative target in xcode?

**Comment by GituBojan** [comment]
@densa 
yes I have it.

**Comment by densa** [comment]
@GituBojan ok. If it your testing project and you can share it we can help find out issue

**Comment by GituBojan** [comment]
@isnifer @densa 

I have now spent the last hours searching for my mistake. After several changes and rebuilds I decided to delete the iOS folder and generate it again with react-native upgrade. After cleaning all my libraries etc. before generating the iOS folder I was able to build the project..

Still don't know what the real issues was. There were for sure some issues with the linking. THanks anyways for your help! Now it is working :)

**Comment by vymallesh** [comment]
I have no idea why i am getting pod file error when i started integrating Socket IO, earlier it was working fine.Finally ends up with the error says, ld: library not found for -lAWSCore.Any help would be appreciated.Attached those screenshots below..
![screen shot 2018-07-07 at 5 27 58 pm](https://user-images.githubusercontent.com/19487513/42410686-54b98ed2-820b-11e8-966b-fd839f7e005a.png)
![screen shot 2018-07-07 at 5 28 43 pm](https://user-images.githubusercontent.com/19487513/42410687-54e1ad72-820b-11e8-9673-3bd34466068e.png)

**Comment by isnifer** [comment]
@vymallesh you need to add Stripe. See https://github.com/tipsi/tipsi-stripe/blob/master/example/ios/Podfile#L9

**Comment by vymallesh** [comment]
@isnifer

I have an issue with AWSCore, while installing Socket iO pod file, i am facing below issue.Are there any dependencies between AWSCore and Socket iO.Earlier in the first build i have added AWS Core, till now it's fine.Now in second build, i have a requirement with socket, i have started integrating Socket iO, now it started throwing errors, which are listed below.
 
1. AWSCore.h' file not found with <angled> include; use "quotes" instead -- Change it to angular brackets ("")
2.Now it is throwing other error like, library not found for -lAWSCore.

Pod which you mentioned here, https://github.com/tipsi/tipsi-stripe/blob/master/example/ios/Podfile#L9 .It is something related to payment i guess.I have issue with AWS Core and Socket iO, no where i am using Stripe pod file which you mentioned.

**Comment by Gribadze** [comment]
I had same issue with ~lFirebaseCore. I've opened project from *.xcworkspace and everything goes fine :)

**Comment by isnifer** [comment]
@vymallesh see @Gribadze answer. Is that your mistake?

**Comment by Ajaykumar02** [comment]
Below two steps would solve you the problem of framework not found for a dependency lib,
1. clear Deriveddata 
2. try running the project using the 'react-native run-ios' from command line.
