### ISSUE TITLE
Build Failed: Multiple dex files define Lcom/google/android/gms/internal/zzaqo

### ISSUE THREAD

**Issue by dhyey35** [tipsi/tipsi-stripe#96]
The Error in console:

    Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzaqo;
        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzaqo;
            at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
            at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
            at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
            at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
            at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
            at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
            at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
            at com.android.dx.command.dexer.Main.run(Main.java:277)
            at com.android.dx.command.dexer.Main.main(Main.java:245)
            at com.android.dx.command.Main.main(Main.java:106)
        
    :app:transformClassesWithDexForDebug FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':app:transformClassesWithDexForDebug'.
    > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

Reason:

In `tipsi-stripe` **build.gradle** `dependencies :
    
    compile 'com.google.android.gms:play-services-wallet:10.+'

which conflicts with other version of `com.google.android.gms` installed by other packages such as [react native onesignal](https://github.com/geektimecoil/react-native-onesignal/blob/master/android/build.gradle):

Here is a snippet of onesignal's `build.gradle`:

    compile 'com.google.android.gms:play-services-gcm:+'
    compile 'com.google.android.gms:play-services-analytics:+'
    compile 'com.google.android.gms:play-services-location:+'

**SOLUTION** :

Change google play services in `build.gradle` of `tipsi-stripe`

FROM :
    
    compile 'com.google.android.gms:play-services-wallet:10.+'

TO :

    compile 'com.google.android.gms:play-services-wallet:+'

**Comment by cybergrind** [comment]
Hey, @dhyey35. 
Thank for your issue. We've thought about such change some time ago but we also had
```  compile 'com.stripe:stripe-android:+' ```
https://github.com/tipsi/tipsi-stripe/blob/1.1.0/android/build.gradle

And one day it was broken by an update, so now we're not sure if it the best solution to allow major updates without proper testing.
So, for now, you may force dependency to the version you want manually.

@paynd as far as I can see, android stripe library already requires `play-services-wallet`: https://github.com/stripe/stripe-android/blob/master/android-pay/build.gradle#L40
Maybe we can omit `play-services-wallet` from our gradle file?

**Comment by dhyey35** [comment]
@cybergrind  You are welcome. I have changed the dependency manually. Even I am not sure what the best solution is. I just opened the issue so that if any other dev faces the exact same issue he / she doesn't need to spend hours trying to resolve the issue :)

**Comment by paynd** [comment]
HI @dhyey35!
Actually you can force gradle to resolve dependency with specific version:
```
compile project(':tipsi-stripe'){
    configurations.all {
        resolutionStrategy {
            force 'compile 'com.google.android.gms:play-services-wallet:SOME_VERSION''
        }
    }
}
```
@cybergrind looks like you are right, will remove it in next release.
