### ISSUE TITLE
paymentRequestWithAndroidPay is never resolving

### ISSUE THREAD

**Issue by girokon** [tipsi/tipsi-stripe#98]
I'm not sure, but I think method `paymentRequestWithAndroidPay` return promise which never will be resolved. I have simple code:

```javascript
let tokenAndCard = await stripe
                .paymentRequestWithAndroidPay({
                    total_price: '10',
                    currency_code: 'USD',
                    line_items: [
                        {
                            currency_code: 'USD',
                            description: 'Payment',
                            total_price: '10',
                            unit_price: '10',
                            quantity: '1'
                        }
                    ]
                });

             //this row will be never reached
            console.log('tokenAndCard: ', tokenAndCard);
```

On my test device, I have one linked card, when I press Pay, I see android pay modal window, I fill my address and press confirm, then window is closing and nothing happen. My code after `paymentRequestWithAndroidPay` never reached, I don't see any errors in console or android debuger. 

I checked https://github.com/tipsi/tipsi-stripe/blob/master/android/src/main/java/com/gettipsi/stripe/StripeModule.java and I don't see any place where a promise passed as a param to this function https://github.com/tipsi/tipsi-stripe/blob/master/android/src/main/java/com/gettipsi/stripe/StripeModule.java#L237 is resolving

**Comment by isnifer** [comment]
Hi, @girokon, thank you for your issue. We will check that code.

**Comment by girokon** [comment]
I think I found the reason https://github.com/tipsi/tipsi-stripe/blob/master/android/src/main/java/com/gettipsi/stripe/StripeModule.java#L94
If environment is production, all will be ok, but in the development environment this code is nothing to do with promise, I think it should reject it as minimum.

**Comment by paynd** [comment]
Hi @girokon! Does paymentRequestWithAndroidPay() works in PRODUCTION mode for you?

**Comment by girokon** [comment]
@paynd we dropped support of android pay, therefore I don't know

**Comment by miraan** [comment]
I am also having this issue.
